# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

"""SubTaskExecutor — 新鲜上下文执行器。

参考 LongHorizon 的核心设计：
- 每个子任务在全新上下文中执行（不继承 Manager 上下文）
- 独立的 system prompt + 仅该子任务相关的信息
- 前置子任务的输出作为上下文传入，但不携带完整对话历史

优势：
- 避免上下文污染（长对话导致的注意力分散）
- 每个子任务有完整的 Token 预算可用
- 失败隔离（一个子任务失败不影响其他）
"""
import json
import logging
import time

logger = logging.getLogger("agent.orchestration.executor")


# 子任务执行系统提示词
_EXECUTOR_SYSTEM_PROMPT = """\
你是数字员工的子任务执行器。你将收到一个独立的子任务，需要在新鲜上下文中完成它。

重要原则：
1. 只关注当前子任务，不要做超出范围的事情
2. 如果需要前置子任务的输出，请参考下方提供的"前置结果"
3. 执行完成后，清晰地总结你的输出结果
4. 如果遇到问题，明确说明失败原因和建议

当前子任务：{description}
{context_section}
"""

# 前置结果模板
_DEPENDENCY_TEMPLATE = """\
前置子任务结果：
{dependencies}
"""


class SubTaskExecutor:
    """新鲜上下文子任务执行器。

    每个子任务在独立的 LLM 上下文中执行，
    仅携带该子任务相关的信息（前置结果、可用工具等）。
    """

    def __init__(self, app):
        """
        参数:
            app: AgentApp 实例（提供 LLM、工具、技能等组件）
        """
        self.app = app

    def execute(self, subtask, plan):
        """在新鲜上下文中执行一个子任务。

        参数:
            subtask: SubTask 实例
            plan: TaskPlan 实例（用于获取前置结果）

        返回:
            (success: bool, result: str, evidence: dict)
        """
        logger.info('开始执行子任务: %s - %s',
                    subtask.id, subtask.description[:80])
        subtask.status = 'running'
        start_time = time.time()

        try:
            # 构建上下文
            context = self._build_context(subtask, plan)

            # 构建系统提示词
            system_prompt = _EXECUTOR_SYSTEM_PROMPT.format(
                description=subtask.description,
                context_section=context)

            # 执行：优先使用建议的技能，否则走 LLM 直答
            if subtask.suggested_skill:
                result, evidence = self._execute_with_skill(
                    subtask, system_prompt)
            else:
                result, evidence = self._execute_with_llm(
                    subtask, system_prompt)

            subtask.status = 'done'
            subtask.result = result
            subtask.evidence = evidence

            elapsed = time.time() - start_time
            logger.info('子任务 %s 执行完成 (%.1fs): %s',
                        subtask.id, elapsed,
                        str(result)[:100] if result else '(无输出)')
            return True, result, evidence

        except Exception as e:
            subtask.status = 'failed'
            subtask.result = str(e)
            subtask.evidence = {'error': str(e)}
            logger.exception('子任务 %s 执行失败', subtask.id)
            return False, str(e), {'error': str(e)}

    def _build_context(self, subtask, plan):
        """构建子任务的上下文（前置结果）。"""
        if not subtask.depends_on:
            return ''

        deps_text = []
        for dep_id in subtask.depends_on:
            dep_task = next(
                (t for t in plan.subtasks if t.id == dep_id), None)
            if dep_task and dep_task.result:
                deps_text.append(
                    '[%s] %s\n结果: %s' % (
                        dep_id, dep_task.description[:100],
                        str(dep_task.result)[:500]))

        if not deps_text:
            return ''
        return _DEPENDENCY_TEMPLATE.format(
            dependencies='\n---\n'.join(deps_text))

    def _execute_with_skill(self, subtask, system_prompt):
        """使用指定技能执行子任务。"""
        skill_name = subtask.suggested_skill
        result = self.app.skills.execute_skill(skill_name, {
            'user_instruction': subtask.description,
            'home': self.app.config.home,
            'agent_id': self.app.config.agent_id,
        })
        if result.get('success'):
            return result.get('output'), {
                'method': 'skill',
                'skill': skill_name,
                'raw_result': result}
        else:
            raise RuntimeError('技能 %s 执行失败: %s' % (
                skill_name, result.get('error', '未知错误')))

    def _execute_with_llm(self, subtask, system_prompt):
        """使用 LLM 直答执行子任务（新鲜上下文）。"""
        messages = [{'role': 'system', 'content': system_prompt}]
        messages.append({
            'role': 'user',
            'content': '请执行以下子任务：%s' % subtask.description})

        tool_schemas = self.app.tools.get_openai_tools_schema()
        reply = None
        evidence = {'method': 'llm', 'tool_calls': []}

        for _ in range(min(3, self.app.config.get('max_tool_rounds'))):
            msg = self.app.llm.chat(
                messages, tools=tool_schemas or None,
                skill='orchestration', category='subtask')
            tool_calls = msg.get('tool_calls')
            if tool_calls:
                messages.append(msg)
                for tc in tool_calls:
                    fn = tc.get('function', {})
                    try:
                        args = json.loads(fn.get('arguments') or '{}')
                    except ValueError:
                        args = {}
                    result = self.app._exec_tool_call(
                        fn.get('name', ''), args)
                    evidence['tool_calls'].append({
                        'tool': fn.get('name', ''),
                        'args': args,
                        'result_summary': str(result)[:200]})
                    messages.append({
                        'role': 'tool',
                        'tool_call_id': tc.get('id', ''),
                        'content': json.dumps(
                            result, ensure_ascii=False)[
                            :self.app.config.get('output_limit')],
                    })
                continue

            reply = msg.get('content') or str(msg)
            break

        if reply is None:
            reply = '子任务执行达到轮数上限'

        return reply, evidence
