# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

"""MonitorReporter — 资源监控 WS 上报器。

设计：
- 定时采集资源快照
- 通过 WS 上报到平台（{"type": "monitor", ...}）
- WS 未连接时缓存到 SQLite metrics 表
- WS 恢复后批量上报缓存数据
"""
import asyncio
import logging
import threading
import time

from agent_runtime.monitor.collector import ResourceCollector
from agent_runtime.ws import protocol

logger = logging.getLogger("agent.monitor.reporter")


class MonitorReporter:
    """资源监控上报器。

    在后台线程中定时采集资源快照并通过 WS 上报。
    WS 未连接时将数据缓存到 SQLite，恢复后批量上报。
    """

    def __init__(self, config, ws_client, db, loop=None):
        """
        参数:
            config: RuntimeConfig 实例
            ws_client: WSClient 实例
            db: Database 实例
            loop: asyncio 事件循环（用于从后台线程调度异步 send）
        """
        self.config = config
        self.ws = ws_client
        self.db = db
        self.loop = loop
        self.collector = ResourceCollector(config)
        self.interval = config.get('monitor_interval', 10)
        self._stop = threading.Event()
        self._thread = None
        self._buffer_flush_threshold = 10  # 缓存超过此数量时批量上报

    def start(self):
        """启动监控上报线程。"""
        if self._thread and self._thread.is_alive():
            return
        self._stop.clear()
        self._thread = threading.Thread(
            target=self._loop, name='monitor', daemon=True)
        self._thread.start()
        logger.info('资源监控已启动（间隔 %ds）', self.interval)

    def stop(self):
        """停止监控。"""
        self._stop.set()

    def _loop(self):
        """主循环：采集 → 上报/缓存。"""
        while not self._stop.wait(self.interval):
            try:
                snapshot = self.collector.collect()
                logger.info('采集快照: cpu=%.1f mem=%.1f load1=%s procs=%s',
                           snapshot.cpu, snapshot.memory,
                           snapshot.load_avg_1, snapshot.process_count)
                self._handle_snapshot(snapshot)
                logger.info('快照已保存')
            except Exception:
                logger.warning('监控循环异常', exc_info=True)

    def _handle_snapshot(self, snapshot):
        """处理单个快照：WS 连接则上报，否则缓存。"""
        # 持久化到 SQLite（始终保存，用于历史查询）
        self.db.save_metric(
            cpu=snapshot.cpu,
            memory=snapshot.memory,
            disk=snapshot.disk,
            network_rx=snapshot.network_rx,
            network_tx=snapshot.network_tx,
            memory_used=snapshot.memory_used,
            memory_total=snapshot.memory_total,
            load_avg_1=snapshot.load_avg_1,
            load_avg_5=snapshot.load_avg_5,
            load_avg_15=snapshot.load_avg_15,
            disk_read=snapshot.disk_read,
            disk_write=snapshot.disk_write,
            disk_read_count=snapshot.disk_read_count,
            disk_write_count=snapshot.disk_write_count,
            process_count=snapshot.process_count,
            top_processes=snapshot.top_processes)

        # 通过 WS 上报
        ws_ok = self.ws is not None
        ws_connected = self.ws.connected if self.ws else False
        loop_ok = self.loop is not None and self.loop.is_running() if self.loop else False
        logger.info('MonitorReporter 状态: ws=%s ws_connected=%s loop=%s',
                     ws_ok, ws_connected, loop_ok)
        if self.ws and self.ws.connected:
            load_avg = None
            if snapshot.load_avg_1 is not None:
                load_avg = [snapshot.load_avg_1, snapshot.load_avg_5, snapshot.load_avg_15]
            disk_io = None
            if snapshot.disk_read is not None:
                disk_io = {
                    'read': snapshot.disk_read, 'write': snapshot.disk_write,
                    'read_count': snapshot.disk_read_count,
                    'write_count': snapshot.disk_write_count,
                }
            msg = protocol.make_monitor(
                agent_id=self.config.agent_id,
                cpu=snapshot.cpu,
                mem=snapshot.memory,
                disk=snapshot.disk,
                network_rx=snapshot.network_rx,
                network_tx=snapshot.network_tx,
                memory_used=snapshot.memory_used,
                memory_total=snapshot.memory_total,
                load_avg=load_avg,
                disk_io=disk_io,
                process_count=snapshot.process_count,
                top_processes=snapshot.top_processes)
            if self.loop and self.loop.is_running():
                asyncio.run_coroutine_threadsafe(
                    self.ws.send(msg), self.loop)
            else:
                logger.debug('无事件循环，监控消息未发送')

            # WS 恢复后，尝试刷新缓存
            self._flush_buffer()
        # 不连接时不做额外操作（数据已存 SQLite）

    def _flush_buffer(self):
        """批量上报缓存的监控数据。

        注意：SQLite 中的 metrics 用于历史查询，不在此处删除。
        清理由 db.cleanup_old_metrics 按较长周期执行。
        """
        pass

    def get_latest(self):
        """获取最新的资源快照（供状态查询使用）。"""
        metrics = self.db.get_recent_metrics(limit=1)
        if metrics:
            return metrics[0]
        return None
