# -*- mode: python ; coding: utf-8 -*-
# OpenChiip Harness — PyInstaller 打包配置
# 在 Windows 上运行: pyinstaller openchiip-harness.spec

import os
import sys
from pathlib import Path

block_cipher = None
ROOT = Path(SPECPATH) if 'SPECPATH' in dir() else Path(__file__).parent

a = Analysis(
    [str(ROOT / 'agent_runtime' / 'launch_server.py')],
    pathex=[str(ROOT)],
    binaries=[],
    datas=[
        # 打包 agent_runtime 全部源码
        (str(ROOT / 'agent_runtime'), 'agent_runtime'),
        # 打包前端构建产物
        (str(ROOT / 'web' / 'dist'), 'web/dist'),
    ],
    hiddenimports=[
        # uvicorn 内部导入
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.loops.asyncio',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.http.httptools_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.protocols.websockets.wsproto_impl',
        'uvicorn.protocols.websockets.websockets_impl',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'uvicorn.middleware',
        'uvicorn.middleware.asgi2',
        'uvicorn.middleware.message_logger',
        'uvicorn.middleware.proxy_headers',
        'uvicorn.middleware.wsgi',
        # FastAPI / Starlette
        'fastapi',
        'starlette',
        'starlette.applications',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.responses',
        'starlette.routing',
        'starlette.staticfiles',
        'starlette.websockets',
        # 序列化
        'pydantic',
        'pydantic.deprecated',
        'pydantic.deprecated.copy_internals',
        # 其他
        'yaml',
        'aiofiles',
        'aiofiles.os',
        'multipart',
        'psutil',
        'websockets',
        'click',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'h11',
        'httptools',
        'uvloop',
        # agent_runtime 模块
        'agent_runtime',
        'agent_runtime.cli',
        'agent_runtime.launch_server',
        'agent_runtime.main',
        'agent_runtime.daemon',
        'agent_runtime.server',
        'agent_runtime.server.app',
        'agent_runtime.server.ws_handler',
        'agent_runtime.server.api',
        'agent_runtime.server.api.chat',
        'agent_runtime.server.api.sessions',
        'agent_runtime.server.api.skills',
        'agent_runtime.server.api.metaskills',
        'agent_runtime.server.api.tools',
        'agent_runtime.server.api.commands',
        'agent_runtime.server.api.a2a',
        'agent_runtime.server.api.memory',
        'agent_runtime.server.api.knowledge',
        'agent_runtime.server.api.config_api',
        'agent_runtime.server.api.monitor',
        'agent_runtime.server.api.status',
        'agent_runtime.server.api.capabilities',
        'agent_runtime.server.api.session_events',
        'agent_runtime.server.api.feedback',
        'agent_runtime.server.api.workspace',
        'agent_runtime.server.api.tasks',
        'agent_runtime.server.api.projects',
        'agent_runtime.server.api.mode',
        'agent_runtime.server.api.credentials',
        'agent_runtime.server.api.llm',
        'agent_runtime.server.ws_handler',
        'agent_runtime.gateway',
        'agent_runtime.gateway.platform_client',
        'agent_runtime.core',
        'agent_runtime.core.config',
        'agent_runtime.core.llm_client',
        'agent_runtime.core.memory',
        'agent_runtime.core.db',
        'agent_runtime.core.intent_router',
        'agent_runtime.core.skill_manager',
        'agent_runtime.core.dag_executor',
    ],
    hiddenimports_collect=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter', 'matplotlib', 'scipy', 'numpy',
        'PIL', 'pandas', 'IPython', 'notebook',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='openchiip-harness-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,  # 替换为 icon.ico 路径
)
