#!/usr/bin/env python3
# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).
"""uninstall_skill.py — 从员工 {RUNTIME_HOME}/skills/ 卸载技能。

用法：
  uninstall_skill.py <name>           卸载指定员工技能
  uninstall_skill.py <name> --dry     仅显示将被删除的内容

注意：只能卸载员工目录内的技能，代码内置技能不可删除
（如需屏蔽内置技能，可在员工目录安装同名技能进行覆盖）。
仅使用 Python3 标准库。
"""
import argparse
import json
import shutil
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent       # agent_runtime/
sys.path.insert(0, str(BASE_DIR.parent))                # backend/

from agent_runtime.core.config import RuntimeConfig      # noqa: E402

REGISTRY_NAME = '_registry.json'


def main():
    parser = argparse.ArgumentParser(description='卸载员工技能')
    parser.add_argument('name', help='技能名')
    parser.add_argument('--dry', action='store_true', help='仅预览')
    args = parser.parse_args()

    config = RuntimeConfig(agent_id='cli')
    skill_dir = config.skills_user_dir / args.name
    if not skill_dir.exists() or not skill_dir.is_dir():
        print('错误: 员工技能 %s 未安装（%s 不存在）' % (args.name, skill_dir))
        return 1
    if args.dry:
        print('将删除: %s' % skill_dir)
        return 0
    shutil.rmtree(skill_dir)

    # 更新用户技能注册表
    reg_file = config.skills_user_dir / REGISTRY_NAME
    if reg_file.exists():
        try:
            data = json.loads(reg_file.read_text(encoding='utf-8'))
            if args.name in data.get('skills', {}):
                del data['skills'][args.name]
                reg_file.write_text(
                    json.dumps(data, indent=2, ensure_ascii=False),
                    encoding='utf-8')
        except (ValueError, OSError):
            pass
    print('技能 %s 已卸载' % args.name)
    return 0


if __name__ == '__main__':
    sys.exit(main())

