// Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
// Copyright: (c) <opensource@openchiip.com>
// Generated By : OpenChiip
// Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
// This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

import { useState, useEffect, useRef, memo } from 'react'
import { Check, Copy, ChevronDown, ChevronUp } from 'lucide-react'
import { cn } from '@/lib/utils'

interface CodeBlockProps {
  code: string
  language: string
}

/** 默认最大显示行数，超出则折叠 */
const MAX_LINES = 16

/**
 * 代码块组件（参考 deepseek-harness CodeBlock）
 * - Shiki 语法高亮（异步加载，回退纯文本）
 * - 语言标签 banner
 * - 复制按钮（带成功反馈）
 * - 长代码高度上限 + 展开/折叠
 */
export const CodeBlock = memo(function CodeBlock({ code, language }: CodeBlockProps) {
  const [highlighted, setHighlighted] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)
  const [expanded, setExpanded] = useState(false)
  const timerRef = useRef<ReturnType<typeof setTimeout>>()

  const lines = code.replace(/\n$/, '').split('\n')
  const shouldCollapse = lines.length > MAX_LINES
  const displayCode = shouldCollapse && !expanded
    ? lines.slice(0, MAX_LINES).join('\n')
    : code

  // Shiki 高亮（异步初始化，懒加载语法）
  useEffect(() => {
    let cancelled = false

    async function highlight() {
      try {
        const { createHighlighter } = await import('shiki')
        const highlighter = await createHighlighter({
          themes: ['github-dark'],
          langs: ['text'],
        })

        // 尝试加载目标语言
        if (language && language !== 'text') {
          try {
            await highlighter.loadLanguage(language as any)
          } catch {
            // 语言不支持，回退 text
          }
        }

        if (cancelled) return

        const lang = highlighter.getLoadedLanguages().includes(language as any)
          ? language
          : 'text'
        const html = highlighter.codeToHtml(displayCode, { lang, theme: 'github-dark' })
        if (!cancelled) setHighlighted(html)
      } catch {
        // Shiki 加载失败，使用纯文本
        if (!cancelled) setHighlighted(null)
      }
    }

    highlight()
    return () => { cancelled = true }
  }, [code, language, displayCode])

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(code)
      setCopied(true)
      if (timerRef.current) clearTimeout(timerRef.current)
      timerRef.current = setTimeout(() => setCopied(false), 1500)
    } catch { /* ignore */ }
  }

  return (
    <div className="group/code relative my-2 overflow-hidden rounded-lg border border-border/40 bg-[#0d1117]">
      {/* Header: 语言标签 + 复制按钮 */}
      <div className="flex items-center justify-between border-b border-white/10 bg-white/5 px-3 py-1.5">
        <span className="text-xs text-gray-400 font-mono">{language || 'text'}</span>
        <button
          type="button"
          onClick={handleCopy}
          className="flex items-center gap-1 rounded px-1.5 py-0.5 text-xs text-gray-400 transition-colors hover:bg-white/10 hover:text-gray-200"
        >
          {copied ? (
            <>
              <Check className="h-3 w-3" />
              <span>已复制</span>
            </>
          ) : (
            <>
              <Copy className="h-3 w-3" />
              <span>复制</span>
            </>
          )}
        </button>
      </div>

      {/* Code content */}
      <div className={cn('overflow-x-auto', shouldCollapse && !expanded && 'max-h-[24rem] overflow-y-hidden')}>
        {highlighted ? (
          <div
            className="shiki-highlight text-sm leading-relaxed"
            dangerouslySetInnerHTML={{ __html: highlighted }}
          />
        ) : (
          <pre className="text-sm leading-relaxed text-gray-300 p-4">
            <code>{displayCode}</code>
          </pre>
        )}
      </div>

      {/* Expand/collapse toggle */}
      {shouldCollapse && (
        <button
          type="button"
          onClick={() => setExpanded(!expanded)}
          className="flex w-full items-center justify-center gap-1 border-t border-white/10 bg-white/5 py-1.5 text-xs text-gray-400 transition-colors hover:bg-white/10 hover:text-gray-200"
        >
          {expanded ? (
            <>
              <ChevronUp className="h-3 w-3" />
              <span>收起</span>
            </>
          ) : (
            <>
              <ChevronDown className="h-3 w-3" />
              <span>展开全部 {lines.length} 行</span>
            </>
          )}
        </button>
      )}
    </div>
  )
})
