// Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
// Copyright: (c) <opensource@openchiip.com>
// Generated By : OpenChiip
// Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
// This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

/**
 * EmptyHero — 空状态引导页。
 *
 * 借鉴 openwork 的 session-empty-hero.tsx：
 * - 大标题 + 副标题
 * - 2x2 建议卡片网格（点击填入输入框）
 * - 居中布局，最大宽度 640px
 */
import {
  FileText,
  Code2,
  BarChart3,
  ClipboardList,
} from 'lucide-react'

interface EmptyHeroProps {
  onSuggestionClick: (text: string) => void
}

const suggestions = [
  {
    icon: FileText,
    title: '总结今日工作',
    description: '帮我整理今天完成的任务和进展',
    text: '帮我总结一下今天的工作内容和完成情况',
  },
  {
    icon: BarChart3,
    title: '帮我写一份报告',
    description: '快速生成项目进展报告',
    text: '帮我写一份项目进展报告，包含本周完成的主要任务',
  },
  {
    icon: Code2,
    title: '分析这段代码',
    description: '审查代码逻辑并提出优化建议',
    text: '帮我分析并优化一段代码，找出潜在问题',
  },
  {
    icon: ClipboardList,
    title: '查询项目状态',
    description: '查看当前进行中的任务和状态',
    text: '查看当前项目的整体状态和待办事项',
  },
]

export function EmptyHero({ onSuggestionClick }: EmptyHeroProps) {
  return (
    <div className="flex h-full flex-col items-center justify-center px-4">
      <div className="w-full max-w-[640px] space-y-8">
        {/* 标题区域 */}
        <div className="text-center space-y-2">
          <h1 className="text-2xl font-bold tracking-tight">
            有什么需要帮忙的？
          </h1>
          <p className="text-sm text-muted-foreground">
            用自然语言描述你的需求
          </p>
        </div>

        {/* 建议卡片网格 */}
        <div className="grid grid-cols-2 gap-3">
          {suggestions.map((s) => (
            <button
              key={s.title}
              onClick={() => onSuggestionClick(s.text)}
              className="group flex flex-col items-start gap-2 rounded-xl border p-4 text-left transition-all hover:border-primary/30 hover:bg-accent/50 hover:shadow-sm"
            >
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary transition-colors group-hover:bg-primary/15">
                <s.icon className="h-4 w-4" />
              </div>
              <div>
                <p className="text-sm font-medium leading-tight">{s.title}</p>
                <p className="mt-0.5 text-xs text-muted-foreground leading-relaxed">
                  {s.description}
                </p>
              </div>
            </button>
          ))}
        </div>
      </div>
    </div>
  )
}
