// Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
// Copyright: (c) <opensource@openchiip.com>
// Generated By : OpenChiip
// Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
// This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

/**
 * SessionSidebar — 会话侧边栏。
 *
 * 借鉴 openwork 的 app-sidebar.tsx：
 * - 按时间分组（今天 / 昨天 / 近 7 天 / 更早）
 * - 搜索框（前端过滤标题）
 * - 右键上下文菜单（重命名 / 归档 / 删除 / 分叉）
 * - 相对时间显示
 * - 会话消息数气泡
 */
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import {
  Archive,
  GitFork,
  MessageSquare,
  MoreHorizontal,
  Pencil,
  Plus,
  Search,
  Trash2,
  X,
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { useChatStore, type SessionItem } from '@/store/chat'

/** 相对时间格式化。 */
function formatRelativeTime(dateStr: string): string {
  const date = new Date(dateStr)
  const now = new Date()
  const diffMs = now.getTime() - date.getTime()
  const diffMin = Math.floor(diffMs / 60000)
  if (diffMin < 1) return '刚刚'
  if (diffMin < 60) return `${diffMin} 分钟前`
  const diffHr = Math.floor(diffMin / 60)
  if (diffHr < 24) return `${diffHr} 小时前`
  const diffDay = Math.floor(diffHr / 24)
  if (diffDay === 1) return '昨天'
  if (diffDay < 7) return `${diffDay} 天前`
  return date.toLocaleDateString('zh-CN', { month: 'short', day: 'numeric' })
}

/** 按时间分组。 */
type Group = { label: string; items: SessionItem[] }

function groupSessions(sessions: SessionItem[]): Group[] {
  const now = new Date()
  const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime()
  const yesterdayStart = todayStart - 86400000
  const weekStart = todayStart - 7 * 86400000

  const groups: Record<string, SessionItem[]> = {
    '今天': [],
    '昨天': [],
    '近 7 天': [],
    '更早': [],
  }

  for (const s of sessions) {
    const t = new Date(s.updated_at).getTime()
    if (t >= todayStart) groups['今天'].push(s)
    else if (t >= yesterdayStart) groups['昨天'].push(s)
    else if (t >= weekStart) groups['近 7 天'].push(s)
    else groups['更早'].push(s)
  }

  return Object.entries(groups)
    .filter(([, items]) => items.length > 0)
    .map(([label, items]) => ({ label, items }))
}

/** 右键菜单。 */
interface ContextMenuState {
  x: number
  y: number
  session: SessionItem
}

export function SessionSidebar() {
  const {
    sessions, currentSessionId, searchQuery,
    loadSessions, createSession, switchSession,
    deleteSession, renameSession, archiveSession, forkSession,
    setSearchQuery,
  } = useChatStore()

  const [ctxMenu, setCtxMenu] = useState<ContextMenuState | null>(null)
  const [renaming, setRenaming] = useState<string | null>(null)
  const [renameTitle, setRenameTitle] = useState('')
  const menuRef = useRef<HTMLDivElement>(null)
  const inputRef = useRef<HTMLInputElement>(null)

  useEffect(() => { loadSessions() }, [loadSessions])

  // 点击外部关闭菜单
  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setCtxMenu(null)
      }
    }
    if (ctxMenu) {
      document.addEventListener('mousedown', handler)
      return () => document.removeEventListener('mousedown', handler)
    }
  }, [ctxMenu])

  // 搜索过滤
  const filtered = useMemo(() => {
    if (!searchQuery.trim()) return sessions
    const q = searchQuery.toLowerCase()
    return sessions.filter((s) => s.title.toLowerCase().includes(q))
  }, [sessions, searchQuery])

  const groups = useMemo(() => groupSessions(filtered), [filtered])

  const handleContextMenu = useCallback(
    (e: React.MouseEvent, session: SessionItem) => {
      e.preventDefault()
      setCtxMenu({ x: e.clientX, y: e.clientY, session })
    },
    [],
  )

  const handleRename = useCallback(() => {
    if (!ctxMenu) return
    setRenaming(ctxMenu.session.id)
    setRenameTitle(ctxMenu.session.title)
    setCtxMenu(null)
    setTimeout(() => inputRef.current?.focus(), 50)
  }, [ctxMenu])

  const handleRenameSubmit = useCallback(
    async (id: string) => {
      if (renameTitle.trim()) {
        await renameSession(id, renameTitle.trim())
      }
      setRenaming(null)
    },
    [renameTitle, renameSession],
  )

  const handleArchive = useCallback(async () => {
    if (!ctxMenu) return
    await archiveSession(ctxMenu.session.id)
    setCtxMenu(null)
  }, [ctxMenu, archiveSession])

  const handleDelete = useCallback(async () => {
    if (!ctxMenu) return
    await deleteSession(ctxMenu.session.id)
    setCtxMenu(null)
  }, [ctxMenu, deleteSession])

  const handleFork = useCallback(async () => {
    if (!ctxMenu) return
    await forkSession(ctxMenu.session.id)
    setCtxMenu(null)
  }, [ctxMenu, forkSession])

  return (
    <div className="flex h-full w-64 flex-col border-r bg-background">
      {/* 头部 */}
      <div className="flex items-center justify-between border-b px-3 py-2.5">
        <span className="text-sm font-semibold">会话</span>
        <button
          onClick={() => createSession()}
          className="rounded-lg p-1.5 text-muted-foreground hover:bg-accent hover:text-foreground transition-colors"
          title="新建会话"
        >
          <Plus className="h-4 w-4" />
        </button>
      </div>

      {/* 搜索框 */}
      <div className="px-3 py-2">
        <div className="flex items-center gap-2 rounded-lg bg-muted/50 px-2.5 py-1.5">
          <Search className="h-3.5 w-3.5 text-muted-foreground shrink-0" />
          <input
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="搜索会话..."
            className="flex-1 bg-transparent text-xs outline-none placeholder:text-muted-foreground"
          />
          {searchQuery && (
            <button onClick={() => setSearchQuery('')} className="text-muted-foreground hover:text-foreground">
              <X className="h-3 w-3" />
            </button>
          )}
        </div>
      </div>

      {/* 会话列表 */}
      <div className="flex-1 overflow-y-auto">
        {groups.length === 0 ? (
          <div className="px-4 py-8 text-center">
            <MessageSquare className="mx-auto h-8 w-8 text-muted-foreground/40" />
            <p className="mt-2 text-xs text-muted-foreground">
              {searchQuery ? '未找到匹配会话' : '暂无会话'}
            </p>
          </div>
        ) : (
          groups.map((group) => (
            <div key={group.label}>
              <div className="px-3 pt-3 pb-1">
                <span className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground/70">
                  {group.label}
                </span>
              </div>
              {group.items.map((s) => (
                <div
                  key={s.id}
                  className={cn(
                    'group relative flex items-center gap-2 px-3 py-2 cursor-pointer transition-colors',
                    'hover:bg-accent/50',
                    s.id === currentSessionId && 'bg-accent',
                  )}
                  onClick={() => switchSession(s.id)}
                  onContextMenu={(e) => handleContextMenu(e, s)}
                >
                  <MessageSquare className="h-3.5 w-3.5 shrink-0 text-muted-foreground/60" />
                  <div className="flex-1 min-w-0">
                    {renaming === s.id ? (
                      <input
                        ref={inputRef}
                        value={renameTitle}
                        onChange={(e) => setRenameTitle(e.target.value)}
                        onBlur={() => handleRenameSubmit(s.id)}
                        onKeyDown={(e) => {
                          if (e.key === 'Enter') handleRenameSubmit(s.id)
                          if (e.key === 'Escape') setRenaming(null)
                        }}
                        className="w-full bg-background rounded px-1 py-0.5 text-xs outline-none ring-1 ring-ring"
                        onClick={(e) => e.stopPropagation()}
                      />
                    ) : (
                      <p className="truncate text-sm leading-tight">{s.title}</p>
                    )}
                    <p className="text-[10px] text-muted-foreground/60 mt-0.5">
                      {formatRelativeTime(s.updated_at)}
                    </p>
                  </div>
                  {s.message_count > 0 && (
                    <span className="shrink-0 rounded-full bg-muted px-1.5 py-0.5 text-[10px] text-muted-foreground">
                      {s.message_count}
                    </span>
                  )}
                </div>
              ))}
            </div>
          ))
        )}
      </div>

      {/* 右键上下文菜单 */}
      {ctxMenu && (
        <div
          ref={menuRef}
          className="fixed z-50 min-w-[140px] rounded-lg border bg-popover p-1 shadow-lg"
          style={{ left: ctxMenu.x, top: ctxMenu.y }}
        >
          <button
            onClick={handleRename}
            className="flex w-full items-center gap-2 rounded-md px-2.5 py-1.5 text-xs hover:bg-accent transition-colors"
          >
            <Pencil className="h-3 w-3" />
            重命名
          </button>
          <button
            onClick={handleFork}
            className="flex w-full items-center gap-2 rounded-md px-2.5 py-1.5 text-xs hover:bg-accent transition-colors"
          >
            <GitFork className="h-3 w-3" />
            分叉
          </button>
          <button
            onClick={handleArchive}
            className="flex w-full items-center gap-2 rounded-md px-2.5 py-1.5 text-xs hover:bg-accent transition-colors"
          >
            <Archive className="h-3 w-3" />
            归档
          </button>
          <div className="my-1 border-t" />
          <button
            onClick={handleDelete}
            className="flex w-full items-center gap-2 rounded-md px-2.5 py-1.5 text-xs text-destructive hover:bg-destructive/10 transition-colors"
          >
            <Trash2 className="h-3 w-3" />
            删除
          </button>
        </div>
      )}
    </div>
  )
}
