// Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
// Copyright: (c) <opensource@openchiip.com>
// Generated By : OpenChiip
// Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
// This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

import { CheckCircle2, Circle, Loader2, ListTodo } from 'lucide-react'
import { cn } from '@/lib/utils'

/** 单个任务项类型 */
export interface TodoItem {
  content: string
  status: 'pending' | 'in_progress' | 'completed'
}

interface TodoBlockProps {
  todos: TodoItem[]
}

/** 状态图标映射 */
function StatusIcon({ status }: { status: TodoItem['status'] }) {
  switch (status) {
    case 'completed':
      return <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-500" />
    case 'in_progress':
      return <Loader2 className="h-4 w-4 shrink-0 text-primary animate-spin" />
    default:
      return <Circle className="h-4 w-4 shrink-0 text-muted-foreground/40" />
  }
}

/** 状态文本 */
function statusLabel(status: TodoItem['status']): string {
  switch (status) {
    case 'completed': return '已完成'
    case 'in_progress': return '进行中'
    default: return '待开始'
  }
}

/**
 * Todo 任务列表组件
 * 参照 deepseek-harness tool-todo 的呈现方式：
 * - 每项显示状态图标 + 任务描述
 * - 底部显示统计（pending / in_progress / completed 数量）
 */
export function TodoBlock({ todos }: TodoBlockProps) {
  if (!todos || todos.length === 0) return null

  // 统计各状态数量
  const pending = todos.filter(t => t.status === 'pending').length
  const inProgress = todos.filter(t => t.status === 'in_progress').length
  const completed = todos.filter(t => t.status === 'completed').length
  const total = todos.length

  // 进度百分比
  const progress = total > 0 ? Math.round((completed / total) * 100) : 0

  return (
    <div className="rounded-lg border border-border/40 bg-muted/20 overflow-hidden">
      {/* 标题栏 */}
      <div className="flex items-center gap-2 px-3 py-2 border-b border-border/30 bg-muted/30">
        <ListTodo className="h-4 w-4 text-muted-foreground shrink-0" />
        <span className="text-xs font-medium text-muted-foreground">任务列表</span>
        {/* 进度条 */}
        <div className="flex-1 h-1.5 rounded-full bg-muted overflow-hidden mx-2">
          <div
            className="h-full rounded-full bg-emerald-500 transition-all duration-300"
            style={{ width: `${progress}%` }}
          />
        </div>
        <span className="text-[10px] text-muted-foreground tabular-nums shrink-0">
          {completed}/{total}
        </span>
      </div>

      {/* 任务列表 */}
      <div className="divide-y divide-border/20">
        {todos.map((todo, i) => (
          <div
            key={i}
            className={cn(
              'flex items-start gap-2.5 px-3 py-2 text-sm transition-colors',
              todo.status === 'completed' && 'opacity-60',
              todo.status === 'in_progress' && 'bg-primary/5',
            )}
          >
            <StatusIcon status={todo.status} />
            <span
              className={cn(
                'flex-1 text-sm leading-relaxed',
                todo.status === 'completed' && 'line-through text-muted-foreground',
                todo.status === 'in_progress' && 'font-medium text-foreground',
                todo.status === 'pending' && 'text-muted-foreground',
              )}
            >
              {todo.content}
            </span>
            <span className={cn(
              'shrink-0 text-[10px] px-1.5 py-0.5 rounded-full',
              todo.status === 'completed' && 'bg-emerald-500/10 text-emerald-600',
              todo.status === 'in_progress' && 'bg-primary/10 text-primary',
              todo.status === 'pending' && 'bg-muted text-muted-foreground/60',
            )}>
              {statusLabel(todo.status)}
            </span>
          </div>
        ))}
      </div>

      {/* 底部统计 */}
      <div className="flex items-center gap-3 px-3 py-1.5 border-t border-border/20 bg-muted/10 text-[10px] text-muted-foreground">
        {pending > 0 && <span>{pending} 待开始</span>}
        {inProgress > 0 && <span className="text-primary">{inProgress} 进行中</span>}
        {completed > 0 && <span className="text-emerald-600">{completed} 已完成</span>}
      </div>
    </div>
  )
}
