// Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
// Copyright: (c) <opensource@openchiip.com>
// Generated By : OpenChiip
// Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
// This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

/**
 * WorkspacePanel — 工作区文件浏览器（多根目录手风琴模式）。
 *
 * 根目录以垂直手风琴形式展示，点击展开某一个时其余自动折叠。
 * 支持右键上下文菜单（新建/重命名/删除）和顶部工具栏按钮。
 */
import { useCallback, useEffect, useRef, useState } from 'react'
import {
  ChevronRight,
  File,
  FileCode,
  FileJson,
  FilePlus,
  FileText,
  Folder,
  FolderOpen,
  FolderPlus,
  Home,
  Loader2,
  RefreshCw,
  Briefcase,
  FileStack,
  Share2,
  Trash2,
  Pencil,
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { api, type FileInfo, type WorkspaceRoot } from '@/lib/api'

interface WorkspacePanelProps {
  onFileSelect?: (file: FileInfo, root: number) => void
}

interface TreeNode {
  file: FileInfo
  children: TreeNode[] | null  // null = not loaded yet
  expanded: boolean
  loading: boolean
}

interface ContextMenuState {
  x: number
  y: number
  node: TreeNode | null
  isRoot?: boolean
  rootIndex?: number
}

/** 根目录图标。 */
function getRootIcon(label: string) {
  switch (label) {
    case '工作区':
      return <Briefcase className="h-3.5 w-3.5" />
    case '家目录':
      return <Home className="h-3.5 w-3.5" />
    case '文档':
      return <FileStack className="h-3.5 w-3.5" />
    case '共享目录':
      return <Share2 className="h-3.5 w-3.5" />
    case '临时目录':
      return <Trash2 className="h-3.5 w-3.5" />
    default:
      return <Folder className="h-3.5 w-3.5" />
  }
}

/** 根据文件名选择合适的图标。 */
function getFileIcon(name: string, isDir: boolean, expanded: boolean) {
  if (isDir) {
    return expanded
      ? <FolderOpen className="h-3.5 w-3.5 text-amber-500 shrink-0" />
      : <Folder className="h-3.5 w-3.5 text-amber-500 shrink-0" />
  }
  const ext = name.split('.').pop()?.toLowerCase()
  switch (ext) {
    case 'py':
      return <FileCode className="h-3.5 w-3.5 text-blue-500 shrink-0" />
    case 'json':
      return <FileJson className="h-3.5 w-3.5 text-yellow-500 shrink-0" />
    case 'md':
    case 'txt':
    case 'yaml':
    case 'yml':
      return <FileText className="h-3.5 w-3.5 text-green-500 shrink-0" />
    default:
      return <File className="h-3.5 w-3.5 text-muted-foreground shrink-0" />
  }
}

export function WorkspacePanel({ onFileSelect }: WorkspacePanelProps) {
  const [roots, setRoots] = useState<WorkspaceRoot[]>([])
  const [activeRoot, setActiveRoot] = useState(0)
  const [treeNodes, setTreeNodes] = useState<TreeNode[]>([])
  const [loading, setLoading] = useState(false)
  const [selectedPath, setSelectedPath] = useState<string | null>(null)
  const [contextMenu, setContextMenu] = useState<ContextMenuState | null>(null)
  const [renamingPath, setRenamingPath] = useState<string | null>(null)
  const [renameValue, setRenameValue] = useState('')
  const [creatingName, setCreatingName] = useState('')
  // 在指定目录中新建文件/文件夹的内联输入框状态
  // null = 未激活，'' = 根目录，'path/to/folder' = 指定目录
  const [creatingInDir, setCreatingInDir] = useState<string | null>(null)
  // 当前选中的文件夹路径，用于工具栏“新建”按钮的目标位置
  const [activeFolder, setActiveFolder] = useState<string | null>(null)
  const menuRef = useRef<HTMLDivElement>(null)

  // 加载根目录列表
  const loadRoots = useCallback(async () => {
    try {
      const data = await api.getWorkspaceRoots()
      setRoots(data)
      const firstExists = data.findIndex(r => r.exists)
      if (firstExists >= 0) {
        setActiveRoot(firstExists)
      }
    } catch {
      // 加载失败不阻塞 UI
    }
  }, [])

  useEffect(() => { loadRoots() }, [loadRoots])

  // 加载指定根目录的内容，默认展开前 4 层目录
  const loadRootContent = useCallback(async (rootIndex: number) => {
    setLoading(true)
    setSelectedPath(null)
    setActiveFolder(null)
    try {
      const resp = await api.listFiles(rootIndex, '')
      // 递归加载并展开目录（最多展开 maxDepth 层）
      const loadAndExpand = async (items: FileInfo[], currentDepth: number, parentPath: string): Promise<TreeNode[]> => {
        const nodes: TreeNode[] = []
        for (const item of items) {
          if (item.is_dir && currentDepth < 3) {
            // 目录且未达到最大深度，递归加载子节点并展开
            const childPath = parentPath ? `${parentPath}/${item.name}` : item.name
            let children: TreeNode[] = []
            try {
              const childResp = await api.listFiles(rootIndex, childPath)
              children = await loadAndExpand(childResp.items, currentDepth + 1, childPath)
            } catch {
              children = []
            }
            nodes.push({
              file: item,
              children,
              expanded: true,
              loading: false,
            })
          } else if (item.is_dir) {
            // 目录但已达到最大深度，不自动展开
            nodes.push({
              file: item,
              children: null,
              expanded: false,
              loading: false,
            })
          } else {
            // 文件
            nodes.push({
              file: item,
              children: undefined as unknown as null,
              expanded: false,
              loading: false,
            })
          }
        }
        return nodes
      }
      const nodes = await loadAndExpand(resp.items, 0, '')
      setTreeNodes(nodes)
    } catch {
      setTreeNodes([])
    } finally {
      setLoading(false)
    }
  }, [])

  // 切换根目录时重新加载
  useEffect(() => {
    if (roots.length > 0) {
      loadRootContent(activeRoot)
    }
  }, [activeRoot, roots.length, loadRootContent])

  const loadChildren = useCallback(async (node: TreeNode, rootIndex: number): Promise<TreeNode[]> => {
    try {
      const resp = await api.listFiles(rootIndex, node.file.path)
      return resp.items.map((item) => ({
        file: item,
        children: item.is_dir ? null : undefined as unknown as null,
        expanded: false,
        loading: false,
      }))
    } catch {
      return []
    }
  }, [])

  const toggleNode = useCallback(async (path: string) => {
    const updateNodes = async (nodes: TreeNode[]): Promise<TreeNode[]> => {
      const result: TreeNode[] = []
      for (const node of nodes) {
        if (node.file.path === path) {
          if (node.expanded) {
            result.push({ ...node, expanded: false })
          } else {
            let children = node.children
            if (children === null) {
              result.push({ ...node, expanded: true, loading: true })
              children = await loadChildren(node, activeRoot)
              result[result.length - 1] = {
                ...result[result.length - 1],
                children,
                loading: false,
                expanded: true,
              }
            } else {
              result.push({ ...node, expanded: true, children })
            }
          }
        } else if (node.children) {
          result.push({
            ...node,
            children: await updateNodes(node.children),
          })
        } else {
          result.push(node)
        }
      }
      return result
    }

    setTreeNodes(await updateNodes(treeNodes))
  }, [treeNodes, loadChildren, activeRoot])

  const handleFileClick = useCallback((node: TreeNode) => {
    if (node.file.is_dir) {
      toggleNode(node.file.path)
      // 记录当前选中的文件夹，供工具栏“新建”按钮使用
      setActiveFolder(node.file.path)
      // 选中文件夹时清除文件选中状态
      setSelectedPath(null)
    } else {
      setSelectedPath(node.file.path)
      // 选中文件时清除文件夹选中状态
      setActiveFolder(null)
      onFileSelect?.(node.file, activeRoot)
    }
  }, [toggleNode, onFileSelect, activeRoot])

  // 点击根目录标题：切换展开/折叠
  const handleRootClick = useCallback((index: number) => {
    if (index === activeRoot) {
      // 点击已展开的根目录时折叠（设为 -1 表示全部折叠）
      setActiveRoot(-1)
    } else {
      setActiveRoot(index)
    }
  }, [activeRoot])

  // 右键菜单
  const handleContextMenu = useCallback((e: React.MouseEvent, node: TreeNode | null, isRoot?: boolean, rootIndex?: number) => {
    e.preventDefault()
    e.stopPropagation()
    setContextMenu({ x: e.clientX, y: e.clientY, node, isRoot, rootIndex })
  }, [])

  // 关闭右键菜单
  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setContextMenu(null)
      }
    }
    if (contextMenu) {
      document.addEventListener('mousedown', handleClickOutside)
    }
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [contextMenu])

  // 新建文件/文件夹
  const handleCreate = useCallback(async (parentPath: string, name: string, isDir: boolean) => {
    try {
      await api.createFileOrFolder(activeRoot, parentPath, name, isDir)
      loadRootContent(activeRoot)
    } catch {
      // ignore
    }
  }, [activeRoot, loadRootContent])

  // 删除
  const handleDelete = useCallback(async (path: string) => {
    try {
      await api.deleteFileOrFolder(activeRoot, path)
      if (selectedPath === path) setSelectedPath(null)
      loadRootContent(activeRoot)
    } catch {
      // ignore
    }
  }, [activeRoot, selectedPath, loadRootContent])

  // 重命名
  const handleRename = useCallback(async (oldPath: string, newName: string) => {
    try {
      await api.renameFileOrFolder(activeRoot, oldPath, newName)
      if (selectedPath === oldPath) setSelectedPath(null)
      loadRootContent(activeRoot)
    } catch {
      // ignore
    }
  }, [activeRoot, selectedPath, loadRootContent])

  return (
    <div className="flex h-full flex-col bg-background">
      {/* 根目录手风琴列表 + 文件树 */}
      <div className="flex-1 overflow-y-auto">
        {roots.length === 0 ? (
          <div className="flex items-center justify-center py-8">
            <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
          </div>
        ) : (
          roots.map((root, i) => (
            <div key={i}>
              {/* 根目录标题行 */}
              <div
                onClick={() => root.exists && handleRootClick(i)}
                onContextMenu={(e) => root.exists && handleContextMenu(e, null, true, i)}
                className={cn(
                  'flex items-center gap-2 px-3 py-2 transition-colors border-b border-border/40',
                  root.exists ? 'cursor-pointer' : 'cursor-not-allowed',
                  i === activeRoot && root.exists
                    ? 'bg-primary/8 text-primary font-medium'
                    : root.exists
                      ? 'hover:bg-accent/60 text-muted-foreground'
                      : 'text-muted-foreground/40',
                )}
                title={root.path}
              >
                {/* 展开/折叠箭头 */}
                <ChevronRight
                  className={cn(
                    'h-3 w-3 shrink-0 transition-transform duration-150',
                    i === activeRoot && root.exists && 'rotate-90',
                  )}
                />
                {getRootIcon(root.label)}
                <span className="text-xs truncate flex-1">{root.label}</span>
                {/* 工具栏按钮（仅展开时显示） */}
                {i === activeRoot && root.exists && (
                  <div className="flex items-center gap-1 shrink-0">
                    {/* 新建文件按钮：在当前选中的文件夹内创建，如果没有选中则在顶部创建 */}
                    <button
                      onClick={(e) => {
                        e.stopPropagation()
                        // 如果选中了文件夹则在内部创建，否则在顶部创建
                        setCreatingInDir(activeFolder || '')
                        setCreatingName('')
                      }}
                      className="rounded-md p-1 text-muted-foreground hover:text-foreground hover:bg-accent/60 transition-colors"
                      title={activeFolder ? `在 ${activeFolder.split('/').pop()} 中新建文件` : '新建文件'}
                    >
                      <FilePlus className="h-3 w-3" />
                    </button>
                    {/* 新建文件夹按钮：同上逻辑 */}
                    <button
                      onClick={(e) => {
                        e.stopPropagation()
                        // 如果选中了文件夹则在内部创建，否则在顶部创建
                        setCreatingInDir(activeFolder || '')
                        setCreatingName('')
                      }}
                      className="rounded-md p-1 text-muted-foreground hover:text-foreground hover:bg-accent/60 transition-colors"
                      title={activeFolder ? `在 ${activeFolder.split('/').pop()} 中新建文件夹` : '新建文件夹'}
                    >
                      <FolderPlus className="h-3 w-3" />
                    </button>
                    {/* 刷新按钮 */}
                    <button
                      onClick={(e) => { e.stopPropagation(); loadRootContent(i) }}
                      className="rounded-md p-1 text-muted-foreground hover:text-foreground hover:bg-accent/60 transition-colors"
                      title="刷新"
                    >
                      <RefreshCw className={cn('h-3 w-3', loading && 'animate-spin')} />
                    </button>
                  </div>
                )}
              </div>

              {/* 展开时：新建输入框 + 文件树 */}
              {i === activeRoot && root.exists && (
                <div>
                  {/* 根目录级新建输入框：当 creatingInDir 为空字符串时显示在文件树顶部 */}
                  {creatingInDir === '' && (
                    <div className="flex items-center gap-1.5 px-3 py-1.5 bg-accent/30 border-b border-border/30">
                      <File className="h-3 w-3 text-muted-foreground shrink-0" />
                      <input
                        value={creatingName}
                        onChange={(e) => setCreatingName(e.target.value)}
                        onKeyDown={(e) => {
                          if (e.key === 'Enter' && creatingName.trim()) {
                            handleCreate('', creatingName.trim(), false)
                            setCreatingInDir(null)
                            setCreatingName('')
                          } else if (e.key === 'Escape') {
                            setCreatingInDir(null)
                            setCreatingName('')
                          }
                        }}
                        placeholder="文件名（回车创建）..."
                        className="flex-1 h-5 text-xs rounded border bg-background px-1.5 placeholder:text-muted-foreground/50"
                        autoFocus
                      />
                    </div>
                  )}

                  {/* 文件树内容 */}
                  {loading && treeNodes.length === 0 ? (
                    <div className="flex items-center justify-center py-6">
                      <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" />
                    </div>
                  ) : treeNodes.length === 0 ? (
                    <div className="px-4 py-6 text-center">
                      <Folder className="mx-auto h-6 w-6 text-muted-foreground/30" />
                      <p className="mt-1.5 text-[10px] text-muted-foreground">目录为空</p>
                    </div>
                  ) : (
                    <div className="py-0.5">
                      {treeNodes.map((node) => (
                        <TreeNodeItem
                          key={node.file.path}
                          node={node}
                          depth={0}
                          selectedPath={selectedPath}
                          activeFolder={activeFolder}
                          onSelect={handleFileClick}
                          onContextMenu={handleContextMenu}
                          renamingPath={renamingPath}
                          renameValue={renameValue}
                          onRenameChange={setRenameValue}
                          onRenameConfirm={() => {
                            if (renamingPath && renameValue.trim()) {
                              handleRename(renamingPath, renameValue.trim())
                            }
                            setRenamingPath(null)
                          }}
                          onRenameCancel={() => setRenamingPath(null)}
                          onStartRename={(path, name) => { setRenamingPath(path); setRenameValue(name) }}
                          onCreateInDir={(dirPath) => { setCreatingInDir(dirPath); setCreatingName('') }}
                          onDelete={handleDelete}
                          activeRoot={activeRoot}
                          creatingInDir={creatingInDir}
                          creatingName={creatingName}
                          onCreatingNameChange={setCreatingName}
                          onCreatingConfirm={(parentPath, name, isDir) => {
                            handleCreate(parentPath, name, isDir)
                            setCreatingInDir(null)
                          }}
                          onCreatingCancel={() => setCreatingInDir(null)}
                        />
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>
          ))
        )}
      </div>

      {/* 右键上下文菜单 */}
      {contextMenu && (
        <div
          ref={menuRef}
          className="fixed z-50 min-w-[140px] rounded-md border border-border/60 bg-background py-1 shadow-lg"
          style={{ left: contextMenu.x, top: contextMenu.y }}
        >
          {(contextMenu.node?.file.is_dir || contextMenu.isRoot) && (
            <>
              <MenuItem
                icon={<FilePlus className="h-3 w-3" />}
                label="新建文件"
                onClick={() => {
                  const parentPath = contextMenu.node?.file.path || ''
                  setCreatingInDir(parentPath)
                  setCreatingName('')
                  setContextMenu(null)
                }}
              />
              <MenuItem
                icon={<FolderPlus className="h-3 w-3" />}
                label="新建文件夹"
                onClick={() => {
                  const parentPath = contextMenu.node?.file.path || ''
                  setCreatingInDir(parentPath)
                  setCreatingName('')
                  setContextMenu(null)
                }}
              />
              <div className="my-1 border-t border-border/40" />
            </>
          )}
          {contextMenu.node && !contextMenu.isRoot && (
            <>
              <MenuItem
                icon={<Pencil className="h-3 w-3" />}
                label="重命名"
                onClick={() => {
                  if (contextMenu.node) {
                    setRenamingPath(contextMenu.node.file.path)
                    setRenameValue(contextMenu.node.file.name)
                  }
                  setContextMenu(null)
                }}
              />
              <MenuItem
                icon={<Trash2 className="h-3 w-3" />}
                label="删除"
                danger
                onClick={() => {
                  if (contextMenu.node && confirm(`确定删除「${contextMenu.node.file.name}」？`)) {
                    handleDelete(contextMenu.node.file.path)
                  }
                  setContextMenu(null)
                }}
              />
            </>
          )}
        </div>
      )}
    </div>
  )
}

/** 菜单项。 */
function MenuItem({ icon, label, onClick, danger }: {
  icon: React.ReactNode
  label: string
  onClick: () => void
  danger?: boolean
}) {
  return (
    <button
      onClick={onClick}
      className={cn(
        'flex w-full items-center gap-2 px-2.5 py-1 text-xs transition-colors',
        danger
          ? 'text-red-600 hover:bg-red-50'
          : 'text-foreground hover:bg-accent',
      )}
    >
      {icon}
      {label}
    </button>
  )
}

/** 递归渲染树节点。 */
function TreeNodeItem({
  node,
  depth,
  selectedPath,
  onSelect,
  onContextMenu,
  renamingPath,
  renameValue,
  onRenameChange,
  onRenameConfirm,
  onRenameCancel,
  onStartRename,
  onCreateInDir,
  onDelete,
  activeRoot,
  creatingInDir,
  creatingName,
  onCreatingNameChange,
  onCreatingConfirm,
  onCreatingCancel,
  activeFolder,
}: {
  node: TreeNode
  depth: number
  selectedPath: string | null
  activeFolder: string | null
  onSelect: (node: TreeNode) => void
  onContextMenu: (e: React.MouseEvent, node: TreeNode) => void
  renamingPath: string | null
  renameValue: string
  onRenameChange: (v: string) => void
  onRenameConfirm: () => void
  onRenameCancel: () => void
  onStartRename: (path: string, name: string) => void
  onCreateInDir: (dirPath: string) => void
  onDelete: (path: string) => void
  activeRoot: number
  creatingInDir: string | null
  creatingName: string
  onCreatingNameChange: (v: string) => void
  onCreatingConfirm: (parentPath: string, name: string, isDir: boolean) => void
  onCreatingCancel: () => void
}) {
  // 文件选中状态：当前节点是文件且路径匹配
  const isFileSelected = node.file.path === selectedPath && !node.file.is_dir
  // 文件夹选中状态：当前节点是文件夹且路径匹配 activeFolder
  const isFolderSelected = node.file.is_dir && node.file.path === activeFolder
  // 综合选中状态（文件或文件夹）
  const isSelected = isFileSelected || isFolderSelected
  const isRenaming = renamingPath === node.file.path
  const isCreatingHere = creatingInDir === node.file.path

  return (
    <>
      <div
        className={cn(
          'flex items-center gap-1.5 cursor-pointer py-1 pr-2 transition-colors',
          'hover:bg-accent/50',
          isSelected && 'bg-primary/15 text-primary hover:bg-primary/20',
        )}
        style={{ paddingLeft: `${depth * 16 + 16}px` }}
        onClick={() => !isRenaming && onSelect(node)}
        onContextMenu={(e) => onContextMenu(e, node)}
      >
        {/* 展开/折叠箭头（目录） */}
        {node.file.is_dir ? (
          <ChevronRight
            className={cn(
              'h-3 w-3 text-muted-foreground transition-transform duration-150 shrink-0',
              node.expanded && 'rotate-90',
            )}
          />
        ) : (
          <span className="w-3 shrink-0" />
        )}

        {/* 加载状态 */}
        {node.loading ? (
          <Loader2 className="h-3.5 w-3.5 animate-spin text-muted-foreground shrink-0" />
        ) : (
          getFileIcon(node.file.name, node.file.is_dir, node.expanded)
        )}

        {/* 文件名 / 重命名输入框 */}
        {isRenaming ? (
          <input
            value={renameValue}
            onChange={(e) => onRenameChange(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter') onRenameConfirm()
              else if (e.key === 'Escape') onRenameCancel()
            }}
            onBlur={onRenameConfirm}
            className="flex-1 h-4 text-xs rounded border bg-background px-1"
            autoFocus
            onClick={(e) => e.stopPropagation()}
          />
        ) : (
          <span className="truncate text-xs">{node.file.name}</span>
        )}

        {/* 文件大小（仅文件） */}
        {!node.file.is_dir && node.file.size > 0 && !isRenaming && (
          <span className="ml-auto shrink-0 text-[10px] text-muted-foreground/60">
            {node.file.size < 1024
              ? `${node.file.size}B`
              : node.file.size < 1024 * 1024
                ? `${(node.file.size / 1024).toFixed(1)}K`
                : `${(node.file.size / 1024 / 1024).toFixed(1)}M`}
          </span>
        )}
      </div>

      {/* 目录内新建输入框 */}
      {node.file.is_dir && node.expanded && isCreatingHere && (
        <div
          className="flex items-center gap-1.5 py-1"
          style={{ paddingLeft: `${(depth + 1) * 16 + 16}px` }}
        >
          <File className="h-3 w-3 text-muted-foreground shrink-0" />
          <input
            value={creatingName}
            onChange={(e) => onCreatingNameChange(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && creatingName.trim()) {
                onCreatingConfirm(node.file.path, creatingName.trim(), false)
              } else if (e.key === 'Escape') {
                onCreatingCancel()
              }
            }}
            placeholder="文件名..."
            className="flex-1 h-4 text-xs rounded border bg-background px-1 mr-2 placeholder:text-muted-foreground/50"
            autoFocus
          />
        </div>
      )}

      {/* 子节点 */}
      {node.expanded && node.children?.map((child) => (
        <TreeNodeItem
          key={child.file.path}
          node={child}
          depth={depth + 1}
          selectedPath={selectedPath}
          activeFolder={activeFolder}
          onSelect={onSelect}
          onContextMenu={onContextMenu}
          renamingPath={renamingPath}
          renameValue={renameValue}
          onRenameChange={onRenameChange}
          onRenameConfirm={onRenameConfirm}
          onRenameCancel={onRenameCancel}
          onStartRename={onStartRename}
          onCreateInDir={onCreateInDir}
          onDelete={onDelete}
          activeRoot={activeRoot}
          creatingInDir={creatingInDir}
          creatingName={creatingName}
          onCreatingNameChange={onCreatingNameChange}
          onCreatingConfirm={onCreatingConfirm}
          onCreatingCancel={onCreatingCancel}
        />
      ))}
    </>
  )
}
