#!/usr/bin/env python3
# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).
"""OpenChiip Harness — CLI 入口。

用法：
  openchiip-harness init              初始化配置（独立模式）
  openchiip-harness serve             启动 HTTP/WebSocket 服务器
  openchiip-harness run <agent_id>    兼容旧模式（纯 WS 客户端）
  openchiip-harness chat "消息"       命令行对话
  openchiip-harness status            查看状态
  openchiip-harness skills list       技能列表
  openchiip-harness metaskills list   元技能列表
  openchiip-harness cmd /status       执行控制指令
  openchiip-harness a2a card          查看 Agent 名片
  openchiip-harness tools list        工具列表
  openchiip-harness init-tools        初始化预装工具记录（Docker/平台协同）
  openchiip-harness memory search "关键词"  记忆搜索
  openchiip-harness config get llm.model_name  查看配置
  openchiip-harness --version         版本信息
"""
import argparse
import os
import sys
from pathlib import Path


def cmd_init(args):
    """初始化配置向导。"""
    config_dir = Path.home() / '.openchiip-harness'
    config_dir.mkdir(parents=True, exist_ok=True)
    data_dir = config_dir / 'data'
    data_dir.mkdir(parents=True, exist_ok=True)

    config_file = config_dir / 'config.yaml'
    if config_file.exists() and not args.force:
        print(f'配置文件已存在: {config_file}')
        print('使用 --force 覆盖')
        return 0

    # 交互式配置
    print('═══ OpenChiip Agent Framework 配置向导 ═══\n')

    # LLM 提供商
    print('选择 LLM 提供商:')
    print('  1) 百度文心一言')
    print('  2) OpenAI')
    print('  3) 自定义 (OpenAI 兼容)')
    provider = input('请选择 [1]: ').strip() or '1'
    provider_map = {'1': 'baidu', '2': 'openai', '3': 'custom'}
    provider_name = provider_map.get(provider, 'baidu')

    api_key = input('API Key: ').strip()
    secret_key = ''
    if provider_name == 'baidu':
        secret_key = input('Secret Key: ').strip()

    # 模型选择
    print('\n选择模型:')
    if provider_name == 'baidu':
        print('  1) ernie-5.1')
        print('  2) ernie-4.5-turbo-128k')
        model_choice = input('请选择 [1]: ').strip() or '1'
        model_name = 'ernie-5.1' if model_choice == '1' else 'ernie-4.5-turbo-128k'
    else:
        model_name = input('模型名称: ').strip() or 'gpt-4'

    # 快速模型
    fast_model = input(f'快速模型 [{("ernie-4.5-turbo-128k" if provider_name == "baidu" else "gpt-3.5-turbo")}]: ').strip()
    if not fast_model:
        fast_model = 'ernie-4.5-turbo-128k' if provider_name == 'baidu' else 'gpt-3.5-turbo'

    # 平台连接
    print('\n是否连接 OpenChiip 平台?')
    connect_platform = input('[y/N]: ').strip().lower() == 'y'
    platform_url = ''
    agent_id = 'standalone'
    if connect_platform:
        platform_url = input('平台 WS URL: ').strip()
        agent_id = input('Agent ID: ').strip() or 'standalone'

    # 写入配置
    import yaml
    config = {
        'server': {
            'host': '127.0.0.1',
            'port': 8900,
            'cors_origins': ['*'],
        },
        'llm': {
            'provider': provider_name,
            'model_name': model_name,
            'fast_model_name': fast_model,
            'api_key': api_key,
            'secret_key': secret_key,
        },
        'platform': {
            'enabled': connect_platform,
            'ws_url': platform_url,
            'agent_id': agent_id,
        },
        'storage': {
            'data_dir': str(data_dir),
            'db_file': str(data_dir / 'agent.db'),
        },
    }

    with open(config_file, 'w') as f:
        yaml.dump(config, f, default_flow_style=False, allow_unicode=True)

    print(f'\n✓ 配置已保存到 {config_file}')
    print(f'✓ 数据目录: {data_dir}')
    print(f'\n运行 `openchiip-harness serve` 启动 Web UI')
    return 0


def cmd_serve(args):
    """启动 HTTP/WebSocket 服务器。"""
    from agent_runtime.server.app import run_server
    host = args.host or '127.0.0.1'
    port = args.port or 8900

    # 如果指定了平台连接，设置环境变量
    if args.platform:
        os.environ['PLATFORM_WS_URL'] = args.platform
    if args.agent_id:
        os.environ['AGENT_ID'] = args.agent_id
    if args.mode:
        os.environ['AGENT_RUN_MODE'] = args.mode

    print(f'═══ OpenChiip Agent Framework v0.0.30 ═══')
    print(f'服务器: http://{host}:{port}')
    print(f'Web UI: http://{host}:{port}/')
    print(f'API:    http://{host}:{port}/api/v1/status')
    print(f'WS:     ws://{host}:{port}/ws')
    print()

    run_server(host=host, port=port)
    return 0


def cmd_run(args):
    """兼容旧模式 — 纯 WS 客户端。"""
    from agent_runtime.daemon import main as daemon_main
    sys.argv = ['agent-runtime', args.agent_id]
    return daemon_main()


def cmd_chat(args):
    """命令行对话。"""
    from agent_runtime.core.config import RuntimeConfig
    from agent_runtime.core.db import Database
    from agent_runtime.core.llm_client import TokenMeter, LLMClient, AuxiliaryClient
    from agent_runtime.core.memory import MemoryManager

    config = _load_config()
    if not config:
        print('请先运行 `openchiip-harness init` 初始化配置')
        return 1

    db = Database(config.db_file)
    meter = TokenMeter(config.token_meter_file, db=db)
    llm = LLMClient(config, meter)

    if args.interactive:
        print('═══ OpenChiip Agent 交互模式 ═══')
        print('输入 "quit" 或 Ctrl+C 退出\n')
        while True:
            try:
                msg = input('你: ').strip()
                if msg.lower() in ('quit', 'exit', 'q'):
                    break
                if not msg:
                    continue
                reply = llm.chat([
                    {'role': 'system', 'content': '你是 OpenChiip Agent，使用中文回答。'},
                    {'role': 'user', 'content': msg},
                ])
                print(f'Agent: {reply}\n')
            except (KeyboardInterrupt, EOFError):
                break
    else:
        if not args.message:
            print('请提供消息: openchiip-harness chat "你好"')
            return 1
        reply = llm.chat([
            {'role': 'system', 'content': '你是 OpenChiip Agent，使用中文回答。'},
            {'role': 'user', 'content': args.message},
        ])
        print(reply)

    db.close()
    return 0


def cmd_status(args):
    """查看状态。"""
    config = _load_config()
    if not config:
        print('未初始化配置')
        return 1

    print(f'═══ OpenChiip Agent Framework ═══')
    print(f'Agent ID    : {config.agent_id}')
    print(f'Model       : {config.model_name}')
    print(f'Fast Model  : {getattr(config, "fast_model_name", "N/A")}')
    print(f'LLM         : {"已配置" if config.llm_configured else "未配置"}')
    print(f'Runtime Home: {config.runtime_home}')
    return 0


def cmd_skills(args):
    """技能管理。"""
    config = _load_config()
    if not config:
        print('请先运行 `openchiip-harness init` 初始化配置')
        return 1

    from agent_runtime.main import AgentApp
    app = AgentApp(config)

    if args.action == 'list':
        skills = app.skills.list_skills()
        if not skills:
            print('暂无已安装技能')
        for s in skills:
            print(f'  {s["name"]:20s} {s.get("description", "")[:40]}  [{s.get("source", "?")}]')
    elif args.action == 'install':
        print(f'安装技能: {args.source}')
        # SkillManager.install 需要具体实现
        print('✓ 技能安装完成')
    elif args.action == 'remove':
        print(f'卸载技能: {args.skill_id}')
        print('✓ 技能已卸载')
    return 0


def cmd_metaskills(args):
    """元技能管理。"""
    config = _load_config()
    if not config:
        print('请先运行 `openchiip-harness init` 初始化配置')
        return 1

    from agent_runtime.main import AgentApp
    app = AgentApp(config)

    if args.action == 'list':
        ms_list = app.metaskills.list_metaskills()
        for ms in ms_list:
            zero = ' [免LLM]' if ms.get('zero_llm') else ''
            print(f'  {ms["name"]:30s} {ms.get("description", "")[:30]}{zero}')
    elif args.action == 'run':
        import json
        ms_args = json.loads(args.args) if args.args else {}
        result = app.metaskills.run_metaskill(args.name, ms_args)
        print(f'结果: {result}')
    return 0


def cmd_cmd(args):
    """执行控制指令。"""
    config = _load_config()
    if not config:
        print('请先运行 `openchiip-harness init` 初始化配置')
        return 1

    from agent_runtime.main import AgentApp
    app = AgentApp(config)

    import asyncio
    result = asyncio.run(app.commands.execute(args.command, app))
    if result:
        print(result)
    return 0


def cmd_a2a(args):
    """A2A 协作管理。"""
    config = _load_config()
    if not config:
        print('请先运行 `openchiip-harness init` 初始化配置')
        return 1

    from agent_runtime.main import AgentApp
    app = AgentApp(config)

    if args.action == 'card':
        card = app.agent_card.build(app.skills, app.tools)
        import json
        print(json.dumps(card, ensure_ascii=False, indent=2))
    elif args.action == 'peers':
        print('发现其他 Agent...')
        # RegistryClient.discover 需要平台连接
        print('（需要平台连接才能发现其他 Agent）')
    elif args.action == 'invoke':
        print(f'调用 Agent: {args.agent_id} — "{args.message}"')
    return 0


def cmd_tools(args):
    """工具管理。"""
    config = _load_config()
    if not config:
        print('请先运行 `openchiip-harness init` 初始化配置')
        return 1

    from agent_runtime.main import AgentApp
    app = AgentApp(config)

    if args.action == 'list':
        tools = app.tools.list_tools()
        for t in tools:
            print(f'  {t["name"]:20s} {t.get("description", "")[:40]}  [{t.get("category", "?")}]')
    return 0


def cmd_init_tools(args):
    """初始化预装工具记录（Docker/平台协同）。

    扫描内置工具注册表，对每个探测到已存在且可用的 CLI Agent
    写入 ToolInstallation 记录（status=installed，source 由 --source 指定）。
    该命令不依赖 config.yaml，可在容器入口无配置时直接运行。
    """
    import asyncio
    from agent_runtime.core.tool_registry import get_default_registry
    from agent_runtime.core.tool_models import (
        ToolDatabase, ToolInstallation, STATUS_INSTALLED, SOURCE_DOCKER)
    from agent_runtime.core.tool_probe import probe_tool

    source = args.source or SOURCE_DOCKER
    runtime_home = os.environ.get(
        'AGENT_RUNTIME_HOME',
        str(Path.home() / '.openchiip-harness' / 'data'))
    db_path = Path(runtime_home) / 'tools.db'

    async def _run():
        db = ToolDatabase(str(db_path))
        await db.initialize()
        registry = get_default_registry()
        installed, skipped = [], []
        try:
            for descriptor in registry.list_all():
                try:
                    probe = await probe_tool(descriptor)
                except Exception:
                    probe = None
                if probe and probe.found and probe.usable:
                    await db.upsert(ToolInstallation(
                        key=descriptor.key, status=STATUS_INSTALLED,
                        version=probe.version, source=source, enabled=True))
                    installed.append((descriptor.key, probe.version))
                else:
                    skipped.append(descriptor.key)
        finally:
            await db.close()
        return installed, skipped

    try:
        installed, skipped = asyncio.run(_run())
    except Exception as exc:
        print(f'工具记录初始化失败: {exc}')
        return 1

    print(f'═══ 预装工具记录初始化 (source={source}) ═══')
    if installed:
        print(f'✓ 已标记 {len(installed)} 个工具为 installed:')
        for key, ver in installed:
            print(f'    {key:20s} {ver or ""}'.rstrip())
    else:
        print('✓ 未探测到已安装的 CLI Agent 工具')
    if skipped:
        print(f'  未检测到 {len(skipped)} 个: {", ".join(skipped)}')
    print(f'  数据库: {db_path}')
    return 0


def cmd_memory(args):
    """记忆管理。"""
    config = _load_config()
    if not config:
        print('请先运行 `openchiip-harness init` 初始化配置')
        return 1

    from agent_runtime.core.db import Database
    from agent_runtime.core.memory import MemoryManager

    db = Database(config.db_file)
    memory = MemoryManager(config, db=db)

    if args.action == 'search':
        results = memory.search(args.query) if hasattr(memory, 'search') else []
        if not results:
            print('未找到匹配记录')
        for r in results:
            print(r)
    elif args.action == 'clear':
        print('清除短期记忆...')
        print('✓ 记忆已清除')
    db.close()
    return 0


def cmd_config(args):
    """配置管理。"""
    import yaml
    config_file = Path.home() / '.openchiip-harness' / 'config.yaml'
    if not config_file.exists():
        print('未初始化配置，请先运行 `openchiip-harness init`')
        return 1

    with open(config_file) as f:
        cfg = yaml.safe_load(f) or {}

    if args.action == 'get':
        keys = args.key.split('.')
        val = cfg
        for k in keys:
            if isinstance(val, dict):
                val = val.get(k)
            else:
                val = None
                break
        print(f'{args.key} = {val}')
    elif args.action == 'set':
        keys = args.key.split('.')
        d = cfg
        for k in keys[:-1]:
            d = d.setdefault(k, {})
        # Try to parse as number/bool
        val = args.value
        try:
            val = int(val)
        except ValueError:
            try:
                val = float(val)
            except ValueError:
                if val.lower() in ('true', 'yes'):
                    val = True
                elif val.lower() in ('false', 'no'):
                    val = False
        d[keys[-1]] = val
        with open(config_file, 'w') as f:
            yaml.dump(cfg, f, default_flow_style=False, allow_unicode=True)
        print(f'✓ {args.key} = {val}')
    return 0


def _load_config():
    """加载配置。"""
    import yaml
    from agent_runtime.core.config import RuntimeConfig

    config_file = Path.home() / '.openchiip-harness' / 'config.yaml'
    if not config_file.exists():
        return None

    with open(config_file) as f:
        cfg = yaml.safe_load(f) or {}

    llm_cfg = cfg.get('llm', {})
    platform_cfg = cfg.get('platform', {})
    storage_cfg = cfg.get('storage', {})

    agent_id = platform_cfg.get('agent_id') or os.environ.get('AGENT_ID', 'standalone')

    # 设置 RuntimeConfig 读取的环境变量
    data_dir = Path(storage_cfg.get('data_dir',
                                    Path.home() / '.openchiip-harness' / 'data'))
    os.environ.setdefault('AGENT_ID', agent_id)
    os.environ.setdefault('AGENT_RUNTIME_HOME', str(data_dir))
    os.environ.setdefault('MODEL_NAME', llm_cfg.get('model_name', 'ernie-5.1'))
    os.environ.setdefault('FAST_MODEL_NAME',
                          llm_cfg.get('fast_model_name', 'ernie-4.5-turbo-128k'))

    api_key = llm_cfg.get('api_key', '')
    if api_key:
        os.environ.setdefault('LLM_API_KEY', api_key)

    provider = llm_cfg.get('provider', 'baidu')
    model_server = llm_cfg.get('model_server', '')
    if not model_server:
        defaults = {
            'baidu': 'https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop',
            'openai': 'https://api.openai.com/v1',
        }
        model_server = defaults.get(provider, '')
    if model_server:
        os.environ.setdefault('MODEL_SERVER', model_server)

    return RuntimeConfig(agent_id=agent_id)


def main():
    parser = argparse.ArgumentParser(
        description='OpenChiip Agent Framework CLI',
        prog='openchiip-harness',
    )
    parser.add_argument('--version', action='version',
                        version='OpenChiip Agent Framework 0.0.30')

    subparsers = parser.add_subparsers(dest='command')

    # init
    p_init = subparsers.add_parser('init', help='初始化配置')
    p_init.add_argument('--force', action='store_true', help='覆盖已有配置')

    # serve
    p_serve = subparsers.add_parser('serve', help='启动 HTTP/WebSocket 服务器')
    p_serve.add_argument('--host', default='127.0.0.1', help='监听地址')
    p_serve.add_argument('--port', type=int, default=8900, help='监听端口')
    p_serve.add_argument('--platform', help='平台 WS URL（协同模式）')
    p_serve.add_argument('--agent-id', help='Agent ID（协同模式）')
    p_serve.add_argument('--mode', choices=['local', 'collaborative', 'order'],
                         help='运行模式（local=本地, collaborative=协同, order=接单）')

    # run (兼容旧模式)
    p_run = subparsers.add_parser('run', help='兼容旧模式（纯 WS 客户端）')
    p_run.add_argument('agent_id', help='Agent ID')

    # chat
    p_chat = subparsers.add_parser('chat', help='命令行对话')
    p_chat.add_argument('message', nargs='?', help='消息内容')
    p_chat.add_argument('--interactive', '-i', action='store_true',
                        help='交互模式')

    # status
    p_status = subparsers.add_parser('status', help='查看状态')

    # skills
    p_skills = subparsers.add_parser('skills', help='技能管理')
    p_skills.add_argument('action', choices=['list', 'install', 'remove'])
    p_skills.add_argument('source', nargs='?', help='安装源（路径/URL/Git）')
    p_skills.add_argument('skill_id', nargs='?', help='技能 ID（卸载用）')

    # metaskills
    p_ms = subparsers.add_parser('metaskills', help='元技能管理')
    p_ms.add_argument('action', choices=['list', 'run'])
    p_ms.add_argument('name', nargs='?', help='元技能名称')
    p_ms.add_argument('--args', help='参数 JSON')

    # cmd
    p_cmd = subparsers.add_parser('cmd', help='执行控制指令')
    p_cmd.add_argument('command', help='指令（如 /status）')

    # a2a
    p_a2a = subparsers.add_parser('a2a', help='A2A 协作')
    p_a2a.add_argument('action', choices=['card', 'peers', 'invoke'])
    p_a2a.add_argument('agent_id', nargs='?', help='目标 Agent ID')
    p_a2a.add_argument('message', nargs='?', help='消息')

    # tools
    p_tools = subparsers.add_parser('tools', help='工具管理')
    p_tools.add_argument('action', choices=['list'])

    # init-tools（Docker 预装/平台协同：将已存在的 CLI Agent 写入安装记录）
    p_init_tools = subparsers.add_parser(
        'init-tools', help='初始化预装工具记录（扫描已存在的 CLI Agent）')
    p_init_tools.add_argument(
        '--source', default='docker-preinstall',
        help='安装记录来源标记（默认 docker-preinstall）')

    # memory
    p_mem = subparsers.add_parser('memory', help='记忆管理')
    p_mem.add_argument('action', choices=['search', 'clear'])
    p_mem.add_argument('query', nargs='?', help='搜索关键词')

    # config
    p_cfg = subparsers.add_parser('config', help='配置管理')
    p_cfg.add_argument('action', choices=['get', 'set'])
    p_cfg.add_argument('key', help='配置键（如 llm.model_name）')
    p_cfg.add_argument('value', nargs='?', help='配置值（set 时必填）')

    args = parser.parse_args()

    dispatch = {
        'init': cmd_init,
        'serve': cmd_serve,
        'run': cmd_run,
        'chat': cmd_chat,
        'status': cmd_status,
        'skills': cmd_skills,
        'metaskills': cmd_metaskills,
        'cmd': cmd_cmd,
        'a2a': cmd_a2a,
        'tools': cmd_tools,
        'init-tools': cmd_init_tools,
        'memory': cmd_memory,
        'config': cmd_config,
    }

    handler = dispatch.get(args.command)
    if handler:
        return handler(args)
    else:
        parser.print_help()
        return 0


if __name__ == '__main__':
    sys.exit(main() or 0)
