# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

"""A2ACaller — 跨员工调用。

当前适配：目标员工工位均运行在同机 127.0.0.1:181xx，
直接 HTTP POST 目标工位的 /chat 端点（走同一 process_message 流水线）。
"""
import json
import logging
import urllib.request

logger = logging.getLogger("agent.a2a")


class A2ACaller:
    """调用其他数字员工工位的 HTTP 接口。"""

    def __init__(self, config, registry_client=None):
        self.config = config
        self.registry = registry_client
        self.timeout = config.get('llm_timeout', 60)

    # ─────────────────────────────────────────
    # 目标解析
    # ─────────────────────────────────────────
    def resolve(self, target):
        """目标可以是：agent_id 字符串（经注册表发现）或完整 card dict。

        返回 chat_url；无法解析返回 None。
        """
        if isinstance(target, dict):
            return target.get('chat_url')
        if self.registry:
            for card in self.registry.discover():
                if card.get('agent_id') == target:
                    return card.get('chat_url') or (
                        'http://127.0.0.1:%s/chat' % card.get('port'))
        return None

    # ─────────────────────────────────────────
    # 调用
    # ─────────────────────────────────────────
    def invoke_chat(self, target, message):
        """向目标员工发送一条对话消息，返回 {task_id, message}。"""
        chat_url = self.resolve(target)
        if not chat_url:
            raise ValueError('无法解析目标员工: %s' % target)
        req = urllib.request.Request(
            chat_url,
            data=json.dumps({'message': message,
                             'from_agent': self.config.agent_id},
                            ensure_ascii=False).encode('utf-8'),
            headers={'Content-Type': 'application/json'},
            method='POST')
        with urllib.request.urlopen(req, timeout=self.timeout) as resp:
            data = json.loads(resp.read().decode('utf-8'))
        logger.info('A2A 调用成功: %s → %s', self.config.agent_id, chat_url)
        return data

    def invoke_skill(self, target, instruction):
        """请求目标员工执行一项任务（由对方意图路由决定走哪个技能）。"""
        return self.invoke_chat(target, instruction)
