# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).
"""运行时敏感配置加密（Fernet，密钥派生自 machine-id + agent_id）。

与平台侧 comms/crypto.py 接口对齐（encrypt_secret / decrypt_secret），
但密钥来源不同：平台用 Django SECRET_KEY，运行时用本机 machine-id
拼接当前 agent_id。同一台机器上不同员工（agent_id 不同）密钥不同，
同一员工跨重启密钥稳定。

注：若运行时与平台部署在不同机器，两边密钥不一致，不能互相解密。
当前仓库凭据只在运行时本地使用，不涉及跨机交换，故无影响。
"""
import base64
import hashlib
import logging
import os

from cryptography.fernet import Fernet, InvalidToken

logger = logging.getLogger('agent.crypto')

_MACHINE_ID_PATHS = ('/etc/machine-id', '/var/lib/dbus/machine-id')

# 模块级缓存：首次调用时派生，后续复用
_fernet_instance = None


def _read_machine_id() -> str:
    for p in _MACHINE_ID_PATHS:
        try:
            with open(p, 'r') as f:
                mid = f.read().strip()
                if mid:
                    return mid
        except OSError:
            continue
    # 兜底：从随机种子文件取，若也没有则用主机名（不推荐）
    seed_file = os.path.expanduser('~/.openchiip-harness/.machine-seed')
    try:
        with open(seed_file, 'r') as f:
            s = f.read().strip()
            if s:
                return s
    except OSError:
        pass
    import socket
    return socket.gethostname() or 'openchiip-runtime'


def _get_fernet():
    """由 machine-id + agent_id 派生 32 字节 Fernet 密钥。"""
    global _fernet_instance
    if _fernet_instance is not None:
        return _fernet_instance
    mid = _read_machine_id()
    # agent_id 从环境变量或默认值取（避免 import RuntimeConfig 造成循环依赖）
    aid = os.environ.get('AGENT_ID') or os.environ.get('AGENT_USER') or 'default'
    seed = ('openchiip-repo-cred:' + mid + ':' + aid).encode('utf-8')
    digest = hashlib.sha256(seed).digest()
    _fernet_instance = Fernet(base64.urlsafe_b64encode(digest))
    return _fernet_instance


def encrypt_secret(plain: str) -> str:
    """加密敏感配置；空值原样返回。"""
    if not plain:
        return ''
    return _get_fernet().encrypt(plain.encode('utf-8')).decode('ascii')


def decrypt_secret(token: str) -> str:
    """解密敏感配置；空值/解密失败返回空串（避免密钥变更导致崩溃）。"""
    if not token:
        return ''
    try:
        return _get_fernet().decrypt(token.encode('ascii')).decode('utf-8')
    except (InvalidToken, ValueError):
        logger.warning('解密失败（密钥可能已变更）')
        return ''


def reset_fernet_cache():
    """重置 Fernet 缓存（测试或 agent_id 变更后使用）。"""
    global _fernet_instance
    _fernet_instance = None
