# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).
"""DAG Executor — Skill Package 确定性执行引擎。

参考 agentd/core/dag_executor.py，适配为 JSON 格式 action_graph + 仅标准库。
核心原则（确定性优先）：
- Layer 1 (Scaffolding)：纯模板/命令，零 LLM
- Layer 2 (Pattern-Guided)：规则 + 少量 LLM
- Layer 3 (Semantic)：LLM 主导，受约束
能走 DAG 不调 LLM。
"""
import json
import logging
import re
from pathlib import Path

logger = logging.getLogger("agent.dag")


class StepExecutor:
    """执行 DAG 中的单个步骤。"""

    def __init__(self, llm_client=None, tool_registry=None, skill_dir=''):
        self.llm = llm_client
        self.tools = tool_registry
        self.skill_dir = Path(skill_dir) if skill_dir else None

    def execute(self, step, context):
        """执行单个 step，返回 {output_key: value}。"""
        action = step.get('action', '')
        step_id = step.get('id', 'unknown')
        handlers = {
            'shell_command': self._exec_shell,
            'template_render': self._exec_template,
            'write_file': self._exec_write_file,
            'table_lookup': self._exec_lookup,
            'llm_generate': self._exec_llm_gen,
        }
        handler = handlers.get(action)
        if not handler:
            raise ValueError('未知 action: %s (step=%s)' % (action, step_id))
        return handler(step, context)

    # ── 变量解析 ───────────────────────────
    def _resolve(self, value, context):
        """将 ${var} 替换为 context 中的值（支持字符串内嵌）。"""
        if not isinstance(value, str):
            return value

        def _sub(match):
            key = match.group(1)
            return str(context.get(key, match.group(0)))
        return re.sub(r'\$\{([^}]+)\}', _sub, value)

    def _resolve_dict(self, d, context):
        return {k: self._resolve(v, context) for k, v in (d or {}).items()}

    # ── shell_command ──────────────────────
    def _exec_shell(self, step, context):
        cmd = self._resolve(step.get('command', ''), context)
        cwd = self._resolve(step.get('cwd', ''), context) or None
        logger.info('Shell: %s', cmd[:100])
        result = self.tools.call_shell('run_command', {'command': cmd, 'cwd': cwd}) \
            if self.tools else {'success': False, 'error': 'ToolRegistry 未就绪'}
        data = result.get('data', result)
        if not result.get('success', data.get('success')):
            err = data.get('stderr') or result.get('error', '命令执行失败')
            if not step.get('allow_failure'):
                raise RuntimeError('Shell 命令失败: %s' % str(err)[:200])
        # capture: stdout/stderr 时仅提取对应字段，便于模板引用
        capture = step.get('capture')
        value = data.get(capture, data) if (capture and isinstance(data, dict)) else data
        return {step.get('output_key', 'shell_result'): value}

    # ── template_render ────────────────────
    def _exec_template(self, step, context):
        template_name = step.get('template', '')
        if template_name and self.skill_dir:
            tpl_path = self.skill_dir / 'templates' / template_name
            if tpl_path.exists():
                template_str = tpl_path.read_text(encoding='utf-8')
            else:
                template_str = step.get('template_string', '')
        else:
            template_str = step.get('template_string', '')
        rendered = self._resolve(template_str, context)
        return {step.get('output_key', 'rendered'): rendered}

    # ── write_file ─────────────────────────
    def _exec_write_file(self, step, context):
        path = self._resolve(step.get('path', ''), context)
        content = self._resolve(step.get('content', ''), context)
        Path(path).expanduser().parent.mkdir(parents=True, exist_ok=True)
        Path(path).expanduser().write_text(str(content), encoding='utf-8')
        return {step.get('output_key', 'written'): path}

    # ── table_lookup ───────────────────────
    def _exec_lookup(self, step, context):
        table_name = step.get('table', '')
        table_path = self.skill_dir / 'knowledge_base' / ('%s.json' % table_name) \
            if self.skill_dir else None
        if not table_path or not table_path.exists():
            raise FileNotFoundError('查找表不存在: %s' % table_path)
        table = json.loads(table_path.read_text(encoding='utf-8'))
        key = self._resolve(step.get('lookup_key', ''), context)
        logic = step.get('logic', 'exact_match')
        if logic == 'progressive_calculation':
            result = self._progressive_calc(table, float(key))
        else:
            result = table.get(key, step.get('default'))
        return {step.get('output_key', 'lookup_result'): result}

    @staticmethod
    def _progressive_calc(table, value):
        """累进计算（如个税阶梯）。"""
        total = 0.0
        details = []
        for bracket in table.get('brackets', []):
            lower = bracket['lower']
            upper = bracket.get('upper', float('inf'))
            rate = bracket['rate']
            if value > lower:
                taxable = min(value, upper) - lower
                tax = taxable * rate
                total += tax
                details.append({'bracket': '%s-%s' % (lower, upper),
                                'tax': round(tax, 2)})
            if value <= lower:
                break
        return {'total': round(total, 2), 'details': details}

    # ── llm_generate ───────────────────────
    def _exec_llm_gen(self, step, context):
        if not self.llm:
            return {step.get('output_key', 'llm_result'): '(LLM 不可用)'}
        system = self._resolve(
            step.get('system_prompt', '你是编程助手，生成高质量内容。'), context)
        user = self._resolve(step.get('user_prompt', ''), context)
        constraint = step.get('constraint', '')
        if constraint:
            system += '\n\n约束：%s' % self._resolve(constraint, context)
        content = self.llm.quick_prompt(
            system, user, skill=step.get('skill', 'unknown'), category='normal')
        return {step.get('output_key', 'llm_result'): content}


class DAGExecutor:
    """加载 Skill 的 action_graph.json，按拓扑顺序确定性执行。"""

    def __init__(self, llm_client=None, tool_registry=None):
        self.llm = llm_client
        self.tools = tool_registry
        self.executor = StepExecutor(llm_client, tool_registry)

    def load_graph(self, skill):
        """从 skill dict 读取 action_graph（已由 SkillManager 加载为 dict）。"""
        return skill.get('dag', {})

    @staticmethod
    def _topological_sort(steps):
        """按 depends_on 拓扑排序。"""
        step_map = {s['id']: s for s in steps}
        deps = {s['id']: set(s.get('depends_on', [])) for s in steps}
        ordered = []
        while deps:
            ready = [k for k, v in deps.items() if not v]
            if not ready:
                raise ValueError('DAG 存在循环依赖: %s' % list(deps.keys()))
            for k in sorted(ready):
                ordered.append(step_map[k])
                del deps[k]
            for v in deps.values():
                v -= set(ready)
        return ordered

    def execute(self, skill, inputs):
        """执行 Skill。skill: {name, manifest, dag, dir}。"""
        name = skill.get('name', '?')
        dag = self.load_graph(skill)
        steps = dag.get('steps', [])
        if not steps:
            return {'success': False, 'error': 'Skill %s 无执行步骤' % name}

        ordered = self._topological_sort(steps)
        context = dict(inputs or {})
        context['_skill_name'] = name
        context['_skill_dir'] = skill.get('dir', '')
        execution_log = []

        logger.info('开始执行 Skill: %s (steps=%d)', name, len(ordered))
        self.executor.skill_dir = Path(skill['dir']) if skill.get('dir') else None

        for step in ordered:
            step_id = step.get('id', '?')
            layer = step.get('layer', 2)
            condition = step.get('condition')
            if condition and not self._eval_condition(condition, context):
                logger.info('  跳过 step=%s (条件不满足)', step_id)
                continue
            logger.info('  step=%s layer=%s action=%s',
                        step_id, layer, step.get('action', ''))
            try:
                output = self.executor.execute(step, context)
                context.update(output)
                execution_log.append({'step': step_id, 'layer': layer,
                                      'status': 'ok',
                                      'output_keys': list(output.keys())})
            except Exception as e:  # noqa: BLE001
                logger.error('  step=%s 失败: %s', step_id, e)
                execution_log.append({'step': step_id, 'layer': layer,
                                      'status': 'failed', 'error': str(e)})
                return {
                    'success': False,
                    'error': str(e),
                    'step': step_id,
                    'log': execution_log,
                }

        logger.info('Skill 执行完成: %s', name)
        outputs = {k: v for k, v in context.items()
                   if not k.startswith('_')}
        # 按 final_output 提取最终交付物；未指定则回退最后一个 output_key
        final_key = dag.get('final_output')
        if not final_key and execution_log:
            last_keys = execution_log[-1].get('output_keys', [])
            final_key = last_keys[0] if last_keys else None
        final = outputs.get(final_key) if final_key else None
        if final is None and outputs:
            final = next(iter(outputs.values()))
        if not isinstance(final, str):
            final = json.dumps(final, ensure_ascii=False, default=str) \
                if final is not None else ''
        return {
            'success': True,
            'output': final,
            'outputs': outputs,
            'log': execution_log,
        }

    def execute_data_collection(self, skill, inputs):
        """执行技能中非 LLM 步骤（数据采集），返回上下文和待处理的 LLM 步骤。

        返回: {
            'success': bool,
            'context': dict,       # 采集到的数据
            'llm_steps': list,     # 待处理的 llm_generate 步骤
            'error': str | None,
        }
        """
        name = skill.get('name', '?')
        dag = self.load_graph(skill)
        steps = dag.get('steps', [])
        if not steps:
            return {'success': False, 'error': 'Skill %s 无执行步骤' % name,
                    'context': {}, 'llm_steps': []}

        ordered = self._topological_sort(steps)
        context = dict(inputs or {})
        context['_skill_name'] = name
        context['_skill_dir'] = skill.get('dir', '')
        self.executor.skill_dir = Path(skill['dir']) if skill.get('dir') else None

        llm_steps = []

        logger.info('开始执行 Skill 数据采集: %s (steps=%d)', name, len(ordered))

        for step in ordered:
            step_id = step.get('id', '?')
            action = step.get('action', '')
            layer = step.get('layer', 2)
            condition = step.get('condition')
            if condition and not self._eval_condition(condition, context):
                logger.info('  跳过 step=%s (条件不满足)', step_id)
                continue

            # 分离 LLM 生成步骤
            if action == 'llm_generate':
                llm_steps.append(step)
                logger.info('  step=%s 延迟为流式 LLM 调用', step_id)
                continue

            logger.info('  step=%s layer=%s action=%s',
                        step_id, layer, action)
            try:
                output = self.executor.execute(step, context)
                context.update(output)
            except Exception as e:  # noqa: BLE001
                logger.error('  step=%s 失败: %s', step_id, e)
                return {'success': False, 'error': str(e),
                        'context': context, 'llm_steps': llm_steps}

        return {
            'success': True,
            'context': context,
            'llm_steps': llm_steps,
            'error': None,
        }

    @staticmethod
    def _eval_condition(condition, context):
        """简单条件表达式求值（受限命名空间）。"""
        try:
            return bool(eval(condition, {'__builtins__': {}}, dict(context)))  # noqa: S307
        except Exception:  # noqa: BLE001
            return False
