# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).
"""SQLite 持久化层 — 统一管理运行时数据。

替代原有的 JSONL 文件存储，提供：
- conversations: 对话历史（替代 short_term.jsonl）
- tasks: 任务记录（本地任务拆解）
- token_meter: Token 计量（替代 token_meter.json）
- checkpoints: 崩溃恢复检查点
- execution_logs: 执行日志（替代 execution_logs/*.jsonl）
- metrics: 资源监控快照

启动时自动建表，并支持从旧 JSONL 文件迁移数据。
"""
import json
import logging
import sqlite3
import threading
import time
from contextlib import contextmanager
from datetime import datetime, timedelta
from pathlib import Path

logger = logging.getLogger("agent.db")


class Database:
    """SQLite 数据库管理器。

    线程安全：使用 check_same_thread=False + 连接锁。
    所有写操作通过 @with_db 装饰器自动管理事务。
    """

    def __init__(self, db_path):
        self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._lock = threading.Lock()
        self._conn = None
        self._init_db()

    def _get_conn(self):
        """获取数据库连接（延迟创建，线程安全）。"""
        if self._conn is None:
            self._conn = sqlite3.connect(
                str(self.db_path),
                check_same_thread=False,
                timeout=10)
            self._conn.row_factory = sqlite3.Row
            self._conn.execute('PRAGMA journal_mode=WAL')
            self._conn.execute('PRAGMA synchronous=NORMAL')
            self._conn.execute('PRAGMA busy_timeout=5000')
        return self._conn

    @contextmanager
    def _cursor(self):
        """获取游标的上下文管理器（自动提交/回滚）。"""
        with self._lock:
            conn = self._get_conn()
            try:
                cur = conn.cursor()
                yield cur
                conn.commit()
            except Exception:
                conn.rollback()
                raise
            finally:
                cur.close()

    def _init_db(self):
        """初始化数据库表结构。"""
        with self._cursor() as cur:
            cur.executescript(_SCHEMA)
        # ALTER TABLE 可能因列已存在而失败，安全忽略
        try:
            with self._cursor() as cur:
                cur.execute(
                    'ALTER TABLE conversations ADD COLUMN session_id TEXT')
        except Exception:
            pass
        try:
            with self._cursor() as cur:
                cur.execute(
                    'CREATE INDEX IF NOT EXISTS idx_conv_session '
                    'ON conversations(session_id)')
        except Exception:
            pass
        # 新增 thinking / metadata 列（思考过程 + 工具调用等扩展数据）
        try:
            with self._cursor() as cur:
                cur.execute(
                    'ALTER TABLE conversations ADD COLUMN thinking TEXT')
        except Exception:
            pass
        try:
            with self._cursor() as cur:
                cur.execute(
                    'ALTER TABLE conversations ADD COLUMN metadata TEXT')
        except Exception:
            pass
        # metrics 表新增字段（运行时监控扩展）
        _metrics_new_cols = [
            ('memory_used', 'REAL'),
            ('memory_total', 'REAL'),
            ('load_avg_1', 'REAL'),
            ('load_avg_5', 'REAL'),
            ('load_avg_15', 'REAL'),
            ('disk_read', 'REAL'),
            ('disk_write', 'REAL'),
            ('disk_read_count', 'REAL'),
            ('disk_write_count', 'REAL'),
            ('process_count', 'INTEGER'),
            ('top_processes', 'TEXT'),
        ]
        for col_name, col_type in _metrics_new_cols:
            try:
                with self._cursor() as cur:
                    cur.execute(
                        f'ALTER TABLE metrics ADD COLUMN {col_name} {col_type}')
            except Exception:
                pass  # 列已存在则安全忽略
        # tasks 表增强字段（借鉴 OpenOPC/QM/Multica）
        _tasks_new_cols = [
            ('priority', 'INTEGER DEFAULT 5'),
            ('kind', "TEXT DEFAULT 'chat'"),
            ('retry_count', 'INTEGER DEFAULT 0'),
            ('max_retries', 'INTEGER DEFAULT 3'),
            ('error_type', 'TEXT'),
            ('error_message', 'TEXT'),
            ('execution_lock', 'INTEGER DEFAULT 0'),
            ('progress', 'INTEGER DEFAULT 0'),
            ('session_id', 'TEXT'),
            ('platform_task_id', 'INTEGER'),
            ('project_id', 'TEXT'),
        ]
        for col_name, col_type in _tasks_new_cols:
            try:
                with self._cursor() as cur:
                    cur.execute(
                        f'ALTER TABLE tasks ADD COLUMN {col_name} {col_type}')
            except Exception:
                pass  # 列已存在则安全忽略
        # task_events 表（借鉴 QM 审计日志）
        try:
            with self._cursor() as cur:
                cur.execute(
                    'CREATE TABLE IF NOT EXISTS task_events ('
                    'id INTEGER PRIMARY KEY AUTOINCREMENT,'
                    'task_id TEXT NOT NULL,'
                    'type TEXT NOT NULL,'
                    'from_status TEXT,'
                    'to_status TEXT,'
                    'message TEXT,'
                    'token_used INTEGER DEFAULT 0,'
                    'created_at TEXT)')
                cur.execute(
                    'CREATE INDEX IF NOT EXISTS idx_task_events_task '
                    'ON task_events(task_id)')
        except Exception:
            pass
        # projects 表增强字段（Git 仓库集成 + 操作人追踪）
        _projects_new_cols = [
            ('project_dir', "TEXT DEFAULT ''"),
            ('repo_url', "TEXT DEFAULT ''"),
            ('repo_provider', "TEXT DEFAULT 'github'"),
            ('repo_branch', "TEXT DEFAULT 'main'"),
            ('repo_secret_ref', "TEXT DEFAULT ''"),
            ('created_by', "TEXT DEFAULT 'system'"),
            ('updated_by', "TEXT DEFAULT ''"),
        ]
        for col_name, col_type in _projects_new_cols:
            try:
                with self._cursor() as cur:
                    cur.execute(
                        f'ALTER TABLE projects ADD COLUMN {col_name} {col_type}')
            except Exception:
                pass  # 列已存在则安全忽略
        # 数据迁移：为已有无 session_id 的 conversations 创建默认会话
        self._migrate_orphan_conversations()
        logger.info('SQLite 数据库已初始化: %s', self.db_path)

    def _migrate_orphan_conversations(self):
        """为没有 session_id 的历史消息创建一个默认会话。"""
        try:
            with self._cursor() as cur:
                cur.execute(
                    'SELECT COUNT(*) FROM conversations WHERE session_id IS NULL')
                orphan_count = cur.fetchone()[0]
            if orphan_count == 0:
                return
            # 检查是否已有默认会话
            existing = self.get_session('default')
            if not existing:
                now = datetime.now().isoformat()
                with self._cursor() as cur:
                    cur.execute(
                        'INSERT INTO sessions '
                        '(id, title, created_at, updated_at, message_count) '
                        "VALUES ('default', '历史会话', ?, ?, ?)",
                        (now, now, orphan_count))
            # 将孤立消息关联到默认会话
            with self._cursor() as cur:
                cur.execute(
                    'UPDATE conversations SET session_id=? '
                    'WHERE session_id IS NULL',
                    ('default',))
            logger.info('已迁移 %d 条孤立消息到默认会话', orphan_count)
        except Exception:
            logger.debug('孤立消息迁移失败', exc_info=True)

    # ─────────────────────────────────────────
    # 对话历史（conversations）
    # ─────────────────────────────────────────
    def record_conversation(self, direction, text, sender=None,
                           intent=None, skill=None, task_id=None,
                           session_id=None, thinking=None, metadata=None):
        """记录一条对话。"""
        with self._cursor() as cur:
            cur.execute(
                'INSERT INTO conversations '
                '(timestamp, direction, text, sender, intent, skill, task_id, '
                'session_id, thinking, metadata) '
                'VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
                (datetime.now().isoformat(), direction,
                 str(text)[:10000] if text else '',
                 sender, intent, skill, task_id, session_id,
                 str(thinking)[:10000] if thinking else None,
                 str(metadata)[:5000] if metadata else None))

    def get_recent_conversations(self, n=20, session_id=None):
        """获取最近 n 条对话记录，可按 session_id 过滤。"""
        with self._cursor() as cur:
            if session_id:
                cur.execute(
                    'SELECT * FROM conversations WHERE session_id=? '
                    'ORDER BY id DESC LIMIT ?',
                    (session_id, n))
            else:
                cur.execute(
                    'SELECT * FROM conversations ORDER BY id DESC LIMIT ?',
                    (n,))
            rows = cur.fetchall()
        return [dict(r) for r in reversed(rows)]

    def get_history_for_llm(self, max_msgs=20, session_id=None):
        """构造 LLM 历史消息列表，可按 session_id 过滤。"""
        records = self.get_recent_conversations(max_msgs * 2, session_id=session_id)
        msgs = []
        prev_role = None
        prev_content = None
        for rec in records[-max_msgs * 2:]:
            role = 'user' if rec.get('direction') == 'in' else 'assistant'
            content = rec.get('text')
            if content:
                # 去重：跳过与上一条相同 role + content 的连续重复记录
                if role == prev_role and content == prev_content:
                    continue
                msgs.append({'role': role, 'content': content})
                prev_role = role
                prev_content = content
        return msgs[-max_msgs:]

    def archive_old_conversations(self, days=7):
        """归档超过 days 天的对话记录。"""
        cutoff = (datetime.now() - timedelta(days=days)).isoformat()
        with self._cursor() as cur:
            cur.execute(
                'SELECT COUNT(*) FROM conversations WHERE timestamp < ?',
                (cutoff,))
            count = cur.fetchone()[0]
            if count > 0:
                cur.execute(
                    'DELETE FROM conversations WHERE timestamp < ?',
                    (cutoff,))
                logger.info('已归档 %d 条过期对话记录', count)
        return count

    def count_conversations(self):
        """统计对话记录总数。"""
        with self._cursor() as cur:
            cur.execute('SELECT COUNT(*) FROM conversations')
            return cur.fetchone()[0]

    def count_sessions(self):
        """统计会话总数。"""
        with self._cursor() as cur:
            cur.execute('SELECT COUNT(*) FROM sessions')
            return cur.fetchone()[0]

    def search_conversations_fts(self, query, limit=15):
        """FTS5 全文检索对话记录。"""
        with self._cursor() as cur:
            # 使用 FTS5 的 MATCH 语法搜索
            cur.execute(
                'SELECT c.* FROM conversations c '
                'JOIN conversations_fts fts ON c.id = fts.rowid '
                'WHERE conversations_fts MATCH ? '
                'ORDER BY rank LIMIT ?',
                (query, limit))
            rows = cur.fetchall()
        return [dict(r) for r in rows]

    # ─────────────────────────────────────────
    # 会话管理（sessions）
    # ─────────────────────────────────────────
    def create_session(self, id, title=''):
        """创建新会话。"""
        now = datetime.now().isoformat()
        with self._cursor() as cur:
            cur.execute(
                'INSERT INTO sessions (id, title, created_at, updated_at, message_count) '
                'VALUES (?, ?, ?, ?, 0)',
                (id, title or '新会话', now, now))
        return self.get_session(id)

    def get_session(self, id):
        """获取单个会话。"""
        with self._cursor() as cur:
            cur.execute('SELECT * FROM sessions WHERE id=?', (id,))
            row = cur.fetchone()
        return dict(row) if row else None

    def list_sessions(self, archived=False):
        """列出会话。"""
        with self._cursor() as cur:
            if archived:
                cur.execute(
                    'SELECT * FROM sessions WHERE archived_at IS NOT NULL '
                    'ORDER BY updated_at DESC')
            else:
                cur.execute(
                    'SELECT * FROM sessions WHERE archived_at IS NULL '
                    'ORDER BY updated_at DESC')
            rows = cur.fetchall()
        return [dict(r) for r in rows]

    def update_session_title(self, id, title):
        """更新会话标题。"""
        with self._cursor() as cur:
            cur.execute(
                'UPDATE sessions SET title=?, updated_at=? WHERE id=?',
                (title, datetime.now().isoformat(), id))

    def archive_session(self, id):
        """归档或取消归档会话。"""
        session = self.get_session(id)
        if not session:
            return
        now = datetime.now().isoformat()
        with self._cursor() as cur:
            if session.get('archived_at'):
                cur.execute(
                    'UPDATE sessions SET archived_at=NULL, updated_at=? WHERE id=?',
                    (now, id))
            else:
                cur.execute(
                    'UPDATE sessions SET archived_at=?, updated_at=? WHERE id=?',
                    (now, now, id))

    def delete_session(self, id):
        """删除会话及其关联消息和事件。"""
        with self._cursor() as cur:
            cur.execute('DELETE FROM conversations WHERE session_id=?', (id,))
            cur.execute('DELETE FROM session_events WHERE session_id=?', (id,))
            cur.execute('DELETE FROM sessions WHERE id=?', (id,))

    def increment_session_message_count(self, id, count=1):
        """增加会话消息计数并更新 updated_at。"""
        now = datetime.now().isoformat()
        with self._cursor() as cur:
            cur.execute(
                'UPDATE sessions SET message_count = message_count + ?, '
                'updated_at=? WHERE id=?',
                (count, now, id))

    def get_session_messages(self, session_id, limit=50, before=None):
        """按会话获取消息。"""
        with self._cursor() as cur:
            if before:
                cur.execute(
                    'SELECT * FROM conversations '
                    'WHERE session_id=? AND id < ? '
                    'ORDER BY id DESC LIMIT ?',
                    (session_id, before, limit))
            else:
                cur.execute(
                    'SELECT * FROM conversations '
                    'WHERE session_id=? '
                    'ORDER BY id DESC LIMIT ?',
                    (session_id, limit))
            rows = cur.fetchall()
        return [dict(r) for r in reversed(rows)]

    def get_session_stats(self):
        """各会话消息统计。"""
        with self._cursor() as cur:
            cur.execute(
                'SELECT s.id, s.title, s.message_count, s.created_at, '
                's.updated_at, s.archived_at, '
                'COUNT(c.id) as actual_count '
                'FROM sessions s '
                'LEFT JOIN conversations c ON c.session_id = s.id '
                'GROUP BY s.id ORDER BY s.updated_at DESC')
            rows = cur.fetchall()
        return [dict(r) for r in rows]

    # ─────────────────────────────────────────
    # 执行日志（execution_logs）
    # ─────────────────────────────────────────
    def log_execution(self, intent=None, skill=None, status='ok',
                      detail=None):
        """记录一条执行日志。"""
        with self._cursor() as cur:
            cur.execute(
                'INSERT INTO execution_logs '
                '(timestamp, intent, skill, status, detail) '
                'VALUES (?, ?, ?, ?, ?)',
                (datetime.now().isoformat(), intent, skill, status,
                 str(detail)[:500] if detail else None))

    def get_execution_logs(self, limit=10):
        """获取最近 limit 条执行日志。"""
        with self._cursor() as cur:
            cur.execute(
                'SELECT * FROM execution_logs ORDER BY id DESC LIMIT ?',
                (limit,))
            rows = cur.fetchall()
        return [dict(r) for r in rows]

    # ─────────────────────────────────────────
    # Token 计量（token_meter）
    # ─────────────────────────────────────────
    def get_token_meter(self, month):
        """获取指定月份的 Token 计量数据。"""
        with self._cursor() as cur:
            cur.execute(
                'SELECT * FROM token_meter WHERE month = ?', (month,))
            row = cur.fetchone()
        if row:
            data = dict(row)
            data['by_skill'] = json.loads(data.get('by_skill') or '{}')
            data['by_category'] = json.loads(
                data.get('by_category') or '{}')
            return data
        return None

    def upsert_token_meter(self, month, used, cap=None,
                           by_skill=None, by_category=None):
        """更新或插入 Token 计量数据。"""
        with self._cursor() as cur:
            cur.execute(
                'INSERT INTO token_meter (month, used, cap, by_skill, by_category) '
                'VALUES (?, ?, ?, ?, ?) '
                'ON CONFLICT(month) DO UPDATE SET '
                'used=excluded.used, cap=COALESCE(excluded.cap, token_meter.cap), '
                'by_skill=excluded.by_skill, by_category=excluded.by_category',
                (month, used, cap,
                 json.dumps(by_skill or {}, ensure_ascii=False),
                 json.dumps(by_category or {}, ensure_ascii=False)))

    # ─────────────────────────────────────────
    # 任务记录（tasks）— 增强版（借鉴 OpenOPC/QM/Multica）
    # ─────────────────────────────────────────
    def create_task(self, task_id, message, parent_id=None,
                    kind='chat', priority=5, max_retries=3,
                    session_id=None, platform_task_id=None,
                    project_id=None):
        """创建新任务。"""
        now = datetime.now().isoformat()
        with self._cursor() as cur:
            cur.execute(
                'INSERT OR IGNORE INTO tasks '
                '(id, parent_id, status, message, kind, priority, '
                'max_retries, session_id, platform_task_id, '
                'project_id, '
                'created_at, updated_at) '
                'VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
                (task_id, parent_id, 'pending', message,
                 kind, priority, max_retries, session_id,
                 platform_task_id, project_id, now, now))
        # 记录创建事件
        self.append_task_event(
            task_id, 'created', to_status='pending',
            message='任务创建: %s' % (message[:100] if message else ''))
        return self.get_task(task_id)

    def update_task(self, task_id, **fields):
        """更新任务字段。"""
        allowed = {'status', 'result', 'evidence', 'token_used',
                   'completed_at', 'priority', 'kind', 'retry_count',
                   'max_retries', 'error_type', 'error_message',
                   'execution_lock', 'progress', 'session_id',
                   'platform_task_id'}
        updates = {k: v for k, v in fields.items() if k in allowed}
        if not updates:
            return
        updates['updated_at'] = datetime.now().isoformat()
        set_clause = ', '.join('%s=?' % k for k in updates)
        values = list(updates.values()) + [task_id]
        with self._cursor() as cur:
            cur.execute(
                'UPDATE tasks SET %s WHERE id=?' % set_clause, values)

    def cas_transition(self, task_id, expected_status, next_status,
                       message=None, token_used=0):
        """CAS 状态转换（借鉴 QM）— 防止并发状态竞争。

        仅当当前状态 == expected_status 时才转换，返回是否成功。
        """
        now = datetime.now().isoformat()
        with self._cursor() as cur:
            cur.execute(
                'UPDATE tasks SET status=?, updated_at=? '
                'WHERE id=? AND status=?',
                (next_status, now, task_id, expected_status))
            affected = cur.rowcount
        if affected == 0:
            return False
        # 状态转换成功，追加审计事件
        self.append_task_event(
            task_id, 'status_changed',
            from_status=expected_status, to_status=next_status,
            message=message, token_used=token_used)
        return True

    def append_task_event(self, task_id, event_type,
                          from_status=None, to_status=None,
                          message=None, token_used=0):
        """追加任务审计事件。"""
        now = datetime.now().isoformat()
        with self._cursor() as cur:
            cur.execute(
                'INSERT INTO task_events '
                '(task_id, type, from_status, to_status, message, '
                'token_used, created_at) '
                'VALUES (?, ?, ?, ?, ?, ?, ?)',
                (task_id, event_type, from_status, to_status,
                 str(message)[:500] if message else None,
                 token_used, now))

    def get_task_events(self, task_id, limit=100):
        """获取任务审计事件列表。"""
        with self._cursor() as cur:
            cur.execute(
                'SELECT * FROM task_events '
                'WHERE task_id=? ORDER BY id DESC LIMIT ?',
                (task_id, limit))
            rows = cur.fetchall()
        return [dict(r) for r in reversed(rows)]

    def get_task_stats(self):
        """任务统计（按状态/类型汇总）。"""
        with self._cursor() as cur:
            cur.execute(
                'SELECT status, kind, COUNT(*) as count '
                'FROM tasks GROUP BY status, kind')
            rows = cur.fetchall()
        stats = {'by_status': {}, 'by_kind': {}, 'total': 0}
        for row in rows:
            s = row['status']
            k = row['kind'] or 'chat'
            c = row['count']
            stats['by_status'][s] = stats['by_status'].get(s, 0) + c
            stats['by_kind'][k] = stats['by_kind'].get(k, 0) + c
            stats['total'] += c
        return stats

    def get_task(self, task_id):
        """获取单个任务。"""
        with self._cursor() as cur:
            cur.execute('SELECT * FROM tasks WHERE id=?', (task_id,))
            row = cur.fetchone()
        return dict(row) if row else None

    def get_subtasks(self, parent_id):
        """获取子任务列表。"""
        with self._cursor() as cur:
            cur.execute(
                'SELECT * FROM tasks WHERE parent_id=? ORDER BY id',
                (parent_id,))
            rows = cur.fetchall()
        return [dict(r) for r in rows]

    def list_recent_tasks(self, hours=48, limit=100,
                          kind=None, status=None, project_id=None):
        """获取最近 N 小时内的任务列表（支持过滤）。"""
        from datetime import datetime, timedelta
        cutoff = (datetime.now() - timedelta(hours=hours)).isoformat()
        query = (
            'SELECT t.*, p.title as project_title '
            'FROM tasks t LEFT JOIN projects p ON t.project_id = p.id '
            'WHERE t.created_at >= ?'
        )
        params = [cutoff]
        if kind:
            query += ' AND t.kind=?'
            params.append(kind)
        if status:
            query += ' AND t.status=?'
            params.append(status)
        if project_id:
            query += ' AND t.project_id=?'
            params.append(project_id)
        query += ' ORDER BY t.priority ASC, t.created_at DESC LIMIT ?'
        params.append(limit)
        with self._cursor() as cur:
            cur.execute(query, params)
            rows = cur.fetchall()
        return [dict(r) for r in rows]

    def list_tasks_paginated(self, status=None, kind=None, project_id=None,
                             search=None, created_after=None, created_before=None,
                             limit=10, offset=0):
        """分页任务列表（支持多条件过滤）。"""
        query = (
            'SELECT t.*, p.title as project_title '
            'FROM tasks t LEFT JOIN projects p ON t.project_id = p.id'
        )
        where_parts = []
        params = []
        if status:
            where_parts.append('t.status=?')
            params.append(status)
        if kind:
            where_parts.append('t.kind=?')
            params.append(kind)
        if project_id:
            where_parts.append('t.project_id=?')
            params.append(project_id)
        if search:
            where_parts.append('(t.message LIKE ? OR t.id LIKE ?)')
            params.extend([f'%{search}%', f'%{search}%'])
        if created_after:
            where_parts.append('t.created_at>=?')
            params.append(created_after)
        if created_before:
            where_parts.append('t.created_at<=?')
            params.append(created_before)
        if where_parts:
            query += ' WHERE ' + ' AND '.join(where_parts)
        query += ' ORDER BY CASE WHEN t.project_id IS NULL THEN 1 ELSE 0 END, p.created_at DESC, t.created_at ASC LIMIT ? OFFSET ?'
        params.extend([limit, offset])
        with self._cursor() as cur:
            cur.execute(query, params)
            rows = cur.fetchall()
        return [dict(r) for r in rows]

    def count_tasks(self, status=None, kind=None, project_id=None,
                    search=None, created_after=None, created_before=None):
        """统计任务总数（支持多条件过滤）。"""
        query = 'SELECT COUNT(*) FROM tasks t'
        where_parts = []
        params = []
        if status:
            where_parts.append('t.status=?')
            params.append(status)
        if kind:
            where_parts.append('t.kind=?')
            params.append(kind)
        if project_id:
            where_parts.append('t.project_id=?')
            params.append(project_id)
        if search:
            where_parts.append('(t.message LIKE ? OR t.id LIKE ?)')
            params.extend([f'%{search}%', f'%{search}%'])
        if created_after:
            where_parts.append('t.created_at>=?')
            params.append(created_after)
        if created_before:
            where_parts.append('t.created_at<=?')
            params.append(created_before)
        if where_parts:
            query += ' WHERE ' + ' AND '.join(where_parts)
        with self._cursor() as cur:
            cur.execute(query, params)
            return cur.fetchone()[0]

    # ─────────────────────────────────────────
    # Checkpoint（崩溃恢复）
    # ─────────────────────────────────────────
    def save_checkpoint(self, task_id, state):
        """保存任务执行检查点。"""
        with self._cursor() as cur:
            cur.execute(
                'INSERT INTO checkpoints (task_id, state, created_at) '
                'VALUES (?, ?, ?) '
                'ON CONFLICT(task_id) DO UPDATE SET '
                'state=excluded.state, created_at=excluded.created_at',
                (task_id, json.dumps(state, ensure_ascii=False),
                 datetime.now().isoformat()))

    def load_checkpoint(self, task_id):
        """加载任务检查点。"""
        with self._cursor() as cur:
            cur.execute(
                'SELECT * FROM checkpoints WHERE task_id=?', (task_id,))
            row = cur.fetchone()
        if row:
            data = dict(row)
            data['state'] = json.loads(data['state'])
            return data
        return None

    def delete_checkpoint(self, task_id):
        """删除已完成的检查点。"""
        with self._cursor() as cur:
            cur.execute(
                'DELETE FROM checkpoints WHERE task_id=?', (task_id,))

    # ─────────────────────────────────────────
    # 资源监控（metrics）
    # ─────────────────────────────────────────
    def save_metric(self, cpu, memory, disk=None,
                    network_rx=None, network_tx=None,
                    memory_used=None, memory_total=None,
                    load_avg_1=None, load_avg_5=None, load_avg_15=None,
                    disk_read=None, disk_write=None,
                    disk_read_count=None, disk_write_count=None,
                    process_count=None, top_processes=None):
        """保存一条资源监控快照。"""
        top_json = None
        if top_processes is not None:
            import json
            top_json = json.dumps(top_processes, ensure_ascii=False)
        with self._cursor() as cur:
            cur.execute(
                'INSERT INTO metrics '
                '(timestamp, cpu, memory, disk, network_rx, network_tx,'
                ' memory_used, memory_total,'
                ' load_avg_1, load_avg_5, load_avg_15,'
                ' disk_read, disk_write, disk_read_count, disk_write_count,'
                ' process_count, top_processes) '
                'VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
                (datetime.now().isoformat(), cpu, memory,
                 disk, network_rx, network_tx,
                 memory_used, memory_total,
                 load_avg_1, load_avg_5, load_avg_15,
                 disk_read, disk_write, disk_read_count, disk_write_count,
                 process_count, top_json))

    def get_recent_metrics(self, limit=60):
        """获取最近 limit 条监控数据。"""
        with self._cursor() as cur:
            cur.execute(
                'SELECT * FROM metrics ORDER BY id DESC LIMIT ?',
                (limit,))
            rows = cur.fetchall()
        return [dict(r) for r in reversed(rows)]

    def get_metrics_range(self, start_ts: float, end_ts: float, limit: int = 500):
        """获取时间范围内的监控数据。

        参数:
            start_ts: 开始时间戳（Unix epoch）
            end_ts: 结束时间戳（Unix epoch）
            limit: 最大返回条数
        """
        start_iso = datetime.fromtimestamp(start_ts).isoformat()
        end_iso = datetime.fromtimestamp(end_ts).isoformat()
        with self._cursor() as cur:
            cur.execute(
                'SELECT * FROM metrics '
                'WHERE timestamp >= ? AND timestamp <= ? '
                'ORDER BY id DESC LIMIT ?',
                (start_iso, end_iso, limit))
            rows = cur.fetchall()
        return [dict(r) for r in reversed(rows)]

    def cleanup_old_metrics(self, hours=24):
        """清理超过 hours 小时的监控数据。"""
        cutoff = (datetime.now() - timedelta(hours=hours)).isoformat()
        with self._cursor() as cur:
            cur.execute(
                'DELETE FROM metrics WHERE timestamp < ?', (cutoff,))

    # ─────────────────────────────────────────
    # JSONL 迁移
    # ─────────────────────────────────────────
    def migrate_from_jsonl(self, config):
        """从旧 JSONL 文件迁移数据到 SQLite。

        启动时自动检测，迁移完成后保留 30 天备份。
        """
        migrated = False

        # 迁移短期记忆
        short_term = Path(config.short_term_file)
        if short_term.exists() and self.count_conversations() == 0:
            count = self._migrate_jsonl_records(short_term)
            if count:
                logger.info('已迁移 %d 条短期记忆到 SQLite', count)
                migrated = True

        # 迁移 Token 计量
        token_file = Path(config.token_meter_file)
        if token_file.exists():
            self._migrate_token_meter(token_file)

        return migrated

    def _migrate_jsonl_records(self, path):
        """从 JSONL 文件迁移对话记录。"""
        count = 0
        try:
            with open(path, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        rec = json.loads(line)
                        self.record_conversation(
                            direction=rec.get('direction', 'in'),
                            text=rec.get('text', ''),
                            sender=rec.get('sender'),
                            intent=rec.get('intent'),
                            skill=rec.get('skill'))
                        count += 1
                    except (ValueError, KeyError):
                        continue
        except (IOError, OSError):
            pass
        return count

    def _migrate_token_meter(self, path):
        """从 JSON 文件迁移 Token 计量数据。"""
        try:
            data = json.loads(path.read_text(encoding='utf-8'))
            month = data.get('month', time.strftime('%Y-%m'))
            existing = self.get_token_meter(month)
            if not existing:
                self.upsert_token_meter(
                    month=month,
                    used=data.get('used', 0),
                    cap=data.get('cap'),
                    by_skill=data.get('by_skill', {}),
                    by_category=data.get('by_category', {}))
                logger.info('已迁移 Token 计量数据到 SQLite')
        except (ValueError, OSError):
            pass

    def close(self):
        """关闭数据库连接。"""
        if self._conn:
            self._conn.close()
            self._conn = None

    # ─────────────────────────────────────────
    # 凭据存储（credentials）— 平台 Token 热加载
    # ─────────────────────────────────────────
    def set_credential(self, key, value):
        """写入或更新一条凭据。"""
        with self._cursor() as cur:
            cur.execute(
                'INSERT OR REPLACE INTO credentials (key, value, updated_at) '
                'VALUES (?, ?, ?)',
                (key, value, datetime.now().isoformat()))

    def get_credential(self, key):
        """读取一条凭据。"""
        with self._cursor() as cur:
            cur.execute(
                'SELECT value FROM credentials WHERE key=?', (key,))
            row = cur.fetchone()
        return row[0] if row else None

    def get_all_credentials(self):
        """读取所有凭据（返回 dict）。"""
        with self._cursor() as cur:
            cur.execute('SELECT key, value FROM credentials')
            rows = cur.fetchall()
        return {row[0]: row[1] for row in rows}

    def delete_credential(self, key):
        """删除一条凭据。"""
        with self._cursor() as cur:
            cur.execute(
                'DELETE FROM credentials WHERE key=?', (key,))

    def clear_credentials(self):
        """清空所有凭据。"""
        with self._cursor() as cur:
            cur.execute('DELETE FROM credentials')

    # ─────────────────────────────────────────
    # 仓库凭据（repo_credentials）— clone 私有仓库
    # ─────────────────────────────────────────
    def list_repo_credentials(self):
        """列出所有仓库凭据（token 脱敏，仅返回前 4 + 后 2 字符）。

        返回 list[dict]，字段：id / platform / org_slug / name / api_base /
        token_hint / updated_at。
        """
        from agent_runtime.core.crypto import decrypt_secret
        with self._cursor() as cur:
            cur.execute(
                'SELECT id, platform, org_slug, name, api_base, '
                'access_token_enc, updated_at '
                'FROM repo_credentials ORDER BY updated_at DESC')
            rows = cur.fetchall()
        result = []
        for row in rows:
            token = decrypt_secret(row['access_token_enc']) if row['access_token_enc'] else ''
            if len(token) > 8:
                hint = '%s...%s' % (token[:4], token[-2:])
            elif token:
                hint = '***'
            else:
                hint = ''
            result.append({
                'id': row['id'],
                'platform': row['platform'],
                'org_slug': row['org_slug'],
                'name': row['name'],
                'api_base': row['api_base'],
                'token_hint': hint,
                'updated_at': row['updated_at'],
            })
        return result

    def get_repo_credential(self, platform, org_slug):
        """按 (platform, org_slug) 取一条凭据，返回完整解密 token。

        返回 dict：id / platform / org_slug / name / api_base / access_token。
        未命中返回 None。
        """
        from agent_runtime.core.crypto import decrypt_secret
        with self._cursor() as cur:
            cur.execute(
                'SELECT id, platform, org_slug, name, api_base, access_token_enc '
                'FROM repo_credentials WHERE platform=? AND org_slug=?',
                (platform, org_slug))
            row = cur.fetchone()
        if not row:
            return None
        return {
            'id': row['id'],
            'platform': row['platform'],
            'org_slug': row['org_slug'],
            'name': row['name'],
            'api_base': row['api_base'],
            'access_token': decrypt_secret(row['access_token_enc'])
            if row['access_token_enc'] else '',
        }

    def set_repo_credential(self, platform, org_slug, access_token,
                             api_base='', name=''):
        """新增或更新一条仓库凭据（按 (platform, org_slug) 幂等）。"""
        from agent_runtime.core.crypto import encrypt_secret
        now = datetime.now().isoformat(timespec='seconds')
        token_enc = encrypt_secret(access_token) if access_token else ''
        with self._cursor() as cur:
            cur.execute(
                'INSERT INTO repo_credentials '
                '(platform, org_slug, access_token_enc, api_base, name, '
                ' created_at, updated_at) '
                'VALUES (?, ?, ?, ?, ?, ?, ?) '
                'ON CONFLICT(platform, org_slug) DO UPDATE SET '
                'access_token_enc=excluded.access_token_enc, '
                'api_base=excluded.api_base, name=excluded.name, '
                'updated_at=excluded.updated_at',
                (platform, org_slug, token_enc, api_base, name, now, now))

    def delete_repo_credential(self, cred_id):
        """按 id 删除一条仓库凭据。"""
        with self._cursor() as cur:
            cur.execute(
                'DELETE FROM repo_credentials WHERE id=?', (cred_id,))

    # ─────────────────────────────────────────
    # LLM 配置（llm_config）— 模型提供商配置
    # ─────────────────────────────────────────
    def set_llm_config(self, key, value):
        """写入或更新一条 LLM 配置。"""
        with self._cursor() as cur:
            cur.execute(
                'INSERT OR REPLACE INTO llm_config (key, value, updated_at) '
                'VALUES (?, ?, ?)',
                (key, value, datetime.now().isoformat()))

    def get_llm_config(self, key):
        """读取一条 LLM 配置。"""
        with self._cursor() as cur:
            cur.execute(
                'SELECT value FROM llm_config WHERE key=?', (key,))
            row = cur.fetchone()
        return row[0] if row else None

    def get_all_llm_config(self):
        """读取所有 LLM 配置（返回 dict）。"""
        with self._cursor() as cur:
            cur.execute('SELECT key, value FROM llm_config')
            rows = cur.fetchall()
        return {row[0]: row[1] for row in rows}

    def clear_llm_config(self):
        """清空所有 LLM 配置。"""
        with self._cursor() as cur:
            cur.execute('DELETE FROM llm_config')

    # ─────────────────────────────────────────
    # 消息反馈（message_feedback）
    # ─────────────────────────────────────────
    def submit_feedback(self, message_id, session_id, rating, comment=None):
        """提交或更新消息反馈（INSERT OR REPLACE）。"""
        with self._cursor() as cur:
            cur.execute(
                'INSERT OR REPLACE INTO message_feedback '
                '(message_id, session_id, rating, comment, created_at) '
                'VALUES (?, ?, ?, ?, ?)',
                (message_id, session_id, rating,
                 str(comment)[:2000] if comment else None,
                 datetime.now().isoformat()))

    def delete_feedback(self, message_id):
        """删除消息反馈。"""
        with self._cursor() as cur:
            cur.execute(
                'DELETE FROM message_feedback WHERE message_id=?',
                (message_id,))

    def get_feedback(self, message_id):
        """获取单条消息的反馈。"""
        with self._cursor() as cur:
            cur.execute(
                'SELECT * FROM message_feedback WHERE message_id=?',
                (message_id,))
            row = cur.fetchone()
        return dict(row) if row else None

    def get_session_feedback(self, session_id):
        """获取会话所有反馈。"""
        with self._cursor() as cur:
            cur.execute(
                'SELECT * FROM message_feedback '
                'WHERE session_id=? ORDER BY id',
                (session_id,))
            rows = cur.fetchall()
        return [dict(r) for r in rows]

    # ─────────────────────────────────────────
    # 项目管理（projects）
    # ─────────────────────────────────────────
    def create_project(self, project_id, title, description='',
                       plan_type='dag', loop_goal='',
                       loop_stop_condition='',
                       loop_max_iterations=10,
                       project_dir='', repo_url='',
                       repo_provider='github', repo_branch='main',
                       repo_secret_ref='', created_by='system'):
        """创建新项目。"""
        now = datetime.now().isoformat()
        with self._cursor() as cur:
            cur.execute(
                'INSERT OR IGNORE INTO projects '
                '(id, title, description, status, plan_type, '
                'loop_goal, loop_stop_condition, loop_max_iterations, '
                'loop_current_iteration, '
                'project_dir, repo_url, repo_provider, repo_branch, repo_secret_ref, '
                'created_by, updated_by, '
                'created_at, updated_at) '
                'VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
                (project_id, title, description, 'draft', plan_type,
                 loop_goal, loop_stop_condition, loop_max_iterations,
                 project_dir, repo_url, repo_provider, repo_branch, repo_secret_ref,
                 created_by, created_by,
                 now, now))
        return self.get_project(project_id)

    def get_project(self, project_id):
        """获取单个项目。"""
        with self._cursor() as cur:
            cur.execute(
                'SELECT * FROM projects WHERE id=?',
                (project_id,))
            row = cur.fetchone()
        return dict(row) if row else None

    def list_projects(self, status=None, search=None, created_by=None,
                      created_after=None, created_before=None, limit=100, offset=0):
        """获取项目列表（分页）。"""
        with self._cursor() as cur:
            where_parts = []
            params = []
            if status:
                where_parts.append('status=?')
                params.append(status)
            if search:
                where_parts.append('(title LIKE ? OR id LIKE ? OR description LIKE ?)')
                params.extend([f'%{search}%', f'%{search}%', f'%{search}%'])
            if created_by:
                where_parts.append('created_by=?')
                params.append(created_by)
            if created_after:
                where_parts.append('created_at>=?')
                params.append(created_after)
            if created_before:
                where_parts.append('created_at<=?')
                params.append(created_before)
            where = ' WHERE ' + ' AND '.join(where_parts) if where_parts else ''
            cur.execute(
                f'SELECT * FROM projects{where} '
                f'ORDER BY updated_at DESC LIMIT ? OFFSET ?',
                params + [limit, offset])
            rows = cur.fetchall()
        return [dict(r) for r in rows]

    def count_projects(self, status=None, search=None, created_by=None,
                       created_after=None, created_before=None):
        """统计项目总数。"""
        with self._cursor() as cur:
            where_parts = []
            params = []
            if status:
                where_parts.append('status=?')
                params.append(status)
            if search:
                where_parts.append('(title LIKE ? OR id LIKE ? OR description LIKE ?)')
                params.extend([f'%{search}%', f'%{search}%', f'%{search}%'])
            if created_by:
                where_parts.append('created_by=?')
                params.append(created_by)
            if created_after:
                where_parts.append('created_at>=?')
                params.append(created_after)
            if created_before:
                where_parts.append('created_at<=?')
                params.append(created_before)
            where = ' WHERE ' + ' AND '.join(where_parts) if where_parts else ''
            cur.execute(f'SELECT COUNT(*) FROM projects{where}', params)
            return cur.fetchone()[0]

    def update_project(self, project_id, **fields):
        """更新项目字段。"""
        allowed = {'title', 'description', 'status', 'plan_type',
                   'loop_goal', 'loop_stop_condition',
                   'loop_max_iterations', 'loop_current_iteration',
                   'plan_document', 'result_document', 'completed_at',
                   'updated_by'}
        updates = {k: v for k, v in fields.items() if k in allowed}
        if not updates:
            return False
        updates['updated_at'] = datetime.now().isoformat()
        set_clause = ', '.join('%s=?' % k for k in updates)
        values = list(updates.values()) + [project_id]
        with self._cursor() as cur:
            cur.execute(
                'UPDATE projects SET %s WHERE id=?' % set_clause,
                values)
            return cur.rowcount > 0

    def delete_project(self, project_id):
        """删除项目。"""
        with self._cursor() as cur:
            cur.execute(
                'DELETE FROM projects WHERE id=?',
                (project_id,))
            return cur.rowcount > 0


# ─────────────────────────────────────────────
# 数据库 Schema
# ─────────────────────────────────────────────

_SCHEMA = """
CREATE TABLE IF NOT EXISTS conversations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TEXT NOT NULL,
    direction TEXT NOT NULL,
    text TEXT NOT NULL,
    sender TEXT,
    intent TEXT,
    skill TEXT,
    task_id TEXT
);
CREATE INDEX IF NOT EXISTS idx_conv_timestamp
    ON conversations(timestamp);
CREATE INDEX IF NOT EXISTS idx_conv_direction
    ON conversations(direction);

CREATE TABLE IF NOT EXISTS tasks (
    id TEXT PRIMARY KEY,
    parent_id TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    message TEXT,
    result TEXT,
    evidence TEXT,
    token_used INTEGER DEFAULT 0,
    created_at TEXT,
    updated_at TEXT,
    completed_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_tasks_parent
    ON tasks(parent_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status
    ON tasks(status);

CREATE TABLE IF NOT EXISTS token_meter (
    month TEXT PRIMARY KEY,
    used INTEGER DEFAULT 0,
    cap INTEGER,
    by_skill TEXT,
    by_category TEXT
);

CREATE TABLE IF NOT EXISTS checkpoints (
    task_id TEXT PRIMARY KEY,
    state TEXT NOT NULL,
    created_at TEXT
);

CREATE TABLE IF NOT EXISTS execution_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TEXT,
    intent TEXT,
    skill TEXT,
    status TEXT,
    detail TEXT
);
CREATE INDEX IF NOT EXISTS idx_execlog_timestamp
    ON execution_logs(timestamp);

CREATE TABLE IF NOT EXISTS metrics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TEXT,
    cpu REAL,
    memory REAL,
    disk REAL,
    network_rx REAL,
    network_tx REAL
);
CREATE INDEX IF NOT EXISTS idx_metrics_timestamp
    ON metrics(timestamp);

-- 会话管理（sessions）
CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL DEFAULT '新会话',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    archived_at TEXT,
    message_count INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_sessions_updated
    ON sessions(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_archived
    ON sessions(archived_at);

-- 事件溯源会话日志
CREATE TABLE IF NOT EXISTS session_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL,
    seq INTEGER NOT NULL,
    time REAL NOT NULL,
    type TEXT NOT NULL,
    data TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_session_events_unique
    ON session_events(session_id, seq);
CREATE INDEX IF NOT EXISTS idx_session_events_type
    ON session_events(session_id, type);

-- 消息反馈
CREATE TABLE IF NOT EXISTS message_feedback (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    message_id INTEGER NOT NULL,
    session_id TEXT NOT NULL,
    rating TEXT NOT NULL,
    comment TEXT,
    created_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_feedback_message
    ON message_feedback(message_id);
CREATE INDEX IF NOT EXISTS idx_feedback_session
    ON message_feedback(session_id);

-- FTS5 全文检索虚拟表（用于 RAG 长期记忆）
CREATE VIRTUAL TABLE IF NOT EXISTS conversations_fts
USING fts5(text, direction, intent, skill,
           content='conversations', content_rowid='id');

-- 触发器保持 FTS 索引与主表同步
CREATE TRIGGER IF NOT EXISTS conversations_ai_insert AFTER INSERT ON conversations BEGIN
  INSERT INTO conversations_fts(rowid, text, direction, intent, skill)
  VALUES (new.id, new.text, new.direction, new.intent, new.skill);
END;
CREATE TRIGGER IF NOT EXISTS conversations_ad_delete AFTER DELETE ON conversations BEGIN
  DELETE FROM conversations_fts WHERE rowid = old.id;
END;
CREATE TRIGGER IF NOT EXISTS conversations_au_update AFTER UPDATE ON conversations BEGIN
  DELETE FROM conversations_fts WHERE rowid = old.id;
  INSERT INTO conversations_fts(rowid, text, direction, intent, skill)
  VALUES (new.id, new.text, new.direction, new.intent, new.skill);
END;

-- 项目管理（projects）
CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT DEFAULT '',
    status TEXT NOT NULL DEFAULT 'draft',
    plan_type TEXT NOT NULL DEFAULT 'dag',
    loop_goal TEXT DEFAULT '',
    loop_stop_condition TEXT DEFAULT '',
    loop_max_iterations INTEGER DEFAULT 10,
    loop_current_iteration INTEGER DEFAULT 1,
    plan_document TEXT DEFAULT '',
    result_document TEXT DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    completed_at TEXT,
    project_dir TEXT DEFAULT '',
    repo_url TEXT DEFAULT '',
    repo_provider TEXT DEFAULT 'github',
    repo_branch TEXT DEFAULT 'main',
    repo_secret_ref TEXT DEFAULT '',
    created_by TEXT DEFAULT 'system',
    updated_by TEXT DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status);
CREATE INDEX IF NOT EXISTS idx_projects_updated ON projects(updated_at DESC);

-- 凭据存储（平台 Token 热加载）
CREATE TABLE IF NOT EXISTS credentials (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- LLM 配置（模型提供商、API Key、模型选择）
CREATE TABLE IF NOT EXISTS llm_config (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 仓库凭据（每个 (platform, org_slug) 一条，token 加密存储）
-- 运行时 clone 私有仓库时，按 URL 解析出 (platform, org) 匹配并嵌入 token
CREATE TABLE IF NOT EXISTS repo_credentials (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    platform TEXT NOT NULL,
    org_slug TEXT NOT NULL,
    access_token_enc TEXT NOT NULL DEFAULT '',
    api_base TEXT NOT NULL DEFAULT '',
    name TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
    UNIQUE(platform, org_slug)
);
"""
