# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).
"""Fallback Diagnoser — Skill 执行失败时的诊断器。

参考 agentd/core/fallback_diagnose.py。两层诊断（成本控制）：
1. 启发式规则匹配（零 Token）—— 覆盖常见错误类别
2. LLM 诊断（可选，仅在启发式无法识别且 LLM 可用时）
诊断结果追加写入 fallback_log.jsonl，供 analyze_patterns 统计。
"""
import json
import logging
import time
from pathlib import Path

logger = logging.getLogger("agent.diagnose")

# ─────────────────────────────────────────────
# 启发式诊断规则：(匹配关键词列表, 错误类别, 根因, 修复策略, 是否可恢复)
# ─────────────────────────────────────────────
HEURISTIC_RULES = [
    (['no such file or directory', '没有那个文件或目录', 'filenotfound'],
     'missing_file', '命令依赖的文件或路径不存在',
     '检查技能 action_graph 中的路径是否使用 ${home} 等变量正确解析', False),
    (['module not found', 'modulenotfounderror', 'importerror', 'cannot find module'],
     'missing_dependency', '缺少 Python 依赖模块',
     '在工位安装缺失的依赖（pip install），或改用标准库实现', True),
    (['permission denied', '权限不够', 'operation not permitted'],
     'permission', '权限不足（文件/目录/执行权限）',
     '检查工位用户权限，避免访问系统目录；必要时申请提权', False),
    (['timed out', 'timeout', '超时'],
     'timeout', '命令或 LLM 调用超时',
     '拆分长任务、增加超时时间，或改为后台执行', True),
    (['connection refused', 'connection reset', '无法连接', 'network is unreachable',
      'name or service not known', 'urlopen error'],
     'network', '网络连接失败（模型服务/后端不可达）',
     '检查 MODEL_SERVER 配置与网络连通性', True),
    (['command not found', '未找到命令'],
     'missing_command', 'Shell 命令不存在',
     '确认命令已安装且在 PATH 中，或改用绝对路径', False),
    (['budget', 'token 预算', 'budgetexceeded'],
     'budget_exceeded', 'Token 预算超限，LLM 熔断',
     '等待次月预算重置，或联系管理员调整 TOKEN_MONTHLY_CAP', False),
    (['syntax error', 'invalid json', 'json.decoder.jsondecodeerror', '解析失败'],
     'parse_error', 'LLM 输出或配置文件格式非法',
     '检查 JSON 配置格式；LLM 输出可增加 json_mode 约束', True),
    (['killed', 'out of memory', 'memoryerror'],
     'resource', '系统资源不足（内存/进程被杀）',
     '减少并发或任务规模，检查工位资源配额', False),
]


class FallbackDiagnoser:
    """失败诊断：启发式规则 → 可选 LLM → 日志落盘。"""

    def __init__(self, config, llm_client=None):
        self.config = config
        self.llm = llm_client
        self.log_file = Path(config.fallback_log_file)
        self.log_file.parent.mkdir(parents=True, exist_ok=True)

    # ─────────────────────────────────────────
    # 启发式诊断（零 Token）
    # ─────────────────────────────────────────
    def _heuristic_diagnose(self, error_text):
        lowered = error_text.lower()
        for keywords, category, root_cause, fix, recoverable in HEURISTIC_RULES:
            if any(k in lowered for k in keywords):
                return {
                    'error_category': category,
                    'root_cause': root_cause,
                    'fix_strategy': fix,
                    'recoverable': recoverable,
                    'confidence': 0.85,
                    'method': 'heuristic',
                }
        return None

    # ─────────────────────────────────────────
    # LLM 诊断（可选）
    # ─────────────────────────────────────────
    def _llm_diagnose(self, skill_name, step_id, error_text, context):
        if not self.llm or not self.config.llm_configured:
            return None
        system = (
            '你是 Skill 执行失败的诊断专家。分析错误并输出严格 JSON：\n'
            '{"error_category": "...", "root_cause": "...", '
            '"fix_strategy": "...", "recoverable": true/false, '
            '"confidence": 0.0-1.0}\n'
            'error_category 取值：missing_dependency/permission/timeout/network/'
            'missing_file/missing_command/parse_error/budget_exceeded/resource/other'
        )
        user = (
            '技能：%s\n失败步骤：%s\n错误信息：%s\n上下文：%s'
            % (skill_name, step_id, str(error_text)[:1500],
               str(context)[:500])
        )
        try:
            result_str = self.llm.quick_prompt(
                system, user, skill='diagnose', category='normal',
                json_mode=True)
            data = json.loads(result_str)
            data['method'] = 'llm'
            data.setdefault('recoverable', False)
            data.setdefault('confidence', 0.6)
            return data
        except (ValueError, KeyError, RuntimeError) as e:
            logger.error('LLM 诊断失败: %s', e)
            return None

    # ─────────────────────────────────────────
    # 主入口
    # ─────────────────────────────────────────
    def diagnose(self, skill_name, step_id, error, context=None):
        """诊断一次 Skill 失败，返回诊断 dict 并落盘。"""
        error_text = str(error)
        result = self._heuristic_diagnose(error_text)
        if result is None:
            result = self._llm_diagnose(skill_name, step_id, error_text,
                                        context or {})
        if result is None:
            result = {
                'error_category': 'other',
                'root_cause': '未知错误，需人工排查',
                'fix_strategy': '查看完整错误日志与技能配置',
                'recoverable': False,
                'confidence': 0.3,
                'method': 'fallback',
            }
        record = {
            'ts': time.time(),
            'skill': skill_name,
            'step': step_id,
            'error': error_text[:500],
            'diagnosis': result,
        }
        try:
            with open(self.log_file, 'a', encoding='utf-8') as f:
                f.write(json.dumps(record, ensure_ascii=False) + '\n')
        except OSError:
            pass
        logger.warning('诊断 [%s/%s]: %s → %s', skill_name, step_id,
                       result['error_category'], result['root_cause'])
        return result

    # ─────────────────────────────────────────
    # 模式统计
    # ─────────────────────────────────────────
    def analyze_patterns(self, days=7):
        """统计近 N 天失败模式：{total, by_category, by_skill}。"""
        cutoff = time.time() - days * 86400
        by_category, by_skill, total = {}, {}, 0
        if not self.log_file.exists():
            return {'total': 0, 'by_category': {}, 'by_skill': {}}
        try:
            lines = self.log_file.read_text(encoding='utf-8').splitlines()
        except OSError:
            return {'total': 0, 'by_category': {}, 'by_skill': {}}
        for line in lines:
            try:
                rec = json.loads(line)
            except ValueError:
                continue
            if rec.get('ts', 0) < cutoff:
                continue
            total += 1
            cat = rec.get('diagnosis', {}).get('error_category', 'other')
            by_category[cat] = by_category.get(cat, 0) + 1
            skill = rec.get('skill', 'unknown')
            by_skill[skill] = by_skill.get(skill, 0) + 1
        return {'total': total, 'by_category': by_category,
                'by_skill': by_skill}
