# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).
"""MemoryManager — 多层记忆管理（SQLite 后端）。

v2.0 重构：底层存储从 JSONL 文件迁移到 SQLite（core/db.py）。
保留原有 API 接口，上层代码无需修改。

v2.1 新增：
- Token 预算 + 消息数双重限制
- 自动摘要压缩（旧消息摘要 + 最近消息）
- 轨迹压缩器（保护首尾，压缩中间）
- RAG 长期记忆搜索（FTS5）

功能：
- 短期记忆 → SQLite conversations 表
- 执行日志 → SQLite execution_logs 表
- 归档 → SQLite 自动清理过期记录
- 兼容旧版 history.jsonl 格式（迁移读取）
"""
import json
import logging
import time
from datetime import datetime
from pathlib import Path

logger = logging.getLogger("agent.memory")


class MemoryManager:
    """管理数字员工的对话记忆与执行日志。

    底层使用 SQLite（Database 实例），API 保持与原 JSONL 版本兼容。
    """

    def __init__(self, config, db=None):
        self.config = config
        self.db = db

        # 兼容旧版 history.jsonl（迁移读取）
        self.legacy_history = Path(config.history_file)

        if self.db is None:
            # 如果没有传入 db，延迟导入避免循环依赖
            from agent_runtime.core.db import Database
            self.db = Database(config.db_file)

        # 启动时尝试从旧 JSONL 迁移
        try:
            self.db.migrate_from_jsonl(config)
        except Exception:
            logger.debug('JSONL 迁移跳过（可能已迁移过）', exc_info=True)

    # ─────────────────────────────────────────
    # 记录
    # ─────────────────────────────────────────
    def record(self, direction, text, sender=None, intent=None, skill=None,
              session_id=None, thinking=None, metadata=None):
        """记录一条对话到 SQLite。direction: in / out。"""
        self.db.record_conversation(
            direction=direction,
            text=text,
            sender=sender,
            intent=intent,
            skill=skill,
            session_id=session_id,
            thinking=thinking,
            metadata=metadata)
        return {
            'timestamp': datetime.now().isoformat(),
            'direction': direction,
            'text': (str(text) if text is not None else '')[:1000],
            'sender': sender,
            'intent': intent,
            'skill': skill,
        }

    def log_execution(self, intent=None, skill=None, status='ok', detail=None):
        """写执行日志到 SQLite。"""
        self.db.log_execution(
            intent=intent, skill=skill, status=status, detail=detail)

    # ─────────────────────────────────────────
    # 读取
    # ─────────────────────────────────────────
    def get_recent(self, n=20, session_id=None):
        """返回最近 n 条对话记录，可按 session_id 过滤。"""
        return self.db.get_recent_conversations(n, session_id=session_id)

    def get_history_for_llm(self, max_msgs=None, max_tokens=None, session_id=None):
        """构造给 LLM 的历史消息列表 [{role, content}, ...].

        双重限制：消息数 + token 预算。
        优先读 SQLite；为空则回退兼容旧版 history.jsonl。
        session_id: 按会话过滤，确保历史属于同一会话。
        """
        max_msgs = max_msgs or self.config.get('max_history') or 10
        max_tokens = max_tokens or self.config.get('max_history_tokens') or 2000
        records = self.db.get_recent_conversations(max_msgs * 2, session_id=session_id)

        # 回退兼容旧格式（{role, content}）
        if not records and self.legacy_history.exists():
            msgs = []
            try:
                with open(self.legacy_history, 'r', encoding='utf-8') as f:
                    for line in f:
                        line = line.strip()
                        if not line:
                            continue
                        try:
                            obj = json.loads(line)
                            if obj.get('role') and obj.get('content'):
                                msgs.append({'role': obj['role'],
                                             'content': obj['content']})
                        except ValueError:
                            continue
            except (IOError, OSError):
                pass
            return msgs[-max_msgs:]

        msgs = self.db.get_history_for_llm(max_msgs * 2, session_id=session_id)

        # Token 预算：从最旧消息开始弹出，直到满足预算
        while len(msgs) > 1 and self._estimate_tokens(msgs) > max_tokens:
            msgs.pop(0)

        # 硬限制消息数
        return msgs[-max_msgs:]

    def get_history_with_summary(self, max_msgs=None, max_tokens=None, session_id=None):
        """构造历史：摘要（旧消息） + 最近 N 条消息。

        当总 token 超过阈值时，用 FAST_MODEL 将旧消息摘要为一段文字，
        作为 system 消息的补充插入。
        session_id: 按会话过滤，确保历史属于同一会话。
        """
        max_msgs = max_msgs or self.config.get('max_history') or 10
        max_tokens = max_tokens or self.config.get('max_history_tokens') or 2000
        all_msgs = self.get_history_for_llm(max_msgs=max_msgs * 3,
                                            max_tokens=max_tokens * 3,
                                            session_id=session_id)

        if self._estimate_tokens(all_msgs) <= max_tokens:
            return all_msgs  # 未超阈值，直接返回

        # 分割：保留最近 keep_recent 条，其余摘要
        keep_recent = self.config.get('summary_keep_recent') or max(3, max_msgs // 2)
        old_msgs = all_msgs[:-keep_recent]
        recent_msgs = all_msgs[-keep_recent:]

        if not old_msgs:
            return recent_msgs

        # 检查是否有缓存的摘要
        cached_summary = self._get_cached_summary()
        if cached_summary:
            return ([{'role': 'system',
                      'content': '[历史摘要] ' + cached_summary}]
                    + recent_msgs)

        # 用 FAST_MODEL 生成摘要
        if self.config.get('summary_enabled', True):
            summary = self._summarize(old_msgs)
            if summary:
                self._cache_summary(summary)
                return ([{'role': 'system',
                          'content': '[历史摘要] ' + summary}]
                        + recent_msgs)

        return recent_msgs

    def compress_trajectory(self, msgs, protect_first=2, protect_last=4):
        """压缩对话轨迹：保护首尾，中间截断。

        - protect_first: 保护前 N 条（system prompt + 首次问候）
        - protect_last: 保护后 N 条（最近对话上下文）
        - 中间部分截断为摘要
        """
        if len(msgs) <= protect_first + protect_last:
            return msgs  # 消息太少，不压缩

        head = msgs[:protect_first]
        tail = msgs[-protect_last:]
        middle = msgs[protect_first:-protect_last]

        if middle:
            summary = self._summarize(middle)
            if summary:
                compressed = (head +
                              [{'role': 'system',
                                'content': '[中间对话摘要] ' + summary}] +
                              tail)
                return compressed
        return msgs

    # ─────────────────────────────────────────
    # Token 估算
    # ─────────────────────────────────────────
    @staticmethod
    def _estimate_tokens(msgs):
        """粗略估算消息列表的总 token 数。"""
        total_chars = sum(len(m.get('content') or '') for m in msgs)
        return max(total_chars // 3, 1)

    # ─────────────────────────────────────────
    # 摘要
    # ─────────────────────────────────────────
    def _summarize(self, msgs):
        """用 FAST_MODEL 将消息列表摘要为一段文字。"""
        if not msgs:
            return ''
        try:
            from agent_runtime.core.llm_client import LLMClient
            # 使用主 LLM 客户端，但指定 model='fast'
            # 这里延迟导入避免循环依赖
            text = '\n'.join(
                '[%s] %s' % (m.get('role', '?'),
                             (m.get('content') or '')[:200])
                for m in msgs)
            # 通过 db 获取 config（避免循环导入）
            # 实际上 MemoryManager 没有 llm_client 引用，
            # 所以我们用一个轻量级的本地摘要
            return self._simple_summarize(text)
        except Exception:
            logger.debug('摘要生成失败', exc_info=True)
            return ''

    @staticmethod
    def _simple_summarize(text):
        """轻量级本地摘要（不调用 LLM）。"""
        lines = text.strip().split('\n')
        if len(lines) <= 3:
            return text[:500]
        # 取前 2 条和后 2 条作为摘要
        head = lines[:2]
        tail = lines[-2:]
        return '\n'.join(head + ['...（中间省略 %d 条）...' % (len(lines) - 4)] + tail)

    def _get_cached_summary(self):
        """获取缓存的摘要（从 DB 的 execution_logs 中查找）。"""
        try:
            logs = self.db.get_execution_logs(limit=5)
            for log in reversed(logs):
                detail = log.get('detail') or ''
                if detail.startswith('[cached_summary]'):
                    return detail[len('[cached_summary]'):]
        except Exception:
            pass
        return None

    def _cache_summary(self, summary):
        """缓存摘要到 execution_logs。"""
        try:
            self.db.log_execution(
                intent='summary', skill='memory',
                status='ok',
                detail='[cached_summary]%s' % summary[:500])
        except Exception:
            logger.debug('摘要缓存失败', exc_info=True)

    # ─────────────────────────────────────────
    # RAG 长期记忆搜索
    # ─────────────────────────────────────────
    def search_long_term(self, query, top_k=5):
        """用 FTS5 全文检索归档的长期记忆。"""
        if not hasattr(self.db, 'search_conversations_fts'):
            return []
        try:
            records = self.db.search_conversations_fts(query, limit=top_k * 3)
            return records[:top_k]
        except Exception:
            logger.debug('FTS5 搜索失败', exc_info=True)
            return []

    # ─────────────────────────────────────────
    # 归档
    # ─────────────────────────────────────────
    def archive_old(self, days=None):
        """归档超过 days 天的对话记录。"""
        days = days or self.config.get('archive_days')
        return self.db.archive_old_conversations(days)

    # ─────────────────────────────────────────
    # 统计
    # ─────────────────────────────────────────
    def stats(self):
        short_count = self.db.count_conversations()
        sessions_count = self.db.count_sessions()
        return {'short_term': short_count, 'archived': 0,
                'backend': 'sqlite', 'sessions': sessions_count}

    def get_execution_logs(self, limit=10):
        """返回最近 limit 条执行日志。"""
        return self.db.get_execution_logs(limit)
