# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).
"""MetaSkillRegistry — 元技能注册表。

扫描两个目录的 MetaSkill：
- 代码内置：backend/agent_runtime/metaskills/（随代码分发，全员共享）
- 员工专属：{RUNTIME_HOME}/metaskills/（可覆盖内置）

每个 MetaSkill 是一个子目录，包含 manifest.json + impl.py。
合并加载，同名时员工目录覆盖内置（与 SkillManager 策略一致）。

暴露 list_metaskills() / run_metaskill(name, args) 两个核心方法。
"""
import importlib.util
import json
import logging
from pathlib import Path

logger = logging.getLogger("agent.metaskills")


class MetaSkillRegistry:
    """扫描、注册、执行 MetaSkill。"""

    MANIFEST = 'manifest.json'
    IMPL = 'impl.py'

    def __init__(self, builtin_dir, user_dir=None):
        self.builtin_dir = Path(builtin_dir)
        self.user_dir = Path(user_dir) if user_dir else None
        self._registry = {}  # {name: {manifest, impl_module, dir}}
        self.scan()

    # ─────────────────────────────────────────
    # 发现与注册
    # ─────────────────────────────────────────
    def scan(self):
        """扫描内置 + 员工目录，重新加载全部 MetaSkill。"""
        self._registry.clear()
        found = {}

        # 先放内置
        if self.builtin_dir.exists():
            for d in sorted(self.builtin_dir.iterdir()):
                if d.is_dir() and (d / self.MANIFEST).exists():
                    found[d.name] = d

        # 员工目录覆盖同名
        if self.user_dir and self.user_dir.exists():
            for d in sorted(self.user_dir.iterdir()):
                if d.is_dir() and (d / self.MANIFEST).exists():
                    found[d.name] = d

        for name, d in found.items():
            try:
                manifest = self._read_json(d / self.MANIFEST) or {}
                impl_module = self._load_impl(d / self.IMPL, name)
                self._registry[name] = {
                    'name': name,
                    'manifest': manifest,
                    'impl': impl_module,
                    'dir': str(d),
                    'source': ('user' if self.user_dir
                               and str(d).startswith(str(self.user_dir))
                               else 'builtin'),
                }
            except Exception:
                logger.exception('加载 MetaSkill 失败: %s', name)

        logger.info('MetaSkillRegistry: 已注册 %d 个元技能', len(self._registry))

    def list_metaskills(self):
        """返回所有已注册 MetaSkill 的摘要列表。"""
        result = []
        for name, info in sorted(self._registry.items()):
            m = info.get('manifest', {})
            result.append({
                'name': name,
                'description': m.get('description', ''),
                'version': m.get('version', '1.0.0'),
                'source': info.get('source', 'builtin'),
                'inputs': m.get('inputs', {}),
                'outputs': m.get('outputs', {}),
                'zero_llm': m.get('zero_llm', True),
            })
        return result

    def get_metaskill(self, name):
        """获取单个 MetaSkill 信息；不存在返回 None。"""
        return self._registry.get(name)

    def run_metaskill(self, name, args=None):
        """执行指定 MetaSkill，返回结果 dict。"""
        info = self._registry.get(name)
        if not info:
            return {'success': False, 'error': "MetaSkill '%s' 未找到" % name}
        impl = info.get('impl')
        if not impl or not hasattr(impl, 'run'):
            return {'success': False,
                    'error': "MetaSkill '%s' 缺少 run() 入口" % name}
        try:
            result = impl.run(**(args or {}))
            if isinstance(result, dict) and 'success' not in result:
                result['success'] = True
            return result
        except Exception as e:
            logger.exception('MetaSkill %s 执行异常', name)
            return {'success': False, 'error': str(e)}

    # ─────────────────────────────────────────
    # 内部工具
    # ─────────────────────────────────────────
    @staticmethod
    def _read_json(path):
        try:
            return json.loads(Path(path).read_text(encoding='utf-8'))
        except (ValueError, OSError):
            return None

    @staticmethod
    def _load_impl(impl_path, name):
        """动态加载 impl.py 为模块。"""
        if not impl_path.exists():
            return None
        module_name = 'metaskill_impl_%s' % name.replace('.', '_')
        spec = importlib.util.spec_from_file_location(module_name, impl_path)
        if spec is None:
            return None
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod
