# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).
"""PromptAssembler — 可插拔的系统提示词组装器。

借鉴 deepseek-harness 的 system-prompt 注册表：
- 插件通过 register_section() 贡献提示词片段
- 按优先级排序组装
- 支持条件片段（仅在特定条件下包含）

用法：
    assembler = PromptAssembler()
    assembler.register_section(0, base_identity)
    assembler.register_section(10, tool_descriptions)
    assembler.register_section(20, skill_descriptions)
    assembler.register_conditional(30, rag_context, condition=has_rag)

    prompt = assembler.assemble(context)
"""
import logging
from typing import Any, Callable, Optional

logger = logging.getLogger("agent.prompt")


class PromptSection:
    """提示词片段。

    Attributes:
        priority: 优先级（越小越靠前）
        provider: 内容提供函数 (context) -> str
        name: 片段名称（用于日志/调试）
        condition: 条件函数 (context) -> bool（可选）
    """

    def __init__(self, priority: int, provider: Callable,
                 name: str = '', condition: Callable = None):
        self.priority = priority
        self.provider = provider
        self.name = name or provider.__name__
        self.condition = condition

    def should_include(self, context: Any) -> bool:
        """判断是否应包含此片段。"""
        if self.condition is None:
            return True
        try:
            return bool(self.condition(context))
        except Exception:
            logger.exception('提示词条件判断异常: %s', self.name)
            return False

    def render(self, context: Any) -> str:
        """渲染片段内容。"""
        try:
            return self.provider(context)
        except Exception:
            logger.exception('提示词片段渲染失败: %s', self.name)
            return ''


class PromptAssembler:
    """可插拔的系统提示词组装器。

    按优先级排序组装所有注册的提示词片段。
    支持条件片段（仅在特定条件下包含）。
    """

    def __init__(self, separator: str = '\n\n'):
        """
        Args:
            separator: 片段之间的分隔符
        """
        self._sections: list[PromptSection] = []
        self._separator = separator

    def register_section(self, priority: int, provider: Callable,
                         name: str = ''):
        """注册一个提示词片段。

        Args:
            priority: 优先级（越小越靠前）
            provider: 内容提供函数 (context) -> str
            name: 片段名称
        """
        self._sections.append(
            PromptSection(priority, provider, name))
        logger.debug('注册提示词片段: %s (priority=%d)',
                     name or provider.__name__, priority)

    def register_conditional(self, priority: int, provider: Callable,
                             condition: Callable, name: str = ''):
        """注册一个条件提示词片段。

        Args:
            priority: 优先级
            provider: 内容提供函数 (context) -> str
            condition: 条件函数 (context) -> bool
            name: 片段名称
        """
        self._sections.append(
            PromptSection(priority, provider, name, condition))
        logger.debug('注册条件提示词片段: %s (priority=%d)',
                     name or provider.__name__, priority)

    def remove_section(self, name: str):
        """移除指定名称的片段。"""
        self._sections = [s for s in self._sections if s.name != name]

    def assemble(self, context: Any = None) -> str:
        """组装完整的系统提示词。

        Args:
            context: 上下文对象（传递给各片段的 provider）

        Returns:
            组装后的完整提示词字符串
        """
        # 按优先级排序
        sorted_sections = sorted(self._sections, key=lambda s: s.priority)

        parts = []
        for section in sorted_sections:
            if not section.should_include(context):
                continue
            content = section.render(context)
            if content and content.strip():
                parts.append(content.strip())

        return self._separator.join(parts)

    def list_sections(self) -> list:
        """列出所有已注册的片段（用于调试）。"""
        return [
            {
                'name': s.name,
                'priority': s.priority,
                'conditional': s.condition is not None,
            }
            for s in sorted(self._sections, key=lambda s: s.priority)
        ]


# ─────────────────────────────────────────
# 内置片段提供函数
# ─────────────────────────────────────────

def make_base_identity(agent_id: str, home: str) -> Callable:
    """创建基础身份片段。"""
    def _provider(context):
        return (
            '你是数字员工 %s，隶属于公司的 AI 团队，运行在独立 Linux 工位上。\n'
            '你的家目录是 %s，所有文件操作必须限制在家目录内。\n'
            '回答使用中文，简洁专业。执行命令后请汇总结果给出人类可读的结论。\n'
            '重要：需要执行命令或读写文件时，直接按规范发起工具调用，'
            '严禁在回复正文里输出工具调用的 JSON 文本。'
        ) % (agent_id, home)
    return _provider


def make_tool_descriptions(tool_registry) -> Callable:
    """创建工具描述片段。"""
    def _provider(context):
        installed = tool_registry.installed_tools()
        if not installed:
            return '已安装的生产力工具：（尚未安装任何工具）'
        tool_lines = '\n'.join(
            '- %s (%s): %s' % (t.get('name'), t.get('key'),
                               t.get('description', ''))
            for t in installed)
        return '已安装的生产力工具：\n%s' % tool_lines
    return _provider


def make_skill_descriptions(skill_manager) -> Callable:
    """创建技能描述片段。"""
    def _provider(context):
        skills = skill_manager.list_skills()
        if not skills:
            return '已装备的技能：（无）'
        skill_lines = '\n'.join(
            '- %s: %s' % (s['name'], s['description'])
            for s in skills)
        return '已装备的技能：\n%s' % skill_lines
    return _provider


def make_metaskill_descriptions(metaskill_registry) -> Callable:
    """创建元技能描述片段。"""
    def _provider(context):
        metaskills = metaskill_registry.list_metaskills()
        if not metaskills:
            return ''
        lines = '\n'.join(
            '- %s: %s' % (m['name'], m['description'])
            for m in metaskills)
        return '可用的元技能（原子工具函数，无需 LLM）：\n%s' % lines
    return _provider


def make_rag_context(memory_manager) -> Callable:
    """创建 RAG 上下文片段（条件性）。"""
    def _provider(context):
        if not context or not hasattr(context, 'query'):
            return ''
        results = memory_manager.search_long_term(context.query, top_k=3)
        if not results:
            return ''
        rag_text = '\n'.join(
            r.get('text', '')[:200] for r in results if r.get('text'))
        return '[相关历史] %s' % rag_text if rag_text else ''

    def _condition(context):
        return context and hasattr(context, 'query') and context.query

    return _provider
