# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).
"""SessionLog — 事件溯源会话日志。

借鉴 deepseek-harness 的 Event-Sourced Session Log 设计：
- Session 是一个 append-only 的 SessionEvent 日志
- LLM 消息历史从日志 derive_messages() 派生，不单独存储
- 支持 fork/resume、崩溃恢复、精确回放

事件类型：
  turn_start, turn_end, step_start, step_end,
  user_message, assistant_message, assistant_chunk,
  tool_call, tool_result, compaction_start, compaction_end, error

持久化：SQLite session_events 表（seq 单调递增）。
"""
import json
import logging
import time
import threading
from dataclasses import dataclass, field, asdict
from typing import Optional

logger = logging.getLogger("agent.session_log")


# ─────────────────────────────────────────
# 事件类型常量
# ─────────────────────────────────────────

class EventType:
    """会话事件类型枚举。"""
    TURN_START = 'turn_start'
    TURN_END = 'turn_end'
    STEP_START = 'step_start'
    STEP_END = 'step_end'
    USER_MESSAGE = 'user_message'
    ASSISTANT_MESSAGE = 'assistant_message'
    ASSISTANT_CHUNK = 'assistant_chunk'
    TOOL_CALL = 'tool_call'
    TOOL_RESULT = 'tool_result'
    COMPACTION_START = 'compaction_start'
    COMPACTION_END = 'compaction_end'
    ERROR = 'error'


@dataclass(frozen=True)
class SessionEvent:
    """不可变事件条目。

    Attributes:
        seq:  单调递增序号（会话内唯一）
        time: epoch 毫秒时间戳
        type: 事件类型（见 EventType）
        data: 事件载荷（不可变 dict）
    """
    seq: int
    time: float
    type: str
    data: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        """序列化为 dict（用于 JSON / SQLite 存储）。"""
        return {
            'seq': self.seq,
            'time': self.time,
            'type': self.type,
            'data': self.data,
        }

    @classmethod
    def from_dict(cls, d: dict) -> 'SessionEvent':
        """从 dict 反序列化。"""
        return cls(
            seq=d['seq'],
            time=d['time'],
            type=d['type'],
            data=d.get('data', {}),
        )


class SessionLog:
    """Append-only 事件日志。

    每个 session_id 对应一条独立的事件流。
    事件按 seq 单调递增，seq 在 session 内唯一。

    用法：
        log = SessionLog(db, session_id='abc-123')
        log.append(EventType.TURN_START, {'turn': 0})
        log.append(EventType.USER_MESSAGE, {'content': '你好'})
        messages = log.derive_messages()
    """

    def __init__(self, db, session_id: str):
        """
        Args:
            db: Database 实例（共享 SQLite 连接）
            session_id: 会话唯一标识
        """
        self.db = db
        self.session_id = session_id
        self._seq = 0
        self._lock = threading.Lock()
        self._listeners: list = []
        self._init_seq()

    def _init_seq(self):
        """从持久化恢复当前 seq（取最大 seq + 1）。"""
        with self.db._cursor() as cur:
            cur.execute(
                'SELECT MAX(seq) FROM session_events WHERE session_id=?',
                (self.session_id,))
            row = cur.fetchone()
            max_seq = row[0] if row and row[0] is not None else -1
            self._seq = max_seq + 1

    # ─────────────────────────────────────────
    # 核心 API
    # ─────────────────────────────────────────

    def append(self, event_type: str, data: dict = None) -> SessionEvent:
        """追加一条事件到日志。

        Args:
            event_type: 事件类型（EventType 常量）
            data: 事件载荷

        Returns:
            新创建的 SessionEvent
        """
        with self._lock:
            event = SessionEvent(
                seq=self._seq,
                time=time.time() * 1000,
                type=event_type,
                data=data or {},
            )
            self._persist(event)
            self._seq += 1

        # 通知监听器（在锁外执行，避免死锁）
        self._notify(event)
        return event

    def get_events(self, start_seq: int = 0, limit: int = 1000) -> list:
        """获取事件列表（按 seq 升序）。

        Args:
            start_seq: 起始序号（含）
            limit: 最大返回数量

        Returns:
            SessionEvent 列表
        """
        with self.db._cursor() as cur:
            cur.execute(
                'SELECT seq, time, type, data FROM session_events '
                'WHERE session_id=? AND seq>=? '
                'ORDER BY seq ASC LIMIT ?',
                (self.session_id, start_seq, limit))
            rows = cur.fetchall()
        return [
            SessionEvent(
                seq=r['seq'], time=r['time'],
                type=r['type'],
                data=json.loads(r['data']) if isinstance(r['data'], str) else r['data'],
            )
            for r in rows
        ]

    def derive_messages(self, max_msgs: int = 50) -> list:
        """从事件日志派生 LLM 消息历史。

        仅提取 user_message 和 assistant_message 事件，
        忽略中间状态（chunk、tool_call 等）。

        Args:
            max_msgs: 最大返回消息数

        Returns:
            [{'role': 'user'|'assistant', 'content': str}, ...]
        """
        events = self.get_events(limit=10000)
        messages = []
        for ev in events:
            if ev.type == EventType.USER_MESSAGE:
                content = ev.data.get('content', '')
                if content:
                    messages.append({'role': 'user', 'content': content})
            elif ev.type == EventType.ASSISTANT_MESSAGE:
                content = ev.data.get('content', '')
                if content:
                    messages.append({'role': 'assistant', 'content': content})
        return messages[-max_msgs:]

    def fork(self, boundary_seq: int, new_session_id: str = None) -> 'SessionLog':
        """从某事件序号分叉出新会话。

        复制 boundary_seq 之前（不含）的所有事件到新会话。

        Args:
            boundary_seq: 分叉边界（新会话不包含此事件）
            new_session_id: 新会话 ID（不指定则自动生成）

        Returns:
            新的 SessionLog 实例
        """
        import uuid
        if new_session_id is None:
            new_session_id = 'fork-%s' % uuid.uuid4().hex[:12]

        new_log = SessionLog(self.db, new_session_id)
        events = self.get_events(start_seq=0, limit=100000)
        for ev in events:
            if ev.seq >= boundary_seq:
                break
            new_log.append(ev.type, ev.data)

        logger.info('会话分叉: %s -> %s (boundary_seq=%d, events=%d)',
                    self.session_id, new_session_id, boundary_seq,
                    new_log._seq)
        return new_log

    def get_turn_count(self) -> int:
        """统计已完成的 turn 数量。"""
        with self.db._cursor() as cur:
            cur.execute(
                'SELECT COUNT(*) FROM session_events '
                'WHERE session_id=? AND type=?',
                (self.session_id, EventType.TURN_END))
            return cur.fetchone()[0]

    def load_from_db(self) -> list:
        """从数据库加载全部事件（用于恢复）。"""
        return self.get_events(start_seq=0, limit=1000000)

    def get_tool_call_summary(self) -> list:
        """获取工具调用摘要（用于前端展示）。"""
        events = self.get_events(limit=10000)
        calls = []
        for ev in events:
            if ev.type == EventType.TOOL_CALL:
                calls.append({
                    'seq': ev.seq,
                    'call_id': ev.data.get('call_id', ''),
                    'name': ev.data.get('name', ''),
                    'args': ev.data.get('args', {}),
                    'time': ev.time,
                    'status': 'running',
                })
            elif ev.type == EventType.TOOL_RESULT:
                call_id = ev.data.get('call_id', '')
                for c in calls:
                    if c['call_id'] == call_id:
                        c['status'] = 'error' if ev.data.get('is_error') else 'completed'
                        c['result'] = ev.data.get('content', '')
                        c['duration_ms'] = ev.time - c['time']
                        break
        return calls

    # ─────────────────────────────────────────
    # 监听器（用于实时推送 / 前端事件流）
    # ─────────────────────────────────────────

    def add_listener(self, callback):
        """注册事件监听器。

        Args:
            callback: callable(SessionEvent) — 每次 append 后调用
        """
        self._listeners.append(callback)

    def remove_listener(self, callback):
        """移除事件监听器。"""
        try:
            self._listeners.remove(callback)
        except ValueError:
            pass

    def _notify(self, event: SessionEvent):
        """通知所有监听器（异常隔离）。"""
        for listener in self._listeners:
            try:
                listener(event)
            except Exception:
                logger.exception('SessionLog 监听器异常（已隔离）')

    # ─────────────────────────────────────────
    # 持久化
    # ─────────────────────────────────────────

    def _persist(self, event: SessionEvent):
        """将事件写入 SQLite。

        处理 UNIQUE 约束冲突：重新获取最大 seq 并重试。
        """
        with self.db._cursor() as cur:
            try:
                cur.execute(
                    'INSERT INTO session_events '
                    '(session_id, seq, time, type, data) '
                    'VALUES (?, ?, ?, ?, ?)',
                    (self.session_id, event.seq, event.time,
                     event.type, json.dumps(event.data, ensure_ascii=False)))
            except Exception as e:
                # UNIQUE constraint failed: 重新获取最大 seq
                if 'UNIQUE constraint' in str(e):
                    logger.warning('session_events seq 冲突，重新获取最大 seq')
                    cur.execute(
                        'SELECT MAX(seq) FROM session_events WHERE session_id=?',
                        (self.session_id,))
                    row = cur.fetchone()
                    new_seq = (row[0] if row and row[0] is not None else -1) + 1
                    event.seq = new_seq
                    self._seq = new_seq + 1
                    cur.execute(
                        'INSERT INTO session_events '
                        '(session_id, seq, time, type, data) '
                        'VALUES (?, ?, ?, ?, ?)',
                        (self.session_id, event.seq, event.time,
                         event.type, json.dumps(event.data, ensure_ascii=False)))
                else:
                    raise

    def __repr__(self):
        return '<SessionLog session=%s seq=%d>' % (
            self.session_id, self._seq)
