# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).
"""SkillManager — Skill Package 仓库管理（两级存放）。

参考 agentd/skills/ 与 agentd/core/dag_executor.py 的 load_skill。
两级存放策略：
- 代码内置：backend/agent_runtime/skills/（随代码分发，全员共享）
- 员工专属：{RUNTIME_HOME}/skills/（install_skill.py 安装）
合并加载，同名时员工目录优先（可覆盖内置技能）。
"""
import json
import logging
from pathlib import Path

logger = logging.getLogger("agent.skills")


class SkillManager:
    """扫描、加载、执行 Skill Package，并提取意图规则。"""

    MANIFEST = 'manifest.json'
    GRAPH = 'action_graph.json'

    def __init__(self, config, dag_executor=None):
        self.config = config
        self.dag = dag_executor
        self.builtin_dir = Path(config.skills_builtin_dir)
        self.user_dir = Path(config.skills_user_dir)

    # ─────────────────────────────────────────
    # 发现
    # ─────────────────────────────────────────
    def _skill_dirs(self):
        """返回 {name: path}，员工目录覆盖内置目录。"""
        found = {}
        # 先放内置
        if self.builtin_dir.exists():
            for d in sorted(self.builtin_dir.iterdir()):
                if d.is_dir() and (d / self.MANIFEST).exists():
                    found[d.name] = d
        # 员工目录覆盖同名
        if self.user_dir.exists():
            for d in sorted(self.user_dir.iterdir()):
                if d.is_dir() and (d / self.MANIFEST).exists():
                    found[d.name] = d
        return found

    def list_skills(self):
        """返回所有已注册技能的摘要列表。"""
        result = []
        for name, d in self._skill_dirs().items():
            manifest = self._read_json(d / self.MANIFEST) or {}
            source = 'user' if str(d).startswith(str(self.user_dir)) else 'builtin'
            result.append({
                'name': name,
                'description': manifest.get('description', ''),
                'version': manifest.get('version', '1.0.0'),
                'source': source,
                'intents': [c.get('intent', '')
                            for c in manifest.get('applicable_when', [])],
            })
        return result

    def load_skill(self, name):
        """加载单个技能，返回 {name, manifest, dag, dir}；不存在返回 None。"""
        dirs = self._skill_dirs()
        d = dirs.get(name)
        if not d:
            logger.error('Skill 不存在: %s', name)
            return None
        manifest = self._read_json(d / self.MANIFEST) or {}
        dag = self._read_json(d / self.GRAPH) or {}
        return {'name': name, 'manifest': manifest, 'dag': dag, 'dir': str(d)}

    def execute_skill(self, name, inputs=None):
        """加载并执行技能（委托 DAGExecutor）。"""
        if not self.dag:
            return {'success': False, 'error': 'DAGExecutor 未就绪'}
        skill = self.load_skill(name)
        if not skill:
            return {'success': False, 'error': "Skill '%s' 未找到" % name}
        return self.dag.execute(skill, inputs or {})

    # ─────────────────────────────────────────
    # 意图规则提取（供 IntentRouter）
    # ─────────────────────────────────────────
    def get_intent_rules(self):
        """从所有技能 manifest 的 applicable_when 提取路由规则。"""
        rules = []
        for name, d in self._skill_dirs().items():
            manifest = self._read_json(d / self.MANIFEST) or {}
            for cond in manifest.get('applicable_when', []):
                if 'intent' in cond:
                    rules.append({
                        'intent': cond['intent'],
                        'keywords': cond.get('keywords', []),
                        'context_keywords': cond.get('context_keywords', []),
                        'regex': cond.get('regex'),
                        'skill': name,
                        'confidence': 0.88,
                    })
        return rules

    @staticmethod
    def _read_json(path):
        try:
            return json.loads(Path(path).read_text(encoding='utf-8'))
        except (ValueError, OSError):
            return None
