# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).
"""任务执行引擎 — 承接平台委派任务的完整执行流水线。

架构:
- TaskContext: 任务执行上下文（封装平台任务的全部元数据）
- TaskResult: 统一执行结果
- TaskPromptBuilder: 任务感知系统提示词构建
- TaskZeroExecutor: Task 0 阶段拆解（队长角色）
- TaskExecutor: 常规任务执行（队员角色，按类型分流）

核心原则:
- 队长待命：队长完成拆解+指派后即进入待命状态
- 代码类走子 Agent：代码编写委托 SubagentProvider（Qoder/Codex）
- 工作空间分层：最终产物 → repos/{仓库}/docs/，中间产物 → tasks/{task_id}/

"""
import asyncio
import json
import logging
import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Optional

logger = logging.getLogger('agent.task_executor')


# ─────────────────────────────────────────
# 数据对象
# ─────────────────────────────────────────

@dataclass
class TaskResult:
    """任务执行结果。"""
    result_document: str = ''
    result_status: str = 'SUCCESS'   # SUCCESS / SUCCESS_WITH_NOTES / REVISION_NEEDED / BLOCKED
    token_used: int = 0
    artifacts: list = field(default_factory=list)  # list[Path]


@dataclass
class TaskContext:
    """封装一次平台任务执行的全部上下文。"""
    platform_task_id: int = 0          # 平台 Task PK
    task_id: str = ''                  # 如 proj-xxx-P1-1
    title: str = ''
    spec_document: str = ''            # 完整规格文档（不截断）
    priority: int = 5
    depends_on: list = field(default_factory=list)
    task_workspace: Path = None        # 中间产物: workspace/projects/{proj}/tasks/{task_id}/
    repo_docs_dir: Path = None         # 最终产物: workspace/projects/{proj}/repos/{仓库名}/docs/
    is_task_zero: bool = False         # 是否为 Task 0
    phase_index: int = 0               # 阶段序号
    project_id: str = ''               # 项目标识
    task_type: str = 'general'         # doc / code / analysis / general
    template_ref: str = ''             # 关联模板名称
    required_skills: list = field(default_factory=list)
    progress_callback: Callable = None # (progress: int, phase: str, message: str) -> None

    @staticmethod
    def from_payload(payload: dict, home: str) -> 'TaskContext':
        """从 platform.task.assign 消息构造 TaskContext。"""
        task_id = payload.get('task_id', '')
        platform_task_id = payload.get('platform_task_id', 0)
        project_id, phase_index = _parse_task_id(task_id)
        is_task_zero = task_id.endswith('-0')

        # 任务类型推断
        title = payload.get('title', '')
        template_ref = payload.get('template_ref', '')
        required_skills = payload.get('required_skills', [])
        task_type = _infer_task_type(title, template_ref, required_skills)

        # 分层工作空间路径
        proj_ws = Path(home) / 'workspace' / 'projects' / project_id
        task_ws = proj_ws / 'tasks' / task_id
        repo_name = payload.get('repo_name') or project_id
        repo_docs = proj_ws / 'repos' / repo_name / 'docs'

        ctx = TaskContext(
            platform_task_id=platform_task_id,
            task_id=task_id,
            title=title,
            spec_document=payload.get('spec_document', ''),
            priority=payload.get('priority', 5),
            depends_on=payload.get('depends_on', []),
            task_workspace=task_ws,
            repo_docs_dir=repo_docs,
            is_task_zero=is_task_zero,
            phase_index=phase_index,
            project_id=project_id,
            task_type=task_type,
            template_ref=template_ref,
            required_skills=required_skills,
        )
        return ctx

    def ensure_dirs(self):
        """创建任务工作空间目录。"""
        if self.task_workspace:
            self.task_workspace.mkdir(parents=True, exist_ok=True)
            (self.task_workspace / 'scratch').mkdir(exist_ok=True)
            (self.task_workspace / 'artifacts').mkdir(exist_ok=True)
        if self.repo_docs_dir:
            self.repo_docs_dir.mkdir(parents=True, exist_ok=True)

    def report_progress(self, progress: int, phase: str = '',
                        message: str = ''):
        """上报进度（安全调用）。"""
        if self.progress_callback:
            try:
                self.progress_callback(progress, phase, message)
            except Exception:
                logger.debug('进度上报失败', exc_info=True)


# ─────────────────────────────────────────
# 辅助函数
# ─────────────────────────────────────────

def _parse_task_id(task_id: str):
    """从 task_id 解析 project_id 和 phase_index。

    格式: {project_id}-P{phase}-{seq}
    例如: proj-abc-P1-3 → ('proj-abc', 1)
    """
    m = re.match(r'^(.+)-P(\d+)-\d+$', task_id)
    if m:
        return m.group(1), int(m.group(2))
    # Task 0 格式: {project_id}-P{phase}-0
    m = re.match(r'^(.+)-P(\d+)-0$', task_id)
    if m:
        return m.group(1), int(m.group(2))
    return task_id, 0


def _infer_task_type(title: str, template_ref: str,
                     required_skills: list) -> str:
    """从标题/模板/技能推断任务类型。"""
    text = (title + ' ' + template_ref).lower()
    skills_lower = [s.lower() for s in (required_skills or [])]

    # 代码编写类
    code_keywords = ['代码', '编码', '接口', '模块', '开发', '编程', '函数',
                     'code', 'api', 'backend', 'frontend']
    for kw in code_keywords:
        if kw in text or kw in skills_lower:
            return 'code'

    # 文档编写类
    doc_keywords = ['编写', '撰写', '文档', '说明书', '报告', '计划',
                    '规格', '大纲', '模板']
    if template_ref:
        return 'doc'
    for kw in doc_keywords:
        if kw in text:
            return 'doc'

    # 分析类
    analysis_keywords = ['分析', '调研', '评审', '评估', '审查', '测试']
    for kw in analysis_keywords:
        if kw in text:
            return 'analysis'

    return 'general'


# ─────────────────────────────────────────
# TaskPromptBuilder — 任务感知提示词构建
# ─────────────────────────────────────────

class TaskPromptBuilder:
    """为平台任务构建专用的系统提示词。"""

    def build_task_system_prompt(self, ctx: TaskContext, app) -> str:
        """构建常规任务专用系统提示词。"""
        sections = [
            self._base_identity(ctx, app),
            self._task_context_section(ctx),
            self._spec_document_section(ctx),
            self._workspace_section(ctx),
            self._output_guidelines(ctx),
        ]
        return '\n\n'.join(s for s in sections if s)

    def build_task_zero_prompt(self, ctx: TaskContext, app) -> str:
        """构建 Task 0 拆解专用系统提示词（队长角色）。"""
        agent_id = app.config.agent_id
        sections = [
            '你是数字员工 %s，当前担任项目队长角色。\n'
            '你的职责是：将阶段工作拆解为可执行任务，并为每个任务指派合适的执行人。\n'
            '完成拆解和指派后你将进入待命状态，具体任务由队员执行。\n'
            '除非任务非常繁重，否则你不需要亲自执行具体任务。' % agent_id,
            self._spec_document_section(ctx),
            self._task_zero_output_format(ctx),
        ]
        return '\n\n'.join(s for s in sections if s)

    # ── 提示词片段 ──

    def _base_identity(self, ctx: TaskContext, app) -> str:
        agent_id = app.config.agent_id
        home = app.config.home
        return (
            '你是数字员工 %s，正在执行项目任务。\n'
            '你的家目录是 %s，所有文件操作必须限制在家目录内。\n'
            '回答使用中文，简洁专业。需要读写文件时直接发起工具调用。'
        ) % (agent_id, home)

    def _task_context_section(self, ctx: TaskContext) -> str:
        parts = [
            '## 当前任务',
            '- 任务 ID: %s' % ctx.task_id,
            '- 任务标题: %s' % ctx.title,
            '- 优先级: %d' % ctx.priority,
            '- 任务类型: %s' % ctx.task_type,
        ]
        if ctx.template_ref:
            parts.append('- 关联模板: %s' % ctx.template_ref)
        if ctx.required_skills:
            parts.append('- 所需技能: %s' % ', '.join(ctx.required_skills))
        if ctx.phase_index:
            parts.append('- 所属阶段: 第 %d 阶段' % ctx.phase_index)
        return '\n'.join(parts)

    def _spec_document_section(self, ctx: TaskContext) -> str:
        if not ctx.spec_document:
            return ''
        spec = ctx.spec_document
        # 超长截断（保留前 8000 字符）
        if len(spec) > 8000:
            spec = spec[:8000] + '\n\n... (规格文档已截断，共 %d 字符)' % len(
                ctx.spec_document)
        return '## 任务规格文档\n\n%s' % spec

    def _workspace_section(self, ctx: TaskContext) -> str:
        return (
            '## 工作空间\n'
            '- 中间产物（草稿、临时文件）写入: %s\n'
            '- 最终产物（正式文档、交付物）写入: %s\n'
            '请确保最终文档保存到最终产物目录。'
        ) % (ctx.task_workspace, ctx.repo_docs_dir)

    def _output_guidelines(self, ctx: TaskContext) -> str:
        if ctx.task_type == 'doc':
            return (
                '## 输出要求\n'
                '- 输出必须是 Markdown 格式\n'
                '- 如果规格文档中有模板内容，请遵循模板格式\n'
                '- 先将草稿写入中间产物目录，最终文档写入最终产物目录\n'
                '- 最终文件命名应清晰反映文档类型'
            )
        elif ctx.task_type == 'code':
            return (
                '## 输出要求\n'
                '- 代码将委托给专业子 Agent（Qoder/Codex）执行\n'
                '- 代码产出物写入最终产物目录\n'
                '- 完成后提供文件路径列表和简要说明'
            )
        elif ctx.task_type == 'analysis':
            return (
                '## 输出要求\n'
                '- 输出结构化分析报告（Markdown 格式）\n'
                '- 包含：背景、发现、结论、建议\n'
                '- 报告写入最终产物目录'
            )
        return (
            '## 输出要求\n'
            '- 完成任务后将结果写入最终产物目录\n'
            '- 提供简要的执行结果说明'
        )

    def _task_zero_output_format(self, ctx: TaskContext) -> str:
        return (
            '## 输出格式要求\n'
            '请以 JSON 数组格式返回拆解结果（用 ```json 代码块包裹）：\n'
            '```json\n'
            '[\n'
            '  {\n'
            '    "title": "任务标题",\n'
            '    "description": "具体要做什么，产出什么",\n'
            '    "required_skills": ["技能标签1", "技能标签2"],\n'
            '    "estimated_hours": 4,\n'
            '    "depends_on": [],\n'
            '    "suggested_role": "建议执行角色",\n'
            '    "suggested_agent_id": "建议执行的 Agent ID",\n'
            '    "template_ref": "来源模板名称"\n'
            '  }\n'
            ']\n'
            '```\n\n'
            '注意事项：\n'
            '- 每个任务必须包含 suggested_agent_id（从花名册中选择）\n'
            '- depends_on 填写前置任务的数组索引（从 0 开始）\n'
            '- 根据团队成员的角色和能力合理指派执行人\n'
            '- 任务粒度适中，每个任务 2-8 小时为宜\n'
            '- 完成拆解和指派后你将进入待命状态'
        )


# ─────────────────────────────────────────
# TaskZeroExecutor — Task 0 阶段拆解（队长角色）
# ─────────────────────────────────────────

class TaskZeroExecutor:
    """Task 0 阶段拆解专用执行器（队长角色）。

    职责链：拆解 → 指派 → 上报 → 待命
    """

    def execute(self, ctx: TaskContext, app) -> TaskResult:
        """执行 Task 0 拆解任务。"""
        token_used = 0
        t_start = time.monotonic()

        try:
            # 1. 进度: 已接收
            ctx.report_progress(5, 'received', '任务已接收')

            # 2. 构建拆解提示词
            builder = TaskPromptBuilder()
            system_prompt = builder.build_task_zero_prompt(ctx, app)
            user_msg = ('请对「%s」阶段进行任务拆解并指派执行人。\n\n%s'
                        % (ctx.title or '当前阶段', ctx.spec_document[:2000]))

            ctx.report_progress(15, 'analyzing', '分析阶段模板内容')

            # 3. LLM 多轮调用
            messages = [
                {'role': 'system', 'content': system_prompt},
                {'role': 'user', 'content': user_msg},
            ]
            tool_schemas = app.tools.get_openai_tools_schema()
            max_rounds = min(5, app.config.get('max_tool_rounds', 5))

            ctx.report_progress(40, 'decomposing', 'LLM 正在生成任务拆解')

            reply_content = ''
            for round_idx in range(max_rounds):
                msg = app.llm.chat(
                    messages, tools=tool_schemas or None,
                    skill='task_zero', category='decomposition')

                # 累计 token
                for m in messages:
                    token_used += LLMClient_quick_estimate(
                        m.get('content', ''))

                # 处理工具调用
                tool_calls = msg.get('tool_calls')
                if tool_calls:
                    messages.append(msg)
                    for tc in tool_calls:
                        fn = tc.get('function', {})
                        try:
                            args = json.loads(fn.get('arguments') or '{}')
                        except ValueError:
                            args = {}
                        result = app._exec_tool_call(
                            fn.get('name', ''), args)
                        messages.append({
                            'role': 'tool',
                            'tool_call_id': tc.get('id', ''),
                            'content': json.dumps(
                                result, ensure_ascii=False)[
                                :app.config.get('output_limit', 8000)],
                        })
                    continue

                reply_content = msg.get('content') or ''
                break

            if not reply_content:
                reply_content = '拆解失败：LLM 未返回有效内容'
                return TaskResult(
                    result_document=reply_content,
                    result_status='REVISION_NEEDED',
                    token_used=token_used)

            ctx.report_progress(60, 'assigning', '为任务指派执行人')

            # 4. JSON 解析与验证
            tasks_json = _parse_task_zero_json(reply_content)

            ctx.report_progress(80, 'formatting', '格式化 JSON 输出')

            # 验证（最多 2 次修正重试）
            for retry in range(2):
                if tasks_json:
                    break
                logger.warning('Task 0 JSON 解析失败，第 %d 次修正', retry + 1)
                messages.append({'role': 'assistant', 'content': reply_content})
                messages.append({
                    'role': 'user',
                    'content': ('你的输出无法解析为有效的任务列表 JSON。'
                                '请重新以 ```json 代码块格式输出任务数组。'
                                '每个任务必须包含 title, description, '
                                'suggested_agent_id 字段。')
                })
                msg = app.llm.chat(
                    messages, skill='task_zero', category='decomposition')
                reply_content = msg.get('content') or ''
                tasks_json = _parse_task_zero_json(reply_content)
                token_used += LLMClient_quick_estimate(reply_content)

            ctx.report_progress(90, 'validating', '验证 JSON Schema')

            # 5. 完成
            if tasks_json:
                # 构造格式化的结果文档
                result_doc = _format_task_zero_result(tasks_json)
            else:
                result_doc = reply_content

            ctx.report_progress(100, 'submitting', '提交拆解+指派方案')

            elapsed = time.monotonic() - t_start
            logger.info('Task 0 执行完成: task=%s tasks=%d token=%d 耗时=%.1fs',
                        ctx.task_id, len(tasks_json), token_used, elapsed)

            return TaskResult(
                result_document=result_doc,
                result_status='SUCCESS' if tasks_json else 'REVISION_NEEDED',
                token_used=token_used)

        except Exception as e:
            logger.exception('Task 0 执行异常: %s', ctx.task_id)
            return TaskResult(
                result_document='Task 0 执行失败: %s' % str(e)[:500],
                result_status='BLOCKED',
                token_used=token_used)


# ─────────────────────────────────────────
# TaskExecutor — 常规任务执行（队员角色）
# ─────────────────────────────────────────

class TaskExecutor:
    """常规项目任务执行器（队员角色）。

    根据任务类型分流：
    - doc/analysis/general → 主 Agent 直接执行（LLM 多轮 + 工具调用）
    - code → 委托 SubagentProvider（Qoder/Codex）
    """

    def execute(self, ctx: TaskContext, app) -> TaskResult:
        """执行常规项目任务。"""
        if ctx.task_type == 'code':
            return self._execute_code_task(ctx, app)
        return self._execute_llm_task(ctx, app)

    # ── 文档/分析/通用任务：主 Agent 直接执行 ──

    def _execute_llm_task(self, ctx: TaskContext, app) -> TaskResult:
        """文档/分析类任务 — 主 Agent LLM 多轮 + 工具调用。"""
        token_used = 0
        t_start = time.monotonic()
        progress = 5

        try:
            ctx.report_progress(progress, 'received', '任务已接收')

            # 构建任务感知提示词
            builder = TaskPromptBuilder()
            system_prompt = builder.build_task_system_prompt(ctx, app)

            # 构造用户消息
            user_msg = '请执行以下任务：%s' % ctx.title
            if ctx.spec_document:
                user_msg += '\n\n详细规格请参见任务规格文档。'

            messages = [
                {'role': 'system', 'content': system_prompt},
                {'role': 'user', 'content': user_msg},
            ]
            tool_schemas = app.tools.get_openai_tools_schema()
            max_rounds = app.config.get('max_tool_rounds', 5)

            ctx.report_progress(15, 'executing', '开始执行任务')

            full_reply = ''
            for round_idx in range(max_rounds):
                msg = app.llm.chat(
                    messages, tools=tool_schemas or None,
                    skill='task_exec', category='project')

                for m in messages:
                    token_used += LLMClient_quick_estimate(
                        m.get('content', ''))

                # 处理工具调用
                tool_calls = msg.get('tool_calls')
                if tool_calls:
                    messages.append(msg)
                    for tc in tool_calls:
                        fn = tc.get('function', {})
                        try:
                            args = json.loads(fn.get('arguments') or '{}')
                        except ValueError:
                            args = {}
                        result = app._exec_tool_call(
                            fn.get('name', ''), args)
                        messages.append({
                            'role': 'tool',
                            'tool_call_id': tc.get('id', ''),
                            'content': json.dumps(
                                result, ensure_ascii=False)[
                                :app.config.get('output_limit', 8000)],
                        })
                    # 进度递增
                    progress = min(progress + 12, 80)
                    ctx.report_progress(
                        progress, 'executing',
                        '第 %d 轮工具调用完成' % (round_idx + 1))
                    continue

                full_reply = msg.get('content') or ''
                break

            if not full_reply:
                full_reply = '任务执行完成（无文本输出）'

            # 收集产出物
            artifacts = _collect_artifacts(ctx)

            # 写入执行日志
            _write_task_log(ctx, full_reply, token_used)

            progress = 95
            ctx.report_progress(progress, 'summarizing', '结果汇总完成')

            # 构造 result_document
            result_doc = full_reply
            if artifacts:
                result_doc += '\n\n---\n产出文件:\n'
                for a in artifacts:
                    result_doc += '- %s\n' % a

            ctx.report_progress(100, 'submitting', '提交结果')

            elapsed = time.monotonic() - t_start
            logger.info('任务执行完成: task=%s type=%s token=%d len=%d 耗时=%.1fs',
                        ctx.task_id, ctx.task_type, token_used,
                        len(full_reply), elapsed)

            return TaskResult(
                result_document=result_doc,
                result_status='SUCCESS',
                token_used=token_used,
                artifacts=artifacts)

        except Exception as e:
            logger.exception('任务执行异常: %s', ctx.task_id)
            return TaskResult(
                result_document='任务执行失败: %s' % str(e)[:500],
                result_status='BLOCKED',
                token_used=token_used)

    # ── 代码任务：委托 SubagentProvider ──

    def _execute_code_task(self, ctx: TaskContext, app) -> TaskResult:
        """代码类任务 — 委托给 Qoder/Codex 子 Agent。"""
        token_used = 0
        t_start = time.monotonic()

        try:
            ctx.report_progress(5, 'received', '代码任务已接收')

            # 构造 SubagentRequest
            from agent_runtime.core.subagent import SubagentRequest
            task_text = ctx.spec_document or ctx.title
            if ctx.title and ctx.spec_document:
                task_text = '%s\n\n%s' % (ctx.title, ctx.spec_document)

            request = SubagentRequest(
                task=task_text,
                context={
                    'cwd': str(ctx.repo_docs_dir or ctx.task_workspace),
                    'instructions': (
                        '你是一个代码编写专家。请根据以下任务规格编写代码。\n'
                        '代码文件保存到: %s\n'
                        '中间工作文件保存到: %s'
                        % (ctx.repo_docs_dir, ctx.task_workspace)
                    ),
                },
                timeout_ms=300_000,  # 5 分钟超时
                provider=_select_code_provider(app),
            )

            ctx.report_progress(10, 'delegating', '委托给子 Agent 执行')

            # 异步执行子 Agent
            loop = asyncio.new_event_loop()
            try:
                result = loop.run_until_complete(
                    app.subagent_manager.execute(request))
            finally:
                loop.close()

            ctx.report_progress(90, 'collecting', '收集代码产出物')

            if result.success:
                artifacts = _collect_artifacts(ctx)
                _write_task_log(ctx, result.output, 0)

                result_doc = result.output or ''
                if artifacts:
                    result_doc += '\n\n---\n代码文件:\n'
                    for a in artifacts:
                        result_doc += '- %s\n' % a

                ctx.report_progress(100, 'submitting', '提交代码结果')

                elapsed = time.monotonic() - t_start
                logger.info('代码任务完成: task=%s provider=%s 耗时=%.1fs',
                            ctx.task_id, result.provider, elapsed)

                return TaskResult(
                    result_document=result_doc,
                    result_status='SUCCESS',
                    token_used=0,
                    artifacts=artifacts)
            else:
                ctx.report_progress(100, 'failed', '子 Agent 执行失败')
                return TaskResult(
                    result_document='代码任务失败: %s' % (result.error or '未知错误'),
                    result_status='BLOCKED',
                    token_used=0)

        except Exception as e:
            logger.exception('代码任务执行异常: %s', ctx.task_id)
            return TaskResult(
                result_document='代码任务执行失败: %s' % str(e)[:500],
                result_status='BLOCKED',
                token_used=token_used)


# ─────────────────────────────────────────
# 内部工具函数
# ─────────────────────────────────────────

def LLMClient_quick_estimate(text: str) -> int:
    """粗略估算 token（与 LLMClient._estimate_tokens 一致）。"""
    return max(len(text) // 3, 1)


def _parse_task_zero_json(text: str) -> list:
    """从 Task 0 返回文本中解析任务列表 JSON。

    支持三种策略：
    1. 纯 JSON 数组
    2. Markdown ```json ... ``` 代码块
    3. 文本中嵌入的 JSON 数组
    """
    if not text:
        return []

    stripped = text.strip()

    # 策略1: 直接解析
    try:
        data = json.loads(stripped)
        if isinstance(data, list):
            return _validate_task_list(data)
    except (json.JSONDecodeError, ValueError):
        pass

    # 策略2: 提取 ```json ... ``` 代码块
    json_blocks = re.findall(r'```(?:json)?\s*\n?(.*?)\n?```', stripped, re.DOTALL)
    for block in json_blocks:
        try:
            data = json.loads(block.strip())
            if isinstance(data, list):
                return _validate_task_list(data)
        except (json.JSONDecodeError, ValueError):
            continue

    # 策略3: 查找文本中的 JSON 数组
    bracket_start = stripped.find('[')
    if bracket_start >= 0:
        bracket_end = stripped.rfind(']')
        if bracket_end > bracket_start:
            try:
                data = json.loads(stripped[bracket_start:bracket_end + 1])
                if isinstance(data, list):
                    return _validate_task_list(data)
            except (json.JSONDecodeError, ValueError):
                pass

    logger.warning('Task 0 JSON 解析失败')
    return []


def _validate_task_list(tasks: list) -> list:
    """验证任务列表，过滤无效条目。"""
    valid = []
    for t in tasks:
        if not isinstance(t, dict):
            continue
        if not t.get('title'):
            continue
        valid.append(t)
    return valid


def _format_task_zero_result(tasks_json: list) -> str:
    """将 Task 0 拆解结果格式化为 result_document。"""
    lines = ['## 任务拆解方案\n']
    for i, t in enumerate(tasks_json):
        title = t.get('title', '任务 %d' % (i + 1))
        desc = t.get('description', '')
        skills = ', '.join(t.get('required_skills', []))
        hours = t.get('estimated_hours', 0)
        depends = t.get('depends_on', [])
        role = t.get('suggested_role', '')
        agent_id = t.get('suggested_agent_id', '')
        tpl = t.get('template_ref', '')

        lines.append('### %d. %s' % (i + 1, title))
        if desc:
            lines.append(desc)
        lines.append('')
        info_parts = []
        if skills:
            info_parts.append('技能: %s' % skills)
        if hours:
            info_parts.append('预估: %dh' % hours)
        if role:
            info_parts.append('角色: %s' % role)
        if agent_id:
            info_parts.append('执行人: %s' % agent_id)
        if tpl:
            info_parts.append('模板: %s' % tpl)
        if depends:
            info_parts.append('依赖: %s' % depends)
        if info_parts:
            lines.append(' | '.join(info_parts))
        lines.append('')

    # 附上原始 JSON（供平台解析）
    lines.append('---\n')
    lines.append('```json')
    lines.append(json.dumps(tasks_json, ensure_ascii=False, indent=2))
    lines.append('```')

    return '\n'.join(lines)


def _select_code_provider(app) -> Optional[str]:
    """选择代码子 Agent provider。优先 Qoder，其次 Codex，兜底 in-process。"""
    providers = app.subagent_manager.providers
    if 'qoder' in providers:
        return 'qoder'
    if 'codex' in providers:
        return 'codex'
    if 'in-process' in providers:
        return 'in-process'
    return None


def _collect_artifacts(ctx: TaskContext) -> list:
    """收集任务工作空间中的产出文件。"""
    artifacts = []
    # 收集 repo_docs_dir 中的文件
    if ctx.repo_docs_dir and ctx.repo_docs_dir.exists():
        for f in ctx.repo_docs_dir.rglob('*'):
            if f.is_file() and not f.name.startswith('.'):
                artifacts.append(f)
    # 收集 task_workspace 中 artifacts/ 子目录的文件
    if ctx.task_workspace:
        art_dir = ctx.task_workspace / 'artifacts'
        if art_dir.exists():
            for f in art_dir.rglob('*'):
                if f.is_file():
                    artifacts.append(f)
        # 也收集根目录的 .md 文件（非草稿）
        for f in ctx.task_workspace.glob('*.md'):
            if f.name != 'draft.md' and f.name != 'task.log':
                artifacts.append(f)
    return artifacts


def _write_task_log(ctx: TaskContext, result: str, token_used: int):
    """写入任务执行日志。"""
    if not ctx.task_workspace:
        return
    log_file = ctx.task_workspace / 'task.log'
    try:
        from datetime import datetime
        with open(log_file, 'w', encoding='utf-8') as f:
            f.write('平台任务执行日志\n')
            f.write('=' * 40 + '\n')
            f.write('任务 ID: %s\n' % ctx.task_id)
            f.write('平台任务 ID: %s\n' % ctx.platform_task_id)
            f.write('标题: %s\n' % ctx.title)
            f.write('类型: %s\n' % ctx.task_type)
            f.write('创建时间: %s\n' % datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
            f.write('工作目录: %s\n' % ctx.task_workspace)
            f.write('Token 消耗: %d\n' % token_used)
            f.write('=' * 40 + '\n\n')
            f.write('结果:\n')
            f.write(result[:5000] if result else '(无输出)')
    except Exception:
        logger.debug('写入任务日志失败', exc_info=True)
