# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).
"""tool_probe — CLI Agent 工具健壮探测。

`shutil.which` 只回答「PATH 上有没有同名文件」，而不是「这个 CLI 能不能用」。
两者之间的差距足以让安装/切换静默失败，因此本模块坚持运行 `<binary> --version`
并上报结果，而不是相信一次路径查找。

移植来源（只读参考）：
- LongHorizon-Harness `probe_agent_cli`：真实执行 --version + Windows Store
  App Execution Alias（0 字节假 exe）识别 + 结构化 problem 归因；
- omnigent `resolve_cli_binary`：PATH 回退阶梯（~/.local/bin、/usr/local/bin、
  nvm 当前版本、npm global bin、macOS 桌面版特例）；
- multica 桌面端：GUI/daemon 启动时继承的 PATH 不完整，通过登录 shell 懒解析
  真实 PATH（带 TTL 缓存）兜底。
"""
import asyncio
import glob
import logging
import os
import re
import shlex
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from typing import Iterable, Optional

from .tool_descriptor import ToolDescriptor

logger = logging.getLogger("agent.tool_probe")


# ─────────────────────────────────────────
# 快速检测辅助函数
# ─────────────────────────────────────────

def find_binary_simple(name: str) -> tuple:
    """快速检测工具是否安装（同步）。

    与 `_resolve_binary` 共用定位阶梯，但收窄搜索范围以保持「快速」语义：
    仅 PATH + 少量扩展目录 + ~/.qoder/bin/<name>，不触发登录 shell / npm /
    whereis 子进程（避免阻塞调用方的事件循环）。它被 subagent/builtin/shell_mcp
    的 async 路径同步调用，必须快速返回。

    返回 (路径, 状态):
    - (path, "found") — 在 PATH 中找到
    - (path, "found_not_in_path") — 在扩展目录中找到，但不在 PATH 中
    - (None, "not_installed") — 完全未安装
    """
    if not name:
        return None, "not_installed"

    # 统一定位阶梯（含 nvm 优先，与 probe_tool 一致）；关闭登录 shell / npm /
    # whereis 子进程以保持快速；env override 失效时继续回退（strict_override=False）。
    path = _resolve_binary(name, use_login_shell=False, use_npm=False,
                           use_whereis=False, strict_override=False)
    if not (path and os.path.isfile(path)
            and not _is_windows_store_alias(path)
            and os.access(path, os.X_OK)):
        return None, "not_installed"

    # status 判定：名称是否可在 PATH 中解析（与旧语义一致）。
    # 即使优先返回 nvm 版本，“node 在 PATH 中”仍记为 found。
    return path, ("found" if shutil.which(name) else "found_not_in_path")


# ─────────────────────────────────────────
# 问题归因常量
# ─────────────────────────────────────────

PROBLEM_NOT_FOUND = "not_found"
PROBLEM_VERSION_TOO_LOW = "version_too_low"
PROBLEM_VERSION_UNVERIFIED = "version_unverified"
PROBLEM_WINDOWS_STORE_ALIAS = "windows_store_alias"
PROBLEM_PERMISSION_DENIED = "permission_denied"
PROBLEM_EXECUTION_ERROR = "execution_error"

# Windows Store App Execution Alias 目录（reparse point，非真实程序）
_WINDOWS_STORE_ALIAS_DIR = os.path.join("Microsoft", "WindowsApps")

# macOS 桌面版 Codex（与 npm 全局 CLI 可能并存，桌面版优先级更高）
_CODEX_DESKTOP_BINARIES = (
    "/Applications/ChatGPT.app/Contents/Resources/codex",
    "~/Applications/ChatGPT.app/Contents/Resources/codex",
)

_VERSION_RE = re.compile(r"\d+\.\d+(?:\.\d+)*(?:[-+][0-9A-Za-z.\-]+)?")
# 版本化产物后缀白名单：仅纯版本号（如 1.1.45 / 2 / 3.0.0-rc1），
# 用于过滤 git-shell / docker-compose / python-config 等同前缀兄弟可执行文件。
_VERSION_SUFFIX_RE = re.compile(r"^\d+(?:\.\d+)*(?:[-+].*)?$")
_ANSI_RE = re.compile(r"\x1b\[[0-9;?]*[a-zA-Z]")

# --version 执行超时（秒）与输出上限（字节）
# 差异化超时：列表场景快速失败，安装场景给冷启动/首次下载足够余量。
PROBE_TIMEOUT_LIST = 8.0
PROBE_TIMEOUT_INSTALL = 30.0
# 向后兼容：既有引用统一指向列表场景超时。
PROBE_TIMEOUT = PROBE_TIMEOUT_LIST
# 健康检查重试的累计总预算上限（秒），作为权威上界收敛总耗时，
# 与 base_timeout/retries/first_run_grace 无关（每次 attempt 前裁剪到剩余预算）。
PROBE_HEALTH_TOTAL_BUDGET = 45.0
# 单次 attempt 超时下限（秒）：剩余预算低于此值则不再发起该次 attempt，
# 同时避免裁剪出非正超时。
PROBE_HEALTH_MIN_TIMEOUT_FLOOR = 0.5
PROBE_OUTPUT_LIMIT = 4096

# 探测结果缓存（避免列表接口每次请求都 fork 子进程）
# 键为 (tool_key, normalized_extra_dirs)，使带 extra_dirs 的探测也能命中缓存。
PROBE_CACHE_TTL = 30.0
_probe_cache: dict[tuple, tuple[float, "ProbeResult"]] = {}


@dataclass
class ProbeResult:
    """探测结果（三级信号分离）。

    借鉴 OpenOPC preflight 的 available/issues/warnings 思想，将「已安装」与
    「完全可用/已鉴权/版本达标」拆开：
    - installed：二进制定位成功 + 非 Windows Store alias + 有执行权限（安装成功判据）；
    - healthy：`--version` 在超时内 rc==0 且能解析版本号且（若声明 min_version）达标；
    - usable：healthy 的别名（兼容旧调用点，恒等于 healthy）。
    """

    found: bool = False                    # 是否定位到可执行文件（含假可执行拦截）
    installed: bool = False                # 二进制可定位 + 非 alias + 有 X_OK（安装成功判据）
    healthy: bool = False                  # --version 成功且版本达标（承载旧 usable 语义）
    version: Optional[str] = None          # 解析出的版本号
    path: Optional[str] = None             # 解析出的绝对路径
    problem: Optional[str] = None          # not_found/version_too_low/version_unverified/
                                           # windows_store_alias/permission_denied/execution_error
    detail: Optional[str] = None           # 人类可读的诊断细节
    duration_ms: float = 0                 # 探测耗时

    @property
    def usable(self) -> bool:
        """旧语义别名：恒等于 healthy（确保 cli/server/subagent/builtin 零破坏）。"""
        return self.healthy

    @usable.setter
    def usable(self, value: bool) -> None:
        self.healthy = bool(value)

    def to_dict(self) -> dict:
        return {
            "found": self.found,
            "installed": self.installed,
            "healthy": self.healthy,
            "usable": self.healthy,
            "version": self.version,
            "path": self.path,
            "problem": self.problem,
            "detail": self.detail,
            "duration_ms": round(self.duration_ms, 1),
        }


# ─────────────────────────────────────────
# PATH 回退搜索阶梯
# ─────────────────────────────────────────

def _static_extra_paths() -> list[str]:
    """构造与平台无关的额外搜索目录（不含需要子进程/npm 探测的项）。"""
    home = os.path.expanduser("~")
    dirs = [
        os.path.join(home, ".local", "bin"),
        "/usr/local/bin",
        "/opt/homebrew/bin",           # macOS Apple Silicon Homebrew
        "/usr/bin",
        os.path.join(home, ".bun", "bin"),
        os.path.join(home, ".volta", "bin"),
        os.path.join(home, ".npm-global", "bin"),
        os.path.join(home, ".deno", "bin"),
        os.path.join(home, "bin"),
    ]
    if os.name == "nt":
        local = os.environ.get("LOCALAPPDATA", "")
        appdata = os.environ.get("APPDATA", "")
        if appdata:
            dirs.append(os.path.join(appdata, "npm"))
        if local:
            dirs.append(os.path.join(local, "Programs"))
    return dirs


def _nvm_paths() -> list[str]:
    """nvm 安装的 node 版本目录（按版本号降序，当前版本优先）。"""
    pattern = os.path.join(os.path.expanduser("~"), ".nvm", "versions", "node", "*", "bin")
    found = glob.glob(pattern)
    if not found:
        return []

    def _ver(d: str) -> tuple:
        name = os.path.basename(os.path.dirname(d)) or os.path.basename(d)
        return _version_tuple(name.lstrip("v"))

    return sorted(found, key=_ver, reverse=True)[:3]


def _find_nvm_binary(binary: str) -> Optional[str]:
    """在 nvm 路径中查找 node/npm（不解析符号链接，避免 npm -> npm-cli.js）。"""
    for d in _nvm_paths():
        candidate = os.path.join(d, binary)
        try:
            if os.path.isfile(candidate) and os.access(candidate, os.X_OK):
                return candidate
        except OSError:
            continue
    return None


# npm 全局 bin（需要执行 npm，懒解析 + 进程内缓存）
_npm_bin_cache: dict = {}
_NPM_CACHE_TTL = 300.0


def _npm_global_bin() -> list[str]:
    """通过 `npm prefix -g` 解析 npm 全局 bin 目录（缓存 5 分钟）。"""
    now = time.time()
    cached = _npm_bin_cache.get("dirs")
    if cached is not None and now - _npm_bin_cache.get("ts", 0) < _NPM_CACHE_TTL:
        return cached

    dirs: list[str] = []
    npm = shutil.which("npm")
    if npm:
        try:
            proc = subprocess.run([npm, "prefix", "-g"], capture_output=True,
                                  text=True, timeout=10)
            if proc.returncode == 0:
                prefix = (proc.stdout or "").strip().splitlines()
                if prefix:
                    root = prefix[-1].strip()
                    if root:
                        if os.name == "nt":
                            dirs.append(root)
                        else:
                            dirs.append(os.path.join(root, "bin"))
        except (subprocess.SubprocessError, OSError):
            logger.debug("npm prefix -g 解析失败", exc_info=True)

    _npm_bin_cache["dirs"] = dirs
    _npm_bin_cache["ts"] = now
    return dirs


def _extra_search_paths(include_npm: bool = True) -> list[str]:
    """PATH 回退阶梯的候选目录（去重、保序）。

    include_npm=False 时跳过 `npm prefix -g` 子进程解析（供快速同步检测使用）。
    """
    candidates = _static_extra_paths() + _nvm_paths()
    if include_npm:
        candidates += _npm_global_bin()
    seen: set = set()
    result: list[str] = []
    for d in candidates:
        if not d:
            continue
        norm = os.path.normpath(os.path.expanduser(d))
        if norm in seen or not os.path.isdir(norm):
            continue
        seen.add(norm)
        result.append(norm)
    return result


# 登录 shell PATH 懒解析缓存（GUI/daemon 启动时 PATH 不全的兜底）
_login_shell_path_cache: dict = {}
_CACHE_TTL = 60  # seconds


def _login_shell_candidates() -> list[str]:
    """可用的登录 shell（用户 $SHELL 优先）。"""
    shell = os.environ.get("SHELL", "").strip()
    candidates = [shell] if shell else []
    for fallback in ("/bin/bash", "/bin/zsh", "/bin/sh"):
        if fallback not in candidates:
            candidates.append(fallback)
    return [c for c in candidates if c and os.path.exists(c)]


def _resolve_login_shell_path() -> str:
    """同步解析登录 shell 的 PATH（带 TTL 缓存）。"""
    cached = _login_shell_path_cache.get("path")
    if cached is not None and time.time() - _login_shell_path_cache.get("ts", 0) < _CACHE_TTL:
        return cached

    path = ""
    if os.name != "nt":
        for shell in _login_shell_candidates():
            try:
                proc = subprocess.run(
                    [shell, "-l", "-c", 'printf %s "$PATH"'],
                    capture_output=True, text=True, timeout=6,
                )
            except (subprocess.SubprocessError, OSError):
                logger.debug("登录 shell PATH 解析失败: %s", shell, exc_info=True)
                continue
            out = (proc.stdout or "").strip()
            if proc.returncode == 0 and out:
                path = out
                break

    _login_shell_path_cache["path"] = path
    _login_shell_path_cache["ts"] = time.time()
    return path


async def _get_login_shell_path() -> str:
    """懒解析登录 shell 的 PATH（解决 GUI/daemon 启动时 PATH 不全的问题）。"""
    return await asyncio.to_thread(_resolve_login_shell_path)


def _login_shell_dirs() -> list[str]:
    return [d for d in (_resolve_login_shell_path() or "").split(os.pathsep) if d]


# ─────────────────────────────────────────
# 二进制解析
# ─────────────────────────────────────────

def _executable_names(binary: str) -> list[str]:
    """可执行文件名变体（Windows 需要扩展名）。"""
    names = [binary]
    if os.name == "nt":
        for ext in (".exe", ".cmd", ".bat", ".com"):
            if not binary.lower().endswith(ext):
                names.append(binary + ext)
    return names


def _env_override(binary: str, key: str) -> Optional[str]:
    """环境变量覆盖：{KEY}_BINARY / {KEY}_PATH / {BINARY}_CLI_PATH。

    显式覆盖具有权威性——即使目标不存在也直接返回，
    以便 probe 上报具体路径与 OS 错误，而不是静默回退到另一份安装。
    """
    names: list[str] = []
    if key:
        stem = key.upper().replace("-", "_")
        names += [f"{stem}_BINARY", f"{stem}_PATH", f"{stem}_CLI_PATH"]
    if binary:
        stem = os.path.basename(binary).upper().replace("-", "_").replace(".", "_")
        names += [f"{stem}_BINARY", f"{stem}_PATH", f"{stem}_CLI_PATH"]
    for name in names:
        value = str(os.environ.get(name) or "").strip()
        if value:
            logger.debug("工具二进制由环境变量覆盖: %s=%s", name, value)
            return os.path.expanduser(value)
    return None


def _qoder_bin_dirs(binary: str) -> list[str]:
    """Qoder 原生安装产物的版本化目录（~/.qoder/bin/<name>/）。

    qodercli 等原生 ELF 安装到 ~/.qoder/bin/<name>/<name>-<version>，并在
    ~/.local/bin 建软链；当 ~/.local/bin 不在 daemon PATH 且登录 shell 兜底
    失效时，直接扫描该版本化目录即可定位，无需子进程。
    """
    if not binary:
        return []
    home = os.path.expanduser("~")
    return [os.path.join(home, ".qoder", "bin", binary)]


def _versioned_artifact_dirs(binary: str) -> frozenset:
    """允许 `{base}-<version>` 版本化 glob 的目录集合（仅 Qoder 原生版本化产物目录）。

    PATH / 公共 bin 目录（/usr/bin、/usr/local/bin、~/.local/bin 等）只做精确
    同名匹配，不做版本化 glob，避免 git→git-shell、docker→docker-compose、
    python→python-config 等同前缀兄弟可执行文件被误判为工具本体。
    """
    return frozenset(
        os.path.normpath(os.path.expanduser(d)) for d in _qoder_bin_dirs(binary))


def _versioned_candidates(directory: str, base_name: str) -> list[str]:
    """目录内 `{base_name}-<version>` 版本化产物（后缀必须是纯版本号，按版本降序）。

    后缀白名单 `^\\d+(\\.\\d+)*([-+].*)?$` 过滤掉同前缀兄弟可执行文件
    （如 git-shell、docker-compose、python-config），只保留 git-2.43.0 这类
    真正的版本化产物。
    """
    try:
        matches = glob.glob(os.path.join(directory, f"{base_name}-*"))
    except OSError:
        return []
    prefix_len = len(base_name) + 1
    result: list[str] = []
    for path in matches:
        suffix = os.path.basename(path)[prefix_len:]
        if not _VERSION_SUFFIX_RE.match(suffix):
            continue
        result.append(path)
    if not result:
        return []

    def _ver(path: str) -> tuple:
        return _version_tuple(os.path.basename(path)[prefix_len:])

    return sorted(result, key=_ver, reverse=True)


def _whereis_binary(binary: str) -> Optional[str]:
    """`whereis -b` 最后兜底（仅 POSIX，返回可执行真实路径或 None）。"""
    if os.name == "nt":
        return None
    try:
        result = subprocess.run(["whereis", "-b", binary],
                                capture_output=True, text=True, timeout=2)
    except (subprocess.SubprocessError, OSError):
        return None
    if result.returncode != 0:
        return None
    parts = (result.stdout or "").strip().split()
    if len(parts) < 2:
        return None
    path = parts[1]
    if (os.path.isfile(path) and os.access(path, os.X_OK)
            and not _is_windows_store_alias(path)):
        return os.path.realpath(path)
    return None


def _search_dirs(binary: str, key: str, use_login_shell: bool = True,
                 use_npm: bool = True) -> list[str]:
    """按优先级返回回退阶梯目录（PATH → 常见安装位置 → ~/.qoder/bin/<name>
    → macOS 桌面版 → 登录 shell）。"""
    dirs = [d for d in os.environ.get("PATH", "").split(os.pathsep) if d]
    dirs += _extra_search_paths(include_npm=use_npm)
    dirs += _qoder_bin_dirs(binary)
    if binary == "codex" and sys.platform == "darwin":
        dirs += [os.path.dirname(os.path.expanduser(p))
                 for p in _CODEX_DESKTOP_BINARIES]
    if use_login_shell:
        dirs += _login_shell_dirs()
    return dirs


def _scan_dirs(base_name: str, names: Iterable[str], dirs: Iterable[str],
               versioned_dirs: Optional[frozenset] = None
               ) -> tuple[Optional[str], Optional[str], Optional[str]]:
    """在目录列表中查找可执行文件。

    所有目录都做精确同名匹配；仅 `versioned_dirs`（版本化产物目录，如
    ~/.qoder/bin/<name>）额外做 `{base_name}-<version>` 版本化 glob，避免对
    PATH/公共 bin 目录误匹配同前缀兄弟可执行文件。

    Returns:
        (可用路径, Windows alias 兜底, 无执行权限兜底)
    """
    versioned_dirs = versioned_dirs or frozenset()
    alias_candidate: Optional[str] = None
    noexec_candidate: Optional[str] = None
    for directory in dirs:
        if not directory:
            continue
        # ① 精确名匹配（所有目录）
        for name in names:
            candidate = os.path.join(directory, name)
            try:
                if not os.path.isfile(candidate):
                    continue
            except OSError:
                continue
            if _is_windows_store_alias(candidate):
                alias_candidate = alias_candidate or candidate
                continue
            if not os.access(candidate, os.X_OK):
                noexec_candidate = noexec_candidate or candidate
                continue
            return os.path.realpath(candidate), alias_candidate, noexec_candidate
        # ② 版本化产物 glob（仅版本化产物目录，如 ~/.qoder/bin/qodercli）
        norm_dir = os.path.normpath(os.path.expanduser(directory))
        if norm_dir not in versioned_dirs:
            continue
        try:
            is_dir = os.path.isdir(directory)
        except OSError:
            is_dir = False
        if is_dir:
            for candidate in _versioned_candidates(directory, base_name):
                try:
                    if not os.path.isfile(candidate):
                        continue
                except OSError:
                    continue
                if _is_windows_store_alias(candidate):
                    alias_candidate = alias_candidate or candidate
                    continue
                if not os.access(candidate, os.X_OK):
                    noexec_candidate = noexec_candidate or candidate
                    continue
                return os.path.realpath(candidate), alias_candidate, noexec_candidate
    return None, alias_candidate, noexec_candidate


def _resolve_binary(binary: str, key: str = "",
                    extra_dirs: Optional[Iterable[str]] = None,
                    use_login_shell: bool = True,
                    use_npm: bool = True,
                    use_whereis: bool = True,
                    strict_override: bool = True) -> Optional[str]:
    """PATH 回退阶梯搜索可执行文件（find_binary_simple 与探测流程共用）。

    顺序：
    1. 环境变量覆盖（strict_override=True 时权威返回，即使路径不存在；
       False 时若覆盖路径失效则继续走后续阶梯）
    2. nvm 优先（node/npm 优先使用 nvm 安装版本；纯文件系统 glob，不受 use_npm 门控）
    3. 调用方指定的 extra_dirs（如刚安装到的 npm --prefix，仅精确匹配）
    4. PATH 上的 shutil.which
    5. 回退阶梯目录（~/.local/bin、/usr/local/bin、nvm、npm global bin、
       ~/.qoder/bin/<name> 版本化产物、macOS 桌面版特例、登录 shell PATH）
    6. whereis 最后兜底（use_whereis=False 时跳过，供快速同步检测使用）

    use_login_shell / use_npm / use_whereis 供快速同步检测（find_binary_simple）
    关闭相应子进程解析；use_npm 仅门控 `npm prefix -g`，不影响 nvm 纯 glob。
    """
    if not binary:
        return None

    override = _env_override(binary, key)
    if override:
        if strict_override:
            return override
        # 非严格：覆盖路径有效才采用，否则继续走后续定位阶梯
        if os.path.isfile(override) and os.access(override, os.X_OK):
            return override

    # 2. nvm 优先：node/npm 优先使用 nvm 安装的版本（纯文件系统 glob，无子进程开销）
    if binary in ("node", "npm"):
        nvm_found = _find_nvm_binary(binary)
        if nvm_found:
            return nvm_found

    names = _executable_names(binary)
    alias_candidate: Optional[str] = None
    noexec_candidate: Optional[str] = None

    # 3. 调用方指定目录（刚安装完成的位置优先于 PATH 上的陈旧版本；仅精确匹配）
    if extra_dirs:
        found, alias, noexec = _scan_dirs(
            binary, names, [os.path.expanduser(d) for d in extra_dirs if d])
        if found:
            return found
        alias_candidate, noexec_candidate = alias, noexec

    # 4. shutil.which（PATH 快路径）
    which_path = shutil.which(binary)
    if which_path and os.path.isfile(which_path):
        if _is_windows_store_alias(which_path):
            alias_candidate = alias_candidate or which_path
        elif os.access(which_path, os.X_OK):
            return os.path.realpath(which_path)
        else:
            noexec_candidate = noexec_candidate or which_path

    # 5. 回退阶梯（含 ~/.qoder/bin/<name> 版本化产物、macOS 桌面版、登录 shell PATH）
    found, alias, noexec = _scan_dirs(
        binary, names,
        _search_dirs(binary, key, use_login_shell=use_login_shell, use_npm=use_npm),
        versioned_dirs=_versioned_artifact_dirs(binary))
    if found:
        return found

    # 6. whereis 最后兜底
    if use_whereis:
        whereis_path = _whereis_binary(binary)
        if whereis_path:
            return whereis_path

    return alias_candidate or alias or noexec_candidate or noexec


def _is_windows_store_alias(path: str) -> bool:
    """检测 Windows 商店 App Execution Alias（文件大小为 0 的假 exe）。"""
    if not path:
        return False
    normalized = str(path).replace("/", os.sep).lower()
    if _WINDOWS_STORE_ALIAS_DIR.lower() not in normalized:
        return False
    try:
        # 真实程序有内容；alias 是空的 reparse point
        return os.stat(path).st_size == 0
    except OSError:
        return True


# ─────────────────────────────────────────
# 版本解析与比较
# ─────────────────────────────────────────

def _strip_ansi(text: str) -> str:
    return _ANSI_RE.sub("", text or "")


def _normalize_version(raw: str) -> str:
    """去掉版本号尾随标点（`,`/`)`/`;` 等）。"""
    return raw.strip().rstrip(".,;:)")


def _extract_version(output: str) -> Optional[str]:
    """从 --version 输出中提取版本号（x.y[.z][-suffix] 格式）。"""
    if not output:
        return None
    text = _strip_ansi(output)
    lines = [ln.strip() for ln in text.splitlines() if ln.strip()]

    # ① 优先匹配明确的版本行（含 "version" 或以 v 开头）
    for line in lines:
        low = line.lower()
        if "version" in low or re.match(r"^v\d", low):
            match = _VERSION_RE.search(line)
            if match:
                return _normalize_version(match.group(0))
    # ② 回退：首个形如版本号的片段
    for line in lines:
        match = _VERSION_RE.search(line)
        if match:
            return _normalize_version(match.group(0))
    # ③ 最后回退：显式版本行中的单个整数（如 "claude 2"）
    for line in lines:
        if "version" in line.lower():
            match = re.search(r"\d+", line)
            if match:
                return match.group(0)
    return None


def _version_tuple(version: str) -> tuple:
    """版本号转可比较元组（非数字段按 0 处理）。"""
    core = re.split(r"[-+]", (version or "").strip().lstrip("v"), 1)[0]
    parts = []
    for seg in core.split("."):
        match = re.match(r"^\d+", seg)
        parts.append(int(match.group(0)) if match else 0)
    return tuple(parts)


def _has_prerelease(version: str) -> bool:
    return bool(re.search(r"-", (version or "").strip().lstrip("v")))


def compare_versions(left: str, right: str) -> int:
    """比较两个版本号：left > right → 1，相等 → 0，小于 → -1。

    简单的元组比较（不引入 packaging 依赖）：主版本号逐段补零对齐，
    核心版本相同时带预发布后缀（-beta/-rc）的一方视为更低。
    """
    lt, rt = _version_tuple(left), _version_tuple(right)
    width = max(len(lt), len(rt))
    lt = lt + (0,) * (width - len(lt))
    rt = rt + (0,) * (width - len(rt))
    if lt != rt:
        return 1 if lt > rt else -1
    lp, rp = _has_prerelease(left), _has_prerelease(right)
    if lp and not rp:
        return -1
    if rp and not lp:
        return 1
    return 0


def _version_args(descriptor: ToolDescriptor) -> list[str]:
    """推导版本探测参数（两条独立分支）。

    - probe_cmd（运行时侧主动声明，可信）：允许完整命令 token（含前缀
      包装），仅剥离与 binary 同名的首段；
    - check_cmd（可能来自平台下发，如 SSH/sudo 包装命令，不可信）：严格判据，
      仅当首段 basename 与 descriptor.binary 同名时才采用其参数，否则回落
      默认 --version（避免把 `sudo -u ... bash -lc ...` 当作探测参数执行）。
    """
    def _split(cmd: str) -> list[str]:
        try:
            return shlex.split(cmd)
        except ValueError:
            return cmd.split()

    def _same_as_binary(token: str) -> bool:
        if not descriptor.binary or not token:
            return False
        head = os.path.basename(token).split(".")[0]
        return head == os.path.basename(descriptor.binary).split(".")[0]

    # ① probe_cmd：可信分支，允许完整命令 token
    probe_cmd = (getattr(descriptor, "probe_cmd", None) or "").strip()
    if probe_cmd:
        parts = _split(probe_cmd)
        if parts:
            if _same_as_binary(parts[0]):
                parts = parts[1:]
            if parts:
                return parts

    # ② check_cmd：严格分支，首段必须与 binary 同名才采用其参数
    cmd = (descriptor.check_cmd or "").strip()
    if cmd:
        parts = _split(cmd)
        if len(parts) >= 2 and _same_as_binary(parts[0]):
            return parts[1:]

    return ["--version"]


# ─────────────────────────────────────────
# 探测主流程
# ─────────────────────────────────────────

def _normalize_extra_dirs(extra_dirs: Optional[Iterable[str]]) -> tuple:
    """归一化 extra_dirs（expanduser + normpath + 去重 + 排序）作为缓存键的一部分。"""
    if not extra_dirs:
        return ()
    seen: set = set()
    for d in extra_dirs:
        if not d:
            continue
        seen.add(os.path.normpath(os.path.expanduser(str(d))))
    return tuple(sorted(seen))


def invalidate_probe_cache(key: Optional[str] = None) -> None:
    """失效探测缓存（安装/卸载后调用；key=None 清空全部）。

    缓存键为 (tool_key, extra_dirs)；按 tool_key 失效时移除该工具的所有条目。
    """
    if key is None:
        _probe_cache.clear()
        return
    for cache_key in [k for k in _probe_cache if k[0] == key]:
        _probe_cache.pop(cache_key, None)


def reset_path_caches() -> None:
    """清空 npm 全局 bin 与登录 shell PATH 缓存。

    安装/卸载后 PATH 布局可能变化（新装 Node、切换 prefix），
    需丢弃缓存后重新解析。
    """
    _npm_bin_cache.clear()
    _login_shell_path_cache.clear()


async def probe_tool(descriptor: ToolDescriptor,
                     timeout: float = PROBE_TIMEOUT_LIST,
                     use_cache: bool = False,
                     extra_dirs: Optional[Iterable[str]] = None,
                     retries: Optional[int] = None,
                     first_run_grace: bool = False,
                     total_budget: Optional[float] = None) -> ProbeResult:
    """完整探测：定位二进制（installed）→ 规避假可执行文件 → 健康检查（healthy）。

    installed 与 healthy 分离：定位成功即 installed=True；--version 失败只降级
    healthy=False（problem=version_unverified），不回退 installed。
    差异化超时由调用方传入（列表场景 PROBE_TIMEOUT_LIST、安装场景
    PROBE_TIMEOUT_INSTALL）；retries / first_run_grace / total_budget 仅作用于
    --version 健康检查。retries=None 表示未指定，回退 descriptor.probe_retries；
    显式传值（含 0）优先，不被 descriptor 覆盖。
    缓存键纳入归一化后的 extra_dirs，使带 extra_dirs 的探测也能命中缓存。
    """
    started = time.monotonic()
    cache_key = (descriptor.key, _normalize_extra_dirs(extra_dirs))

    if use_cache:
        hit = _probe_cache.get(cache_key)
        if hit and time.time() - hit[0] < PROBE_CACHE_TTL:
            return hit[1]

    result = await _probe_tool_uncached(descriptor, timeout, extra_dirs,
                                        retries=retries,
                                        first_run_grace=first_run_grace,
                                        total_budget=total_budget)
    result.duration_ms = (time.monotonic() - started) * 1000
    _probe_cache[cache_key] = (time.time(), result)
    return result


async def _probe_tool_uncached(descriptor: ToolDescriptor, timeout: float,
                               extra_dirs: Optional[Iterable[str]] = None,
                               retries: Optional[int] = None,
                               first_run_grace: bool = False,
                               total_budget: Optional[float] = None) -> ProbeResult:
    """未缓存探测：第一段定位（installed）+ 第二段健康检查（healthy）。"""
    if not descriptor.binary:
        return ProbeResult(found=False, problem=PROBLEM_NOT_FOUND,
                           detail="工具未配置可执行命令（binary）")

    # ══ 第一段：定位（安装判据）══
    path = await asyncio.to_thread(_resolve_binary, descriptor.binary,
                                   descriptor.key, extra_dirs)
    if not path:
        logger.debug("未找到工具二进制: %s (%s)", descriptor.key, descriptor.binary)
        return ProbeResult(found=False, problem=PROBLEM_NOT_FOUND,
                           detail=f"未在 PATH 及回退目录中找到 `{descriptor.binary}`")

    # Windows 商店 alias 检测（放宽点之前；条件跳过：仅 Windows 命中）
    if _is_windows_store_alias(path):
        return ProbeResult(found=True, installed=False, healthy=False, path=path,
                           problem=PROBLEM_WINDOWS_STORE_ALIAS,
                           detail=_store_alias_hint(descriptor, path))

    # 环境变量覆盖指向不存在的路径（权威覆盖，不做回退）
    if not os.path.exists(path):
        return ProbeResult(found=False, installed=False, healthy=False, path=path,
                           problem=PROBLEM_NOT_FOUND,
                           detail=f"指定的可执行文件不存在: {path}")

    # 必须是普通可执行文件（排除目录，如 NODE_PATH=/usr/lib 被误判 installed）
    if not os.path.isfile(path):
        return ProbeResult(found=True, installed=False, healthy=False, path=path,
                           problem=PROBLEM_NOT_FOUND,
                           detail=f"`{path}` 不是可执行文件（可能是一个目录）")

    # 执行权限检测
    if not os.access(path, os.X_OK):
        return ProbeResult(found=True, installed=False, healthy=False, path=path,
                           problem=PROBLEM_PERMISSION_DENIED,
                           detail=f"`{path}` 存在但无执行权限")

    # 定位通过 → installed=True；此后任何 --version 失败都不得回退 installed。
    # ══ 第二段：健康检查（只影响 healthy）══
    return await _health_check(descriptor, path, timeout,
                               retries=retries, first_run_grace=first_run_grace,
                               total_budget=total_budget)


def _effective_timeout(descriptor: ToolDescriptor,
                       timeout: Optional[float]) -> float:
    """健康检查超时：descriptor.probe_timeout 覆盖 > 调用方 timeout > 列表默认。

    timeout=None 视为未指定，回落 PROBE_TIMEOUT_LIST。
    """
    override = getattr(descriptor, "probe_timeout", None)
    try:
        if override is not None and float(override) > 0:
            return float(override)
    except (TypeError, ValueError):
        pass
    try:
        if timeout is not None and float(timeout) > 0:
            return float(timeout)
    except (TypeError, ValueError):
        pass
    return PROBE_TIMEOUT_LIST


def _effective_retries(descriptor: ToolDescriptor,
                       retries: Optional[int]) -> int:
    """健康检查重试次数（None 哨兵语义）。

    - retries 显式传值（含 0）：直接采用，不被 descriptor 覆盖（列表场景
      probe_tools 传 retries=0 保持快速失败）；
    - retries=None（未指定）：回退 descriptor.probe_retries，缺省 0。
    """
    if retries is not None:
        try:
            return max(0, int(retries))
        except (TypeError, ValueError):
            return 0
    fallback = getattr(descriptor, "probe_retries", None)
    try:
        if fallback is not None and int(fallback) > 0:
            return int(fallback)
    except (TypeError, ValueError):
        pass
    return 0


def _build_version_command(path: str, args: list[str]) -> tuple[str, list[str]]:
    """构造 --version 执行命令。

    npm 在 nvm 中是 .js 文件（shebang #!/usr/bin/env node），需要用 nvm 安装的
    node 执行，避免 env node 解析到系统旧版本。
    """
    exec_cmd = path
    exec_args = list(args)
    real_path = os.path.realpath(path)
    if real_path.endswith('.js'):
        # 从 .js 文件路径向上查找 nvm 的 bin/node
        # 例: .../v20.20.2/lib/node_modules/npm/bin/npm-cli.js
        #   → .../v20.20.2/bin/node
        nvm_node = None
        d = os.path.dirname(real_path)
        for _ in range(6):
            candidate = os.path.join(d, 'bin', 'node')
            if os.path.isfile(candidate) and os.access(candidate, os.X_OK):
                nvm_node = candidate
                break
            d = os.path.dirname(d)
        if nvm_node:
            exec_cmd = nvm_node
            exec_args = [real_path] + list(args)
    return exec_cmd, exec_args


def _version_unverified_result(descriptor: ToolDescriptor, path: str,
                               args: Iterable[str], reason: str,
                               version: Optional[str] = None) -> ProbeResult:
    """installed=True 但 --version 未通过时的降级结果（warning，不回退 installed）。"""
    cmd = f"{path} {' '.join(args)}".strip()
    hint = (f"已安装但 `{cmd}` 未通过（{reason}）；"
            f"可能需要先登录或配置访问令牌（token）后重试。")
    keys = list(getattr(descriptor, "env_config_keys", None) or [])
    if keys:
        hint += f" 相关环境变量：{', '.join(keys)}。"
    return ProbeResult(found=True, installed=True, healthy=False, path=path,
                       version=version, problem=PROBLEM_VERSION_UNVERIFIED,
                       detail=hint)


async def _health_check(descriptor: ToolDescriptor, path: str,
                        timeout: Optional[float],
                        retries: Optional[int] = None,
                        first_run_grace: bool = False,
                        total_budget: Optional[float] = None) -> ProbeResult:
    """第二段：健康检查（--version 执行 + 退出码 + 版本解析 + min_version 比对）。

    仅在定位段已确认 installed=True 后调用；本段任何失败都只影响 healthy，
    绝不回退 installed。rc≠0 / 超时 / 无版本号统一降级为 version_unverified
    （warning），而非笼统的 execution_error 阻断。min_version 比对仅当声明
    min_version 且成功解析出 version 时执行。

    重试策略：first_run_grace 仅在**第一次重试**（attempt==1）延长超时（冷启动
    宽限）；rc==0 但输出为空/无法解析版本号时**不重试**（重试无意义）；
    total_budget（默认 PROBE_HEALTH_TOTAL_BUDGET）为**权威上界**——每次 attempt
    开始前把本次超时裁剪到剩余预算 `min(cur_timeout, max(FLOOR, budget-elapsed))`，
    剩余预算不足 FLOOR 则 break，使总耗时被 budget 收敛，与 base/retries/grace 无关。
    """
    args = _version_args(descriptor)
    exec_cmd, exec_args = _build_version_command(path, args)
    base_timeout = _effective_timeout(descriptor, timeout)
    attempts = max(1, _effective_retries(descriptor, retries) + 1)
    try:
        budget = (float(total_budget) if total_budget and float(total_budget) > 0
                  else PROBE_HEALTH_TOTAL_BUDGET)
    except (TypeError, ValueError):
        budget = PROBE_HEALTH_TOTAL_BUDGET

    health_started = time.monotonic()
    timeout_result: Optional[ProbeResult] = None
    for attempt in range(attempts):
        # first_run_grace：仅第一次重试延长超时（冷启动/首次下载宽限）
        cur_timeout = base_timeout
        if attempt == 1 and first_run_grace:
            cur_timeout = base_timeout * 2

        # 总预算为权威上界：把本次超时裁剪到剩余预算内，收敛总耗时。
        # 先判断剩余预算是否已不足下限（不足则不再发起该次 attempt），
        # 再裁剪 cur_timeout = min(cur_timeout, max(FLOOR, budget - elapsed))。
        elapsed = time.monotonic() - health_started
        remaining = budget - elapsed
        if remaining < PROBE_HEALTH_MIN_TIMEOUT_FLOOR:
            logger.debug("健康检查剩余预算(%.2fs)不足下限(%.2fs)，停止: %s",
                         remaining, PROBE_HEALTH_MIN_TIMEOUT_FLOOR, descriptor.key)
            break
        cur_timeout = min(cur_timeout, max(PROBE_HEALTH_MIN_TIMEOUT_FLOOR, remaining))

        try:
            proc = await asyncio.create_subprocess_exec(
                exec_cmd, *exec_args,
                stdin=asyncio.subprocess.DEVNULL,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
        except PermissionError as exc:
            return ProbeResult(found=True, installed=True, healthy=False, path=path,
                               problem=PROBLEM_PERMISSION_DENIED,
                               detail=f"`{path} {' '.join(args)}` 无法启动: {exc}")
        except OSError as exc:
            return ProbeResult(found=True, installed=True, healthy=False, path=path,
                               problem=PROBLEM_EXECUTION_ERROR,
                               detail=f"`{path} {' '.join(args)}` 无法启动: {exc}")

        try:
            stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=cur_timeout)
        except asyncio.TimeoutError:
            try:
                proc.kill()
            except ProcessLookupError:
                pass
            except Exception:
                logger.debug("终止探测子进程失败", exc_info=True)
            timeout_result = _version_unverified_result(
                descriptor, path, args, f"在 {cur_timeout:.0f}s 内无响应")
            # 超时可能是冷启动，重试（first_run_grace 会延长超时）
            continue

        output = ((stdout or b"").decode("utf-8", errors="replace")
                  + (stderr or b"").decode("utf-8", errors="replace"))[:PROBE_OUTPUT_LIMIT]

        # 退出码非 0 → 降级为 version_unverified（可重试）
        if proc.returncode != 0:
            tail = [ln for ln in _strip_ansi(output).strip().splitlines() if ln.strip()]
            reason = f"exit {proc.returncode}"
            if tail:
                reason += f": {tail[-1][:160]}"
            if attempt + 1 < attempts:
                continue
            return _version_unverified_result(descriptor, path, args, reason)

        # 版本号解析（rc==0 但输出为空/无法解析：重试无意义，直接降级不重试）
        version = _extract_version(output)
        if not version:
            return _version_unverified_result(
                descriptor, path, args, "未输出可识别的版本号")

        # 最低版本比对（仅当声明 min_version 且成功解析出 version 时）
        if descriptor.min_version and compare_versions(version, descriptor.min_version) < 0:
            return ProbeResult(found=True, installed=True, healthy=False,
                               version=version, path=path,
                               problem=PROBLEM_VERSION_TOO_LOW,
                               detail=f"当前版本 {version} 低于最低要求 {descriptor.min_version}")

        return ProbeResult(found=True, installed=True, healthy=True,
                           version=version, path=path)

    # 重试耗尽仍超时
    return timeout_result or _version_unverified_result(
        descriptor, path, args, "多次重试仍无响应")


def _store_alias_hint(descriptor: ToolDescriptor, path: str) -> str:
    """Windows Store App Execution Alias 的诊断指引。"""
    install = (f"请安装 CLI 本体（npm install -g {descriptor.package}）"
               if descriptor.package else "请安装真实的 CLI 二进制")
    return (
        f"`{path}` 指向 Microsoft Store App Execution Alias（桌面应用的 0 字节占位符，"
        f"不是完整 CLI）。{install}，或在「设置 > 应用 > 高级应用设置 > 应用执行别名」中"
        f"关闭该别名，使 PATH 能找到真实二进制。"
    )


async def probe_tools(descriptors: Iterable[ToolDescriptor],
                      timeout: float = PROBE_TIMEOUT_LIST,
                      use_cache: bool = True,
                      max_concurrency: int = 4,
                      extra_dirs_map: Optional[dict] = None,
                      retries: int = 0,
                      first_run_grace: bool = False,
                      total_budget: Optional[float] = None) -> dict[str, ProbeResult]:
    """批量并发探测，返回 {key: ProbeResult}。

    extra_dirs_map: 可选的 {key: [目录]}，为特定工具追加搜索目录（如自定义
    npm --prefix 安装产物所在的 bin 目录，不在 PATH 上时仍可探测到）。
    retries / first_run_grace / total_budget 透传给每个工具的健康检查；列表场景
    retries 默认显式 0（快速失败，不被 descriptor.probe_retries 放大）。
    """
    items = list(descriptors)
    if not items:
        return {}
    extra_dirs_map = extra_dirs_map or {}
    semaphore = asyncio.Semaphore(max(1, max_concurrency))

    async def _bounded(descriptor: ToolDescriptor) -> tuple[str, ProbeResult]:
        async with semaphore:
            try:
                return descriptor.key, await probe_tool(
                    descriptor, timeout, use_cache,
                    extra_dirs=extra_dirs_map.get(descriptor.key),
                    retries=retries, first_run_grace=first_run_grace,
                    total_budget=total_budget)
            except Exception as exc:  # 单个工具异常不影响整体列表
                logger.warning("探测工具 %s 异常: %s", descriptor.key, exc)
                return descriptor.key, ProbeResult(
                    found=False, problem=PROBLEM_EXECUTION_ERROR, detail=str(exc))

    pairs = await asyncio.gather(*(_bounded(d) for d in items))
    return dict(pairs)
