# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).
"""tool_models — 工具安装记录持久化（SQLite）。

项目未引入 aiosqlite（见 pyproject.toml），因此沿用 core/db.py 的做法：
标准库 sqlite3 + threading.Lock，异步接口通过 asyncio.to_thread 包装，
不阻塞事件循环，也不新增外部依赖。

表结构：
    tool_installations(key PK, status, version, exec_log, env_vars JSON,
                       installed_at, source, enabled, updated_at)
"""
import asyncio
import json
import logging
import sqlite3
import threading
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

logger = logging.getLogger("agent.tool_models")

# 安装状态取值
STATUS_NOT_INSTALLED = "not_installed"
STATUS_INSTALLING = "installing"
STATUS_INSTALLED = "installed"
STATUS_FAILED = "failed"
STATUS_UNINSTALLED = "uninstalled"

# 记录来源
SOURCE_LOCAL = "local"
SOURCE_PLATFORM = "platform"
SOURCE_DOCKER = "docker-preinstall"

_TABLE_DDL = """
CREATE TABLE IF NOT EXISTS tool_installations (
    key          TEXT PRIMARY KEY,
    status       TEXT DEFAULT 'not_installed',
    version      TEXT,
    exec_log     TEXT,
    env_vars     TEXT DEFAULT '{}',
    installed_at TEXT,
    source       TEXT DEFAULT 'local',
    enabled      INTEGER DEFAULT 1,
    updated_at   TEXT
)
"""

_COLUMNS = ("key", "status", "version", "exec_log", "env_vars",
            "installed_at", "source", "enabled", "updated_at")


def _now() -> str:
    return datetime.now().isoformat(timespec="seconds")


@dataclass
class ToolInstallation:
    """单个工具的安装记录。"""

    key: str
    status: str = STATUS_NOT_INSTALLED   # installing|installed|failed|uninstalled|not_installed
    version: Optional[str] = None
    exec_log: Optional[str] = None
    env_vars: dict = field(default_factory=dict)
    installed_at: Optional[str] = None
    source: str = SOURCE_LOCAL           # local|platform|docker-preinstall
    enabled: bool = True
    updated_at: Optional[str] = None

    def to_dict(self) -> dict:
        return {
            "key": self.key,
            "status": self.status,
            "version": self.version,
            "exec_log": self.exec_log,
            "env_vars": dict(self.env_vars),
            "installed_at": self.installed_at,
            "source": self.source,
            "enabled": self.enabled,
            "updated_at": self.updated_at,
        }

    @classmethod
    def from_row(cls, row: sqlite3.Row) -> "ToolInstallation":
        try:
            env_vars = json.loads(row["env_vars"] or "{}")
            if not isinstance(env_vars, dict):
                env_vars = {}
        except (ValueError, TypeError):
            env_vars = {}
        data = dict(row)
        return cls(
            key=data.get("key", ""),
            status=data.get("status") or STATUS_NOT_INSTALLED,
            version=data.get("version"),
            exec_log=data.get("exec_log"),
            env_vars=env_vars,
            installed_at=data.get("installed_at"),
            source=data.get("source") or SOURCE_LOCAL,
            enabled=bool(data.get("enabled", 1)),
            updated_at=data.get("updated_at"),
        )


class ToolDatabase:
    """工具安装记录持久化（SQLite）。"""

    def __init__(self, db_path: str):
        self._db_path = Path(db_path)
        self._conn: Optional[sqlite3.Connection] = None
        self._lock = threading.Lock()

    @property
    def db_path(self) -> str:
        return str(self._db_path)

    # ─────────────────────────────────────────
    # 连接管理
    # ─────────────────────────────────────────

    def _get_conn_sync(self) -> sqlite3.Connection:
        """延迟创建连接（线程安全）。"""
        if self._conn is None:
            self._db_path.parent.mkdir(parents=True, exist_ok=True)
            self._conn = sqlite3.connect(str(self._db_path), timeout=10,
                                         check_same_thread=False)
            self._conn.row_factory = sqlite3.Row
            self._conn.execute("PRAGMA journal_mode=WAL")
        return self._conn

    def _init_sync(self) -> None:
        with self._lock:
            conn = self._get_conn_sync()
            conn.execute(_TABLE_DDL)
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_tool_status ON tool_installations(status)")
            conn.commit()

    async def initialize(self) -> None:
        """创建表（如不存在）。"""
        await asyncio.to_thread(self._init_sync)
        logger.info("工具安装记录库已就绪: %s", self._db_path)

    async def close(self) -> None:
        """关闭连接。"""
        def _close() -> None:
            with self._lock:
                if self._conn is not None:
                    try:
                        self._conn.close()
                    except sqlite3.Error:
                        logger.debug("关闭工具库连接失败", exc_info=True)
                    finally:
                        self._conn = None

        await asyncio.to_thread(_close)

    # ─────────────────────────────────────────
    # 查询
    # ─────────────────────────────────────────

    def _get_sync(self, key: str) -> Optional[ToolInstallation]:
        with self._lock:
            cur = self._get_conn_sync().execute(
                "SELECT %s FROM tool_installations WHERE key = ?" % ", ".join(_COLUMNS),
                (key,))
            row = cur.fetchone()
        return ToolInstallation.from_row(row) if row else None

    async def get(self, key: str) -> Optional[ToolInstallation]:
        """读取单条安装记录。"""
        return await asyncio.to_thread(self._get_sync, key)

    def _list_all_sync(self) -> list[ToolInstallation]:
        with self._lock:
            cur = self._get_conn_sync().execute(
                "SELECT %s FROM tool_installations ORDER BY key" % ", ".join(_COLUMNS))
            rows = cur.fetchall()
        return [ToolInstallation.from_row(r) for r in rows]

    async def list_all(self) -> list[ToolInstallation]:
        """读取全部安装记录。"""
        return await asyncio.to_thread(self._list_all_sync)

    async def get_map(self) -> dict[str, ToolInstallation]:
        """读取为 {key: ToolInstallation}（列表接口批量合并用）。"""
        return {item.key: item for item in await self.list_all()}

    # ─────────────────────────────────────────
    # 写入
    # ─────────────────────────────────────────

    def _upsert_sync(self, installation: ToolInstallation) -> None:
        now = _now()
        installed_at = installation.installed_at
        if installed_at is None and installation.status == STATUS_INSTALLED:
            installed_at = now
        values = (
            installation.key,
            installation.status or STATUS_NOT_INSTALLED,
            installation.version,
            installation.exec_log,
            json.dumps(installation.env_vars or {}, ensure_ascii=False),
            installed_at,
            installation.source or SOURCE_LOCAL,
            1 if installation.enabled else 0,
            now,
        )
        sql = (
            "INSERT INTO tool_installations "
            "(key, status, version, exec_log, env_vars, installed_at, source, enabled, updated_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) "
            "ON CONFLICT(key) DO UPDATE SET "
            "status=excluded.status, version=excluded.version, exec_log=excluded.exec_log, "
            "env_vars=excluded.env_vars, "
            "installed_at=COALESCE(excluded.installed_at, tool_installations.installed_at), "
            "source=excluded.source, enabled=excluded.enabled, updated_at=excluded.updated_at"
        )
        with self._lock:
            conn = self._get_conn_sync()
            conn.execute(sql, values)
            conn.commit()

    async def upsert(self, installation: ToolInstallation) -> None:
        """插入或整体更新一条记录。"""
        await asyncio.to_thread(self._upsert_sync, installation)

    def _update_status_sync(self, key: str, status: str,
                            version: Optional[str], exec_log: Optional[str],
                            source: Optional[str]) -> bool:
        now = _now()
        sets = ["status = ?", "updated_at = ?"]
        params: list = [status, now]
        if version is not None:
            sets.append("version = ?")
            params.append(version)
        if exec_log is not None:
            sets.append("exec_log = ?")
            # exec_log 可能很长，截断保留尾部（诊断信息集中在末尾）
            params.append(exec_log[-20000:] if len(exec_log) > 20000 else exec_log)
        if source is not None:
            sets.append("source = ?")
            params.append(source)
        if status == STATUS_INSTALLED:
            sets.append("installed_at = COALESCE(installed_at, ?)")
            params.append(now)
        params.append(key)
        # 记录不存在时先补一行，再走 UPDATE 分支（避免状态更新丢失）
        with self._lock:
            conn = self._get_conn_sync()
            conn.execute(
                "INSERT INTO tool_installations (key, status, version, exec_log, source, "
                "installed_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?) "
                "ON CONFLICT(key) DO NOTHING",
                (key, status, version, exec_log, source or SOURCE_LOCAL,
                 now if status == STATUS_INSTALLED else None, now))
            cur = conn.execute(
                "UPDATE tool_installations SET %s WHERE key = ?" % ", ".join(sets),
                params)
            conn.commit()
            return cur.rowcount > 0

    async def update_status(self, key: str, status: str,
                            version: Optional[str] = None,
                            exec_log: Optional[str] = None,
                            source: Optional[str] = None) -> bool:
        """更新安装状态（可选同步写入版本、执行日志与来源）。"""
        return await asyncio.to_thread(
            self._update_status_sync, key, status, version, exec_log, source)

    def _update_env_vars_sync(self, key: str, env_vars: dict, merge: bool) -> bool:
        payload = dict(env_vars or {})
        with self._lock:
            conn = self._get_conn_sync()
            if merge:
                cur = conn.execute(
                    "SELECT env_vars FROM tool_installations WHERE key = ?", (key,))
                row = cur.fetchone()
                if row is None:
                    conn.execute(
                        "INSERT INTO tool_installations (key, env_vars, updated_at) "
                        "VALUES (?, ?, ?)",
                        (key, json.dumps(payload, ensure_ascii=False), _now()))
                    conn.commit()
                    return True
                try:
                    existing = json.loads(row["env_vars"] or "{}")
                    if not isinstance(existing, dict):
                        existing = {}
                except (ValueError, TypeError):
                    existing = {}
                existing.update(payload)
                payload = existing
            cur = conn.execute(
                "UPDATE tool_installations SET env_vars = ?, updated_at = ? WHERE key = ?",
                (json.dumps(payload, ensure_ascii=False), _now(), key))
            if cur.rowcount == 0:
                conn.execute(
                    "INSERT INTO tool_installations (key, env_vars, updated_at) "
                    "VALUES (?, ?, ?)",
                    (key, json.dumps(payload, ensure_ascii=False), _now()))
            conn.commit()
            return True

    async def update_env_vars(self, key: str, env_vars: dict, merge: bool = True) -> bool:
        """保存环境变量配置（默认增量合并，空值表示删除该键）。"""
        cleaned = {k: v for k, v in (env_vars or {}).items()}
        if merge:
            cleaned = {k: v for k, v in cleaned.items() if v is not None and v != ""}
        return await asyncio.to_thread(self._update_env_vars_sync, key, cleaned, merge)

    def _update_enabled_sync(self, key: str, enabled: bool) -> bool:
        with self._lock:
            conn = self._get_conn_sync()
            cur = conn.execute(
                "UPDATE tool_installations SET enabled = ?, updated_at = ? WHERE key = ?",
                (1 if enabled else 0, _now(), key))
            if cur.rowcount == 0:
                conn.execute(
                    "INSERT INTO tool_installations (key, enabled, updated_at) VALUES (?, ?, ?)",
                    (key, 1 if enabled else 0, _now()))
            conn.commit()
            return True

    async def update_enabled(self, key: str, enabled: bool) -> bool:
        """启用/禁用工具。"""
        return await asyncio.to_thread(self._update_enabled_sync, key, enabled)

    def _delete_sync(self, key: str) -> bool:
        with self._lock:
            conn = self._get_conn_sync()
            cur = conn.execute("DELETE FROM tool_installations WHERE key = ?", (key,))
            conn.commit()
            return cur.rowcount > 0

    async def delete(self, key: str) -> bool:
        """删除一条安装记录。"""
        return await asyncio.to_thread(self._delete_sync, key)
