# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).
"""ToolRegistry — CLI Agent 工具注册表。

内置 7 个可管理的工具描述符（codex / claude-code / qoder-cli / gemini-cli /
opencode / nodejs / npm），并支持运行时动态注册（平台下发、插件追加）。
其中 nodejs 和 npm 为 dev 类工具，出现在「其他工具」分组，作为 npm 系工具的前置依赖。

注意：本模块的 ToolRegistry 管理「工具安装元数据」，
与 agent_runtime.tools.mcp_client.ToolRegistry（MCP 工具调用分发）职责不同。
"""
import logging
from typing import Optional

from .tool_descriptor import ToolDescriptor

logger = logging.getLogger("agent.tool_registry")


# ─────────────────────────────────────────
# 内置工具描述符
# ─────────────────────────────────────────

BUILTIN_TOOLS: list[ToolDescriptor] = [
    ToolDescriptor(
        key="codex",
        name="Codex CLI",
        description="OpenAI Codex 命令行编码 Agent，通过 `codex exec` 非交互模式委派子任务",
        category="ai-agent",
        icon="Bot",
        binary="codex",
        package="@openai/codex",
        install_cmds=["npm install -g @openai/codex"],
        uninstall_cmds=["npm uninstall -g @openai/codex"],
        check_cmd="codex --version",
        env_config_keys=["OPENAI_API_KEY"],
        provider_name="codex",
        sort_order=1,
    ),
    ToolDescriptor(
        key="claude-code",
        name="Claude Code",
        description="Anthropic Claude Code CLI，终端内的自主编码 Agent",
        category="ai-agent",
        icon="MessageSquare",
        binary="claude",
        package="@anthropic-ai/claude-code",
        install_cmds=["npm install -g @anthropic-ai/claude-code"],
        uninstall_cmds=["npm uninstall -g @anthropic-ai/claude-code"],
        check_cmd="claude --version",
        env_config_keys=["ANTHROPIC_API_KEY"],
        provider_name="claude-code",
        sort_order=2,
    ),
    ToolDescriptor(
        key="qoder-cli",
        name="Qoder CLI",
        description="Qoder 命令行 Agent（qodercli -p 非交互模式）",
        category="ai-agent",
        icon="Terminal",
        binary="qodercli",
        package="@qoder-ai/qodercli",
        install_cmds=["npm install -g @qoder-ai/qodercli"],
        uninstall_cmds=["npm uninstall -g @qoder-ai/qodercli"],
        check_cmd="qodercli --version",
        env_config_keys=["QODER_PERSONAL_ACCESS_TOKEN"],
        provider_name="qoder",
        sort_order=3,
    ),
    ToolDescriptor(
        key="gemini-cli",
        name="Gemini CLI",
        description="Google Gemini 命令行 Agent，开源终端 AI 助手",
        category="ai-agent",
        icon="Sparkles",
        binary="gemini",
        package="@google/gemini-cli",
        install_cmds=["npm install -g @google/gemini-cli"],
        uninstall_cmds=["npm uninstall -g @google/gemini-cli"],
        check_cmd="gemini --version",
        env_config_keys=["GOOGLE_API_KEY"],
        provider_name=None,
        sort_order=4,
    ),
    ToolDescriptor(
        key="opencode",
        name="OpenCode",
        description="开源终端编码 Agent（opencode-ai），支持多模型 Provider",
        category="ai-agent",
        icon="Code",
        binary="opencode",
        package="opencode-ai",
        install_cmds=["npm install -g opencode-ai"],
        uninstall_cmds=["npm uninstall -g opencode-ai"],
        check_cmd="opencode --version",
        provider_name=None,
        sort_order=5,
    ),
    # ── 开发工具（dev）── 出现在「其他工具」分组 ──
    ToolDescriptor(
        key="nodejs",
        name="Node.js",
        description="JavaScript 运行时，多个 AI Agent CLI 工具的依赖基础",
        category="dev",
        icon="Terminal",
        binary="node",
        package=None,
        install_cmds=[
            "bash -c 'source ~/.nvm/nvm.sh 2>/dev/null || { curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash && source ~/.nvm/nvm.sh; } && nvm install {version}'",
        ],
        uninstall_cmds=[
            "bash -c 'source ~/.nvm/nvm.sh 2>/dev/null && nvm uninstall {version}'",
        ],
        check_cmd="node --version",
        min_version="18.0.0",
        install_hint="缺少 Node.js，请先安装 Node.js 20+: https://nodejs.org/ （或使用 nvm: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash）",
        sort_order=10,
    ),
    ToolDescriptor(
        key="npm",
        name="npm",
        description="Node.js 包管理器，随 Node.js 一起安装（通过 nvm）",
        category="dev",
        icon="Terminal",
        binary="npm",
        package=None,
        install_cmds=[
            "bash -c 'source ~/.nvm/nvm.sh 2>/dev/null || { curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash && source ~/.nvm/nvm.sh; } && nvm install {version}'",
        ],
        uninstall_cmds=[
            "bash -c 'source ~/.nvm/nvm.sh 2>/dev/null && nvm uninstall {version}'",
        ],
        check_cmd="npm --version",
        install_hint="缺少 npm，请先安装 Node.js 20+（npm 随 Node.js 一起安装）: https://nodejs.org/",
        sort_order=11,
    ),
]


class ToolRegistry:
    """工具注册表 — 管理 ToolDescriptor 集合，支持动态追加/注销。"""

    def __init__(self, load_builtin: bool = True):
        self._tools: dict[str, ToolDescriptor] = {}
        if load_builtin:
            for t in BUILTIN_TOOLS:
                self._tools[t.key] = t

    # ── 增删查 ──

    def register(self, descriptor: ToolDescriptor) -> None:
        """注册（或覆盖）一个工具描述符。"""
        if not descriptor.key:
            raise ValueError("ToolDescriptor.key 不能为空")
        existed = descriptor.key in self._tools
        self._tools[descriptor.key] = descriptor
        logger.info("工具描述符已%s: %s", "更新" if existed else "注册", descriptor.key)

    def unregister(self, key: str) -> bool:
        """注销一个工具描述符，返回是否确实移除了。"""
        removed = self._tools.pop(key, None) is not None
        if removed:
            logger.info("工具描述符已注销: %s", key)
        return removed

    def get(self, key: str) -> Optional[ToolDescriptor]:
        """按 key 获取描述符。"""
        return self._tools.get(key)

    def has(self, key: str) -> bool:
        return key in self._tools

    def list_all(self) -> list[ToolDescriptor]:
        """全部描述符，按 (sort_order, key) 排序。"""
        return sorted(self._tools.values(),
                      key=lambda t: (t.sort_order, t.key))

    def list_by_category(self, category: str) -> list[ToolDescriptor]:
        """按分类过滤，排序规则同 list_all。"""
        return [t for t in self.list_all() if t.category == category]

    def keys(self) -> list[str]:
        return [t.key for t in self.list_all()]

    def __len__(self) -> int:
        return len(self._tools)

    def __contains__(self, key: object) -> bool:
        return key in self._tools


# 进程级默认注册表（API 层与安装器共享同一实例）
_default_registry: Optional[ToolRegistry] = None


def get_default_registry() -> ToolRegistry:
    """获取进程级默认工具注册表（懒初始化）。"""
    global _default_registry
    if _default_registry is None:
        _default_registry = ToolRegistry()
    return _default_registry
