# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).
"""文本内嵌工具调用解析 — 兼容不原生支持 function calling 的模型。

部分模型收到 tools schema 后不返回标准 `tool_calls` 字段，而是把调用
以 JSON 形式写进正文（如 [{"name":"write_file","arguments":{...}}, ...]，
甚至丢下划线写成 writefile）。本模块负责：
1. 从回复文本中提取内嵌工具调用（JSON 数组 / 单对象 / ```json 代码块 /
   "前缀文字 + JSON" 混排），并做括号平衡修复；
2. 工具名归一化匹配（去下划线/连字符、忽略大小写），
   writefile → write_file、runcommand → run_command。
"""
import json
import re

# ─────────────────────────────────────────────
# 名称归一化
# ─────────────────────────────────────────────
def normalize_name(name):
    """write_file / WriteFile / write-file → writefile。"""
    return re.sub(r'[_\-\s]', '', str(name or '')).lower()


def resolve_tool_name(name, known_names):
    """按归一化规则把模型给出的名称映射回注册名，未命中返回 None。"""
    target = normalize_name(name)
    if not target:
        return None
    for known in known_names:
        if normalize_name(known) == target:
            return known
    return None


# ─────────────────────────────────────────────
# 文本提取
# ─────────────────────────────────────────────
def _to_calls(parsed):
    """把解析出的 JSON 规整为 [{'name','arguments'}, ...]，非法返回 []。"""
    if isinstance(parsed, dict):
        parsed = [parsed]
    if not isinstance(parsed, list):
        return []
    calls = []
    for item in parsed:
        if not isinstance(item, dict):
            continue
        name = item.get('name') or item.get('function') or item.get('tool')
        args = item.get('arguments')
        if args is None:
            args = item.get('parameters') or item.get('args') or {}
        if isinstance(args, str):
            try:
                args = json.loads(args)
            except ValueError:
                args = {}
        if not name or not isinstance(args, dict):
            continue
        calls.append({'name': name, 'arguments': args})
    return calls


def extract_tool_calls(text):
    """从模型回复文本中提取内嵌工具调用。无调用返回 []。"""
    if not text or not isinstance(text, str):
        return []

    candidates = []
    # 1) ```json / ``` 代码块
    for m in re.finditer(r'```(?:json)?\s*([\s\S]*?)```', text):
        candidates.append(m.group(1).strip())
    # 2) 首个 '[' 或 '{' 起的原文（覆盖纯 JSON 与"前缀文字+JSON"）
    idx = next((i for i, ch in enumerate(text) if ch in '[{'), -1)
    if idx >= 0:
        candidates.append(text[idx:].strip())

    for cand in candidates:
        calls = _try_parse(cand)
        if calls:
            return calls
    return []


def _try_parse(fragment):
    """逐级截断尾部尝试 json.loads，兼容模型多写的尾巴/缺失的闭括号。"""
    frag = fragment.strip()
    for end in range(len(frag), 0, -1):
        piece = frag[:end].strip()
        if not piece or piece[-1] not in ']}':
            continue
        try:
            parsed = json.loads(piece)
        except ValueError:
            continue
        calls = _to_calls(parsed)
        if calls:
            return calls
    return []
