# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).
"""ToolPipeline — 守卫工具执行管道。

借鉴 deepseek-harness 的 guarded execution pipeline：
  tools/pre-execute (waterfall, 可拒绝)
    -> tools/execute (实际执行)
      -> tools/post-execute (结果处理)
        -> tool/result (最终观察)

特性：
- pre/post 钩子链（审批、沙箱检查、结果裁剪、日志）
- 超时控制（per-call + 全局默认）
- 并行工具调用（bounded rolling pool）
- 异常隔离（单个钩子失败不影响执行）
"""
import asyncio
import json
import logging
import time
from dataclasses import dataclass, field
from typing import Any, Callable, Optional

logger = logging.getLogger("agent.tool_pipeline")


@dataclass
class ToolCall:
    """工具调用请求。"""
    call_id: str = ''
    name: str = ''
    args: dict = field(default_factory=dict)
    timeout_ms: int = 30_000       # 默认 30 秒超时
    turn: int = 0                  # 所属 turn 编号
    step: int = 0                  # 所属 step 编号
    metadata: dict = field(default_factory=dict)


@dataclass
class ToolResult:
    """工具调用结果。"""
    call_id: str = ''
    name: str = ''
    success: bool = True
    data: Any = None
    error: str = ''
    is_error: bool = False
    duration_ms: float = 0
    timed_out: bool = False
    rejected: bool = False         # 被 pre-hook 拒绝
    reject_reason: str = ''
    metadata: dict = field(default_factory=dict)

    def to_content_str(self, limit: int = 4000) -> str:
        """转为 LLM tool message 的 content 字符串。"""
        if self.is_error or self.timed_out:
            return json.dumps({'success': False, 'error': self.error},
                              ensure_ascii=False)[:limit]
        if self.rejected:
            return json.dumps({'success': False,
                               'error': 'rejected: %s' % self.reject_reason},
                              ensure_ascii=False)[:limit]
        payload = self.data if isinstance(self.data, dict) else {'result': self.data}
        return json.dumps(payload, ensure_ascii=False)[:limit]


# ─────────────────────────────────────────
# 钩子类型
# ─────────────────────────────────────────

# Pre-hook: 接收 ToolCall，返回 None 表示放行，返回 str 表示拒绝原因
PreHook = Callable[[ToolCall], Optional[str]]

# Post-hook: 接收 (ToolCall, ToolResult)，返回修改后的 ToolResult
PostHook = Callable[[ToolCall, ToolResult], ToolResult]


class ToolPipeline:
    """守卫工具执行管道。

    用法：
        pipeline = ToolPipeline(dispatch_fn)
        pipeline.add_pre_hook(approval_guard)
        pipeline.add_pre_hook(sandbox_check)
        pipeline.add_post_hook(result_logger)
        pipeline.add_post_hook(output_trimmer)

        result = await pipeline.execute(ToolCall(name='shell_exec', args={...}))
    """

    def __init__(self, dispatch_fn: Callable = None,
                 default_timeout_ms: int = 30_000,
                 max_parallel: int = 5):
        """
        Args:
            dispatch_fn: 实际的工具调用分发函数 (name, args) -> Any
            default_timeout_ms: 默认超时（毫秒）
            max_parallel: 并行工具调用上限
        """
        self._dispatch_fn = dispatch_fn
        self._default_timeout_ms = default_timeout_ms
        self._max_parallel = max_parallel
        self._pre_hooks: list[PreHook] = []
        self._post_hooks: list[PostHook] = []
        self._semaphore: Optional[asyncio.Semaphore] = None

    @property
    def semaphore(self) -> asyncio.Semaphore:
        """延迟创建 semaphore（需要在事件循环内）。"""
        if self._semaphore is None:
            self._semaphore = asyncio.Semaphore(self._max_parallel)
        return self._semaphore

    def set_dispatch(self, dispatch_fn: Callable):
        """设置/替换工具调用分发函数。"""
        self._dispatch_fn = dispatch_fn

    # ─────────────────────────────────────────
    # 钩子注册
    # ─────────────────────────────────────────

    def add_pre_hook(self, hook: PreHook, name: str = ''):
        """添加前置守卫钩子。

        Args:
            hook: callable(ToolCall) -> Optional[str]
                  返回 None 表示放行，返回 str 表示拒绝原因
            name: 钩子名称（用于日志）
        """
        self._pre_hooks.append(hook)
        logger.debug('注册 pre-hook: %s', name or hook.__name__)

    def add_post_hook(self, hook: PostHook, name: str = ''):
        """添加后置处理钩子。

        Args:
            hook: callable(ToolCall, ToolResult) -> ToolResult
            name: 钩子名称（用于日志）
        """
        self._post_hooks.append(hook)
        logger.debug('注册 post-hook: %s', name or hook.__name__)

    # ─────────────────────────────────────────
    # 执行管道
    # ─────────────────────────────────────────

    async def execute(self, call: ToolCall) -> ToolResult:
        """执行单个工具调用（完整管道）。

        流程：pre-hooks -> execute -> post-hooks
        """
        t_start = time.monotonic()

        if not call.timeout_ms:
            call.timeout_ms = self._default_timeout_ms

        # ① Pre-hooks（waterfall，任一拒绝则终止）
        for hook in self._pre_hooks:
            try:
                reject_reason = hook(call)
                if reject_reason is not None:
                    logger.info('工具 %s 被 pre-hook %s 拒绝: %s',
                                call.name, hook.__name__, reject_reason)
                    return ToolResult(
                        call_id=call.call_id, name=call.name,
                        success=False, rejected=True,
                        reject_reason=reject_reason,
                        error=reject_reason,
                        duration_ms=(time.monotonic() - t_start) * 1000,
                    )
            except Exception:
                # 防御性：钩子异常不影响执行
                logger.exception('pre-hook %s 异常（已隔离）', hook.__name__)

        # ② Execute（带超时）
        result = await self._execute_with_timeout(call)

        # ③ Post-hooks（链式处理）
        for hook in self._post_hooks:
            try:
                result = hook(call, result)
            except Exception:
                logger.exception('post-hook %s 异常（已隔离）', hook.__name__)

        result.duration_ms = (time.monotonic() - t_start) * 1000
        return result

    async def execute_batch(self, calls: list) -> list:
        """并行执行多个工具调用（bounded rolling pool）。

        Args:
            calls: ToolCall 列表

        Returns:
            ToolResult 列表（顺序与 calls 对应）
        """
        if not calls:
            return []

        async def _bounded(call):
            async with self.semaphore:
                return await self.execute(call)

        tasks = [asyncio.create_task(_bounded(c)) for c in calls]
        return await asyncio.gather(*tasks, return_exceptions=False)

    # ─────────────────────────────────────────
    # 内部执行
    # ─────────────────────────────────────────

    async def _execute_with_timeout(self, call: ToolCall) -> ToolResult:
        """带超时的工具调用执行。"""
        timeout_sec = call.timeout_ms / 1000.0

        try:
            if asyncio.iscoroutinefunction(self._dispatch_fn):
                data = await asyncio.wait_for(
                    self._dispatch_fn(call.name, call.args),
                    timeout=timeout_sec)
            else:
                # 同步函数放到线程池
                loop = asyncio.get_event_loop()
                data = await asyncio.wait_for(
                    loop.run_in_executor(
                        None, self._dispatch_fn, call.name, call.args),
                    timeout=timeout_sec)

            return ToolResult(
                call_id=call.call_id, name=call.name,
                success=True, data=data,
            )

        except asyncio.TimeoutError:
            logger.warning('工具 %s 执行超时 (%dms)', call.name, call.timeout_ms)
            return ToolResult(
                call_id=call.call_id, name=call.name,
                success=False, is_error=True, timed_out=True,
                error='工具执行超时 (%dms)' % call.timeout_ms,
            )
        except ValueError as e:
            return ToolResult(
                call_id=call.call_id, name=call.name,
                success=False, is_error=True,
                error=str(e),
            )
        except Exception as e:
            logger.exception('工具 %s 执行异常', call.name)
            return ToolResult(
                call_id=call.call_id, name=call.name,
                success=False, is_error=True,
                error=str(e),
            )

    def execute_sync(self, call: ToolCall) -> ToolResult:
        """同步版本的执行（用于非异步上下文）。

        内部创建事件循环运行 execute()。
        """
        try:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                # 已在事件循环中，使用 run_until_complete 会死锁
                # 降级为直接同步调用
                return self._execute_sync_fallback(call)
        except RuntimeError:
            pass

        loop = asyncio.new_event_loop()
        try:
            return loop.run_until_complete(self.execute(call))
        finally:
            loop.close()

    def _execute_sync_fallback(self, call: ToolCall) -> ToolResult:
        """同步降级执行（无超时保护）。"""
        t_start = time.monotonic()

        # Pre-hooks
        for hook in self._pre_hooks:
            try:
                reject_reason = hook(call)
                if reject_reason is not None:
                    return ToolResult(
                        call_id=call.call_id, name=call.name,
                        success=False, rejected=True,
                        reject_reason=reject_reason,
                        error=reject_reason,
                        duration_ms=(time.monotonic() - t_start) * 1000,
                    )
            except Exception:
                logger.exception('pre-hook %s 异常（已隔离）', hook.__name__)

        # Execute
        try:
            data = self._dispatch_fn(call.name, call.args)
            result = ToolResult(
                call_id=call.call_id, name=call.name,
                success=True, data=data,
            )
        except ValueError as e:
            result = ToolResult(
                call_id=call.call_id, name=call.name,
                success=False, is_error=True, error=str(e),
            )
        except Exception as e:
            logger.exception('工具 %s 执行异常', call.name)
            result = ToolResult(
                call_id=call.call_id, name=call.name,
                success=False, is_error=True, error=str(e),
            )

        # Post-hooks
        for hook in self._post_hooks:
            try:
                result = hook(call, result)
            except Exception:
                logger.exception('post-hook %s 异常（已隔离）', hook.__name__)

        result.duration_ms = (time.monotonic() - t_start) * 1000
        return result


# ─────────────────────────────────────────
# 内置钩子
# ─────────────────────────────────────────

def make_output_limit_hook(limit: int = 4000) -> PostHook:
    """创建输出裁剪钩子。"""
    def _hook(call: ToolCall, result: ToolResult) -> ToolResult:
        if result.data and isinstance(result.data, str):
            if len(result.data) > limit:
                result.data = result.data[:limit] + '...(truncated)'
        return result
    return _hook


def make_call_logger() -> PostHook:
    """创建调用日志钩子。"""
    def _hook(call: ToolCall, result: ToolResult) -> ToolResult:
        status = 'ok' if result.success else ('timeout' if result.timed_out
                                               else 'error')
        logger.info('[ToolPipeline] %s(%s) -> %s %.0fms',
                    call.name, call.call_id, status, result.duration_ms)
        return result
    return _hook


def make_sandbox_deny_hook(denied_tools: list = None) -> PreHook:
    """创建沙箱拒绝钩子（禁止特定工具）。"""
    denied = set(denied_tools or [])
    def _hook(call: ToolCall) -> Optional[str]:
        if call.name in denied:
            return '工具 %s 已被沙箱策略禁止' % call.name
        return None
    return _hook
