# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

"""metaskill.file.read — 读取文件内容。

底层委托给 tools.shell_mcp.read_file。
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))


def run(path, max_lines=500, offset=0, **kwargs):
    from agent_runtime.tools.shell_mcp import read_file
    return read_file(path, max_lines=max_lines, offset=offset)
