// Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
// Copyright: (c) <opensource@openchiip.com>
// Generated By : OpenChiip
// Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
// This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

import { useEffect, useRef } from 'react'
import * as echarts from 'echarts/core'
import { LineChart } from 'echarts/charts'
import {
  GridComponent, TooltipComponent, LegendComponent,
} from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'

echarts.use([LineChart, GridComponent, TooltipComponent, LegendComponent, CanvasRenderer])

interface SeriesConfig {
  name: string
  data: (number | null)[]
  color: string
  unit?: string
}

interface MetricChartProps {
  title: string
  times: (string | number)[]
  series: SeriesConfig[]
  yAxisMax?: number
  yAxisFormatter?: string | ((value: number) => string)
  height?: number
  /** 当前时间范围（如 '1h' | '24h' | '7d'），用于自适应 xAxis 标签格式 */
  timeRange?: string
  /** 显式覆盖 ECharts time 轴标签格式；未提供时按 timeRange 推导 */
  timeAxisFormatter?: string
}

/** 判断字符串是否可解析为数字 */
function isNumericString(v: string): boolean {
  return v.trim() !== '' && !Number.isNaN(Number(v))
}

/**
 * 归一化 times 数组：
 * - number（epoch ms）→ 直接使用
 * - 可解析为数字的 string → 转为 number
 * - 旧的短标签 string（如 "16:10"）→ 无法解析，整体降级为 category 轴
 */
function normalizeTimes(times: (string | number)[]): {
  axisType: 'time' | 'category'
  values: (number | string)[]
} {
  const values: (number | string)[] = []
  let allNumeric = true
  for (const t of times) {
    if (typeof t === 'number') {
      values.push(t)
    } else if (typeof t === 'string' && isNumericString(t)) {
      values.push(Number(t))
    } else {
      allNumeric = false
      values.push(t)
    }
  }
  return { axisType: allNumeric ? 'time' : 'category', values }
}

/** 根据时间范围推导 xAxis 标签格式 */
function pickAxisFormatter(timeRange?: string): string {
  switch (timeRange) {
    case '1h':  case '3h':  case '6h':  case '12h':  case '24h':
      return '{HH}:{mm}'
    case '7d':  case '30d':
      return '{MM}-{dd} {HH}:{mm}'
    default:
      return '{MM}-{dd} {HH}:{mm}'
  }
}

/** timeRange → 毫秒数 */
function rangeToMs(range?: string): number {
  const H = 3600_000, D = 86400_000
  switch (range) {
    case '1h':  return H
    case '3h':  return 3 * H
    case '6h':  return 6 * H
    case '12h': return 12 * H
    case '24h': return D
    case '7d':  return 7 * D
    case '30d': return 30 * D
    default:    return H
  }
}

/** 格式化为完整人性化时间，如 "2026-09-07 16:10:35" */
function formatFullTime(t: number | string): string {
  const d =
    typeof t === 'number'
      ? new Date(t)
      : isNumericString(t)
        ? new Date(Number(t))
        : null
  if (!d || Number.isNaN(d.getTime())) return String(t)
  const pad = (n: number) => String(n).padStart(2, '0')
  return (
    `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ` +
    `${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`
  )
}

export function MetricChart({
  title,
  times,
  series,
  yAxisMax,
  yAxisFormatter,
  height = 260,
  timeRange,
  timeAxisFormatter,
}: MetricChartProps) {
  const chartRef = useRef<HTMLDivElement>(null)
  const instanceRef = useRef<echarts.ECharts | null>(null)

  useEffect(() => {
    if (!chartRef.current) return
    if (!instanceRef.current) {
      instanceRef.current = echarts.init(chartRef.current)
    }
    const chart = instanceRef.current

    const { axisType, values } = normalizeTimes(times)
    const axisFormatter = timeAxisFormatter ?? pickAxisFormatter(timeRange)

    // 构建 series data：time 轴生成 [time, value] 对，间隔 >60s 插入 null 断开曲线
    const GAP_MS = 60_000
    const toSeriesData = (data: (number | null)[]) => {
      if (axisType !== 'time') return data.map(v => v ?? null)
      const out: (number | null)[][] = []
      for (let i = 0; i < values.length; i++) {
        const t = values[i] as number
        if (i > 0) {
          const p = values[i - 1] as number
          if (typeof p === 'number' && typeof t === 'number' && t - p > GAP_MS)
            out.push([Math.round(p + (t - p) / 2), null])
        }
        out.push([t, data[i] ?? null])
      }
      return out
    }

    // x 轴锁定到查询时间范围，无数据区间显示空白而非自动收缩
    const xMax = Date.now()
    const xMin = xMax - rangeToMs(timeRange)

    const option: echarts.EChartsCoreOption = {
      tooltip: {
        trigger: 'axis',
        axisPointer: { type: 'cross' },
        formatter: (params: unknown) => {
          const arr = (Array.isArray(params) ? params : [params]) as {
            value: unknown
            axisValue: unknown
            seriesName: string
            marker: string
            color: string
          }[]
          if (arr.length === 0) return ''
          const first = arr[0]
          const rawTime =
            axisType === 'time'
              ? Array.isArray(first.value)
                ? (first.value[0] as number | string)
                : (first.axisValue as number | string)
              : (first.axisValue as number | string)
          const timeLabel =
            axisType === 'time' ? formatFullTime(rawTime) : String(rawTime)
          const rows = arr.map(p => {
            const val = Array.isArray(p.value)
              ? (p.value[1] as number | null)
              : (p.value as number | null)
            const cfg = series.find(s => s.name === p.seriesName)
            const suffix = cfg?.unit ? ' ' + cfg.unit : ''
            const text = val === null || val === undefined ? '-' : `${val}${suffix}`
            return `<div style="display:flex;align-items:center;gap:6px">${p.marker}<span>${p.seriesName}</span><b style="margin-left:auto">${text}</b></div>`
          })
          return (
            `<div style="font-weight:600;margin-bottom:4px">${timeLabel}</div>` +
            rows.join('')
          )
        },
      },
      legend: {
        data: series.map(s => s.name),
        top: 0,
        textStyle: { fontSize: 11, color: '#64748b' },
      },
      grid: { left: '3%', right: '4%', bottom: '3%', top: '14%', containLabel: true },
      xAxis:
        axisType === 'time'
          ? {
              type: 'time',
              min: xMin,
              max: xMax,
              axisLabel: {
                fontSize: 10,
                color: '#94a3b8',
                formatter: axisFormatter,
              },
              boundaryGap: false,
            }
          : {
              type: 'category',
              data: values as string[],
              axisLabel: {
                fontSize: 10,
                color: '#94a3b8',
              },
              boundaryGap: false,
            },
      yAxis: {
        type: 'value',
        ...(yAxisMax ? { max: yAxisMax } : {}),
        axisLabel: {
          fontSize: 10,
          color: '#94a3b8',
          ...(typeof yAxisFormatter === 'string'
            ? { formatter: yAxisFormatter }
            : yAxisFormatter ? { formatter: yAxisFormatter }
            : {}),
        },
        splitLine: { lineStyle: { type: 'dashed', color: '#e2e8f0' } },
      },
      series: series.map(s => ({
        name: s.name,
        type: 'line' as const,
        data: toSeriesData(s.data),
        connectNulls: false,
        smooth: true,
        symbol: 'none',
        lineStyle: { width: 2, color: s.color },
        areaStyle: {
          color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [
            { offset: 0, color: s.color + '40' },
            { offset: 1, color: s.color + '05' },
          ]),
        },
        itemStyle: { color: s.color },
      })),
    }

    chart.setOption(option, true)

    const handleResize = () => chart.resize()
    window.addEventListener('resize', handleResize)
    return () => {
      window.removeEventListener('resize', handleResize)
    }
  }, [times, series, yAxisMax, yAxisFormatter, timeRange, timeAxisFormatter])

  useEffect(() => {
    return () => {
      instanceRef.current?.dispose()
      instanceRef.current = null
    }
  }, [])

  return (
    <div className="rounded-xl border bg-card p-5">
      <h3 className="text-sm font-semibold text-slate-700 mb-3">{title}</h3>
      <div ref={chartRef} style={{ height }} />
    </div>
  )
}
