// Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
// Copyright: (c) <opensource@openchiip.com>
// Generated By : OpenChiip
// Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
// This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

import { useRef, useState, useCallback, useEffect } from 'react'
import { useParams } from 'react-router-dom'
import { useChatStore } from '@/store/chat'
import { cn } from '@/lib/utils'
import { api } from '@/lib/api'
import { Send, Loader2, Square, ChevronDown, PanelLeftClose, PanelRightClose, X, FileText } from 'lucide-react'
import { EmptyHero } from '@/components/chat/EmptyHero'
import { MessageBubble } from '@/components/chat/MessageBubble'
import { FeedbackModal } from '@/components/chat/FeedbackModal'
import { WorkspacePanel } from '@/components/chat/WorkspacePanel'
import { ProjectPanel } from '@/components/chat/ProjectPanel'
import { ExecutionPanel } from '@/components/chat/ExecutionPanel'
import { ResizablePanel } from '@/components/ResizablePanel'
import type { FileInfo } from '@/lib/api'

// --- 滚动控制常量（参考 openwork scroll-controller.ts） ---
const EXACT_BOTTOM_GAP_PX = 1
const SCROLL_GESTURE_WINDOW_MS = 600
const MANUAL_BROWSE_UPWARD_THRESHOLD_PX = 16

export function Chat() {
  const { sessionId: urlSessionId } = useParams<{ sessionId?: string }>()
  const {
    messages, isStreaming, currentSessionId,
    sendMessage, abortStreaming, submitFeedback, deleteFeedback, toggleBookmark, switchSession,
  } = useChatStore()
  const [input, setInput] = useState('')
  const scrollRef = useRef<HTMLDivElement>(null)
  const contentRef = useRef<HTMLDivElement>(null)
  const inputRef = useRef<HTMLTextAreaElement>(null)
  const [showScrollToBottom, setShowScrollToBottom] = useState(false)
  const isProgrammaticScroll = useRef(false)
  const lastGestureAt = useRef(0)
  // 追踪首条消息 ID，检测 session 切换（参考 dify chatList[0].id 变化检测）
  const prevFirstMessageIdRef = useRef<string | undefined>(undefined)
  // 反馈弹窗状态
  const [feedbackModalOpen, setFeedbackModalOpen] = useState(false)
  const [feedbackTargetId, setFeedbackTargetId] = useState<number | null>(null)
  // 工作区选中文件
  const [selectedFile, setSelectedFile] = useState<FileInfo | null>(null)
  const [selectedFileRoot, setSelectedFileRoot] = useState<number>(0)
  // 输入框中的文件引用（@文件 chips）
  const [fileMentions, setFileMentions] = useState<FileInfo[]>([])
  // 左右面板折叠状态
  const [leftCollapsed, setLeftCollapsed] = useState(false)
  const [rightCollapsed, setRightCollapsed] = useState(false)
  // 运行模式
  const [runMode, setRunMode] = useState<string>('local')
  // 选中的项目 ID（用于联动右侧任务列表）
  const [selectedProjectId, setSelectedProjectId] = useState<string | null>(null)

  // 获取运行模式
  useEffect(() => {
    api.getStatus().then(s => {
      if (s.run_mode) setRunMode(s.run_mode)
    }).catch(() => {})
  }, [])

  // 从 URL 参数加载会话
  useEffect(() => {
    if (urlSessionId && urlSessionId !== currentSessionId) {
      switchSession(urlSessionId)
    }
  }, [urlSessionId, currentSessionId, switchSession])

  // --- 滚动辅助函数（参考 openwork scroll-controller.ts） ---
  const scrollBottomGap = useCallback((container: HTMLDivElement) => {
    return container.scrollHeight - (container.scrollTop + container.clientHeight)
  }, [])

  const isExactlyAtBottom = useCallback((container: HTMLDivElement) => {
    return scrollBottomGap(container) <= EXACT_BOTTOM_GAP_PX
  }, [scrollBottomGap])

  const hasScrollGesture = useCallback(() => {
    return Date.now() - lastGestureAt.current < SCROLL_GESTURE_WINDOW_MS
  }, [])

  const scrollToBottom = useCallback((smooth = false) => {
    const container = scrollRef.current
    if (!container) return
    isProgrammaticScroll.current = true
    if (smooth) {
      container.scrollTo({ top: container.scrollHeight, behavior: 'smooth' })
    } else {
      container.scrollTop = container.scrollHeight
    }
    setShowScrollToBottom(false)
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        isProgrammaticScroll.current = false
      })
    })
  }, [])

  // 手势检测：wheel / touchstart 标记用户主动滚动
  const onChatGesture = useCallback(() => {
    lastGestureAt.current = Date.now()
  }, [])

  // 滚动事件处理
  const onChatScroll = useCallback(() => {
    const container = scrollRef.current
    if (!container) return
    if (isProgrammaticScroll.current) return
    if (isExactlyAtBottom(container)) {
      setShowScrollToBottom(false)
    } else {
      setShowScrollToBottom(scrollBottomGap(container) > MANUAL_BROWSE_UPWARD_THRESHOLD_PX)
    }
  }, [isExactlyAtBottom, scrollBottomGap])

  // 消息变化时自动滚动
  useEffect(() => {
    const container = scrollRef.current
    if (!container) return

    const firstId = messages[0]?.id?.toString()

    // 检测 session 切换（首条消息 ID 变化）→ 强制滚动到底部
    if (firstId && prevFirstMessageIdRef.current !== firstId) {
      prevFirstMessageIdRef.current = firstId
      lastGestureAt.current = 0 // 清除手势标记
      // 阶梯延迟确保 DOM 渲染完成（参考 hermes-agent）
      requestAnimationFrame(() => scrollToBottom())
      setTimeout(() => scrollToBottom(), 80)
      setTimeout(() => scrollToBottom(), 240)
      return
    }
    if (!firstId) {
      prevFirstMessageIdRef.current = undefined
    }

    // 常规消息追加：仅在 sticky 模式下跟随
    const gap = scrollBottomGap(container)
    if (gap < 100 && !hasScrollGesture()) {
      scrollToBottom()
    }
  }, [messages, scrollBottomGap, hasScrollGesture, scrollToBottom])

  // ResizeObserver 监听内容增长（参考 openwork scroll-controller.ts L260-289）
  useEffect(() => {
    const container = scrollRef.current
    if (!container) return
    const observer = new ResizeObserver(() => {
      if (!scrollRef.current) return
      const gap = scrollBottomGap(scrollRef.current)
      // 仅在接近底部（sticky 模式）且无手势时自动跟随
      if (gap < 100 && !hasScrollGesture()) {
        scrollToBottom()
      }
    })
    observer.observe(container)
    return () => observer.disconnect()
  }, [scrollBottomGap, hasScrollGesture, scrollToBottom])

  // 工作区文件点击：在输入框光标处插入 @文件名 + 右侧预览
  const handleFileSelect = useCallback((file: FileInfo, root: number) => {
    setSelectedFile(file)
    setSelectedFileRoot(root)
    // 避免重复添加 chip
    setFileMentions(prev => {
      if (prev.some(f => f.path === file.path)) return prev
      return [...prev, file]
    })
    // 在 textarea 光标位置插入 @文件名
    const ta = inputRef.current
    if (ta) {
      const start = ta.selectionStart
      const end = ta.selectionEnd
      const mention = `@${file.name} `
      const newText = input.slice(0, start) + mention + input.slice(end)
      setInput(newText)
      // 光标移到插入的 @文件名 之后
      requestAnimationFrame(() => {
        const pos = start + mention.length
        ta.setSelectionRange(pos, pos)
        ta.focus()
      })
    }
  }, [input])

  // 移除文件引用 chip，同时从输入框中删除对应的 @文件名
  const removeFileMention = useCallback((path: string) => {
    const file = fileMentions.find(f => f.path === path)
    if (file) {
      const mention = `@${file.name} `
      const idx = input.indexOf(mention)
      if (idx >= 0) {
        setInput(prev => prev.slice(0, idx) + prev.slice(idx + mention.length))
      } else {
        // 尝试不带空格的版本
        const mentionNoSpace = `@${file.name}`
        setInput(prev => prev.replace(mentionNoSpace, ''))
      }
    }
    setFileMentions(prev => prev.filter(f => f.path !== path))
  }, [fileMentions, input])

  const handleSend = useCallback(async () => {
    const msg = input.trim()
    if (!msg || isStreaming) return
    setInput('')
    setFileMentions([])
    await sendMessage(msg)
    scrollToBottom()
    inputRef.current?.focus()
  }, [input, isStreaming, sendMessage, scrollToBottom])

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleSend()
    }
  }

  const handleSuggestionClick = useCallback((text: string) => {
    setInput(text)
    inputRef.current?.focus()
  }, [])

  // 重新生成：找到对应 user 消息，删除当前 assistant 及之后消息，重新发送
  const handleRegenerate = useCallback(async (assistantMsgId: number) => {
    const idx = messages.findIndex(m => m.id === assistantMsgId)
    if (idx < 0) return
    let userMsgIndex = -1
    for (let i = idx - 1; i >= 0; i--) {
      if (messages[i].role === 'user') {
        userMsgIndex = i
        break
      }
    }
    if (userMsgIndex < 0) return
    const userContent = messages[userMsgIndex].content
    // 从当前 assistant 消息开始截断（store 内部会重新追加）
    useChatStore.setState((s) => ({
      messages: s.messages.slice(0, idx),
    }))
    await sendMessage(userContent)
    scrollToBottom()
  }, [messages, sendMessage, scrollToBottom])

  // --- 反馈处理 ---
  const handleFeedback = useCallback((messageId: number, rating: 'like' | 'dislike', comment?: string) => {
    if (!currentSessionId) return
    submitFeedback(messageId, rating, comment)
  }, [currentSessionId, submitFeedback])

  const handleDeleteFeedback = useCallback((messageId: number) => {
    deleteFeedback(messageId)
  }, [deleteFeedback])

  const handleFeedbackSubmit = useCallback((comment: string) => {
    if (feedbackTargetId != null) {
      handleFeedback(feedbackTargetId, 'dislike', comment || undefined)
    }
  }, [feedbackTargetId, handleFeedback])

  const showEmpty = messages.length === 0

  return (
    <div className="flex h-full">
      {/* 左侧：工作区文件浏览器 */}
      <ResizablePanel
        initialWidth={240}
        minWidth={180}
        maxWidth={400}
        side="left"
        collapsed={leftCollapsed}
        onCollapse={setLeftCollapsed}
        className="border-r"
      >
        <div className="flex flex-col h-full">
          {/* 上半部分：工作区 */}
          <div className="flex-1 min-h-0">
            <WorkspacePanel onFileSelect={handleFileSelect} />
          </div>
          {/* 分隔线 */}
          <div className="border-t" />
          {/* 下半部分：项目面板 */}
          <div className="flex-1 min-h-0">
            <ProjectPanel
              selectedProjectId={selectedProjectId}
              onProjectSelect={setSelectedProjectId}
            />
          </div>
        </div>
      </ResizablePanel>

      {/* 左侧面板折叠时的展开按钮 */}
      {leftCollapsed && (
        <button
          onClick={() => setLeftCollapsed(false)}
          className="flex items-center justify-center w-6 border-r hover:bg-accent transition-colors shrink-0"
          title="展开工作区"
        >
          <PanelLeftClose className="h-3.5 w-3.5 text-muted-foreground" />
        </button>
      )}

      {/* 中间：聊天区域 */}
      <div className="flex flex-1 flex-col min-w-0">
        {/* 第一层：relative 包裹层（参考 openwork: relative min-h-0 flex-1） */}
        <div className="relative min-h-0 flex-1">
          {/* 第二层：absolute 滚动容器（参考 openwork: absolute inset-0 overflow-y-auto） */}
          <div
            ref={scrollRef}
            onWheel={(e) => onChatGesture()}
            onTouchStart={() => onChatGesture()}
            onScroll={onChatScroll}
            className="absolute inset-0 overflow-x-hidden overflow-y-auto overscroll-y-contain"
          >
            {showEmpty ? (
              <EmptyHero onSuggestionClick={handleSuggestionClick} />
            ) : (
              <div ref={contentRef} className="mx-auto max-w-3xl space-y-4 px-4 py-6">
                {messages.map((msg) => (
                  <MessageBubble
                    key={msg.id}
                    message={msg}
                    isStreaming={isStreaming}
                    onRegenerate={handleRegenerate}
                    onFeedback={handleFeedback}
                    onDeleteFeedback={handleDeleteFeedback}
                    onBookmark={toggleBookmark}
                    onFeedbackOpen={(messageId) => {
                      setFeedbackTargetId(messageId)
                      setFeedbackModalOpen(true)
                    }}
                  />
                ))}
              </div>
            )}
          </div>

          {/* 反馈弹窗 */}
          <FeedbackModal
            open={feedbackModalOpen}
            onClose={() => setFeedbackModalOpen(false)}
            onSubmit={handleFeedbackSubmit}
          />

          {/* 第三层：浮动 "回到最新" 按钮（参考 openwork scroll-overlay.tsx） */}
          <div
            className={cn(
              'absolute bottom-3 left-1/2 -translate-x-1/2 z-30 pointer-events-none transition-opacity duration-200',
              showScrollToBottom ? 'opacity-100' : 'opacity-0',
            )}
          >
            <button
              onClick={() => scrollToBottom(true)}
              className="pointer-events-auto flex items-center gap-1 rounded-full border border-border bg-background/95 px-3 py-1.5 text-xs text-muted-foreground shadow-md backdrop-blur-sm transition-colors hover:bg-accent"
            >
              <ChevronDown className="h-3.5 w-3.5" /> 回到最新
            </button>
          </div>
        </div>

        {/* 输入区域（shrink-0 固定，参考 openwork: shrink-0） */}
        <div className="border-t bg-background shrink-0">
          {/* 接单模式提示 */}
          {runMode === 'order' && (
            <div className="rounded-lg border border-amber-200 bg-amber-50 mx-auto max-w-3xl px-4 py-2 mt-2 text-center text-sm text-amber-700">
              当前为接单模式，仅处理平台委派的项目任务，不接受对话请求。
            </div>
          )}
          <div className="mx-auto flex max-w-3xl items-end gap-2 px-4 py-3">
            <div className="flex-1 rounded-xl border bg-background focus-within:ring-2 focus-within:ring-ring transition-shadow">
              {/* @文件引用 chips */}
              {fileMentions.length > 0 && (
                <div className="flex flex-wrap gap-1.5 px-3 pt-2.5">
                  {fileMentions.map((file) => (
                    <span
                      key={file.path}
                      className="inline-flex items-center gap-1 rounded-md bg-primary/10 text-primary px-2 py-0.5 text-xs font-medium"
                    >
                      <FileText className="h-3 w-3" />
                      {file.name}
                      <button
                        onClick={() => removeFileMention(file.path)}
                        className="ml-0.5 rounded-full hover:bg-primary/20 transition-colors"
                      >
                        <X className="h-3 w-3" />
                      </button>
                    </span>
                  ))}
                </div>
              )}
              <textarea
                ref={inputRef}
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder={fileMentions.length > 0 ? '继续输入消息...' : '输入消息... (Enter 发送, Shift+Enter 换行)'}
                className="w-full resize-none bg-transparent px-4 py-3 text-sm outline-none placeholder:text-muted-foreground"
                rows={1}
                style={{ maxHeight: '150px' }}
                disabled={isStreaming}
              />
            </div>
            {isStreaming ? (
              <button
                onClick={abortStreaming}
                className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-destructive text-destructive-foreground hover:bg-destructive/90 transition-colors"
                title="停止生成"
              >
                <Square className="h-3.5 w-3.5" />
              </button>
            ) : (
              <button
                onClick={handleSend}
                disabled={!input.trim()}
                className={cn(
                  'flex h-10 w-10 shrink-0 items-center justify-center rounded-xl transition-colors',
                  input.trim()
                    ? 'bg-primary text-primary-foreground hover:bg-primary/90'
                    : 'bg-muted text-muted-foreground',
                )}
              >
                <Send className="h-4 w-4" />
              </button>
            )}
          </div>
        </div>
      </div>

      {/* 右侧面板折叠时的展开按钮 */}
      {rightCollapsed && (
        <button
          onClick={() => setRightCollapsed(false)}
          className="flex items-center justify-center w-6 border-l hover:bg-accent transition-colors shrink-0"
          title="展开执行台"
        >
          <PanelRightClose className="h-3.5 w-3.5 text-muted-foreground" />
        </button>
      )}

      {/* 右侧：执行台面板 */}
      <ResizablePanel
        initialWidth={300}
        minWidth={240}
        maxWidth={500}
        side="right"
        collapsed={rightCollapsed}
        onCollapse={setRightCollapsed}
        className="border-l"
      >
        <ExecutionPanel messages={messages} selectedFile={selectedFile} selectedFileRoot={selectedFileRoot} selectedProjectId={selectedProjectId} />
      </ResizablePanel>
    </div>
  )
}
