// Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
// Copyright: (c) <opensource@openchiip.com>
// Generated By : OpenChiip
// Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
// This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

import { useQuery } from '@tanstack/react-query'
import { api } from '@/lib/api'
import { Terminal, Play } from 'lucide-react'
import { useState } from 'react'

export function Commands() {
  const { data: commands } = useQuery({ queryKey: ['commands'], queryFn: api.getCommands })
  const [executing, setExecuting] = useState<string | null>(null)
  const [results, setResults] = useState<Record<string, { output: string; success: boolean }>>({})
  const [customCmd, setCustomCmd] = useState('')

  const handleExecute = async (cmd: string, args?: string) => {
    setExecuting(cmd)
    try {
      const res = await api.executeCommand(cmd, args)
      setResults((prev) => ({ ...prev, [cmd]: { output: res.output || res.error || '执行完成', success: res.success !== false } }))
    } catch (e) {
      setResults((prev) => ({ ...prev, [cmd]: { output: (e as Error).message, success: false } }))
    } finally {
      setExecuting(null)
    }
  }

  // 解析自定义命令输入（支持 "/qoder 任务描述" 格式）
  const handleCustomExecute = () => {
    const input = customCmd.trim()
    if (!input) return
    const spaceIdx = input.indexOf(' ')
    if (spaceIdx > 0) {
      const cmd = input.slice(0, spaceIdx)
      const args = input.slice(spaceIdx + 1)
      handleExecute(cmd, args)
    } else {
      handleExecute(input)
    }
  }

  return (
    <div className="p-6 space-y-6">
      <div>
        <h2 className="text-2xl font-bold">控制指令</h2>
        <p className="text-muted-foreground">内置系统控制命令</p>
      </div>

      {/* Custom command input */}
      <div className="flex gap-2">
        <input
          value={customCmd}
          onChange={(e) => setCustomCmd(e.target.value)}
          placeholder="输入指令，如 /status 或 /qoder 写一个冒泡排序"
          className="flex-1 rounded-lg border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-ring"
          onKeyDown={(e) => { if (e.key === 'Enter' && customCmd.trim()) handleCustomExecute() }}
        />
        <button
          onClick={handleCustomExecute}
          className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm text-primary-foreground hover:bg-primary/90"
        >
          <Play className="h-4 w-4" /> 执行
        </button>
      </div>

      {/* Commands list */}
      <div className="grid gap-3 sm:grid-cols-2">
        {!commands ? null : commands.map((cmd) => (
          <div key={cmd.name} className="rounded-xl border bg-card p-4">
            <div className="flex items-start gap-3">
              <Terminal className="h-5 w-5 text-orange-500 mt-0.5" />
              <div className="flex-1">
                <div className="flex items-center gap-2">
                  <h3 className="font-medium text-sm font-mono">{cmd.name}</h3>
                  {cmd.require_llm && (
                    <span className="rounded bg-yellow-500/10 px-1.5 py-0.5 text-xs text-yellow-600">需LLM</span>
                  )}
                </div>
                <p className="mt-1 text-xs text-muted-foreground">{cmd.description}</p>
                <p className="mt-1 text-xs text-muted-foreground font-mono">{cmd.usage_example}</p>
                <button
                  onClick={() => handleExecute(cmd.name)}
                  disabled={executing === cmd.name}
                  className="mt-2 flex items-center gap-1 rounded-lg bg-secondary px-3 py-1.5 text-xs hover:bg-secondary/80 disabled:opacity-50"
                >
                  <Play className="h-3 w-3" /> {executing === cmd.name ? '执行中...' : '运行'}
                </button>
                {results[cmd.name] && (
                  <pre className={`mt-2 rounded p-2 text-xs overflow-auto max-h-32 ${results[cmd.name].success ? 'bg-muted' : 'bg-destructive/10'}`}>
                    {results[cmd.name].output}
                  </pre>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
