// Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
// Copyright: (c) <opensource@openchiip.com>
// Generated By : OpenChiip
// Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
// This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

/**
 * Tasks — 独立任务管理页面。
 *
 * 功能:
 * - 统计卡片（总任务/执行中/已完成/成功率）
 * - 看板视图（按状态分列展示）
 * - 列表视图（表格形式，与看板共享数据源）
 * - 视图切换（看板/列表）
 * - 任务详情抽屉（状态时间线 + 子任务 + 操作按钮）
 */
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import {
  ClipboardList, Plus, LayoutGrid, List, RefreshCw,
  CheckCircle2, Circle, XCircle, Clock,
  ChevronRight, AlertTriangle, RotateCcw, X,
  Play, Square, FileText, Folder as FolderIcon,
  Search, ChevronsLeft, ChevronsRight,
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { api, type TaskInfo, type TaskEvent, type TaskStats, type ProjectInfo } from '@/lib/api'

// ─── 常量 ─────────────────────────────────────────
const REFRESH_MS = 15_000

const STATUS_COLUMNS = [
  { key: 'pending', label: '待执行' },
  { key: 'running', label: '执行中' },
  { key: 'completed', label: '已完成' },
  { key: 'failed', label: '失败' },
]

// ─── 辅助函数 ──────────────────────────────────────

function formatTime(iso: string): string {
  try {
    const d = new Date(iso)
    const now = new Date()
    const diffMs = now.getTime() - d.getTime()
    const diffMin = Math.floor(diffMs / 60000)
    if (diffMin < 1) return '刚刚'
    if (diffMin < 60) return `${diffMin}分钟前`
    const diffHr = Math.floor(diffMin / 60)
    if (diffHr < 24) return `${diffHr}小时前`
    return d.toLocaleDateString('zh-CN', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
  } catch {
    return iso
  }
}

function formatDuration(startIso: string, endIso: string | null): string {
  try {
    const start = new Date(startIso)
    const end = endIso ? new Date(endIso) : new Date()
    const diffMs = end.getTime() - start.getTime()
    const diffSec = Math.floor(diffMs / 1000)
    if (diffSec < 60) return `${diffSec}s`
    const diffMin = Math.floor(diffSec / 60)
    const remainSec = diffSec % 60
    if (diffMin < 60) return `${diffMin}m${remainSec}s`
    const diffHr = Math.floor(diffMin / 60)
    const remainMin = diffMin % 60
    return `${diffHr}h${remainMin}m${remainSec}s`
  } catch {
    return ''
  }
}

function getPriorityInfo(priority: number) {
  const p = priority || 5
  if (p <= 2) return { label: 'P1', color: 'bg-red-100 text-red-700', border: 'border-l-red-500' }
  if (p <= 4) return { label: 'P2', color: 'bg-amber-100 text-amber-700', border: 'border-l-amber-400' }
  if (p <= 6) return { label: 'P3', color: 'bg-slate-100 text-slate-600', border: 'border-l-slate-300' }
  return { label: 'P4', color: 'bg-blue-50 text-blue-600', border: 'border-l-blue-400' }
}

function getKindBadge(kind: string) {
  switch (kind) {
    case 'chat': return 'bg-blue-100 text-blue-700'
    case 'project': return 'bg-purple-100 text-purple-700'
    case 'scheduled': return 'bg-amber-100 text-amber-700'
    case 'subtask': return 'bg-slate-100 text-slate-600'
    default: return 'bg-slate-100 text-slate-600'
  }
}

function StatusIcon({ status, className }: { status: string; className?: string }) {
  const cls = cn('shrink-0', className)
  switch (status) {
    case 'completed':
    case 'done':
      return <CheckCircle2 className={cn('text-emerald-500', cls)} />
    case 'running':
      return <Circle className={cn('text-blue-500 animate-pulse', cls)} />
    case 'pending':
      return <Clock className={cn('text-slate-400', cls)} />
    case 'failed':
    case 'error':
      return <XCircle className={cn('text-red-500', cls)} />
    case 'cancelled':
      return <XCircle className={cn('text-muted-foreground/40', cls)} />
    default:
      return <Circle className={cn('text-muted-foreground/40', cls)} />
  }
}

// ─── 主页面组件 ─────────────────────────────────────

export function Tasks() {
  const [tasks, setTasks] = useState<TaskInfo[]>([])
  const [stats, setStats] = useState<TaskStats | null>(null)
  const [projects, setProjects] = useState<ProjectInfo[]>([])
  const [loading, setLoading] = useState(true)
  const [viewMode, setViewMode] = useState<'kanban' | 'list'>('list')
  const [statusFilter, setStatusFilter] = useState<string>('all')
  const [kindFilter, setKindFilter] = useState<string>('all')
  const [projectFilter, setProjectFilter] = useState<string>('all')
  const [searchTerm, setSearchTerm] = useState('')
  const [timeRange, setTimeRange] = useState<string>('all')
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(10)
  const [total, setTotal] = useState(0)
  const [gotoPage, setGotoPage] = useState('')
  const [selectedTask, setSelectedTask] = useState<TaskInfo | null>(null)
  const [showCreateInput, setShowCreateInput] = useState(false)
  const [newTaskMessage, setNewTaskMessage] = useState('')
  const [newTaskPriority, setNewTaskPriority] = useState(5)
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const searchTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const loadData = useCallback(async () => {
    try {
      const status = statusFilter === 'all' ? undefined : statusFilter
      const kind = kindFilter === 'all' ? undefined : kindFilter
      const project = projectFilter === 'all' ? undefined : projectFilter

      // 计算时间范围
      let createdAfter: string | undefined
      let createdBefore: string | undefined
      if (timeRange !== 'all') {
        const now = new Date()
        const today = new Date(now.getFullYear(), now.getMonth(), now.getDate())
        switch (timeRange) {
          case 'today':
            createdAfter = today.toISOString()
            break
          case 'week':
            createdAfter = new Date(today.getTime() - 7 * 86400000).toISOString()
            break
          case 'month':
            createdAfter = new Date(today.getTime() - 30 * 86400000).toISOString()
            break
          case 'this_month':
            createdAfter = new Date(now.getFullYear(), now.getMonth(), 1).toISOString()
            break
          case 'last_month':
            createdAfter = new Date(now.getFullYear(), now.getMonth() - 1, 1).toISOString()
            createdBefore = new Date(now.getFullYear(), now.getMonth(), 1).toISOString()
            break
        }
      }

      if (viewMode === 'list') {
        const [taskData, statsData, projData] = await Promise.all([
          api.getTasksPaginated({ status, kind, project, search: searchTerm || undefined, created_after: createdAfter, created_before: createdBefore, page, page_size: pageSize }),
          api.getTaskStats(),
          api.getProjects(),
        ])
        setTasks(taskData.items)
        setTotal(taskData.total)
        setStats(statsData)
        setProjects(projData.items || [])
      } else {
        const [taskData, statsData, projData] = await Promise.all([
          api.getRecentTasks(168, kind, status, project),
          api.getTaskStats(),
          api.getProjects(),
        ])
        setTasks(taskData)
        setStats(statsData)
        setProjects(projData.items || [])
      }
    } catch {
      // ignore
    } finally {
      setLoading(false)
    }
  }, [statusFilter, kindFilter, projectFilter, searchTerm, timeRange, page, pageSize, viewMode])

  useEffect(() => {
    setLoading(true)
    loadData()
    timerRef.current = setInterval(loadData, REFRESH_MS)
    return () => { if (timerRef.current) clearInterval(timerRef.current) }
  }, [loadData])

  // 创建任务
  const handleCreate = async () => {
    if (!newTaskMessage.trim()) return
    try {
      await api.createTask({ message: newTaskMessage.trim(), kind: 'chat', priority: newTaskPriority })
      setNewTaskMessage('')
      setShowCreateInput(false)
      setNewTaskPriority(5)
      loadData()
    } catch { /* ignore */ }
  }

  // 任务操作
  const handleRetry = async (id: string) => {
    try { await api.retryTask(id); loadData() } catch { /* ignore */ }
  }
  const handleCancel = async (id: string) => {
    try { await api.cancelTask(id); loadData() } catch { /* ignore */ }
  }

  // 搜索防抖
  const handleSearchChange = (value: string) => {
    if (searchTimerRef.current) clearTimeout(searchTimerRef.current)
    searchTimerRef.current = setTimeout(() => {
      setSearchTerm(value)
      setPage(1)
    }, 300)
  }

  // 筛选变更重置页码
  const handleStatusChange = (v: string) => { setStatusFilter(v); setPage(1) }
  const handleKindChange = (v: string) => { setKindFilter(v); setPage(1) }
  const handleProjectChange = (v: string) => { setProjectFilter(v); setPage(1) }
  const handleTimeRangeChange = (v: string) => { setTimeRange(v); setPage(1) }

  // 按状态分组（看板用）
  const tasksByStatus = useMemo(() => {
    const groups: Record<string, TaskInfo[]> = {}
    for (const col of STATUS_COLUMNS) {
      groups[col.key] = []
    }
    for (const t of tasks) {
      const s = t.status === 'done' ? 'completed' : t.status
      if (groups[s]) groups[s].push(t)
      else if (groups['failed'] && (s === 'error')) groups['failed'].push(t)
    }
    // 按优先级排序
    for (const key of Object.keys(groups)) {
      groups[key].sort((a, b) => (a.priority || 5) - (b.priority || 5))
    }
    return groups
  }, [tasks])

  // 成功率计算
  const successRate = useMemo(() => {
    if (!stats || stats.total === 0) return 0
    const completed = stats.by_status['completed'] || 0
    const failed = stats.by_status['failed'] || 0
    const finished = completed + failed
    return finished > 0 ? Math.round((completed / finished) * 100) : 0
  }, [stats])

  return (
    <div className="space-y-6 p-6">
      {/* 头部 */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold">任务管理</h2>
          <p className="text-sm text-muted-foreground">管理和监控所有 Agent 任务</p>
        </div>
        <button
          onClick={() => setShowCreateInput(!showCreateInput)}
          className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm text-primary-foreground hover:bg-primary/90 transition-colors"
        >
          <Plus className="h-4 w-4" /> 新建任务
        </button>
      </div>

      {/* 内联创建表单 */}
      {showCreateInput && (
        <div className="rounded-xl border bg-card p-4 space-y-3">
          <input
            value={newTaskMessage}
            onChange={(e) => setNewTaskMessage(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleCreate()}
            placeholder="输入任务描述..."
            className="w-full rounded-lg border bg-background px-3 py-2 text-sm outline-none placeholder:text-muted-foreground/50 focus:ring-2 focus:ring-primary/20"
            autoFocus
          />
          <div className="flex items-center gap-3">
            <select
              value={newTaskPriority}
              onChange={(e) => setNewTaskPriority(Number(e.target.value))}
              className="h-8 text-xs rounded border bg-background px-2"
            >
              <option value={1}>P1 紧急</option>
              <option value={3}>P2 高</option>
              <option value={5}>P3 普通</option>
              <option value={8}>P4 低</option>
            </select>
            <button
              onClick={handleCreate}
              className="h-8 px-4 text-xs rounded-lg bg-primary text-primary-foreground hover:bg-primary/90"
            >
              创建
            </button>
            <button
              onClick={() => { setShowCreateInput(false); setNewTaskMessage('') }}
              className="h-8 px-4 text-xs rounded-lg border text-muted-foreground hover:bg-accent"
            >
              取消
            </button>
          </div>
        </div>
      )}

      {/* 统计卡片 */}
      <div className="grid grid-cols-4 gap-4">
        <StatCard label="总任务" value={stats?.total ?? 0} icon={<ClipboardList className="h-5 w-5" />} />
        <StatCard label="执行中" value={stats?.by_status?.running ?? 0} icon={<Circle className="h-5 w-5 animate-pulse" />} accent="text-blue-500" />
        <StatCard label="已完成" value={stats?.by_status?.completed ?? 0} icon={<CheckCircle2 className="h-5 w-5" />} accent="text-emerald-500" />
        <StatCard label="成功率" value={`${successRate}%`} icon={<CheckCircle2 className="h-5 w-5" />} accent={successRate >= 80 ? 'text-emerald-500' : successRate >= 50 ? 'text-amber-500' : 'text-red-500'} />
      </div>

      {/* 工具栏 */}
      <div className="flex items-center gap-2 flex-wrap">
        <div className="flex rounded-lg border bg-card overflow-hidden">
          <button
            onClick={() => setViewMode('kanban')}
            className={cn(
              'flex items-center gap-1.5 px-3 py-1.5 text-xs transition-colors',
              viewMode === 'kanban' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-accent',
            )}
          >
            <LayoutGrid className="h-3.5 w-3.5" /> 看板
          </button>
          <button
            onClick={() => setViewMode('list')}
            className={cn(
              'flex items-center gap-1.5 px-3 py-1.5 text-xs transition-colors',
              viewMode === 'list' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-accent',
            )}
          >
            <List className="h-3.5 w-3.5" /> 列表
          </button>
        </div>
        {/* 搜索框 */}
        <div className="relative">
          <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground/50" />
          <input
            type="text"
            placeholder="搜索任务..."
            defaultValue={searchTerm}
            onChange={(e) => handleSearchChange(e.target.value)}
            className="h-8 w-[240px] rounded-lg border bg-card pl-8 pr-3 text-xs text-foreground outline-none placeholder:text-muted-foreground/50 focus:ring-2 focus:ring-primary/20"
          />
        </div>
        <select
          value={statusFilter}
          onChange={(e) => handleStatusChange(e.target.value)}
          className="h-8 text-xs rounded-lg border bg-card px-2 text-muted-foreground"
        >
          <option value="all">全部状态</option>
          <option value="pending">待执行</option>
          <option value="running">执行中</option>
          <option value="completed">已完成</option>
          <option value="failed">失败</option>
        </select>
        <select
          value={kindFilter}
          onChange={(e) => handleKindChange(e.target.value)}
          className="h-8 text-xs rounded-lg border bg-card px-2 text-muted-foreground"
        >
          <option value="all">全部类型</option>
          <option value="chat">对话</option>
          <option value="project">项目</option>
          <option value="scheduled">定时</option>
          <option value="subtask">子任务</option>
        </select>
        <select
          value={projectFilter}
          onChange={(e) => handleProjectChange(e.target.value)}
          className="h-8 text-xs rounded-lg border bg-card px-2 text-muted-foreground max-w-[150px]"
        >
          <option value="all">全部项目</option>
          {projects.map(p => (
            <option key={p.id} value={p.id}>{p.title}</option>
          ))}
        </select>
        <select
          value={timeRange}
          onChange={(e) => handleTimeRangeChange(e.target.value)}
          className="h-8 text-xs rounded-lg border bg-card px-2 text-muted-foreground"
        >
          <option value="all">全部时间</option>
          <option value="today">今天</option>
          <option value="week">近 7 天</option>
          <option value="month">近 30 天</option>
          <option value="this_month">本月</option>
          <option value="last_month">上月</option>
        </select>
        <button
          onClick={loadData}
          className="ml-auto flex items-center gap-1.5 rounded-lg border bg-card px-3 py-1.5 text-xs text-muted-foreground hover:bg-accent transition-colors"
        >
          <RefreshCw className={cn('h-3.5 w-3.5', loading && 'animate-spin')} /> 刷新
        </button>
      </div>

      {/* 内容区 */}
      {loading && tasks.length === 0 ? (
        <div className="flex items-center justify-center py-20">
          <RefreshCw className="h-6 w-6 animate-spin text-muted-foreground" />
        </div>
      ) : tasks.length === 0 ? (
        <div className="rounded-xl border bg-card p-16 text-center">
          <ClipboardList className="mx-auto h-12 w-12 text-muted-foreground/30" />
          <p className="mt-4 text-muted-foreground">暂无任务</p>
          <p className="mt-1 text-sm text-muted-foreground/60">
            点击「新建任务」开始创建，或在对话中让 Agent 自动创建
          </p>
        </div>
      ) : viewMode === 'kanban' ? (
        <KanbanView tasksByStatus={tasksByStatus} onSelect={setSelectedTask} onRetry={handleRetry} />
      ) : (
        <ListView
          tasks={tasks}
          page={page}
          pageSize={pageSize}
          total={total}
          onPageChange={setPage}
          onPageSizeChange={(s) => { setPageSize(s); setPage(1) }}
          onSelect={setSelectedTask}
          onRetry={handleRetry}
        />
      )}

      {/* 任务详情抽屉 */}
      {selectedTask && (
        <TaskDetailDrawer
          task={selectedTask}
          onClose={() => setSelectedTask(null)}
          onRetry={handleRetry}
          onCancel={handleCancel}
          onRefresh={loadData}
        />
      )}
    </div>
  )
}

// ─── 统计卡片 ──────────────────────────────────────

function StatCard({ label, value, icon, accent }: {
  label: string; value: string | number; icon: React.ReactNode; accent?: string
}) {
  return (
    <div className="rounded-xl border bg-card p-4 text-center">
      <div className={cn('mx-auto mb-2 flex h-10 w-10 items-center justify-center rounded-lg bg-muted/50', accent || 'text-muted-foreground')}>
        {icon}
      </div>
      <div className={cn('text-2xl font-bold transition-all duration-300', accent)}>{value}</div>
      <div className="text-xs text-muted-foreground">{label}</div>
    </div>
  )
}

// ─── 看板视图 ──────────────────────────────────────

function KanbanView({ tasksByStatus, onSelect, onRetry }: {
  tasksByStatus: Record<string, TaskInfo[]>
  onSelect: (t: TaskInfo) => void
  onRetry: (id: string) => void
}) {
  return (
    <div className="grid grid-cols-4 gap-4">
      {STATUS_COLUMNS.map((col) => {
        const items = tasksByStatus[col.key] || []
        return (
          <div key={col.key} className="flex flex-col rounded-xl bg-muted/30">
            {/* 列头 */}
            <div className="flex items-center gap-2 rounded-t-xl bg-muted/50 px-3 py-2">
              <StatusIcon status={col.key} className="h-3.5 w-3.5" />
              <span className="text-xs font-medium">{col.label}</span>
              <span className="ml-auto rounded-full bg-background border px-1.5 py-0.5 text-[10px] text-muted-foreground">
                {items.length}
              </span>
            </div>
            {/* 卡片列表 */}
            <div className="flex-1 space-y-2 p-2 min-h-[120px]">
              {items.length === 0 ? (
                <div className="flex items-center justify-center py-8 text-xs text-muted-foreground/50">
                  暂无任务
                </div>
              ) : (
                items.map((task) => (
                  <KanbanCard key={task.id} task={task} onClick={() => onSelect(task)} onRetry={onRetry} />
                ))
              )}
            </div>
          </div>
        )
      })}
    </div>
  )
}

function KanbanCard({ task, onClick, onRetry }: {
  task: TaskInfo; onClick: () => void; onRetry: (id: string) => void
}) {
  const prio = getPriorityInfo(task.priority)
  const progress = task.progress || 0
  const showProgress = task.status === 'running' || progress > 0

  return (
    <div
      onClick={onClick}
      className={cn(
        'cursor-pointer rounded-lg border bg-card p-3 shadow-sm transition-all',
        'hover:shadow-md',
        prio.border, 'border-l-4',
      )}
    >
      {/* 优先级 + 来源 */}
      <div className="flex items-center gap-1.5 mb-1.5">
        <span className={cn('rounded-full px-1.5 py-0.5 text-[10px] font-medium', prio.color)}>
          {prio.label}
        </span>
        {task.kind && (
          <span className={cn('rounded px-1 py-0.5 text-[9px]', getKindBadge(task.kind))}>
            {task.kind}
          </span>
        )}
        <span className="ml-auto text-[10px] text-muted-foreground/70">
          {formatDuration(task.created_at, task.completed_at)}
        </span>
      </div>
      {/* 标题 */}
      <p className="text-sm font-medium leading-snug line-clamp-2 mb-1">
        {task.message || '(无描述)'}
      </p>
      {/* 项目名 */}
      {task.project_title && (
        <div className="flex items-center gap-1 mb-1">
          <FolderIcon className="h-2.5 w-2.5 text-purple-400 shrink-0" />
          <span className="text-[10px] text-purple-600 truncate">{task.project_title}</span>
        </div>
      )}
      {/* 进度条 */}
      {showProgress && (
        <div className="flex items-center gap-1.5 mt-2">
          <div className="flex-1 h-1.5 rounded-full bg-muted overflow-hidden">
            <div
              className={cn(
                'h-full rounded-full transition-all duration-300',
                task.status === 'completed' ? 'bg-emerald-500' : task.status === 'failed' ? 'bg-red-500' : 'bg-blue-500',
              )}
              style={{ width: `${Math.min(100, progress)}%` }}
            />
          </div>
          <span className="text-[9px] text-muted-foreground w-7 text-right">{progress}%</span>
        </div>
      )}
      {/* 底部信息 */}
      <div className="flex items-center gap-2 mt-2 text-[10px] text-muted-foreground/70">
        <Clock className="h-2.5 w-2.5" />
        <span>{formatTime(task.created_at)}</span>
        {task.token_used > 0 && (
          <span className="ml-auto">{task.token_used.toLocaleString()} tok</span>
        )}
      </div>
      {/* 失败任务：错误摘要 + 重试 */}
      {task.status === 'failed' && task.error_message && (
        <div className="flex items-center gap-1 mt-2 pt-2 border-t border-dashed">
          <AlertTriangle className="h-2.5 w-2.5 text-red-500 shrink-0" />
          <span className="text-[10px] text-red-600 truncate flex-1">{task.error_message}</span>
          <button
            onClick={(e) => { e.stopPropagation(); onRetry(task.id) }}
            className="flex items-center gap-0.5 text-[10px] text-blue-500 hover:underline shrink-0"
          >
            <RotateCcw className="h-2.5 w-2.5" /> 重试
          </button>
        </div>
      )}
    </div>
  )
}

// ─── 列表视图 ──────────────────────────────────────

function buildPageNumbers(current: number, totalPages: number): (number | '...')[] {
  if (totalPages <= 7) return Array.from({ length: totalPages }, (_, i) => i + 1)
  const pages: (number | '...')[] = [1]
  if (current > 3) pages.push('...')
  const start = Math.max(2, current - 1)
  const end = Math.min(totalPages - 1, current + 1)
  for (let i = start; i <= end; i++) pages.push(i)
  if (current < totalPages - 2) pages.push('...')
  pages.push(totalPages)
  return pages
}

function ListView({ tasks, page, pageSize, total, onPageChange, onPageSizeChange, onSelect, onRetry }: {
  tasks: TaskInfo[]
  page: number
  pageSize: number
  total: number
  onPageChange: (p: number) => void
  onPageSizeChange: (s: number) => void
  onSelect: (t: TaskInfo) => void
  onRetry: (id: string) => void
}) {
  const totalPages = Math.max(1, Math.ceil(total / pageSize))
  const pageNumbers = buildPageNumbers(page, totalPages)
  const [gotoPage, setGotoPage] = useState('')

  const handleGoto = () => {
    const p = parseInt(gotoPage, 10)
    if (!isNaN(p) && p >= 1 && p <= totalPages) {
      onPageChange(p)
      setGotoPage('')
    }
  }

  return (
    <div className="rounded-xl border bg-card overflow-hidden">
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b bg-muted/30 text-xs text-muted-foreground">
            <th className="text-left px-3 py-2.5 font-medium w-[40px]">#</th>
            <th className="text-left px-3 py-2.5 font-medium w-[130px]">任务号</th>
            <th className="text-left px-3 py-2.5 font-medium w-[300px]">任务标题</th>
            <th className="text-left px-3 py-2.5 font-medium w-[160px]">项目</th>
            <th className="text-left px-3 py-2.5 font-medium w-[60px]">优先级</th>
            <th className="text-left px-3 py-2.5 font-medium w-[70px]">状态</th>
            <th className="text-left px-3 py-2.5 font-medium w-[50px]">类型</th>
            <th className="text-left px-3 py-2.5 font-medium w-[70px]">进度</th>
            <th className="text-left px-3 py-2.5 font-medium w-[50px]">耗时</th>
            <th className="text-left px-3 py-2.5 font-medium w-[60px]">词元</th>
            <th className="text-left px-3 py-2.5 font-medium w-[100px]">创建时间</th>
            <th className="text-left px-3 py-2.5 font-medium w-[100px]">完成时间</th>
            <th className="text-left px-3 py-2.5 font-medium w-[70px]">操作</th>
          </tr>
        </thead>
        <tbody className="divide-y">
          {tasks.map((task, idx) => {
            const prio = getPriorityInfo(task.priority)
            const seq = (page - 1) * pageSize + idx + 1
            return (
              <tr
                key={task.id}
                className="cursor-pointer hover:bg-accent/50 transition-colors"
                onClick={() => onSelect(task)}
              >
                <td className="px-3 py-2.5 text-xs text-muted-foreground whitespace-nowrap">{seq}</td>
                <td className="px-3 py-2.5 whitespace-nowrap">
                  <span className="text-[10px] font-mono text-muted-foreground" title={task.id}>{task.id}</span>
                </td>
                <td className="px-3 py-2.5 whitespace-nowrap overflow-hidden text-ellipsis">
                  <span className="font-medium block max-w-[300px] overflow-hidden text-ellipsis" title={task.message || undefined}>{task.message || '(无描述)'}</span>
                </td>
                <td className="px-3 py-2.5 whitespace-nowrap">
                  {task.project_title ? (
                    <span className="text-xs font-medium text-foreground overflow-hidden text-ellipsis max-w-[160px] block" title={task.project_title}>{task.project_title}</span>
                  ) : (
                    <span className="text-xs text-muted-foreground">-</span>
                  )}
                </td>
                <td className="px-3 py-2.5 whitespace-nowrap">
                  <span className={cn('rounded-full px-1.5 py-0.5 text-[10px] font-medium', prio.color)}>
                    {prio.label}
                  </span>
                </td>
                <td className="px-3 py-2.5 whitespace-nowrap">
                  <div className="flex items-center gap-1">
                    <StatusIcon status={task.status} className="h-3.5 w-3.5" />
                    <span className="text-xs">{statusLabel(task.status)}</span>
                  </div>
                </td>
                <td className="px-3 py-2.5 whitespace-nowrap">
                  {task.kind && (
                    <span className={cn('rounded px-1 py-0.5 text-[9px]', getKindBadge(task.kind))}>
                      {task.kind}
                    </span>
                  )}
                </td>
                <td className="px-3 py-2.5 whitespace-nowrap">
                  {(task.status === 'running' || (task.progress || 0) > 0) && (
                    <div className="flex items-center gap-1">
                      <div className="w-10 h-1.5 rounded-full bg-muted overflow-hidden">
                        <div
                          className={cn(
                            'h-full rounded-full',
                            task.status === 'completed' ? 'bg-emerald-500' : task.status === 'failed' ? 'bg-red-500' : 'bg-blue-500',
                          )}
                          style={{ width: `${Math.min(100, task.progress || 0)}%` }}
                        />
                      </div>
                      <span className="text-[9px] text-muted-foreground">{task.progress || 0}%</span>
                    </div>
                  )}
                </td>
                <td className="px-3 py-2.5 text-[10px] text-muted-foreground whitespace-nowrap">
                  {formatDuration(task.created_at, task.completed_at)}
                </td>
                <td className="px-3 py-2.5 text-[10px] text-muted-foreground whitespace-nowrap">
                  {task.token_used > 0 ? task.token_used.toLocaleString() : '-'}
                </td>
                <td className="px-3 py-2.5 text-[10px] text-muted-foreground whitespace-nowrap">
                  {new Date(task.created_at).toLocaleDateString('zh-CN', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' })}
                </td>
                <td className="px-3 py-2.5 text-[10px] text-muted-foreground whitespace-nowrap">
                  {task.completed_at ? new Date(task.completed_at).toLocaleDateString('zh-CN', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' }) : '-'}
                </td>
                <td className="px-3 py-2.5 whitespace-nowrap">
                  <div className="flex items-center gap-1">
                    {task.status === 'failed' && (
                      <button
                        onClick={(e) => { e.stopPropagation(); onRetry(task.id) }}
                        className="rounded px-1.5 py-0.5 text-[10px] text-blue-600 hover:bg-blue-50 transition-colors"
                      >
                        重试
                      </button>
                    )}
                    <ChevronRight className="h-3 w-3 text-muted-foreground/50" />
                  </div>
                </td>
              </tr>
            )
          })}
        </tbody>
      </table>

      {/* 分页栏 */}
      <div className="flex items-center justify-between border-t px-4 py-2.5 text-xs text-muted-foreground">
        <div className="flex items-center gap-3">
          <span>共 {total} 条</span>
          <select
            value={pageSize}
            onChange={(e) => onPageSizeChange(Number(e.target.value))}
            className="h-6 rounded border bg-background px-1.5 text-xs"
          >
            <option value={10}>10 条/页</option>
            <option value={20}>20 条/页</option>
            <option value={50}>50 条/页</option>
            <option value={100}>100 条/页</option>
          </select>
        </div>
        <div className="flex items-center gap-1">
          <button
            onClick={() => onPageChange(1)}
            disabled={page === 1}
            className="rounded p-1 hover:bg-accent disabled:opacity-30 disabled:cursor-not-allowed"
            title="首页"
          >
            <ChevronsLeft className="h-3.5 w-3.5" />
          </button>
          <button
            onClick={() => onPageChange(Math.max(1, page - 1))}
            disabled={page === 1}
            className="rounded p-1 hover:bg-accent disabled:opacity-30 disabled:cursor-not-allowed"
            title="上一页"
          >
            <ChevronRight className="h-3.5 w-3.5 rotate-180" />
          </button>
          {pageNumbers.map((n, i) =>
            n === '...' ? (
              <span key={`e${i}`} className="px-1 text-muted-foreground/50">...</span>
            ) : (
              <button
                key={n}
                onClick={() => onPageChange(n)}
                className={cn(
                  'min-w-[24px] rounded px-1 py-0.5 text-xs',
                  n === page ? 'bg-primary text-primary-foreground' : 'hover:bg-accent',
                )}
              >
                {n}
              </button>
            )
          )}
          <button
            onClick={() => onPageChange(Math.min(totalPages, page + 1))}
            disabled={page === totalPages}
            className="rounded p-1 hover:bg-accent disabled:opacity-30 disabled:cursor-not-allowed"
            title="下一页"
          >
            <ChevronRight className="h-3.5 w-3.5" />
          </button>
          <button
            onClick={() => onPageChange(totalPages)}
            disabled={page === totalPages}
            className="rounded p-1 hover:bg-accent disabled:opacity-30 disabled:cursor-not-allowed"
            title="末页"
          >
            <ChevronsRight className="h-3.5 w-3.5" />
          </button>
          {totalPages > 5 && (
            <div className="ml-2 flex items-center gap-1">
              <input
                type="text"
                value={gotoPage}
                onChange={(e) => setGotoPage(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleGoto()}
                placeholder="页码"
                className="h-6 w-12 rounded border bg-background px-1.5 text-xs text-center outline-none"
              />
              <button
                onClick={handleGoto}
                className="rounded px-1.5 py-0.5 hover:bg-accent text-[10px]"
              >
                跳转
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

function statusLabel(status: string): string {
  switch (status) {
    case 'pending': return '待执行'
    case 'running': return '执行中'
    case 'completed':
    case 'done': return '已完成'
    case 'failed':
    case 'error': return '失败'
    case 'cancelled': return '已取消'
    default: return status
  }
}

// ─── 任务详情抽屉 ──────────────────────────────────

function TaskDetailDrawer({ task, onClose, onRetry, onCancel, onRefresh }: {
  task: TaskInfo
  onClose: () => void
  onRetry: (id: string) => void
  onCancel: (id: string) => void
  onRefresh: () => void
}) {
  const [detail, setDetail] = useState<TaskInfo | null>(null)
  const [events, setEvents] = useState<TaskEvent[]>([])
  const [loadingDetail, setLoadingDetail] = useState(true)
  const [subtasksExpanded, setSubtasksExpanded] = useState(true)

  useEffect(() => {
    setLoadingDetail(true)
    Promise.all([
      api.getTaskDetail(task.id),
      api.getTaskEvents(task.id),
    ]).then(([d, e]) => {
      setDetail(d)
      setEvents(e)
    }).catch(() => {
      // ignore
    }).finally(() => setLoadingDetail(false))
  }, [task.id])

  const handleRetry = async () => {
    await onRetry(task.id)
    onRefresh()
  }
  const handleCancel = async () => {
    await onCancel(task.id)
    onRefresh()
  }

  const prio = getPriorityInfo(task.priority)

  return (
    <div className="fixed inset-0 z-50">
      {/* 背景 */}
      <div className="absolute inset-0 bg-black/20" onClick={onClose} />
      {/* 抽屉 */}
      <div className="absolute right-0 top-0 bottom-0 w-[480px] max-w-full bg-background border-l shadow-xl flex flex-col animate-in slide-in-from-right duration-200">
        {/* 头部 */}
        <div className="flex items-center gap-3 border-b px-5 py-4 shrink-0">
          <button onClick={onClose} className="rounded-md p-1 hover:bg-accent transition-colors">
            <ChevronRight className="h-4 w-4 rotate-180" />
          </button>
          <div className="flex-1 min-w-0">
            <h3 className="text-sm font-semibold truncate">{task.message || '(无描述)'}</h3>
            <div className="flex items-center gap-2 mt-0.5 text-xs text-muted-foreground">
              <span className={cn('rounded-full px-1.5 py-0.5 text-[10px] font-medium', prio.color)}>{prio.label}</span>
              <span>·</span>
              <span>{task.kind}</span>
              <span>·</span>
              <span>创建于 {formatTime(task.created_at)}</span>
            </div>
          </div>
          <button onClick={onClose} className="rounded-md p-1 hover:bg-accent transition-colors">
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* 内容 */}
        <div className="flex-1 overflow-y-auto">
          {loadingDetail ? (
            <div className="flex items-center justify-center py-16">
              <RefreshCw className="h-5 w-5 animate-spin text-muted-foreground" />
            </div>
          ) : (
            <div className="space-y-5 p-5">
              {/* 状态概览 */}
              <div className="flex items-center gap-3 rounded-lg border bg-card p-3">
                <StatusIcon status={task.status} className="h-5 w-5" />
                <div>
                  <div className="text-sm font-medium">{statusLabel(task.status)}</div>
                  <div className="text-xs text-muted-foreground">
                    {task.status === 'running' && `进度 ${task.progress || 0}%`}
                    {task.status === 'failed' && task.error_type && `错误类型: ${task.error_type}`}
                    {task.status === 'completed' && `耗时 ${formatDuration(task.created_at, task.completed_at)}`}
                  </div>
                </div>
                {task.token_used > 0 && (
                  <span className="ml-auto text-xs text-muted-foreground">
                    {task.token_used.toLocaleString()} tokens
                  </span>
                )}
              </div>

              {/* 进度条（执行中时） */}
              {task.status === 'running' && (
                <div className="space-y-1.5">
                  <div className="flex justify-between text-xs text-muted-foreground">
                    <span>执行进度</span>
                    <span>{task.progress || 0}%</span>
                  </div>
                  <div className="h-2 rounded-full bg-muted overflow-hidden">
                    <div
                      className="h-full rounded-full bg-blue-500 transition-all duration-300"
                      style={{ width: `${Math.min(100, task.progress || 0)}%` }}
                    />
                  </div>
                </div>
              )}

              {/* 错误信息 */}
              {task.status === 'failed' && task.error_message && (
                <div className="rounded-lg border border-red-200 bg-red-50 p-3">
                  <div className="flex items-center gap-1.5 text-xs font-medium text-red-700">
                    <AlertTriangle className="h-3.5 w-3.5" />
                    {task.error_type || '错误'}
                  </div>
                  <p className="mt-1 text-xs text-red-600">{task.error_message}</p>
                  {task.retry_count > 0 && (
                    <p className="mt-1 text-[10px] text-red-500">
                      已重试 {task.retry_count}/{task.max_retries} 次
                    </p>
                  )}
                </div>
              )}

              {/* 状态时间线 */}
              <div>
                <h4 className="text-xs font-medium text-muted-foreground mb-3">状态时间线</h4>
                {events.length === 0 ? (
                  <p className="text-xs text-muted-foreground/60">暂无事件记录</p>
                ) : (
                  <div className="relative ml-1.5 border-l-2 border-muted pl-4 space-y-3">
                    {events.map((evt) => (
                      <div key={evt.id} className="relative">
                        {/* 圆点 */}
                        <div className={cn(
                          'absolute -left-[21px] top-0.5 h-2.5 w-2.5 rounded-full border-2 border-background',
                          evt.to_status === 'completed' ? 'bg-emerald-500' :
                          evt.to_status === 'running' ? 'bg-blue-500' :
                          evt.to_status === 'failed' ? 'bg-red-500' :
                          evt.type === 'progress' ? 'bg-blue-400' :
                          'bg-slate-300',
                        )} />
                        <div className="flex items-baseline gap-2">
                          <span className="text-[10px] text-muted-foreground shrink-0">
                            {new Date(evt.created_at).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}
                          </span>
                          <span className="text-xs">
                            {evt.message || `${evt.from_status || '?'} → ${evt.to_status || '?'}`}
                          </span>
                        </div>
                        {evt.token_used > 0 && (
                          <span className="text-[10px] text-muted-foreground/60">
                            {evt.token_used.toLocaleString()} tokens
                          </span>
                        )}
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* 子任务 */}
              {detail?.subtasks && detail.subtasks.length > 0 && (
                <div>
                  <button
                    onClick={() => setSubtasksExpanded(!subtasksExpanded)}
                    className="flex items-center gap-1.5 text-xs font-medium text-muted-foreground mb-2 hover:text-foreground transition-colors"
                  >
                    <ChevronRight className={cn('h-3 w-3 transition-transform', subtasksExpanded && 'rotate-90')} />
                    子任务 ({detail.subtasks.length})
                  </button>
                  {subtasksExpanded && (
                    <div className="space-y-1 ml-1 border-l-2 border-muted pl-3">
                      {detail.subtasks.map((st) => (
                        <div key={st.id} className="flex items-center gap-2 py-1.5">
                          <StatusIcon status={st.status} className="h-3 w-3" />
                          <span className="text-xs truncate flex-1">{st.message || '(无描述)'}</span>
                          <span className="text-[10px] text-muted-foreground">
                            {formatDuration(st.created_at, st.completed_at)}
                          </span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {/* 结果 */}
              {detail?.result && (
                <div>
                  <h4 className="text-xs font-medium text-muted-foreground mb-2 flex items-center gap-1.5">
                    <FileText className="h-3 w-3" /> 执行结果
                  </h4>
                  <div className="rounded-lg border bg-card p-3 text-xs text-muted-foreground whitespace-pre-wrap">
                    {detail.result}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>

        {/* 底部操作区 */}
        <div className="border-t bg-background p-4 shrink-0">
          <div className="flex items-center gap-2">
            {(task.status === 'pending' || task.status === 'running') && (
              <button
                onClick={handleCancel}
                className="flex items-center gap-1.5 rounded-lg border px-3 py-1.5 text-xs text-muted-foreground hover:bg-accent transition-colors"
              >
                <Square className="h-3 w-3" /> 取消任务
              </button>
            )}
            {task.status === 'failed' && (
              <button
                onClick={handleRetry}
                className="flex items-center gap-1.5 rounded-lg bg-blue-500 px-3 py-1.5 text-xs text-white hover:bg-blue-600 transition-colors"
              >
                <RotateCcw className="h-3 w-3" /> 重试
              </button>
            )}
            {task.status === 'pending' && (
              <button
                onClick={async () => {
                  try {
                    await api.executeTask(task.id)
                    onRefresh()
                  } catch { /* ignore */ }
                }}
                className="flex items-center gap-1.5 rounded-lg bg-primary px-3 py-1.5 text-xs text-primary-foreground hover:bg-primary/90 transition-colors"
              >
                <Play className="h-3 w-3" /> 开始执行
              </button>
            )}
            {task.status === 'running' && (
              <span className="flex items-center gap-1.5 rounded-lg bg-blue-50 px-3 py-1.5 text-xs text-blue-600">
                <Circle className="h-2 w-2 animate-pulse fill-blue-500" /> 执行中...
              </span>
            )}
            <span className="ml-auto text-[10px] text-muted-foreground">
              ID: {task.id}
            </span>
          </div>
        </div>
      </div>
    </div>
  )
}
