// Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
// Copyright: (c) <opensource@openchiip.com>
// Generated By : OpenChiip
// Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
// This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

import { useMemo } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { toast } from 'sonner'
import { Wrench, Bot, Boxes, RefreshCw, Cpu } from 'lucide-react'
import { api } from '@/lib/api'
import type { ToolItem } from '@/lib/api'
import { ToolCard } from '@/components/tools/ToolCard'
import { Button, StatusBadge, HealthDot, ToolIcon } from '@/components/tools/ui'

export function Tools() {
  const queryClient = useQueryClient()

  const { data: tools, isLoading } = useQuery({
    queryKey: ['tools'],
    queryFn: api.getTools,
    // 安装中轮询：任一工具处于 installing 状态时每 3s 自动刷新
    refetchInterval: (query) => {
      const list = query.state.data as ToolItem[] | undefined
      const anyInstalling = list?.some(
        (t) => t.status === 'installing' || t.installing,
      )
      return anyInstalling ? 3000 : false
    },
  })

  const reloadMutation = useMutation({
    mutationFn: api.reloadPlatformTools,
    onSuccess: (res) => {
      queryClient.invalidateQueries({ queryKey: ['tools'] })
      if (res && res.success === false) {
        toast.error(res.error || '重载失败')
        return
      }
      toast.success('平台工具已重载')
    },
    onError: (e: Error) => toast.error(e.message),
  })

  const groups = useMemo(() => {
    const list = tools ?? []
    const aiAgent = list.filter((t) => t.category === 'ai-agent')
    const mcp = list.filter((t) => t.category === 'mcp')
    const other = list.filter((t) => t.category !== 'ai-agent' && t.category !== 'mcp')
    return { aiAgent, mcp, other }
  }, [tools])

  return (
    <div className="p-6 space-y-8">
      {/* 顶部标题栏 */}
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h2 className="text-2xl font-bold">工具管理</h2>
          <p className="text-muted-foreground">管理已安装的生产力工具与 AI Agent</p>
        </div>
        <Button
          variant="outline"
          loading={reloadMutation.isPending}
          onClick={() => reloadMutation.mutate()}
        >
          {!reloadMutation.isPending && <RefreshCw className="h-3.5 w-3.5" />}
          重载平台工具
        </Button>
      </div>

      {isLoading ? (
        <div className="rounded-xl border bg-card p-10 text-center text-muted-foreground">
          <RefreshCw className="mx-auto mb-3 h-8 w-8 animate-spin" />
          加载中...
        </div>
      ) : (
        <>
          {/* ── AI Agent 工具 ─────────────────────────────── */}
          <Section
            icon={<Bot className="h-4 w-4 text-primary" />}
            title="AI Agent 工具"
            count={groups.aiAgent.length}
          >
            {groups.aiAgent.length === 0 ? (
              <EmptyHint text="暂无 AI Agent 工具" />
            ) : (
              <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
                {groups.aiAgent.map((tool) => (
                  <ToolCard key={tool.key} tool={tool} />
                ))}
              </div>
            )}
          </Section>

          {/* ── MCP 工具 ──────────────────────────────────── */}
          <Section
            icon={<Boxes className="h-4 w-4 text-primary" />}
            title="MCP 工具"
            count={groups.mcp.length}
          >
            {groups.mcp.length === 0 ? (
              <EmptyHint text="暂无已注册 MCP 工具" />
            ) : (
              <div className="grid gap-3">
                {groups.mcp.map((tool) => (
                  <McpRow key={tool.key} tool={tool} />
                ))}
              </div>
            )}
          </Section>

          {/* ── 其他工具（builtin / dev）────────────────────── */}
          <Section
            icon={<Cpu className="h-4 w-4 text-primary" />}
            title="其他工具"
            count={groups.other.length}
          >
            {groups.other.length === 0 ? (
              <EmptyHint text="暂无其他工具" />
            ) : (
              <div className="grid gap-2">
                {groups.other.map((tool) => (
                  <OtherRow key={tool.key} tool={tool} />
                ))}
              </div>
            )}
          </Section>
        </>
      )}
    </div>
  )
}

// ── 分组容器 ───────────────────────────────────────────────
function Section({
  icon,
  title,
  count,
  children,
}: {
  icon: React.ReactNode
  title: string
  count: number
  children: React.ReactNode
}) {
  return (
    <section className="space-y-3">
      <div className="flex items-center gap-2">
        {icon}
        <h3 className="font-semibold">{title}</h3>
        <span className="rounded-full bg-muted px-2 py-0.5 text-xs text-muted-foreground">
          {count}
        </span>
      </div>
      {children}
    </section>
  )
}

function EmptyHint({ text }: { text: string }) {
  return (
    <div className="rounded-xl border border-dashed bg-muted/20 p-6 text-center">
      <Wrench className="mx-auto mb-2 h-6 w-6 text-muted-foreground" />
      <p className="text-sm text-muted-foreground">{text}</p>
    </div>
  )
}

// ── MCP 工具行（保留 methods 渲染逻辑）─────────────────────
function McpRow({ tool }: { tool: ToolItem }) {
  return (
    <div className="rounded-xl border bg-card p-4">
      <div className="flex items-start gap-3">
        <div className="mt-0.5 flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-lg bg-green-500/10 text-green-600 dark:text-green-400">
          <ToolIcon name={tool.icon} className="h-4 w-4" />
        </div>
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <h4 className="font-medium">{tool.name}</h4>
            <span className="rounded bg-secondary px-1.5 py-0.5 text-xs text-secondary-foreground">
              {tool.category}
            </span>
            {tool.version && (
              <span className="font-mono text-xs text-muted-foreground">v{tool.version}</span>
            )}
          </div>
          <p className="mt-1 text-sm text-muted-foreground">{tool.description}</p>
          {tool.methods && tool.methods.length > 0 && (
            <div className="mt-2 flex flex-wrap gap-1">
              {tool.methods.map((m) => (
                <span key={m} className="rounded bg-muted px-2 py-0.5 font-mono text-xs">
                  {m}
                </span>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// ── 其他工具行（简洁列表）──────────────────────────────────
function OtherRow({ tool }: { tool: ToolItem }) {
  return (
    <div className="flex items-center gap-3 rounded-lg border bg-card px-4 py-2.5">
      <ToolIcon name={tool.icon} className="h-4 w-4 flex-shrink-0 text-muted-foreground" />
      <div className="min-w-0 flex-1">
        <div className="flex items-center gap-2">
          <span className="truncate text-sm font-medium">{tool.name}</span>
          {tool.version && (
            <span className="font-mono text-xs text-muted-foreground">v{tool.version}</span>
          )}
        </div>
        {tool.description && (
          <p className="truncate text-xs text-muted-foreground">{tool.description}</p>
        )}
      </div>
      <div className="flex flex-shrink-0 items-center gap-3">
        <HealthDot healthy={tool.healthy} />
        <StatusBadge status={tool.status} />
      </div>
    </div>
  )
}
