// Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
// Copyright: (c) <opensource@openchiip.com>
// Generated By : OpenChiip
// Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
// This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

/**
 * TurnStatus — Turn 级别的实时状态指示。
 *
 * 借鉴 deepseek-harness 的 TurnStatus 组件：
 * 显示当前 turn 的活动状态 + 计时器。
 */
import { useEffect, useState } from 'react'
import { Loader2 } from 'lucide-react'

interface Props {
  turn: number
  label?: string
}

export function TurnStatus({ turn, label }: Props) {
  const [elapsed, setElapsed] = useState(0)

  useEffect(() => {
    setElapsed(0)
    const timer = setInterval(() => setElapsed((s) => s + 1), 1000)
    return () => clearInterval(timer)
  }, [turn])

  const formatTime = (s: number) => {
    if (s < 60) return `${s}s`
    const m = Math.floor(s / 60)
    return `${m}m ${s % 60}s`
  }

  return (
    <div className="flex items-center gap-2 py-2 px-3 text-sm text-muted-foreground">
      <Loader2 className="h-3.5 w-3.5 animate-spin text-primary" />
      <span className="text-xs">
        {label || '深度潜水中'}
        <span className="ml-1.5 tabular-nums text-primary/70">{formatTime(elapsed)}</span>
      </span>
    </div>
  )
}
