// Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
// Copyright: (c) <opensource@openchiip.com>
// Generated By : OpenChiip
// Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
// This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

import { Routes, Route, Navigate } from 'react-router-dom'
import { Toaster } from 'sonner'
import { Layout } from '@/components/Layout'
import { Dashboard } from '@/pages/Dashboard'
import { Chat } from '@/pages/Chat'
import { Sessions } from '@/pages/Sessions'
import { Skills } from '@/pages/Skills'
import { MetaSkills } from '@/pages/MetaSkills'
import { Commands } from '@/pages/Commands'
import { Tools } from '@/pages/Tools'
import { A2A } from '@/pages/A2A'
import { Memory } from '@/pages/Memory'
import { Activity } from '@/pages/Activity'
import { Settings } from '@/pages/Settings'
import { Monitor } from '@/pages/Monitor'
import { Tasks } from '@/pages/Tasks'
import { Projects } from '@/pages/Projects'
import { LLM } from '@/pages/LLM'
import { RepoCredentials } from '@/pages/RepoCredentials'

export default function App() {
  return (
    <>
      <Toaster position="top-center" richColors closeButton />
      <Routes>
      <Route element={<Layout />}>
        <Route path="/" element={<Navigate to="/chat" replace />} />
        <Route path="/dashboard" element={<Dashboard />} />
        <Route path="/chat" element={<Chat />} />
        <Route path="/chat/:sessionId" element={<Chat />} />
        <Route path="/sessions" element={<Sessions />} />
        <Route path="/skills" element={<Skills />} />
        <Route path="/metaskills" element={<MetaSkills />} />
        <Route path="/commands" element={<Commands />} />
        <Route path="/tools" element={<Tools />} />
        <Route path="/a2a" element={<A2A />} />
        <Route path="/memory" element={<Memory />} />
        <Route path="/activity" element={<Activity />} />
        <Route path="/monitor" element={<Monitor />} />
        <Route path="/tasks" element={<Tasks />} />
        <Route path="/projects" element={<Projects />} />
        <Route path="/llm" element={<LLM />} />
        <Route path="/repo-credentials" element={<RepoCredentials />} />
        <Route path="/settings" element={<Settings />} />
        <Route path="*" element={<Navigate to="/" replace />} />
      </Route>
    </Routes>
    </>
  )
}
