// Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
// Copyright: (c) <opensource@openchiip.com>
// Generated By : OpenChiip
// Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
// This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

import { Outlet, NavLink, useLocation } from 'react-router-dom'
import {
  LayoutDashboard, MessageSquare, ListTree, Puzzle, Brain,
  Terminal, Wrench, Users, Database, Clock, Settings, Menu, X,
  PanelLeftClose, PanelLeftOpen, Bell, User,
  Activity, ClipboardList, FolderKanban, GitBranch
} from 'lucide-react'
import { useState, useEffect } from 'react'
import { toast } from 'sonner'
import { cn } from '@/lib/utils'
import { api } from '@/lib/api'
import type { ModeInfo } from '@/lib/api'
import logoImg from '@/assets/logo.png'

const navItems = [
  { to: '/chat', icon: MessageSquare, label: '对话' },
  { to: '/sessions', icon: ListTree, label: '会话' },
  { to: '/skills', icon: Puzzle, label: '技能' },
  { to: '/metaskills', icon: Brain, label: '元技能' },
  { to: '/commands', icon: Terminal, label: '指令' },
  { to: '/tools', icon: Wrench, label: '工具' },
  { to: '/a2a', icon: Users, label: '协作' },
  { to: '/memory', icon: Database, label: '记忆' },
  { to: '/activity', icon: Clock, label: '活动' },
  { to: '/monitor', icon: Activity, label: '监控' },
  { to: '/projects', icon: FolderKanban, label: '项目' },
  { to: '/tasks', icon: ClipboardList, label: '任务' },
  { to: '/llm', icon: Brain, label: '提供商' },
  { to: '/repo-credentials', icon: GitBranch, label: '仓库凭据' },
  { to: '/dashboard', icon: LayoutDashboard, label: '仪表盘' },
  { to: '/settings', icon: Settings, label: '设置' },
]

// 面包屑页面信息（参考 Vue 端 TopBar pageInfoMap）
const pageInfoMap: Record<string, { title: string; description?: string }> = {
  '/chat':        { title: '对话', description: '与 Agent 智能交互' },
  '/sessions':    { title: '会话', description: '管理对话会话历史' },
  '/skills':      { title: '技能', description: '管理业务执行技能' },
  '/metaskills':  { title: '元技能', description: '管理可复用的基础能力原语' },
  '/commands':    { title: '指令', description: '管理自然语言快捷指令' },
  '/tools':       { title: '工具', description: '管理已安装的生产力工具' },
  '/a2a':         { title: '协作', description: '跨 Agent 调用与授权' },
  '/memory':      { title: '记忆', description: '查看与管理 Agent 记忆' },
  '/activity':    { title: '活动', description: '查看近期操作记录' },
  '/monitor':     { title: '监控', description: 'CPU、内存、磁盘资源监控' },
  '/projects':    { title: '项目管理', description: '管理和监控所有 Agent 项目' },
  '/tasks':       { title: '任务管理', description: '跨项目任务汇总与跟踪' },
  '/llm':         { title: '模型提供商', description: '配置 LLM 模型提供商和模型' },
  '/repo-credentials': { title: '仓库凭据', description: '管理 Git 仓库访问凭据' },
  '/dashboard':   { title: '仪表盘', description: '系统概览' },
  '/settings':    { title: '设置', description: '运行时配置管理' },
}

type RunMode = 'local' | 'collaborative' | 'order'

const MODE_CONFIG: Record<RunMode, { label: string; color: string; bgColor: string; desc: string }> = {
  local:         { label: '本地模式', color: 'text-emerald-600', bgColor: 'bg-emerald-500', desc: '独立运行，不连接平台' },
  collaborative: { label: '平台协同', color: 'text-blue-600',    bgColor: 'bg-blue-500',    desc: '连接平台，双向同步' },
  order:         { label: '接单模式', color: 'text-amber-600',   bgColor: 'bg-amber-500',   desc: '仅处理平台委派任务' },
}

export function Layout() {
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [collapsed, setCollapsed] = useState(false)
  const location = useLocation()

  // Agent 工作模式
  const [agentMode, setAgentMode] = useState<RunMode>('local')
  const [modePanelOpen, setModePanelOpen] = useState(false)
  const [modeConfirmOpen, setModeConfirmOpen] = useState(false)
  const [pendingMode, setPendingMode] = useState<RunMode | null>(null)
  const [switching, setSwitching] = useState(false)

  // 从 API 获取初始模式
  useEffect(() => {
    api.getStatus().then(s => {
      if (s.run_mode && (s.run_mode === 'local' || s.run_mode === 'collaborative' || s.run_mode === 'order')) {
        setAgentMode(s.run_mode)
      }
    }).catch(() => {})
  }, [])

  const requestModeSwitch = (mode: RunMode) => {
    if (mode === agentMode) return
    setPendingMode(mode)
    setModePanelOpen(false)
    setModeConfirmOpen(true)
  }

  const confirmModeSwitch = async () => {
    if (!pendingMode) return
    setSwitching(true)
    try {
      const result = await api.setMode(pendingMode)
      // 检查是否返回错误
      if (result.error) {
        toast.error(result.error)
        setModeConfirmOpen(false)
        setPendingMode(null)
        return
      }
      if (result.run_mode) {
        setAgentMode(result.run_mode as RunMode)
        toast.success(`已切换到${MODE_CONFIG[result.run_mode as RunMode]?.label || result.run_mode}`)
      }
      setModeConfirmOpen(false)
      setPendingMode(null)
    } catch (e) {
      console.error('模式切换失败:', e)
      toast.error('模式切换失败')
    } finally {
      setSwitching(false)
    }
  }

  return (
    <div className="flex h-screen overflow-hidden bg-background">
      {/* Mobile overlay */}
      {sidebarOpen && (
        <div
          className="fixed inset-0 z-40 bg-black/50 lg:hidden"
          onClick={() => setSidebarOpen(false)}
        />
      )}

      {/* Sidebar */}
      <aside
        className={cn(
          'fixed inset-y-0 left-0 z-50 flex flex-col border-r bg-card transition-all duration-200 lg:static lg:translate-x-0',
          collapsed ? 'w-14' : 'w-48',
          sidebarOpen ? 'translate-x-0' : '-translate-x-full',
        )}
      >
        {/* Logo + 收缩按钮 */}
        <div className="flex h-14 items-center border-b-0 px-3 shrink-0">
          <img src={logoImg} alt="OpenChiip" className="h-8 w-8 rounded-lg object-cover shrink-0" />
          {!collapsed && (
            <div className="ml-2 overflow-hidden">
              <h1 className="text-sm font-semibold whitespace-nowrap">OpenChiip</h1>
            </div>
          )}
          {/* 收缩/展开切换按钮 */}
          <button
            onClick={() => setCollapsed(c => !c)}
            className={cn(
              'ml-auto flex items-center justify-center rounded-md p-1 text-muted-foreground hover:bg-accent hover:text-foreground transition-colors shrink-0',
              collapsed && 'ml-auto',
            )}
            title={collapsed ? '展开菜单' : '收起菜单'}
          >
            {collapsed ? <PanelLeftOpen className="h-4 w-4" /> : <PanelLeftClose className="h-4 w-4" />}
          </button>
          {/* 移动端关闭按钮 */}
          <button
            className="lg:hidden ml-1"
            onClick={() => setSidebarOpen(false)}
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Navigation */}
        <nav className="flex-1 overflow-y-auto p-2">
          {navItems.map((item) => {
            const isActive = location.pathname.startsWith(item.to)
            return (
              <NavLink
                key={item.to}
                to={item.to}
                onClick={() => setSidebarOpen(false)}
                className={cn(
                  'flex items-center rounded-lg transition-colors mb-0.5',
                  collapsed ? 'justify-center px-2 py-2.5' : 'gap-3 px-3 py-2 text-sm',
                  isActive
                    ? 'bg-primary/10 text-primary font-medium'
                    : 'text-muted-foreground hover:bg-accent hover:text-accent-foreground',
                )}
                title={collapsed ? item.label : undefined}
              >
                <item.icon className={cn('shrink-0', collapsed ? 'h-5 w-5' : 'h-4 w-4')} />
                {!collapsed && <span className="truncate">{item.label}</span>}
              </NavLink>
            )
          })}
        </nav>

        {/* Footer */}
        {collapsed ? (
          <div className="border-t p-2 flex justify-center">
            <button
              onClick={() => setModePanelOpen(v => !v)}
              className={cn(
                'h-3 w-3 rounded-full transition-colors',
                MODE_CONFIG[agentMode].bgColor,
              )}
              title={MODE_CONFIG[agentMode].label}
            />
          </div>
        ) : (
          <div className="border-t p-3">
            <div className="flex items-center justify-center gap-1.5 text-xs text-muted-foreground">
              <span className={cn(
                'h-1.5 w-1.5 rounded-full',
                MODE_CONFIG[agentMode].bgColor,
              )} />
              <span>OpenChiip Harness V0.0.30</span>
            </div>
          </div>
        )}
      </aside>

      {/* Main content */}
      <div className="flex flex-1 flex-col overflow-hidden">
        {/* Top bar */}
        <header className="flex h-12 items-center justify-between border-b px-4 shrink-0 bg-background">
          {/* 左侧：移动端菜单按钮 + 面包屑路径 */}
          <div className="flex items-center gap-1.5 text-sm">
            <button className="lg:hidden" onClick={() => setSidebarOpen(true)}>
              <Menu className="h-5 w-5" />
            </button>
            <span className="text-muted-foreground">首页</span>
            {(() => {
              const current = navItems.find(item =>
                location.pathname.startsWith(item.to)
              )
              if (current) {
                const info = pageInfoMap[current.to]
                if (info) {
                  return (
                    <>
                      <span className="text-muted-foreground/50">/</span>
                      <span className="font-semibold">{info.title}</span>
                      {info.description && (
                        <>
                          <span className="text-muted-foreground/30">|</span>
                          <span className="text-muted-foreground text-xs">{info.description}</span>
                        </>
                      )}
                    </>
                  )
                }
                return (
                  <>
                    <span className="text-muted-foreground/50">/</span>
                    <span className="font-semibold">{current.label}</span>
                  </>
                )
              }
              return null
            })()}
          </div>
          {/* 右侧：模式指示器 + 通知 + 用户头像 */}
          <div className="flex items-center gap-2">
            {/* Agent 工作模式指示器 */}
            <button
              onClick={() => setModePanelOpen(v => !v)}
              className={cn(
                'flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-medium transition-colors',
                agentMode === 'local'
                  ? 'bg-emerald-500/10 text-emerald-600 hover:bg-emerald-500/20'
                  : agentMode === 'collaborative'
                    ? 'bg-blue-500/10 text-blue-600 hover:bg-blue-500/20'
                    : 'bg-amber-500/10 text-amber-600 hover:bg-amber-500/20',
              )}
            >
              <span className={cn(
                'h-1.5 w-1.5 rounded-full',
                MODE_CONFIG[agentMode].bgColor,
              )} />
              {MODE_CONFIG[agentMode].label}
            </button>
            <button className="relative rounded-md p-1.5 text-muted-foreground hover:bg-accent hover:text-foreground transition-colors">
              <Bell className="h-4 w-4" />
            </button>
            <button className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/10 text-primary">
              <User className="h-4 w-4" />
            </button>
          </div>
        </header>

        {/* Page content */}
        <main className="flex-1 overflow-auto">
          <Outlet />
        </main>

        {/* Footer */}
        <footer className="border-t px-4 py-2 shrink-0 bg-background">
          <p className="text-center text-[11px] text-muted-foreground">
            © OpenChiip All rights reserved.
          </p>
        </footer>
      </div>

      {/* 模式选择面板 */}
      {modePanelOpen && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center">
          <div className="absolute inset-0 bg-black/30" onClick={() => setModePanelOpen(false)} />
          <div className="relative z-10 w-full max-w-sm rounded-xl border bg-background p-5 shadow-lg">
            <h3 className="text-sm font-semibold mb-4">选择工作模式</h3>
            <div className="space-y-2">
              {(['local', 'collaborative', 'order'] as RunMode[]).map(mode => {
                const cfg = MODE_CONFIG[mode]
                const isActive = mode === agentMode
                return (
                  <button
                    key={mode}
                    onClick={() => requestModeSwitch(mode)}
                    disabled={isActive}
                    className={cn(
                      'flex w-full items-center gap-3 rounded-lg border p-3 text-left transition-colors',
                      isActive ? 'border-primary bg-primary/5' : 'hover:bg-accent',
                    )}
                  >
                    <span className={cn('h-2.5 w-2.5 rounded-full shrink-0', cfg.bgColor)} />
                    <div className="flex-1 min-w-0">
                      <div className="text-sm font-medium">{cfg.label}</div>
                      <div className="text-xs text-muted-foreground">{cfg.desc}</div>
                    </div>
                    {isActive && <span className="text-xs text-primary font-medium">当前</span>}
                  </button>
                )
              })}
            </div>
          </div>
        </div>
      )}

      {/* 工作模式切换确认弹窗 */}
      {modeConfirmOpen && pendingMode && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center">
          <div className="absolute inset-0 bg-black/50" onClick={() => setModeConfirmOpen(false)} />
          <div className="relative z-10 w-full max-w-sm rounded-xl border bg-background p-6 shadow-lg">
            <h3 className="text-sm font-semibold">切换工作模式</h3>
            <p className="mt-3 text-xs text-muted-foreground leading-relaxed">
              将从 <span className="font-medium">{MODE_CONFIG[agentMode].label}</span> 切换到{' '}
              <span className="font-medium">{MODE_CONFIG[pendingMode].label}</span>。
              {pendingMode === 'order' && ' 接单模式下将不再接受对话请求，仅处理平台委派的项目任务。'}
              {pendingMode === 'local' && ' 本地模式下将断开平台连接，不同步数据。'}
            </p>
            <div className="mt-5 flex justify-end gap-2">
              <button
                onClick={() => setModeConfirmOpen(false)}
                className="rounded-lg border px-3 py-1.5 text-xs text-muted-foreground hover:bg-accent transition-colors"
              >
                取消
              </button>
              <button
                onClick={confirmModeSwitch}
                disabled={switching}
                className="rounded-lg bg-primary px-3 py-1.5 text-xs text-primary-foreground hover:bg-primary/90 transition-colors disabled:opacity-50"
              >
                {switching ? '切换中...' : '确认切换'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
