// Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
// Copyright: (c) <opensource@openchiip.com>
// Generated By : OpenChiip
// Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
// This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

/**
 * ErrorNode — 错误事件节点渲染。
 *
 * 在对话流中展示 turn 级别的错误信息。
 */
import { AlertTriangle } from 'lucide-react'

interface Props {
  message: string
}

export function ErrorNode({ message }: Props) {
  return (
    <div className="flex justify-start">
      <div className="flex items-start gap-2.5 max-w-[80%] rounded-lg border border-red-200 dark:border-red-900 bg-red-50/50 dark:bg-red-950/20 px-3 py-2.5">
        <AlertTriangle className="h-4 w-4 shrink-0 text-red-500 mt-0.5" />
        <div className="text-sm text-red-700 dark:text-red-400">
          <p className="font-medium text-xs mb-0.5">错误</p>
          <p className="whitespace-pre-wrap text-xs">{message}</p>
        </div>
      </div>
    </div>
  )
}
