// Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
// Copyright: (c) <opensource@openchiip.com>
// Generated By : OpenChiip
// Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
// This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

/**
 * Conversation Node 注册表 — 借鉴 deepseek-harness 的 ConversationNode 插件化渲染。
 *
 * 每种事件类型注册一个渲染器，ChatView 遍历事件列表时按类型分发。
 */
import { type ReactNode } from 'react'
import { EventType, type SessionEvent } from '../types'
import { UserMessageNode } from './UserMessageNode'
import { AssistantMessageNode } from './AssistantMessageNode'
import { ToolCallNode } from './ToolCallNode'
import { TurnBoundaryNode } from './TurnBoundaryNode'
import { ErrorNode } from './ErrorNode'

export interface NodeRenderProps {
  event: SessionEvent
  index: number
}

export interface ConversationNodeDef {
  kind: string
  match: (event: SessionEvent) => boolean
  render: (props: NodeRenderProps) => ReactNode
}

/** 默认节点注册表 — 按优先级排列（先匹配先生效）。 */
export const defaultNodes: ConversationNodeDef[] = [
  {
    kind: 'user-message',
    match: (e) => e.type === EventType.USER_MESSAGE,
    render: (props) => <UserMessageNode content={String(props.event.data.content || '')} />,
  },
  {
    kind: 'assistant-message',
    match: (e) => e.type === EventType.ASSISTANT_MESSAGE,
    render: (props) => <AssistantMessageNode content={String(props.event.data.content || '')} />,
  },
  {
    kind: 'tool-call',
    match: (e) => e.type === EventType.TOOL_CALL,
    render: (props) => (
      <ToolCallNode
        callId={String(props.event.data.call_id || '')}
        name={String(props.event.data.name || '')}
        args={props.event.data.args as Record<string, unknown> || {}}
      />
    ),
  },
  {
    kind: 'tool-result',
    match: (e) => e.type === EventType.TOOL_RESULT,
    render: (props) => (
      <ToolCallNode
        callId={String(props.event.data.call_id || '')}
        name={String(props.event.data.name || '')}
        result={String(props.event.data.content || '')}
        isError={Boolean(props.event.data.is_error)}
      />
    ),
  },
  {
    kind: 'turn-start',
    match: (e) => e.type === EventType.TURN_START,
    render: (props) => (
      <TurnBoundaryNode
        kind="start"
        turn={Number(props.event.data.turn ?? 0)}
      />
    ),
  },
  {
    kind: 'turn-end',
    match: (e) => e.type === EventType.TURN_END,
    render: (props) => (
      <TurnBoundaryNode
        kind="end"
        turn={Number(props.event.data.turn ?? 0)}
        reason={String(props.event.data.reason || '')}
      />
    ),
  },
  {
    kind: 'error',
    match: (e) => e.type === EventType.ERROR,
    render: (props) => (
      <ErrorNode message={String(props.event.data.message || props.event.data.error || '未知错误')} />
    ),
  },
]

/**
 * 根据事件匹配节点渲染器。
 */
export function matchNode(
  event: SessionEvent,
  nodes: ConversationNodeDef[] = defaultNodes,
): ConversationNodeDef | undefined {
  return nodes.find((n) => n.match(event))
}
