// Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
// Copyright: (c) <opensource@openchiip.com>
// Generated By : OpenChiip
// Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
// This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

import { cn } from '@/lib/utils'

interface Props {
  content: string
}

export function UserMessageNode({ content }: Props) {
  return (
    <div className="flex justify-end">
      <div className="max-w-[80%] rounded-2xl bg-primary px-4 py-2.5 text-sm text-primary-foreground">
        <p className="whitespace-pre-wrap">{content}</p>
      </div>
    </div>
  )
}
