# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

"""对话 API — 非流式 + SSE 流式 + 会话标题自动生成。"""
import asyncio
import json
import logging
import threading
import uuid
from datetime import datetime

from fastapi import APIRouter, Request
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

logger = logging.getLogger('agent.api.chat')
router = APIRouter(tags=['chat'])


class ChatRequest(BaseModel):
    message: str
    session_id: str | None = None
    sender: str | None = None


class ChatResponse(BaseModel):
    reply: str
    session_id: str
    intent: str | None = None
    skill: str | None = None
    elapsed_ms: float = 0


@router.post('/chat', response_model=ChatResponse)
async def chat(req: ChatRequest):
    """发送消息（非流式），返回完整回复。"""
    from agent_runtime.server.app import get_agent_app
    app = get_agent_app()
    if not app:
        return {'reply': 'Agent 未初始化', 'session_id': req.session_id or ''}

    import time
    t0 = time.monotonic()
    session_id = req.session_id or str(uuid.uuid4())

    # 确保会话已创建
    _ensure_session(app, session_id)

    # 收集流式输出为完整回复
    full_reply = []
    for chunk in app.process_message_stream(
            req.message, sender=req.sender, session_id=session_id):
        full_reply.append(chunk)

    reply = ''.join(full_reply)
    elapsed = (time.monotonic() - t0) * 1000

    # 自动生成标题
    _maybe_generate_title(app, session_id, req.message)

    return ChatResponse(
        reply=reply,
        session_id=session_id,
        elapsed_ms=round(elapsed, 1),
    )


@router.post('/chat/stream')
async def chat_stream(req: ChatRequest, request: Request):
    """发送消息（SSE 流式），逐 chunk 返回。"""
    from agent_runtime.server.app import get_agent_app
    app = get_agent_app()
    if not app:
        async def _error():
            yield _sse_event({'error': 'Agent 未初始化'})
            yield _sse_event('[DONE]')
        return StreamingResponse(_error(), media_type='text/event-stream')

    session_id = req.session_id or str(uuid.uuid4())

    # 确保会话已创建
    _ensure_session(app, session_id)

    async def _generate():
        # 发送 session_id
        yield _sse_event({'session_id': session_id, 'type': 'session'})

        loop = asyncio.get_event_loop()
        import time
        t0 = time.monotonic()

        # 取消信号：客户端断开时设置，传递给 producer 和 LLM 客户端
        cancel_event = threading.Event()

        # 使用 Queue 桥接同步生成器与异步生成器
        queue = asyncio.Queue()
        # 字符级流式缓冲：将大块 chunk 拆为逐字符输出
        char_queue = asyncio.Queue()
        producer_done = False

        def _producer():
            try:
                for item in app.process_message_stream(
                        req.message, sender=req.sender, session_id=session_id,
                        cancel_event=cancel_event):
                    if cancel_event.is_set():
                        break
                    if isinstance(item, tuple):
                        kind, data = item
                    else:
                        # 兼容旧的纯字符串 yield
                        kind, data = 'content', item
                    loop.call_soon_threadsafe(queue.put_nowait, (kind, data))
            except Exception as e:
                logger.exception('流式处理异常')
                loop.call_soon_threadsafe(queue.put_nowait, ('error', str(e)))
            finally:
                loop.call_soon_threadsafe(queue.put_nowait, ('done', None))

        async def _char_feeder():
            """从 chunk queue 读取数据，逐字符放入 char_queue。
            
            - 'content' 和 'reasoning': 拆为逐字符，带类型标记
            - 'tool_call' 和 'tool_result': 直接传递，不拆字符
            """
            nonlocal producer_done
            while True:
                kind, data = await queue.get()
                if kind in ('content', 'reasoning'):
                    # 将文本 chunk 拆为逐字符，带类型标记
                    for ch in data:
                        await char_queue.put((kind, ch))
                elif kind in ('tool_call', 'tool_result'):
                    # 工具事件直接传递
                    await char_queue.put((kind, data))
                elif kind == 'error':
                    await char_queue.put(('__error__', data))
                    producer_done = True
                    return
                else:
                    producer_done = True
                    await char_queue.put(None)  # sentinel
                    return

        # 启动生产者和字符拆分器
        loop.run_in_executor(None, _producer)
        feeder_task = loop.create_task(_char_feeder())

        # 逐字符流式发送（每字符间隔 ~15ms）
        try:
            while True:
                item = await char_queue.get()
                if item is None:
                    break
                kind, data = item
                if kind == '__error__':
                    yield _sse_event({'type': 'error', 'content': data})
                    break
                elif kind == 'content':
                    yield _sse_event({'type': 'delta', 'content': data})
                    await asyncio.sleep(0.015)
                elif kind == 'reasoning':
                    yield _sse_event({'type': 'reasoning', 'content': data})
                    await asyncio.sleep(0.015)
                elif kind == 'tool_call':
                    yield _sse_event({
                        'type': 'tool_call',
                        'tool_name': data.get('name', ''),
                        'tool_args': data.get('args', {}),
                        'tool_id': data.get('id', ''),
                    })
                elif kind == 'tool_result':
                    yield _sse_event({
                        'type': 'tool_result',
                        'tool_name': data.get('name', ''),
                        'tool_result': data.get('result', ''),
                        'tool_id': data.get('id', ''),
                        'success': data.get('success', True),
                    })
        except asyncio.CancelledError:
            logger.info('[chat_stream] 客户端断开，发送取消信号')
            cancel_event.set()
            raise
        finally:
            cancel_event.set()
            feeder_task.cancel()

        elapsed = (time.monotonic() - t0) * 1000
        yield _sse_event({'type': 'done', 'elapsed_ms': round(elapsed, 1)})
        yield 'data: [DONE]\n\n'

        # 流式完成后自动生成标题
        _maybe_generate_title(app, session_id, req.message)

    return StreamingResponse(_generate(), media_type='text/event-stream')


def _ensure_session(app, session_id: str):
    """确保会话记录存在。"""
    if not app or not hasattr(app, 'db'):
        return
    existing = app.db.get_session(session_id)
    if not existing:
        app.db.create_session(session_id)


def _maybe_generate_title(app, session_id: str, user_message: str):
    """当会话消息数 <= 2 时，用 LLM 生成简短标题。"""
    if not app or not hasattr(app, 'db'):
        return
    try:
        session = app.db.get_session(session_id)
        if not session:
            return
        # 只在首条消息后生成标题（message_count <= 2 说明刚完成第一轮对话）
        if session.get('message_count', 0) > 2:
            return
        # 如果标题已经不是默认的，不覆盖
        if session.get('title', '') not in ('新会话', ''):
            return
        # 使用 LLM 生成简短标题
        title = _generate_title(app, user_message)
        if title:
            app.db.update_session_title(session_id, title)
    except Exception:
        logger.debug('自动生成标题失败', exc_info=True)


def _generate_title(app, message: str) -> str:
    """用 LLM 从首条消息生成简短标题（10 字以内）。"""
    try:
        from agent_runtime.core.llm_client import AuxiliaryClient
        aux = getattr(app, 'aux', None)
        if not aux:
            # 简单截断作为兜底
            return message[:10].rstrip() or '新会话'
        client = aux.get_client('title')
        if not client:
            return message[:10].rstrip() or '新会话'
        resp = client.chat([
            {'role': 'system',
             'content': '根据用户消息生成一个简短的会话标题，不超过10个字，只输出标题文本，不要加引号或其他符号。'},
            {'role': 'user', 'content': message},
        ], max_tokens=30)
        title = (resp.get('content') or '').strip()[:10]
        return title or message[:10].rstrip()
    except Exception:
        # 兜底：截断用户消息
        return message[:10].rstrip() or '新会话'


def _sse_event(data: dict | str) -> str:
    """构造 SSE 事件行。"""
    if isinstance(data, str):
        return f'data: {data}\n\n'
    return f'data: {json.dumps(data, ensure_ascii=False)}\n\n'
