# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

"""消息反馈 API。"""
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional

router = APIRouter(prefix='/feedback', tags=['feedback'])


class FeedbackSubmit(BaseModel):
    message_id: int
    session_id: str
    rating: str  # 'like' | 'dislike'
    comment: Optional[str] = None


class FeedbackDelete(BaseModel):
    message_id: int


@router.post('')
async def submit_feedback(body: FeedbackSubmit):
    """提交或更新消息反馈。"""
    if body.rating not in ('like', 'dislike'):
        raise HTTPException(400, 'rating must be "like" or "dislike"')

    from agent_runtime.server.app import get_agent_app
    app = get_agent_app()
    if not app:
        raise HTTPException(500, 'Agent 未初始化')

    app.db.submit_feedback(
        message_id=body.message_id,
        session_id=body.session_id,
        rating=body.rating,
        comment=body.comment,
    )
    return {'ok': True, 'message_id': body.message_id, 'rating': body.rating}


@router.delete('')
async def delete_feedback(body: FeedbackDelete):
    """删除消息反馈（取消点赞/踩）。"""
    from agent_runtime.server.app import get_agent_app
    app = get_agent_app()
    if not app:
        raise HTTPException(500, 'Agent 未初始化')

    app.db.delete_feedback(message_id=body.message_id)
    return {'ok': True, 'message_id': body.message_id}


@router.get('/{message_id}')
async def get_feedback(message_id: int):
    """获取单条消息的反馈。"""
    from agent_runtime.server.app import get_agent_app
    app = get_agent_app()
    if not app:
        raise HTTPException(500, 'Agent 未初始化')

    result = app.db.get_feedback(message_id)
    return result or {'message_id': message_id, 'rating': None}


@router.get('')
async def get_session_feedback(session_id: str):
    """获取会话所有反馈。"""
    from agent_runtime.server.app import get_agent_app
    app = get_agent_app()
    if not app:
        raise HTTPException(500, 'Agent 未初始化')

    return app.db.get_session_feedback(session_id)
