# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

"""知识库 API — 知识库 CRUD + 文档上传。"""
from fastapi import APIRouter, UploadFile, File
from pydantic import BaseModel

router = APIRouter(prefix='/knowledge', tags=['knowledge'])


class KnowledgeCreate(BaseModel):
    name: str
    description: str = ''


@router.get('')
async def list_knowledge_bases():
    """知识库列表。"""
    # TODO: 实现知识库持久化
    return []


@router.post('')
async def create_knowledge_base(req: KnowledgeCreate):
    """创建知识库。"""
    return {'success': True, 'name': req.name, 'description': req.description}


@router.post('/{kb_id}/documents')
async def upload_document(kb_id: str, file: UploadFile = File(...)):
    """上传文档到知识库。"""
    return {'success': True, 'kb_id': kb_id, 'filename': file.filename}
