# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

"""运行模式 API — 获取/切换 Agent 工作模式（local / collaborative / order）。"""
import asyncio
import logging

from fastapi import APIRouter
from pydantic import BaseModel

logger = logging.getLogger('agent.server.mode')

router = APIRouter(prefix='/mode', tags=['mode'])

VALID_MODES = ('local', 'collaborative', 'order')
MODE_LABELS = {
    'local': '本地模式',
    'collaborative': '平台协同',
    'order': '接单模式',
}


class ModeSwitchRequest(BaseModel):
    mode: str


def _current_mode() -> str:
    """从 AgentApp 获取当前模式。"""
    from agent_runtime.server.app import get_agent_app
    app = get_agent_app()
    if app:
        return getattr(app.config, 'run_mode', 'local')
    return 'local'


@router.get('')
async def get_mode():
    """获取当前运行模式。"""
    mode = _current_mode()
    return {
        'run_mode': mode,
        'mode_label': MODE_LABELS.get(mode, '本地模式'),
    }


@router.put('')
async def switch_mode(req: ModeSwitchRequest):
    """热切换运行模式。

    切换逻辑: 任何模式都保持平台 WS 连接，模式仅作为标记随心跳上报。
    尚无连接时（如启动时未配置 Token）建连，由注册心跳携带新模式。
    """
    new_mode = req.mode
    if new_mode not in VALID_MODES:
        return {'error': f'无效模式: {new_mode}，可选: {", ".join(VALID_MODES)}'}

    from agent_runtime.server.app import get_agent_app
    app = get_agent_app()
    if not app:
        return {'error': 'Agent 未初始化'}

    old_mode = app.config.run_mode
    if old_mode == new_mode:
        return {
            'run_mode': new_mode,
            'mode_label': MODE_LABELS.get(new_mode, '本地模式'),
            'changed': False,
        }

    logger.info('模式切换: %s → %s', old_mode, new_mode)

    # 凭据门控: collaborative/order 模式需要有效 Token
    if new_mode in ('collaborative', 'order'):
        if not app.config.ws_token:
            return {
                'error': '未配置 Token，无法进入%s模式。' % MODE_LABELS.get(new_mode, ''),
                'guide': {
                    'register_url': (app.config.backend_url.rstrip('/') + '/register'
                                     if app.config.backend_url else 'https://openchiip.com/register'),
                    'configure_cmd': ('curl -X PUT http://127.0.0.1:%d/api/v1/credentials '
                                     '-H "Content-Type: application/json" '
                                     '-d \'{"token": "your-token"}\'' % app.config.port),
                }
            }

    # 更新内存中的模式
    app.config.run_mode = new_mode
    app.run_mode = new_mode

    # WS 连接管理（保持连接，仅上报新模式）
    await apply_mode_change(app, new_mode)

    # 模式不持久化到文件，仅通过心跳上报到平台 DB（DB 是唯一权威源）

    logger.info('模式已切换: %s → %s', old_mode, new_mode)

    return {
        'run_mode': new_mode,
        'mode_label': MODE_LABELS.get(new_mode, '本地模式'),
        'changed': True,
        'previous_mode': old_mode,
    }


async def apply_mode_change(app, mode: str):
    """应用模式变更：确保平台 WS 连接存在，并立即上报新模式。

    任何模式都保持平台连接 —— 断开会让平台同时失去模式与在线状态的来源；
    并且平台下发的模式切换是在 WS 自身的事件循环内处理的，在那里断开
    会杀掉正在执行的处理器所在的循环。
    """
    if getattr(app, 'ws_client', None) is None:
        # 尚无连接（如启动时未配置 Token）
        # _on_connected() 会发送含新模式的注册心跳
        _start_ws_connection(app)
    else:
        await _async_notify_platform(app, mode)


async def _async_notify_platform(app, mode: str):
    """通过 WS 心跳通知平台当前运行模式（投递并确认）。

    ★ WS 客户端运行在独立线程的独立事件循环中，而本函数运行在
      FastAPI 事件循环中。不能直接 await ws.send()（其内部对属于
      其他循环的 asyncio.Queue 做 put_nowait，不会唤醒目标循环，
      消息会滞留数十秒）。
      此处用 run_coroutine_threadsafe + wrap_future：既能正确跳循环，
      又能 await 到消息真正发出的时刻（供 → local 分支在关连接前确认）。
      wrap_future 不阻塞 FastAPI 线程；两个循环位于不同线程，不存在死锁。
    """
    from agent_runtime.ws import protocol

    ws = getattr(app, 'ws_client', None)
    if not (ws and ws.connected):
        return

    try:
        status_data = {}
        try:
            status_data = app.status_snapshot()
        except Exception:
            pass
        status_data['runtime_mode'] = mode
        msg = protocol.make_heartbeat(app.config.agent_id, status=status_data)

        ws_loop = ws.loop
        if ws_loop is None:
            logger.warning('WS 事件循环未就绪，模式通知跳过')
            return

        if ws_loop is asyncio.get_running_loop():
            # 平台下发模式切换时本函数就跑在 WS 循环内，直接发送
            await ws.send_now(msg)
        else:
            fut = asyncio.run_coroutine_threadsafe(ws.send_now(msg), ws_loop)
            await asyncio.wait_for(asyncio.wrap_future(fut), 1.0)

        logger.info('已通知平台模式变更: %s', mode)
    except asyncio.TimeoutError:
        logger.warning('通知平台模式变更超时，依赖周期心跳兜底: %s', mode)
    except Exception as e:
        logger.warning('通知平台模式变更失败: %s', e)


def _start_ws_connection(app):
    """启动平台 WS 连接。

    修复记录:
    - 先清理旧 WS 连接，避免残留连接干扰
    - 创建新连接后更新 MonitorReporter 的 ws/loop 引用
    - WS 连接成功后由 WSClient._on_connected 自动发送完整状态注册
    """
    import threading

    try:
        from agent_runtime.ws.client import WSClient
        from agent_runtime.ws.handlers import MessageHandlers

        # 1. 先清理旧连接（避免残留连接继续发送消息）
        _stop_ws_connection(app)

        # 调试日志：检查 token 是否存在
        logger.info('启动 WS 连接: agent_id=%s, ws_token=%s, ws_url=%s',
                    app.config.agent_id,
                    'set(%s...)' % app.config.ws_token[:10] if app.config.ws_token else 'EMPTY',
                    app.config.ws_url or app.config.backend_url)

        ws_client = WSClient(app.config, None)
        handlers = MessageHandlers(app, ws_client)
        ws_client.handlers = handlers
        ws_client.app = app  # 用于连接后发送完整状态注册
        app.ws_client = ws_client

        # 2. 更新 MonitorReporter 的 ws 引用
        if app.monitor:
            app.monitor.ws = ws_client
            # 3. 注册 loop 回调：WS 线程启动事件循环后自动更新 MonitorReporter.loop
            ws_client._loop_callback = lambda loop: setattr(app.monitor, 'loop', loop)

        def run_ws():
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            ws_client._loop = loop
            try:
                loop.run_until_complete(ws_client.run_forever())
            except Exception as e:
                logger.warning('平台 WS 连接失败: %s', e)

        ws_thread = threading.Thread(target=run_ws, daemon=True)
        ws_thread.start()
        logger.info('模式切换: WS 连接已启动')
    except Exception as e:
        logger.warning('模式切换: WS 初始化失败: %s', e)


def _stop_ws_connection(app):
    """断开平台 WS 连接（仅用于重建连接前的清理）。"""
    if app.ws_client:
        try:
            app.ws_client.stop()
        except Exception:
            pass
        app.ws_client = None
        # 清理 MonitorReporter 的悬空引用，避免向已关闭的循环投递监控数据
        if getattr(app, 'monitor', None):
            app.monitor.ws = None
        logger.info('模式切换: WS 连接已断开')


# _persist_mode 已移除: 运行模式仅存于平台 DB，不持久化到本地文件
