# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

"""项目 API — 项目 CRUD 与状态管理。

端点:
  GET    /projects          — 项目列表
  POST   /projects          — 创建项目（自动拆解子任务）
  GET    /projects/{id}     — 项目详情
  PUT    /projects/{id}     — 更新项目
  DELETE /projects/{id}     — 删除项目
  POST   /projects/{id}/decompose — 手动触发拆解
"""
import logging
from fastapi import APIRouter, Query, HTTPException
from pydantic import BaseModel, Field
from typing import Optional

logger = logging.getLogger('agent.api.projects')

router = APIRouter(prefix='/projects', tags=['projects'])


def _get_engine():
    """获取 ProjectEngine 实例。"""
    from agent_runtime.server.app import get_agent_app
    from agent_runtime.core.project_engine import ProjectEngine
    from agent_runtime.core.task_engine import TaskEngine
    app = get_agent_app()
    if not app:
        raise HTTPException(503, 'Agent 未初始化')
    task_engine = TaskEngine(
        db=app.db,
        ws_client=app.ws_client,
        agent_id=app.config.agent_id)
    return ProjectEngine(
        db=app.db,
        ws_client=app.ws_client,
        agent_id=app.config.agent_id,
        llm=app.llm,
        task_engine=task_engine,
        home=app.config.home)


# ─────────────────────────────────────────
# 请求/响应模型
# ─────────────────────────────────────────

class CreateProjectRequest(BaseModel):
    """创建项目请求。"""
    title: str = Field(..., min_length=1, max_length=200,
                       description='项目标题')
    description: str = Field('', max_length=2000,
                             description='项目描述')
    plan_type: str = Field('dag',
                           description='执行计划类型: dag/loop')
    loop_goal: str = Field('', max_length=2000,
                           description='Loop 目标')
    loop_stop_condition: str = Field('', max_length=2000,
                                     description='Loop 停止条件')
    loop_max_iterations: int = Field(10, ge=1, le=100,
                                      description='最大迭代次数')
    repo_url: str = Field('', description='Git 仓库地址')
    repo_provider: str = Field('github', description='提供商: github/gitlab/gitee/cnb/yunxiao')
    repo_branch: str = Field('main', description='默认分支')
    repo_secret_ref: str = Field('', description='凭证引用 ID')
    created_by: str = Field('system', description='创建人')


class UpdateProjectRequest(BaseModel):
    """更新项目请求。"""
    title: Optional[str] = Field(None, max_length=200)
    description: Optional[str] = Field(None, max_length=2000)
    status: Optional[str] = Field(None)
    plan_type: Optional[str] = Field(None)
    loop_goal: Optional[str] = Field(None, max_length=2000)
    loop_stop_condition: Optional[str] = Field(None, max_length=2000)
    loop_max_iterations: Optional[int] = Field(None, ge=1, le=100)
    plan_document: Optional[str] = None
    result_document: Optional[str] = None
    repo_url: Optional[str] = Field(None, description='Git 仓库地址')
    repo_provider: Optional[str] = Field(None, description='提供商')
    repo_branch: Optional[str] = Field(None, description='默认分支')
    repo_secret_ref: Optional[str] = Field(None, description='凭证引用 ID')
    updated_by: Optional[str] = Field(None, description='更新人')


# ─────────────────────────────────────────
# 端点
# ─────────────────────────────────────────

@router.get('')
async def list_projects(
    status: Optional[str] = Query(None, description='按状态过滤'),
    search: Optional[str] = Query(None, description='搜索项目名称/ID/描述'),
    created_by: Optional[str] = Query(None, description='按创建人过滤'),
    created_after: Optional[str] = Query(None, description='创建时间起始 (ISO 格式)'),
    created_before: Optional[str] = Query(None, description='创建时间截止 (ISO 格式)'),
    page: int = Query(1, ge=1, description='页码'),
    page_size: int = Query(20, ge=1, le=100, description='每页条数'),
):
    """获取项目列表（分页）。"""
    engine = _get_engine()
    limit = page_size
    offset = (page - 1) * page_size
    result = engine.list_projects(
        status=status, search=search, created_by=created_by,
        created_after=created_after, created_before=created_before,
        limit=limit, offset=offset)
    return result


@router.post('')
async def create_project(req: CreateProjectRequest):
    """创建新项目并自动拆解子任务。"""
    engine = _get_engine()
    project = engine.create_project(
        title=req.title,
        description=req.description,
        plan_type=req.plan_type,
        loop_goal=req.loop_goal,
        loop_stop_condition=req.loop_stop_condition,
        loop_max_iterations=req.loop_max_iterations,
        repo_url=req.repo_url,
        repo_provider=req.repo_provider,
        repo_branch=req.repo_branch,
        repo_secret_ref=req.repo_secret_ref,
        created_by=req.created_by,
    )
    # 自动拆解子任务（异步执行，不阻塞响应）
    engine.decompose_project_async(project['id'])
    return project


@router.get('/{project_id}')
async def get_project(project_id: str):
    """获取项目详情。"""
    engine = _get_engine()
    project = engine.get_project(project_id)
    if not project:
        raise HTTPException(404, '项目不存在: %s' % project_id)
    return project


@router.put('/{project_id}')
async def update_project(project_id: str, req: UpdateProjectRequest):
    """更新项目。"""
    engine = _get_engine()
    updates = {k: v for k, v in req.model_dump().items() if v is not None}
    if not updates:
        raise HTTPException(400, '未提供更新字段')
    project = engine.update_project(project_id, **updates)
    if not project:
        raise HTTPException(404, '项目不存在: %s' % project_id)
    return project


@router.post('/{project_id}/transition')
async def transition_project(project_id: str, status: str):
    """状态流转。"""
    engine = _get_engine()
    project = engine.transition(project_id, status)
    if not project:
        raise HTTPException(400, '状态转换失败')
    return project


@router.delete('/{project_id}')
async def delete_project(project_id: str):
    """删除项目。"""
    engine = _get_engine()
    ok = engine.delete_project(project_id)
    if not ok:
        raise HTTPException(404, '项目不存在: %s' % project_id)
    return {'deleted': True, 'project_id': project_id}


@router.post('/{project_id}/decompose')
async def decompose_project(project_id: str):
    """手动触发项目拆解。"""
    engine = _get_engine()
    project = engine.get_project(project_id)
    if not project:
        raise HTTPException(404, '项目不存在: %s' % project_id)
    tasks = engine.decompose_project(project_id)
    if tasks is None:
        raise HTTPException(503, '拆解失败（LLM 或 TaskEngine 不可用）')
    return {
        'project_id': project_id,
        'subtask_count': len(tasks),
        'subtasks': tasks,
    }
