# Copyright: (c) OpenChiip Organization. https://github.com/OpenChiip/openchiip-harness
# Copyright: (c) <opensource@openchiip.com>
# Generated By : OpenChiip
# Released under the AIGCGPL-1.0 License. For more information, see [https://github.com/OpenChiip/AIGCGPL/blob/main/LICENSE].
# This code was generated using a generative artificial intelligence system and is licensed under the Artificial Intelligence Generated Code General Public License (AIGCGPL).

"""技能管理 API — Skill Package CRUD。"""
from fastapi import APIRouter
from pydantic import BaseModel

router = APIRouter(prefix='/skills', tags=['skills'])


class SkillInstallRequest(BaseModel):
    source: str  # 目录路径 / URL / Git 地址
    name: str = ''


@router.get('')
async def list_skills():
    """列出已装备技能。"""
    from agent_runtime.server.app import get_agent_app
    app = get_agent_app()
    if not app:
        return []
    return app.skills.list_skills()


@router.post('/install')
async def install_skill(req: SkillInstallRequest):
    """安装技能（从目录/URL/Git）。"""
    from agent_runtime.server.app import get_agent_app
    app = get_agent_app()
    if not app:
        return {'error': 'Agent 未初始化'}
    try:
        result = app.skills.install(req.source, name=req.name or None)
        return {'success': True, 'result': result}
    except Exception as e:
        return {'success': False, 'error': str(e)}


@router.get('/{skill_id}')
async def get_skill(skill_id: str):
    """技能详情。"""
    from agent_runtime.server.app import get_agent_app
    app = get_agent_app()
    if not app:
        return {'error': 'Agent 未初始化'}
    for s in app.skills.list_skills():
        if s.get('name') == skill_id:
            return s
    return {'error': f'技能 {skill_id} 不存在'}


@router.delete('/{skill_id}')
async def remove_skill(skill_id: str):
    """卸载技能。"""
    from agent_runtime.server.app import get_agent_app
    app = get_agent_app()
    if not app:
        return {'error': 'Agent 未初始化'}
    try:
        app.skills.remove(skill_id)
        return {'success': True, 'removed': skill_id}
    except Exception as e:
        return {'success': False, 'error': str(e)}


@router.post('/{skill_id}/test')
async def test_skill(skill_id: str, args: dict = {}):
    """测试运行技能。"""
    from agent_runtime.server.app import get_agent_app
    app = get_agent_app()
    if not app:
        return {'error': 'Agent 未初始化'}
    try:
        result = app.skills.run_skill(skill_id, args)
        return {'success': True, 'result': result}
    except Exception as e:
        return {'success': False, 'error': str(e)}
